/**
 * THE SURFACE REGISTRY — what each interactive surface of csoai.org actually is.
 *
 * WHY THIS FILE EXISTS
 * EU AI Act Article 50(1) applies from 2 August 2026: a person must be told, at the start of the
 * first interaction, when they are interacting with an AI system. Article 3(1) defines an AI
 * system as one that *infers* from input how to generate output. Recital 12 places outside that
 * definition "systems that are based on the rules defined solely by natural persons to
 * automatically execute operations".
 *
 * WHAT WAS MEASURED, NOT ASSUMED
 * article50_guard.py walked the wouter route table: 311 routes resolve to a page file, 135 of
 * them take input and return something, and 0 of those reach a model provider through any
 * import, transitive or direct. So no surface on this site currently engages Article 50(1).
 *
 * Three of the SDKs in package.json — @anthropic-ai/sdk, openai, @google/generative-ai — are
 * declared but never imported anywhere in client/ or server/. A dependency is not a call, so
 * this is not a violation. It is the shortest possible distance to becoming one: adding
 * inference is a single import with no install step. The guard reports it as a watch condition.
 *
 * WHY MOST ENTRIES SAY `unclassified`
 * Only four mechanisms below were written after actually reading the surface. Inventing plausible
 * descriptions for the other 131 would make this page look complete and be partly false — the
 * worse failure, because a reader cannot tell which sentences were checked. `unclassified` is a
 * real, published state with a visible count, and it is what the remaining surfaces honestly are.
 *
 * THE STRUCTURAL PART
 * A registry maintained by remembering to maintain it is not a control. article50_guard.py reads
 * this file and cross-checks it against the source: a surface whose code reaches a model provider
 * must be registered `ai_system` and must mount <AISystemNotice>, and an interactive surface
 * missing from this file fails the check. It runs in the release gate.
 */

export type SurfaceNature = "rule_based" | "ai_system" | "unclassified";

export interface Surface {
  route: string;
  label: string;
  nature: SurfaceNature;
  mechanism: string;
  evidence: string[];
}

export const SURFACES: Surface[] = [
  { route: "/", label: "Home + Sovereign Console", nature: "rule_based",
    mechanism: "The console pattern-matches your question against frozen statute text and renders the matching provision. There is no inference call in the file, and nothing you type is transmitted or stored \u2014 no fetch, no analytics, no session capture. The page also carries an email form posting to /api/subscribe.",
    evidence: ["client/src/components/SovereignConsole.tsx", "client/src/pages/NewHome-v2.tsx"] },
  { route: "/instrument", label: "The GSPC instrument", nature: "rule_based",
    mechanism: "One chat pane over four lenses. Dispatch is deterministic pattern matching over frozen statute; no model is consulted and nothing is sent anywhere. Deliberately not LMArena: pairwise human preference voting is crowd judgement, which the design rules exclude from a primary score.",
    evidence: ["client/src/pages/Instrument.tsx"] },
  { route: "/benchmarks", label: "Measured results", nature: "rule_based",
    mechanism: "Static rendering of figures read from published artefacts in the govbench dataset. Nothing is computed at render time and nothing is typed in by hand \u2014 each row names the artefact it came from.",
    evidence: ["client/src/pages/Benchmarks.tsx"] },
  { route: "/agent-council", label: "AgentCouncil", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/AgentCouncil.tsx"] },
  { route: "/agent-registry", label: "AgentRegistry", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/AgentRegistry.tsx"] },
  { route: "/agents-network", label: "NetworkPage", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NetworkPage.tsx"] },
  { route: "/ai-act-faq", label: "AiActFaq", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/AiActFaq.tsx"] },
  { route: "/ai-act-summary", label: "ActSummary", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ActSummary.tsx"] },
  { route: "/ai-glossary", label: "Glossary", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Glossary.tsx"] },
  { route: "/ai-governance", label: "AiGovernanceHub", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/AiGovernanceHub.tsx"] },
  { route: "/ai-governance-guide", label: "AiGovernanceHub", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/AiGovernanceHub.tsx"] },
  { route: "/ai-systems", label: "AISystems", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/AISystems.tsx"] },
  { route: "/all", label: "RegistryAll", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/RegistryAll.tsx"] },
  { route: "/api-keys", label: "ApiKeys", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ApiKeys.tsx"] },
  { route: "/assess", label: "Readiness assessment", nature: "rule_based",
    mechanism: "A decision table over your answers. Each response maps to a fixed control identifier; unclaimed controls are reported as gaps. No model is consulted.", evidence: ["client/src/pages/AssessTool.tsx"] },
  { route: "/assurance", label: "SystemCard", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SystemCard.tsx"] },
  { route: "/battlecards", label: "Competitors", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Competitors.tsx"] },
  { route: "/bft", label: "BftConfig", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/BftConfig.tsx"] },
  { route: "/blog", label: "Blog index", nature: "rule_based",
    mechanism: "Static post index with a client-side substring filter.", evidence: ["client/src/pages/Blog.tsx"] },
  { route: "/bulk-import", label: "BulkAISystemImport", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/BulkAISystemImport.tsx"] },
  { route: "/byzantine", label: "AgentCouncil", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/AgentCouncil.tsx"] },
  { route: "/certification/review", label: "ExamReview", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ExamReview.tsx"] },
  { route: "/classifier", label: "Annex III classifier", nature: "rule_based",
    mechanism: "Keyword matching of your description against the Annex III category lists. The same input always produces the same output.", evidence: ["client/src/pages/EuActClassifier.tsx"] },
  { route: "/command-center", label: "ComplianceCommandCenter", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ComplianceCommandCenter.tsx"] },
  { route: "/commons", label: "OpenMedia", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/OpenMedia.tsx"] },
  { route: "/competitors", label: "Competitors", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Competitors.tsx"] },
  { route: "/compliance", label: "Compliance", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Compliance.tsx"] },
  { route: "/conformity-assessment", label: "ConformityAssessment", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ConformityAssessment.tsx"] },
  { route: "/connect", label: "SocialConnect", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SocialConnect.tsx"] },
  { route: "/consensus", label: "BftConfig", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/BftConfig.tsx"] },
  { route: "/courses", label: "Courses", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Courses.tsx"] },
  { route: "/cyber-scan", label: "CyberScan", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/CyberScan.tsx"] },
  { route: "/dashboard/progress", label: "StudentProgress", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/StudentProgress.tsx"] },
  { route: "/deepfake-protection", label: "Protect", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Protect.tsx"] },
  { route: "/demo", label: "TryCouncil", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/TryCouncil.tsx"] },
  { route: "/egg", label: "EmergencePage", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/EmergencePage.tsx"] },
  { route: "/emergence", label: "EmergencePage", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/EmergencePage.tsx"] },
  { route: "/enter", label: "OsEnter", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/OsEnter.tsx"] },
  { route: "/enterprise-onboarding", label: "EnterpriseOnboarding", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/EnterpriseOnboarding.tsx"] },
  { route: "/eu-ai-act", label: "EUAIActGuide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/EUAIActGuide.tsx"] },
  { route: "/eu-ai-act-explained", label: "ActSummary", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ActSummary.tsx"] },
  { route: "/eu-ai-act-faq", label: "AiActFaq", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/AiActFaq.tsx"] },
  { route: "/evidence", label: "Evidence explorer", nature: "rule_based",
    mechanism: "Renders stored evidence records and checks their hash chain. It verifies integrity, not truth.", evidence: ["client/src/pages/EvidenceHub.tsx"] },
  { route: "/faq", label: "FAQ", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/FAQ.tsx"] },
  { route: "/fines", label: "Penalties", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Penalties.tsx"] },
  { route: "/foundation-models", label: "GpaiObligations", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GpaiObligations.tsx"] },
  { route: "/framework-catalog", label: "FrameworkCatalog", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/FrameworkCatalog.tsx"] },
  { route: "/frameworks/eu-ai-act", label: "EUAIActGuide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/EUAIActGuide.tsx"] },
  { route: "/frameworks/iso-42001", label: "ISO42001Guide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ISO42001Guide.tsx"] },
  { route: "/frameworks/nist", label: "NISTAIRMFGuide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NISTAIRMFGuide.tsx"] },
  { route: "/frameworks/tc260", label: "TC260Guide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/TC260Guide.tsx"] },
  { route: "/frequently-asked-questions", label: "FAQ", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/FAQ.tsx"] },
  { route: "/global-regulations", label: "GlobalRegulationTracker", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GlobalRegulationTracker.tsx"] },
  { route: "/globe", label: "WorldGlobe", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WorldGlobe.tsx"] },
  { route: "/glossary", label: "Glossary", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Glossary.tsx"] },
  { route: "/gods-eye", label: "CyberScan", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/CyberScan.tsx"] },
  { route: "/governance-graph", label: "GovGraph", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GovGraph.tsx"] },
  { route: "/government", label: "GovernmentDashboard", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GovernmentDashboard.tsx"] },
  { route: "/government-dashboard", label: "GovernmentDashboard", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GovernmentDashboard.tsx"] },
  { route: "/gpai", label: "GpaiObligations", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GpaiObligations.tsx"] },
  { route: "/graph", label: "GovGraph", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GovGraph.tsx"] },
  { route: "/guides/eu-ai-act", label: "EUAIActGuide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/EUAIActGuide.tsx"] },
  { route: "/guides/iso-42001", label: "ISO42001Guide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ISO42001Guide.tsx"] },
  { route: "/guides/nist-ai-rmf", label: "NISTAIRMFGuide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NISTAIRMFGuide.tsx"] },
  { route: "/guides/tc260", label: "TC260Guide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/TC260Guide.tsx"] },
  { route: "/hatch", label: "EmergencePage", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/EmergencePage.tsx"] },
  { route: "/heatmap", label: "WatchdogMap", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WatchdogMap.tsx"] },
  { route: "/high-risk-ai", label: "HighRiskSystems", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/HighRiskSystems.tsx"] },
  { route: "/high-risk-ai-systems", label: "HighRiskSystems", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/HighRiskSystems.tsx"] },
  { route: "/hive/:slug", label: "FrameworkHive", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/FrameworkHive.tsx"] },
  { route: "/humanoids-poc", label: "PocShowcase", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/PocShowcase.tsx"] },
  { route: "/iso-42001", label: "ISO42001Guide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ISO42001Guide.tsx"] },
  { route: "/iso-42001-vs-eu-ai-act", label: "Iso42001VsEuAct", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Iso42001VsEuAct.tsx"] },
  { route: "/iso-eu", label: "Iso42001VsEuAct", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Iso42001VsEuAct.tsx"] },
  { route: "/jobs", label: "Jobs", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Jobs.tsx"] },
  { route: "/join", label: "SovereignRegistry", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SovereignRegistry.tsx"] },
  { route: "/knowledge-base", label: "KnowledgeBase", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/KnowledgeBase.tsx"] },
  { route: "/login", label: "Login", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Login.tsx"] },
  { route: "/marketing", label: "MarketingHome", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/MarketingHome.tsx"] },
  { route: "/mcp-fleet", label: "McpFleet", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/McpFleet.tsx"] },
  { route: "/mcp-tools", label: "ToolCommons", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ToolCommons.tsx"] },
  { route: "/network", label: "NetworkPage", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NetworkPage.tsx"] },
  { route: "/nist-ai-rmf", label: "NISTAIRMFGuide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NISTAIRMFGuide.tsx"] },
  { route: "/nist-eu", label: "NistVsEuAct", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NistVsEuAct.tsx"] },
  { route: "/nist-vs-eu-ai-act", label: "NistVsEuAct", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NistVsEuAct.tsx"] },
  { route: "/one-os", label: "PocShowcase", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/PocShowcase.tsx"] },
  { route: "/open-media", label: "OpenMedia", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/OpenMedia.tsx"] },
  { route: "/os", label: "OsLauncher", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/OsLauncher.tsx"] },
  { route: "/os-demo", label: "DemoOS", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/DemoOS.tsx"] },
  { route: "/oscal", label: "OscalStudio", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/OscalStudio.tsx"] },
  { route: "/our-difference", label: "WhyCSOAI", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WhyCSOAI.tsx"] },
  { route: "/pdca", label: "PDCACycles", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/PDCACycles.tsx"] },
  { route: "/penalties", label: "Penalties", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Penalties.tsx"] },
  { route: "/personal-protection", label: "Protect", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Protect.tsx"] },
  { route: "/poc", label: "PocShowcase", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/PocShowcase.tsx"] },
  { route: "/policy-generator", label: "PolicyGenerator", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/PolicyGenerator.tsx"] },
  { route: "/protect", label: "Protect", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Protect.tsx"] },
  { route: "/public-watchdog", label: "PublicWatchdog", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/PublicWatchdog.tsx"] },
  { route: "/pulse", label: "GovernancePulse", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GovernancePulse.tsx"] },
  { route: "/recommendations", label: "Recommendations", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Recommendations.tsx"] },
  { route: "/register", label: "SovereignRegistry", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SovereignRegistry.tsx"] },
  { route: "/registry", label: "RegistryAll", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/RegistryAll.tsx"] },
  { route: "/regulation-tracker", label: "GlobalRegulationTracker", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GlobalRegulationTracker.tsx"] },
  { route: "/regulator", label: "RegulatorDashboard", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/RegulatorDashboard.tsx"] },
  { route: "/regulator-atlas", label: "RegulatorAtlas", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/RegulatorAtlas.tsx"] },
  { route: "/regulators", label: "RegulatorAtlas", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/RegulatorAtlas.tsx"] },
  { route: "/report", label: "IncidentReport", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/IncidentReport.tsx"] },
  { route: "/reports", label: "Reports", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Reports.tsx"] },
  { route: "/roi", label: "ROICalculator", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ROICalculator.tsx"] },
  { route: "/roi-calculator", label: "ROICalculator", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ROICalculator.tsx"] },
  { route: "/scan", label: "CyberScan", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/CyberScan.tsx"] },
  { route: "/settings", label: "Settings", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Settings.tsx"] },
  { route: "/settings/notifications", label: "NotificationSettings", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NotificationSettings.tsx"] },
  { route: "/signup", label: "Signup", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Signup.tsx"] },
  { route: "/simulate", label: "SovSpace", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SovSpace.tsx"] },
  { route: "/sov-space", label: "SovSpace", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SovSpace.tsx"] },
  { route: "/sov-towns", label: "SovTowns", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SovTowns.tsx"] },
  { route: "/sov3", label: "Workbench", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Workbench.tsx"] },
  { route: "/sovereign-network", label: "NetworkPage", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/NetworkPage.tsx"] },
  { route: "/sovereign-space", label: "SovSpace", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SovSpace.tsx"] },
  { route: "/system-card", label: "SystemCard", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SystemCard.tsx"] },
  { route: "/systemcard", label: "SystemCard", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SystemCard.tsx"] },
  { route: "/tc260", label: "TC260Guide", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/TC260Guide.tsx"] },
  { route: "/tool-commons", label: "ToolCommons", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ToolCommons.tsx"] },
  { route: "/tools", label: "ToolCommons", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/ToolCommons.tsx"] },
  { route: "/towns", label: "SovTowns", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/SovTowns.tsx"] },
  { route: "/try", label: "TryCouncil", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/TryCouncil.tsx"] },
  { route: "/usp", label: "WhyCSOAI", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WhyCSOAI.tsx"] },
  { route: "/verify-certificate", label: "CertificateVerification", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/CertificateVerification.tsx"] },
  { route: "/watchdog-heatmap", label: "WatchdogMap", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WatchdogMap.tsx"] },
  { route: "/watchdog-map", label: "WatchdogMap", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WatchdogMap.tsx"] },
  { route: "/watchdog-signup", label: "WatchdogSignup", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WatchdogSignup.tsx"] },
  { route: "/webhooks", label: "Webhooks", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Webhooks.tsx"] },
  { route: "/why", label: "WhyCSOAI", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WhyCSOAI.tsx"] },
  { route: "/widget", label: "WidgetCourses", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WidgetCourses.tsx"] },
  { route: "/workbench", label: "Workbench", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/Workbench.tsx"] },
  { route: "/world", label: "WorldGlobe", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/WorldGlobe.tsx"] },
  { route: "/world-data", label: "GovGraph", nature: "unclassified",
    mechanism: "", evidence: ["client/src/pages/GovGraph.tsx"] },
];

export function surfaceFor(route: string): Surface {
  return (
    SURFACES.find((s) => s.route === route) ?? {
      route, label: route, nature: "unclassified",
      mechanism: "Not registered in client/src/lib/ai-surfaces.ts.", evidence: [],
    }
  );
}

export const AI_SYSTEM_SURFACES = SURFACES.filter((s) => s.nature === "ai_system");

export const COUNTS = {
  total: SURFACES.length,
  rule_based: SURFACES.filter((s) => s.nature === "rule_based").length,
  ai_system: AI_SYSTEM_SURFACES.length,
  unclassified: SURFACES.filter((s) => s.nature === "unclassified").length,
};

/** Model SDKs present in package.json but never imported. Measured, not asserted. */
export const DECLARED_UNCALLED_SDKS = ["@anthropic-ai/sdk", "openai", "@google/generative-ai"];

/** Routes that resolve to a page file, of which SURFACES are the interactive ones. */
export const ROUTES_SCANNED = 311;

export const REGISTRY_VERSION = "1.0.0";
export const ASSESSED_AT = "2026-07-29";
