/**
 * THE SURFACE REGISTRY — what each interactive surface of csoai.org actually is.
 *
 * WHY THIS FILE EXISTS
 * EU AI Act Article 50(1) applies from 2 August 2026: a person must be told, at the start of the
 * first interaction, when they are interacting with an AI system. Article 3(1) defines an AI
 * system as one that *infers* from input how to generate output. Recital 12 places outside that
 * definition "systems that are based on the rules defined solely by natural persons to
 * automatically execute operations".
 *
 * THE 2026-08-01 CORRECTION (published, like every other miss)
 * Version 1.0.0 (2026-07-29) reported that ZERO surfaces reach a model. That was wrong, and the
 * method was why: the guard walked *imports* of model-provider SDKs, but the surfaces that talk
 * to a model do it with a plain fetch to our own gateway (os.meok.ai/api/chat), which needs no
 * SDK. A manual audit of every fetch on 1 Aug 2026 — the day before Article 50 became
 * enforceable — found 14 components that call the live Sovereign chat endpoint. They are
 * registered ai_system below, with the state of their Art 50(1) notice in the mechanism line.
 * The earlier claim is corrected here, in the file that made it.
 *
 * WHAT WAS CHECKED, ENTRY BY ENTRY
 * Every page file was grep-audited for model calls (the chat endpoint and the askSovereign
 * helper). rule_based entries below carry a family mechanism line; it asserts only what was
 * verified — that no model call exists in the surface's own code — plus what kind of surface it
 * is. Anything not in this registry defaults to the STRICTEST reading (treated as an AI system)
 * until it is classified, and surfaceFor() says so.
 *
 * THE STRUCTURAL PART
 * A registry maintained by remembering to maintain it is not a control. article50_guard.py reads
 * this file and cross-checks it against the source: a surface whose code reaches a model must be
 * registered ai_system and must mount <AISystemNotice>, and an interactive surface missing from
 * this file fails the check. It runs in the release gate. The guard's import-walk is being
 * extended to cover gateway fetch calls — the blind spot this version corrects by hand.
 *
 * GLOBAL SURFACE, NOT A ROUTE: the Sovereign dock (components/SovereignDock.tsx) is mounted
 * site-wide from App.tsx and chats with the live endpoint. It is an AI-system surface; the
 * notice wiring for it is tracked in the Art 50 pack, and it is named here because a registry
 * that only counts routes would miss it.
 */

export type SurfaceNature = "rule_based" | "ai_system" | "unclassified";

export interface Surface {
  route: string;
  label: string;
  nature: SurfaceNature;
  mechanism: string;
  evidence: string[];
}


export const SURFACES: Surface[] = [
  { route: "/sovereign-dock", label: "Sovereign dock (global)", nature: "ai_system",
    mechanism: "The dock sends your message to the live Sovereign gateway (os.meok.ai/api/chat) and a model writes the reply. It is mounted on every page; the notice below the dock header discloses this at first interaction, per Article 50(1).",
    evidence: ["client/src/components/SovereignDock.tsx", "client/src/lib/sovAsk.ts"] },
  { route: "/", label: "Home + Sovereign Console", nature: "rule_based",
    mechanism: "The console pattern-matches your question against frozen statute text and renders the matching provision. There is no inference call in the console's code, and nothing you type into it is transmitted or stored. The page also carries an email form posting to /api/subscribe, and — like every page — the global Sovereign dock, which IS an AI-system surface (see the note at the top of this file).",
    evidence: ["client/src/components/SovereignConsole.tsx", "client/src/pages/NewHome-v2.tsx"] },
  { route: "/instrument", label: "The GSPC instrument", nature: "rule_based",
    mechanism: "One chat pane over four lenses. Dispatch is deterministic pattern matching over frozen statute; no model is consulted and nothing is sent anywhere. Deliberately not LMArena: pairwise human preference voting is crowd judgement, which the design rules exclude from a primary score.",
    evidence: ["client/src/pages/Instrument.tsx"] },
  { route: "/benchmarks", label: "Measured results", nature: "rule_based",
    mechanism: "Static rendering of figures read from published artefacts in the govbench dataset. Nothing is computed at render time and nothing is typed in by hand — each row names the artefact it came from.",
    evidence: ["client/src/pages/Benchmarks.tsx"] },
  { route: "/agent-council", label: "AgentCouncil", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/AgentCouncil.tsx"] },
  { route: "/agent-registry", label: "AgentRegistry", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/AgentRegistry.tsx"] },
  { route: "/agents-network", label: "NetworkPage", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/NetworkPage.tsx"] },
  { route: "/ai-act-faq", label: "AiActFaq", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/AiActFaq.tsx"] },
  { route: "/ai-act-summary", label: "ActSummary", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/ActSummary.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/ai-glossary", label: "Glossary", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/Glossary.tsx"] },
  { route: "/ai-governance", label: "AiGovernanceHub", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/AiGovernanceHub.tsx"] },
  { route: "/ai-governance-guide", label: "AiGovernanceHub", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/AiGovernanceHub.tsx"] },
  { route: "/ai-systems", label: "AISystems", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/AISystems.tsx"] },
  { route: "/all", label: "RegistryAll", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/RegistryAll.tsx"] },
  { route: "/api-keys", label: "ApiKeys", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/ApiKeys.tsx"] },
  { route: "/assess", label: "Readiness assessment", nature: "rule_based",
    mechanism: "A decision table over your answers, scored by the signed /api/assess endpoint. Each response maps to a fixed control identifier; unclaimed controls are reported as gaps. No model is consulted.",
    evidence: ["client/src/pages/AssessTool.tsx"] },
  { route: "/assurance", label: "SystemCard", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/SystemCard.tsx"] },
  { route: "/battlecards", label: "Competitors", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/Competitors.tsx"] },
  { route: "/bft", label: "BftConfig", nature: "rule_based",
    mechanism: "A deterministic instrument — fixed tables, templates or arithmetic over your input, so the same input gives the same output. No model call exists in this surface's code.",
    evidence: ["client/src/pages/BftConfig.tsx"] },
  { route: "/blog", label: "Blog index", nature: "rule_based",
    mechanism: "Static post index with a client-side substring filter.",
    evidence: ["client/src/pages/Blog.tsx"] },
  { route: "/bulk-import", label: "BulkAISystemImport", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/BulkAISystemImport.tsx"] },
  { route: "/byzantine", label: "AgentCouncil", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/AgentCouncil.tsx"] },
  { route: "/certification/review", label: "ExamReview", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/ExamReview.tsx"] },
  { route: "/classifier", label: "Annex III classifier", nature: "ai_system",
    mechanism: "CORRECTED 1 Aug 2026 — v1.0.0 registered this as keyword matching; the code actually sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Article 50(1) notice is mounted above the input.",
    evidence: ["client/src/pages/EuActClassifier.tsx"] },
  { route: "/command-center", label: "ComplianceCommandCenter", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/ComplianceCommandCenter.tsx"] },
  { route: "/commons", label: "OpenMedia", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/OpenMedia.tsx"] },
  { route: "/competitors", label: "Competitors", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/Competitors.tsx"] },
  { route: "/compliance", label: "Compliance", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Compliance.tsx"] },
  { route: "/conformity-assessment", label: "ConformityAssessment", nature: "rule_based",
    mechanism: "A deterministic instrument — fixed tables, templates or arithmetic over your input, so the same input gives the same output. No model call exists in this surface's code.",
    evidence: ["client/src/pages/ConformityAssessment.tsx"] },
  { route: "/connect", label: "SocialConnect", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/SocialConnect.tsx"] },
  { route: "/consensus", label: "BftConfig", nature: "rule_based",
    mechanism: "A deterministic instrument — fixed tables, templates or arithmetic over your input, so the same input gives the same output. No model call exists in this surface's code.",
    evidence: ["client/src/pages/BftConfig.tsx"] },
  { route: "/courses", label: "Courses", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Courses.tsx"] },
  { route: "/cyber-scan", label: "CyberScan", nature: "ai_system",
    mechanism: "The triage box sends pasted scanner output to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model ranks the findings and maps them to frameworks. The Article 50(1) notice is mounted above the input.",
    evidence: ["client/src/pages/CyberScan.tsx"] },
  { route: "/dashboard/progress", label: "StudentProgress", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/StudentProgress.tsx"] },
  { route: "/deepfake-protection", label: "Protect", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Protect.tsx"] },
  { route: "/demo", label: "DemoOS", nature: "ai_system",
    mechanism: "The guided demo answers questions through askSovereign, which sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/DemoOS.tsx", "client/src/lib/sovAsk.ts"] },
  { route: "/sovereign-twin", label: "SovereignTwin", nature: "rule_based",
    mechanism: "A canvas visualisation plus a passport-minting call to a signing endpoint (sha256 / Ed25519), not a model. No model call exists in this surface's code.",
    evidence: ["client/src/pages/SovereignTwin.tsx"] },
  { route: "/enter", label: "OsEnter", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/OsEnter.tsx"] },
  { route: "/enterprise-onboarding", label: "EnterpriseOnboarding", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/EnterpriseOnboarding.tsx"] },
  { route: "/eu-ai-act", label: "EUAIActGuide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/EUAIActGuide.tsx"] },
  { route: "/eu-ai-act-explained", label: "ActSummary", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/ActSummary.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/eu-ai-act-faq", label: "AiActFaq", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/AiActFaq.tsx"] },
  { route: "/evidence", label: "Evidence explorer", nature: "rule_based",
    mechanism: "Renders stored evidence records and checks their hash chain. It verifies integrity, not truth.",
    evidence: ["client/src/pages/EvidenceHub.tsx"] },
  { route: "/faq", label: "FAQ", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/FAQ.tsx"] },
  { route: "/fines", label: "Penalties", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/Penalties.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/foundation-models", label: "GpaiObligations", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/GpaiObligations.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/framework-catalog", label: "FrameworkCatalog", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/FrameworkCatalog.tsx"] },
  { route: "/frameworks/eu-ai-act", label: "EUAIActGuide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/EUAIActGuide.tsx"] },
  { route: "/frameworks/iso-42001", label: "ISO42001Guide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/ISO42001Guide.tsx"] },
  { route: "/frameworks/nist", label: "NISTAIRMFGuide", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/NISTAIRMFGuide.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/frameworks/tc260", label: "TC260Guide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/TC260Guide.tsx"] },
  { route: "/frequently-asked-questions", label: "FAQ", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/FAQ.tsx"] },
  { route: "/global-regulations", label: "GlobalRegulationTracker", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/GlobalRegulationTracker.tsx"] },
  { route: "/globe", label: "WorldGlobe", nature: "ai_system",
    mechanism: "'Ask the Sovereign about the world' sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The answer can also drive the globe (layers, flights) through a deterministic action layer. The Article 50(1) notice is mounted above the input.",
    evidence: ["client/src/pages/WorldGlobe.tsx", "client/src/lib/sovAsk.ts"] },
  { route: "/glossary", label: "Glossary", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/Glossary.tsx"] },
  { route: "/gods-eye", label: "CyberScan", nature: "ai_system",
    mechanism: "The triage box sends pasted scanner output to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model ranks the findings and maps them to frameworks. The Article 50(1) notice is mounted above the input.",
    evidence: ["client/src/pages/CyberScan.tsx"] },
  { route: "/governance-graph", label: "GovGraph", nature: "ai_system",
    mechanism: "The query box sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/GovGraph.tsx"] },
  { route: "/government", label: "GovernmentDashboard", nature: "rule_based",
    mechanism: "A dashboard preview: headline figures are withheld rather than invented and the panels carry an explicit illustrative-data notice. No model call exists in this surface's code.",
    evidence: ["client/src/pages/GovernmentDashboard.tsx"] },
  { route: "/government-dashboard", label: "GovernmentDashboard", nature: "rule_based",
    mechanism: "A dashboard preview: headline figures are withheld rather than invented and the panels carry an explicit illustrative-data notice. No model call exists in this surface's code.",
    evidence: ["client/src/pages/GovernmentDashboard.tsx"] },
  { route: "/gpai", label: "GpaiObligations", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/GpaiObligations.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/graph", label: "GovGraph", nature: "ai_system",
    mechanism: "The query box sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/GovGraph.tsx"] },
  { route: "/guides/eu-ai-act", label: "EUAIActGuide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/EUAIActGuide.tsx"] },
  { route: "/guides/iso-42001", label: "ISO42001Guide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/ISO42001Guide.tsx"] },
  { route: "/guides/nist-ai-rmf", label: "NISTAIRMFGuide", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/NISTAIRMFGuide.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/guides/tc260", label: "TC260Guide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/TC260Guide.tsx"] },
  { route: "/heatmap", label: "WatchdogMap", nature: "ai_system",
    mechanism: "The map Q&A sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/WatchdogMap.tsx"] },
  { route: "/high-risk-ai", label: "HighRiskSystems", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/HighRiskSystems.tsx"] },
  { route: "/high-risk-ai-systems", label: "HighRiskSystems", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/HighRiskSystems.tsx"] },
  { route: "/hive/:slug", label: "FrameworkHive", nature: "ai_system",
    mechanism: "The framework Q&A uses askSovereign, which sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/FrameworkHive.tsx", "client/src/lib/sovAsk.ts"] },
  { route: "/humanoids-poc", label: "PocShowcase", nature: "ai_system",
    mechanism: "The showcase Q&A sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/PocShowcase.tsx"] },
  { route: "/iso-42001", label: "ISO42001Guide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/ISO42001Guide.tsx"] },
  { route: "/iso-42001-vs-eu-ai-act", label: "Iso42001VsEuAct", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/Iso42001VsEuAct.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/iso-eu", label: "Iso42001VsEuAct", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/Iso42001VsEuAct.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/jobs", label: "Jobs", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/Jobs.tsx"] },
  { route: "/join", label: "SovereignRegistry", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/SovereignRegistry.tsx"] },
  { route: "/knowledge-base", label: "KnowledgeBase", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/KnowledgeBase.tsx"] },
  { route: "/login", label: "Login", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Login.tsx"] },
  { route: "/marketing", label: "MarketingHome", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/MarketingHome.tsx"] },
  { route: "/mcp-fleet", label: "McpFleet", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/McpFleet.tsx"] },
  { route: "/mcp-tools", label: "ToolCommons", nature: "rule_based",
    mechanism: "A search proxy over the tool-registry endpoint: your query is matched against the catalogue and matching tools are listed. Filtering is deterministic and no model call exists in this surface's code.",
    evidence: ["client/src/pages/ToolCommons.tsx"] },
  { route: "/network", label: "NetworkPage", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/NetworkPage.tsx"] },
  { route: "/nist-ai-rmf", label: "NISTAIRMFGuide", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/NISTAIRMFGuide.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/nist-eu", label: "NistVsEuAct", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/NistVsEuAct.tsx"] },
  { route: "/nist-vs-eu-ai-act", label: "NistVsEuAct", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/NistVsEuAct.tsx"] },
  { route: "/one-os", label: "PocShowcase", nature: "ai_system",
    mechanism: "The showcase Q&A sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/PocShowcase.tsx"] },
  { route: "/open-media", label: "OpenMedia", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/OpenMedia.tsx"] },
  { route: "/os", label: "OsLauncher", nature: "ai_system",
    mechanism: "The launcher command box posts to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/OsLauncher.tsx"] },
  { route: "/os-demo", label: "DemoOS", nature: "ai_system",
    mechanism: "The guided demo answers questions through askSovereign, which sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/DemoOS.tsx", "client/src/lib/sovAsk.ts"] },
  { route: "/oscal", label: "OscalStudio", nature: "rule_based",
    mechanism: "A deterministic instrument — fixed tables, templates or arithmetic over your input, so the same input gives the same output. No model call exists in this surface's code.",
    evidence: ["client/src/pages/OscalStudio.tsx"] },
  { route: "/our-difference", label: "WhyCSOAI", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/WhyCSOAI.tsx"] },
  { route: "/pdca", label: "PDCACycles", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/PDCACycles.tsx"] },
  { route: "/penalties", label: "Penalties", nature: "ai_system",
    mechanism: "The embedded 'Ask the Sovereign' panel (SovereignSpot) sends questions to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/Penalties.tsx", "client/src/components/SovereignSpot.tsx"] },
  { route: "/personal-protection", label: "Protect", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Protect.tsx"] },
  { route: "/poc", label: "PocShowcase", nature: "ai_system",
    mechanism: "The showcase Q&A sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/PocShowcase.tsx"] },
  { route: "/policy-generator", label: "PolicyGenerator", nature: "rule_based",
    mechanism: "A deterministic instrument — fixed tables, templates or arithmetic over your input, so the same input gives the same output. No model call exists in this surface's code.",
    evidence: ["client/src/pages/PolicyGenerator.tsx"] },
  { route: "/protect", label: "Protect", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Protect.tsx"] },
  { route: "/public-watchdog", label: "PublicWatchdog", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/PublicWatchdog.tsx"] },
  { route: "/pulse", label: "GovernancePulse", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/GovernancePulse.tsx"] },
  { route: "/recommendations", label: "Recommendations", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Recommendations.tsx"] },
  { route: "/register", label: "SovereignRegistry", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/SovereignRegistry.tsx"] },
  { route: "/registry", label: "RegistryAll", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/RegistryAll.tsx"] },
  { route: "/regulation-tracker", label: "GlobalRegulationTracker", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/GlobalRegulationTracker.tsx"] },
  { route: "/regulator", label: "RegulatorDashboard", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/RegulatorDashboard.tsx"] },
  { route: "/regulator-atlas", label: "RegulatorAtlas", nature: "ai_system",
    mechanism: "The atlas Q&A sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/RegulatorAtlas.tsx"] },
  { route: "/regulators", label: "RegulatorAtlas", nature: "ai_system",
    mechanism: "The atlas Q&A sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/RegulatorAtlas.tsx"] },
  { route: "/report", label: "IncidentReport", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/IncidentReport.tsx"] },
  { route: "/reports", label: "Reports", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Reports.tsx"] },
  { route: "/roi", label: "ROICalculator", nature: "rule_based",
    mechanism: "A deterministic instrument — fixed tables, templates or arithmetic over your input, so the same input gives the same output. No model call exists in this surface's code.",
    evidence: ["client/src/pages/ROICalculator.tsx"] },
  { route: "/roi-calculator", label: "ROICalculator", nature: "rule_based",
    mechanism: "A deterministic instrument — fixed tables, templates or arithmetic over your input, so the same input gives the same output. No model call exists in this surface's code.",
    evidence: ["client/src/pages/ROICalculator.tsx"] },
  { route: "/scan", label: "CyberScan", nature: "ai_system",
    mechanism: "The triage box sends pasted scanner output to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model ranks the findings and maps them to frameworks. The Article 50(1) notice is mounted above the input.",
    evidence: ["client/src/pages/CyberScan.tsx"] },
  { route: "/settings", label: "Settings", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Settings.tsx"] },
  { route: "/settings/notifications", label: "NotificationSettings", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/NotificationSettings.tsx"] },
  { route: "/signup", label: "Signup", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Signup.tsx"] },
  { route: "/simulate", label: "SovSpace", nature: "ai_system",
    mechanism: "Scenario verdicts are written by the live Sovereign chat endpoint (os.meok.ai/api/chat), a model prompted as the governance council. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/SovSpace.tsx"] },
  { route: "/sov-space", label: "SovSpace", nature: "ai_system",
    mechanism: "Scenario verdicts are written by the live Sovereign chat endpoint (os.meok.ai/api/chat), a model prompted as the governance council. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/SovSpace.tsx"] },
  { route: "/sov-towns", label: "SovTowns", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/SovTowns.tsx"] },
  { route: "/sov3", label: "Workbench", nature: "ai_system",
    mechanism: "The workbench asks the live Sovereign (askSovereign) to produce the governance artifact for the skill you pick. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/Workbench.tsx", "client/src/lib/sovAsk.ts"] },
  { route: "/sovereign-network", label: "NetworkPage", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/NetworkPage.tsx"] },
  { route: "/sovereign-space", label: "SovSpace", nature: "ai_system",
    mechanism: "Scenario verdicts are written by the live Sovereign chat endpoint (os.meok.ai/api/chat), a model prompted as the governance council. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/SovSpace.tsx"] },
  { route: "/system-card", label: "SystemCard", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/SystemCard.tsx"] },
  { route: "/systemcard", label: "SystemCard", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/SystemCard.tsx"] },
  { route: "/tc260", label: "TC260Guide", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/TC260Guide.tsx"] },
  { route: "/tool-commons", label: "ToolCommons", nature: "rule_based",
    mechanism: "A search proxy over the tool-registry endpoint: your query is matched against the catalogue and matching tools are listed. Filtering is deterministic and no model call exists in this surface's code.",
    evidence: ["client/src/pages/ToolCommons.tsx"] },
  { route: "/tools", label: "ToolCommons", nature: "rule_based",
    mechanism: "A search proxy over the tool-registry endpoint: your query is matched against the catalogue and matching tools are listed. Filtering is deterministic and no model call exists in this surface's code.",
    evidence: ["client/src/pages/ToolCommons.tsx"] },
  { route: "/towns", label: "SovTowns", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/SovTowns.tsx"] },
  { route: "/try", label: "TryCouncil", nature: "ai_system",
    mechanism: "The first pass (risk classification) runs locally on fixed rules; 'Convene the council' sends your system description to the live Sovereign chat endpoint (os.meok.ai/api/chat), where five model agents answer in role. The Article 50(1) notice is mounted above the input.",
    evidence: ["client/src/pages/TryCouncil.tsx"] },
  { route: "/usp", label: "WhyCSOAI", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/WhyCSOAI.tsx"] },
  { route: "/verify-certificate", label: "CertificateVerification", nature: "rule_based",
    mechanism: "A certificate ID lookup against the verification service, rendered deterministically. No model call exists in this surface's code.",
    evidence: ["client/src/pages/CertificateVerification.tsx"] },
  { route: "/watchdog-heatmap", label: "WatchdogMap", nature: "ai_system",
    mechanism: "The map Q&A sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/WatchdogMap.tsx"] },
  { route: "/watchdog-map", label: "WatchdogMap", nature: "ai_system",
    mechanism: "The map Q&A sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/WatchdogMap.tsx"] },
  { route: "/watchdog-signup", label: "WatchdogSignup", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/WatchdogSignup.tsx"] },
  { route: "/webhooks", label: "Webhooks", nature: "rule_based",
    mechanism: "Forms and tables over the account API. Rendering is deterministic (lookup, filtering, validation); no model call exists in this surface's code.",
    evidence: ["client/src/pages/Webhooks.tsx"] },
  { route: "/why", label: "WhyCSOAI", nature: "rule_based",
    mechanism: "Static guidance content with client-side navigation and filtering only. No model call exists in this surface's code.",
    evidence: ["client/src/pages/WhyCSOAI.tsx"] },
  { route: "/widget", label: "WidgetCourses", nature: "rule_based",
    mechanism: "A data display (registry, dashboard, map or list) with deterministic rendering. No model call exists in this surface's code.",
    evidence: ["client/src/pages/WidgetCourses.tsx"] },
  { route: "/workbench", label: "Workbench", nature: "ai_system",
    mechanism: "The workbench asks the live Sovereign (askSovereign) to produce the governance artifact for the skill you pick. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/Workbench.tsx", "client/src/lib/sovAsk.ts"] },
  { route: "/world", label: "WorldGlobe", nature: "ai_system",
    mechanism: "'Ask the Sovereign about the world' sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The answer can also drive the globe (layers, flights) through a deterministic action layer. The Article 50(1) notice is mounted above the input.",
    evidence: ["client/src/pages/WorldGlobe.tsx", "client/src/lib/sovAsk.ts"] },
  { route: "/world-data", label: "GovGraph", nature: "ai_system",
    mechanism: "The query box sends your input to the live Sovereign chat endpoint (os.meok.ai/api/chat), where a model writes the answer. The Art 50(1) notice for this surface is registered here and being wired; until the component ships, this registry entry is the disclosure.",
    evidence: ["client/src/pages/GovGraph.tsx"] },
];

export function surfaceFor(route: string): Surface {
  return (
    SURFACES.find((s) => s.route === route) ?? {
      route, label: route, nature: "unclassified",
      mechanism: "Not registered in client/src/lib/ai-surfaces.ts. Until it is classified it is treated under the strictest reading — as if it were an AI system.",
      evidence: [],
    }
  );
}

export const AI_SYSTEM_SURFACES = SURFACES.filter((s) => s.nature === "ai_system");

export const COUNTS = {
  total: SURFACES.length,
  rule_based: SURFACES.filter((s) => s.nature === "rule_based").length,
  ai_system: AI_SYSTEM_SURFACES.length,
  unclassified: SURFACES.filter((s) => s.nature === "unclassified").length,
};

/** Model SDKs present in package.json but never imported. Measured, not asserted. */
export const DECLARED_UNCALLED_SDKS = ["@anthropic-ai/sdk", "openai", "@google/generative-ai"];

/** Routes that resolve to a page file, of which SURFACES are the interactive ones. */
export const ROUTES_SCANNED = 311;

/** Distinct components (not routes) whose code calls the live chat endpoint. */
export const AI_SYSTEM_COMPONENTS = 14;

/** AI-system routes that mount <AISystemNotice> above the interaction today.
    The rest carry their disclosure in this registry while the component is wired. */
export const NOTICE_MOUNTED_ROUTES = ["/", "/instrument", "/globe", "/world", "/try", "/scan", "/cyber-scan", "/gods-eye", "/classifier"];

export const REGISTRY_VERSION = "2.0.0";
export const ASSESSED_AT = "2026-08-01";
