import { describe, expect, it } from "vitest";
import { gspcAxisDatasets, gspcBoardDataset } from "./datasetSchema";
import {
  RECORD_NOT_CLAIMED,
  RECORD_RELATED,
  RECORD_SLIDES,
} from "../data/deckWorlds/whereTheRecordLives";
import softwareHeritage from "../../../public/.well-known/software-heritage.json";

const SNAPSHOT = "swh:1:snp:894aa7e162eb90d4e66f1a549e4d133503f84c02";

describe("evidence discovery metadata", () => {
  it("does not label a Hugging Face landing page as a JSON download", () => {
    const axes = gspcAxisDatasets();
    expect(axes.length).toBeGreaterThan(0);
    for (const axis of axes) {
      expect(axis.url).toMatch(/^https:\/\/huggingface\.co\/datasets\/csoai\//);
      expect(axis.sameAs).toBe(axis.url);
      expect(axis).not.toHaveProperty("distribution");
    }
  });

  it("keeps the board API as the real machine-readable distribution", () => {
    expect(gspcBoardDataset(false).distribution).toEqual([
      {
        "@type": "DataDownload",
        encodingFormat: "application/json",
        contentUrl: "https://councilof.ai/api/gspc",
      },
    ]);
  });

  it("states the dated archive identity without claiming the current release", () => {
    const limits = RECORD_NOT_CLAIMED.join("\n");
    expect(limits).toContain(SNAPSHOT);
    expect(limits).toContain("not today's release");
    expect(limits).toContain("not endorsement");
    expect(limits).not.toContain("do not have a Software Heritage identifier");

    const archiveLink = RECORD_RELATED.find(
      (entry) => entry.href === "/.well-known/software-heritage.json",
    );
    expect(archiveLink?.what).toContain("dated snapshot");
    expect(RECORD_SLIDES[1].points?.some((point) =>
      point.text.includes("15 September 2026"),
    )).toBe(true);

    // The door is generated by scripts/watch_swh_archival.py, never hand-typed.
    expect(softwareHeritage.generated_by).toBe("scripts/watch_swh_archival.py");
    expect(softwareHeritage.primary_snapshot.swhid).toBe(SNAPSHOT);
    expect(softwareHeritage.primary_snapshot.origin).toBe(
      "https://github.com/CSOAI-ORG/councilof-ai",
    );
    expect(softwareHeritage.primary_snapshot.visit_status).toBe("full");
  });

  it("records a failed archival visit as a fact instead of assuming archival", () => {
    // The defect this guards: a save request answers "accepted" and its task
    // later fails, so the door must never read healthy on a failing origin.
    const canonical = softwareHeritage.origins.find(
      (o) => o.origin === "https://github.com/CSOAI-ORG/councilof-ai",
    );
    expect(canonical).toBeDefined();
    expect(canonical!.role).toBe("canonical");

    // Every origin carries an explicit state; none is silently omitted.
    for (const origin of softwareHeritage.origins) {
      expect(origin.state).toMatch(
        /^(ARCHIVED_CURRENT|ARCHIVED_STALE|ARCHIVAL_FAILING|NEVER_ARCHIVED|NOT_IN_ARCHIVE|FETCH_FAILED)$/,
      );
    }

    // When failures have accrued since the last good visit, they are listed,
    // and primary_snapshot must not pass itself off as the latest visit.
    if (canonical!.failed_visits_since_last_full.length > 0) {
      expect(canonical!.state).toBe("ARCHIVAL_FAILING");
      expect(softwareHeritage.primary_snapshot.is_latest_visit).toBe(false);
      expect(softwareHeritage.state).not.toBe("ARCHIVED_BY_THIRD_PARTY");
    }
  });
});
