/** Offline AXES snapshot for gspcAxes — not a count authority. Consumed only as rows. */
export const AXES = [
  { axis: "governance", bench: "GovBench", n: 237, macro_f1: 0.705, accuracy: 0.7, unparsed_rate: 0.0386, status: "MEASURED",
    colour: "#34d399", lng: 4.37, lat: 50.84, seat: "Brussels", instrument: "EU AI Act (Reg. 2024/1689)",
    task: "EU AI Act risk-tier classification",
    note: "v2 bank: 237 public items (+102 held back privately), imported 2026-08-05 from the AI Act Evaluation Benchmark (NCSR 'Demokritos', arXiv:2603.09435, CC-BY-4.0). The tuned governance specialist leads AND the lead is separ", dataset: "csoai/gspc-gov" },
  { axis: "safety", bench: "DefBench", n: 36, macro_f1: 0.944, accuracy: 0.944, unparsed_rate: 0.0541, status: "MEASURED",
    colour: "#f87171", lng: -0.12, lat: 51.5, seat: "London", instrument: "UK AI Safety Institute",
    task: "calibrated refusal on paired requests",
    note: "A base model holds the point lead but the lead is a TIE (McNemar p=0.69 vs qwen2.5:3b). Honestly reported: the tuned specialists do not own this axis.", dataset: "csoai/gspc-agi" },
  { axis: "provenance", bench: "ProvBench", n: 32, macro_f1: 0.776, accuracy: 0.781, unparsed_rate: 0.148, status: "MEASURED",
    colour: "#60a5fa", lng: -122.42, lat: 37.77, seat: "San Francisco", instrument: "C2PA Specification 2.4",
    task: "Article 50 marking survival by validity",
    note: "v3 bank (validity principle: a manifest present but whose binding no longer validates has NOT survived). The tuned specialist leads on points; TIE vs llama3.2:3b (p=0.77).", dataset: "csoai/gspc-prv" },
  { axis: "continuity", bench: "PQCBench", n: 33, macro_f1: 0.512, accuracy: 0.606, unparsed_rate: 0.0463, status: "MEASURED",
    colour: "#c084fc", lng: -77.27, lat: 39.14, seat: "Gaithersburg", instrument: "NIST FIPS 204 / ML-DSA",
    task: "post-quantum status of a cryptographic assumption",
    note: "The axis designed to discriminate across frontier models. The tuned specialist leads on points; flat TIE vs gemma3:12b (p=1.0).", dataset: "csoai/gspc-asi" },
  { axis: "conformance", bench: "MCPBench", n: 35, macro_f1: 0.735, accuracy: 0.743, unparsed_rate: 0.1338, status: "MEASURED",
    colour: "#fbbf24", lng: -122.33, lat: 47.61, seat: "Seattle", instrument: "Model Context Protocol 2026-07-28",
    task: "MCP tool conformance",
    note: "Canonical bank count 35 (supersedes the stale 11 in older matrices — registry v2). The tuned specialist leads on points; flat TIE vs mistral:7b (p=1.0).", dataset: "csoai/gspc-mcp" },
  { axis: "openness", bench: "OSSBench", n: 32, macro_f1: 0.875, accuracy: 0.875, unparsed_rate: 0.0493, status: "MEASURED",
    colour: "#2dd4bf", lng: -122.68, lat: 45.52, seat: "Portland", instrument: "OSI licence set",
    task: "licence reasoning versus intended use",
    note: "v2 bank (AGPL network trigger, directional compatibility, SSPL/ELv2/BSL service clauses). Canonical count 32 (supersedes stale 16). The tuned specialist leads on points; flat TIE vs gemma3:12b.", dataset: "csoai/gspc-oss" },
  { axis: "machinery-conformity", bench: "MachBench", n: 33, macro_f1: 0.465, accuracy: 0.545, unparsed_rate: 0.0558, status: "MEASURED",
    colour: "#fb923c", lng: 12.57, lat: 55.68, seat: "Copenhagen", instrument: "Machinery Reg (EU) 2023/1230 Annex I Part A — 14 Jan 2027",
    task: "Machinery Reg self-evolving safety-function classification (PART_A / OUT_OF_SCOPE / NOT_SAFETY_FUNCTION)",
    note: "A base model leads on points; TIE. Anchor: Machinery Reg (EU) 2023/1230 Annex I Part A items 5-6, applies 14 Jan 2027. Gold labels remain under legal review — measurement, not a conformity verdict.", dataset: "csoai/gspc-mach" },
  { axis: "care", bench: "CareBench", n: 199, macro_f1: 0.528, accuracy: 0.535, unparsed_rate: 0.1742, status: "MEASURED",
    colour: "#f472b6", lng: -3.19, lat: 55.95, seat: "Edinburgh", instrument: "paired protection / over-refusal design",
    task: "care-cost (protect × help) under paired conduct scenarios",
    note: "SEPARATED vs the best base (p=0.036) but NOT clear of the majority-class baseline — quote it only as 'separated from base models'. The fleet mean is 0.293 and the worst 5% of items carry harm 0.990 (CVaR, n=199): calibra", dataset: "csoai/gspc-care" },
  { axis: "cross-reality", bench: "XRAIV", n: 32, macro_f1: 0.803, accuracy: 0.812, unparsed_rate: 0.0247, status: "MEASURED",
    colour: "#a78bfa", lng: -1.26, lat: 51.75, seat: "Oxford", instrument: "EU AI Act, applied to agent conduct",
    task: "autonomous agent action authority (PROCEED / CONFIRM / REFUSE)",
    note: "A base model leads on points; TIE (p=0.065 — the closest near-miss on the board, still not separated at p<0.05). Bank: 32 scored (public + held-out split per the bank card).", dataset: "csoai/gspc-xr" },
  { axis: "detector-interop", bench: "DetBench", n: 33, macro_f1: 0.855, accuracy: 0.879, unparsed_rate: 0.1754, status: "MEASURED",
    colour: "#38bdf8", lng: 4.9, lat: 50.85, seat: "Brussels", instrument: "EU Code of Practice — interoperability due 2 Feb 2027",
    task: "cross-detector watermark interoperability matrix",
    note: "A base model leads on points; TIE, and NOT clear of the majority baseline. Methodology: POAI detector-interop. Code-of-Practice target 2 Feb 2027.", dataset: "csoai/gspc-det" },
  { axis: "art5-safeguard", bench: "Art5Bench", n: 36, macro_f1: 0.972, accuracy: 0.972, unparsed_rate: 0.0117, status: "MEASURED",
    colour: "#fb7185", lng: -77.04, lat: 38.9, seat: "Washington DC", instrument: "EU AI Act Art 5 — prohibited practices",
    task: "EU AI Act Article 5 prohibited-practice trip",
    note: "The tuned specialist leads on points at 0.972; TIE vs gemma3:12b (p=1.0) — the whole fleet is strong here (fleet mean 0.830). The NCII/CSAM corpus is never handled by CSOAI.", dataset: "csoai/gspc-art5" },
  { axis: "swarm", bench: "SwarmBench", n: 40, macro_f1: 0.494, accuracy: 0.975, unparsed_rate: 0.1868, status: "MEASURED",
    colour: "#94a3b8", lng: 139.69, lat: 35.68, seat: "Tokyo", instrument: "multi-agent coordination safety",
    task: "multi-agent coordination safety",
    note: "The honesty-clause gold template. Raw CIs on this bank LOOK disjoint but the paired test says p=1.0 (low-discrimination prompts) — the exact case the McNemar-primary rule exists for. TIE, and the interval is withheld by ", dataset: "csoai/gspc-swarm" },
  { axis: "affect", bench: "AffectBench", n: 41, macro_f1: 0.864, accuracy: 0.878, unparsed_rate: 0.0642, status: "MEASURED",
    colour: "#ec4899", lng: 4.35, lat: 50.85, seat: "Brussels", instrument: "EU AI Act Art 5(1)(a)/(b)/(f) + Art 50 — emotional & manipulation safety",
    task: "emotional & embodied safety (manipulation / disclosure / vulnerability)",
    note: "COUNSEL-PENDING: the legal gold labels and 1-5 severity bases await counsel review; this is a measurement of model behaviour against a counsel-pending key, NOT a legal verdict. The cleanest separation on the board: tuned", dataset: "csoai/gspc-affect" },
];
