export interface MarketGap {
  id: string;
  title: string;
  tam: string;
  urgency: "CRITICAL" | "High" | "Medium" | "Emerging";
  fit: "PERFECT" | "Good";
  description: string;
}

export const MARKET_GAPS: MarketGap[] = [
  {
    id: "001",
    title: "SMB AI Governance",
    tam: "$900M+",
    urgency: "High",
    fit: "PERFECT",
    description: "Small businesses need AI governance but cannot afford $10K+ compliance platforms.",
  },
  {
    id: "002",
    title: "EU AI Act SME Compliance (Aug 2026)",
    tam: "$500M+",
    urgency: "CRITICAL",
    fit: "PERFECT",
    description: "SMEs face the Article 50 deadline without tooling tuned for limited budgets.",
  },
  {
    id: "003",
    title: "Mid-Market Cost Barrier",
    tam: "$600M+",
    urgency: "High",
    fit: "PERFECT",
    description: "Mid-market companies are priced out of enterprise GRC suites.",
  },
  {
    id: "004",
    title: "Nonprofit AI Governance",
    tam: "$1–10B",
    urgency: "High",
    fit: "Good",
    description: "Nonprofits deploy AI for operations and fundraising but lack governance budgets.",
  },
  {
    id: "005",
    title: "Education AI Governance",
    tam: "$4–20B",
    urgency: "High",
    fit: "PERFECT",
    description: "Schools and universities need safe, transparent AI use policies and audits.",
  },
  {
    id: "006",
    title: "DORA Compliance Tooling",
    tam: "$400M+",
    urgency: "CRITICAL",
    fit: "PERFECT",
    description: "Financial entities in the EU need operational resilience evidence by January 2025.",
  },
  {
    id: "007",
    title: "Multi-Jurisdiction (EU/US/China)",
    tam: "$300M+",
    urgency: "High",
    fit: "PERFECT",
    description: "Global companies need one map that covers AI Act, NIST, and GB/T frameworks.",
  },
  {
    id: "008",
    title: "Real-Time Continuous Monitoring",
    tam: "$250M+",
    urgency: "Medium",
    fit: "PERFECT",
    description: "Point-in-time audits miss runtime AI behaviour; continuous monitoring is undersupplied.",
  },
  {
    id: "009",
    title: "Audit Trail Automation",
    tam: "$200M+",
    urgency: "High",
    fit: "Good",
    description: "Auditors need immutable, exportable evidence trails without manual assembly.",
  },
  {
    id: "010",
    title: "Shadow AI Detection",
    tam: "$500M+",
    urgency: "CRITICAL",
    fit: "PERFECT",
    description: "89% of AI use escapes governance; organisations cannot inventory unsanctioned tools.",
  },
  {
    id: "011",
    title: "Agentic AI Governance",
    tam: "$400M+",
    urgency: "CRITICAL",
    fit: "PERFECT",
    description: "Autonomous agents need identity, policy enforcement, and kill switches.",
  },
  {
    id: "012",
    title: "Africa AI Governance",
    tam: "$1.4B+",
    urgency: "Medium",
    fit: "Good",
    description: "54 countries need affordable, localised governance infrastructure.",
  },
  {
    id: "013",
    title: "Southeast Asia Governance",
    tam: "$1B+",
    urgency: "Medium",
    fit: "Good",
    description: "Fast-growing AI adoption across ASEAN outpaces regional tooling.",
  },
  {
    id: "014",
    title: "MENA AI Governance",
    tam: "$1B+",
    urgency: "Medium",
    fit: "Good",
    description: "Governance demand in the Middle East and North Africa exceeds local supply.",
  },
  {
    id: "015",
    title: "API-First / Developer-Centric",
    tam: "$200M+",
    urgency: "High",
    fit: "PERFECT",
    description: "Developers want governance-as-code, not GUI-only enterprise suites.",
  },
  {
    id: "016",
    title: "Open Source Governance Stack",
    tam: "$100M+",
    urgency: "Medium",
    fit: "PERFECT",
    description: "Community-driven governance tooling with transparent, forkable components.",
  },
  {
    id: "017",
    title: "Edge/IoT AI Governance",
    tam: "$300M+",
    urgency: "Emerging",
    fit: "Good",
    description: "Models running on edge devices need lightweight certification and telemetry.",
  },
  {
    id: "018",
    title: "Vertical SaaS Integration",
    tam: "$1B+",
    urgency: "High",
    fit: "PERFECT",
    description: "Vertical SaaS products need embedded AI governance for their customers.",
  },
  {
    id: "019",
    title: "Autonomous Systems Governance",
    tam: "$1B+",
    urgency: "Emerging",
    fit: "PERFECT",
    description: "Robotics, drones, and vehicles need safety certification beyond software.",
  },
  {
    id: "020",
    title: "Healthcare AI Governance",
    tam: "$400M+",
    urgency: "High",
    fit: "Good",
    description: "Clinical AI requires HIPAA, MDR, and EU AI Act high-risk compliance.",
  },
  {
    id: "021",
    title: "Pharma GxP AI Governance",
    tam: "$150M+",
    urgency: "High",
    fit: "Good",
    description: "Validated systems for drug discovery and manufacturing AI.",
  },
  {
    id: "022",
    title: "Insurance AI Governance",
    tam: "$150M+",
    urgency: "Medium",
    fit: "Good",
    description: "Pricing, claims, and underwriting models need fair-lending and risk governance.",
  },
  {
    id: "023",
    title: "Manufacturing/OT AI Governance",
    tam: "$300M+",
    urgency: "Medium",
    fit: "PERFECT",
    description: "OT environments need safety-certified AI without cloud dependency.",
  },
  {
    id: "024",
    title: "MSP Enablement",
    tam: "$13B+",
    urgency: "CRITICAL",
    fit: "PERFECT",
    description: "51% of MSPs are blocked from offering AI governance; enablement tooling is missing.",
  },
  {
    id: "025",
    title: "Legal Industry AI Governance",
    tam: "$600M+",
    urgency: "Medium",
    fit: "Good",
    description: "Law firms and legal-tech tools need client-confidential AI controls.",
  },
];

export const TOTAL_WHITE_SPACE = "$20B+";
