#!/usr/bin/env bash
# Re-render the committed YAML from the chart and the provider package. Needs helm + python3.
#   rendered/panel-sandbox.yaml  sandbox mode, NO namespace field (Import YAML / oc apply -n <ns>)
#   rendered/panel-cluster.yaml  console-plugin mode for a cluster where you are cluster-admin
set -euo pipefail
cd "$(dirname "$0")/.."
node ../vendor-panel.mjs
H=charts/gspc-evidence-plugin
mkdir -p deploy/rendered
{ echo "# GENERATED by deploy/render.sh (helm template, values-sandbox.yaml). Namespace-scoped objects only; no namespace field."
  helm template gspc-evidence "$H" -f "$H/values-sandbox.yaml" | grep -v '^  namespace: default$'; } > deploy/rendered/panel-sandbox.yaml
{ echo "# GENERATED by deploy/render.sh (helm template, cluster mode). Contains the cluster-scoped ConsolePlugin: cluster-admin only."
  helm template gspc-evidence "$H" --namespace gspc-evidence \
    --set plugin.image=image-registry.openshift-image-registry.svc:5000/gspc-evidence/gspc-evidence-plugin:0.1.0; } > deploy/rendered/panel-cluster.yaml
python3 deploy/llama-stack-provider/render.py
