#!/usr/bin/env python3
"""publish_scoreboard.py — consume measured bench + arena rounds and emit a SIGNED,
content-addressed per-axis leaderboard, then stage it into the repo surface.

This is the pod-canonical publish step: measure (axis-engine / EAT) -> grade ->
per-axis Elo (with CI) -> content_id + Ed25519 -> write arena_scoreboard.json.
A separate step copies it to the councilof.ai /api/arena/scoreboard surface.

Inputs (all optional; grab whatever is present):
  --rounds   /workspace/arena_rounds.jsonl      (pairwise rounds, generated by axis_arena.py)
  --bench    /workspace/bench/*.jsonl           (per-model per-axis responses from pod-bench/axis-engine)
  --key      estate signing key
  --out      output JSON
  --pg       pubkey to also record for the verify path

Scoring of --bench: deterministic. Each axis's bank item has an `expected` keyword or
`must_inc` set; benchmark responses are graded on keyword presence. This mirrors the
estate's measure-not-certify doctrine (never LLM-as-judge).
"""
import argparse, glob, hashlib, json, os
from collections import defaultdict
from pathlib import Path
from elo import EloSystem
from canon import cjson

def content_id(obj): return hashlib.sha256(cjson(obj).encode()).hexdigest()
def sign(cid, keyfile):
    from nacl.signing import SigningKey
    return SigningKey(keyfile.read_bytes()).sign(cid.encode()).signature.hex()

def grade(text, expected_keywords=None, must_inc=None):
    """Deterministic keyword grade (0/1). Returns None if unanswerable."""
    if not text or not text.strip():
        return None
    a = text.lower()
    if expected_keywords:
        return int(any(k in a for k in expected_keywords))
    if must_inc:
        hits = sum(1 for k in must_inc if k in a)
        return int(hits >= max(1, len(must_inc) // 2))
    return None

def load_banks_grades(root="/workspace/banks-all"):
    """axis -> list of {text, expected, must_inc} for grading bench responses."""
    banks = {}
    for f in sorted(glob.glob(f"{root}/gspc-*.jsonl")):
        axis = Path(f).stem.replace("gspc-", "")
        items = []
        for l in open(f):
            l = l.strip()
            if not l: continue
            try:
                d = json.loads(l)
                items.append(d)
            except Exception:
                pass
        if items:
            banks[axis] = items
    return banks

# OOWM fleet per owner directive — tiny models (0.5b/1.5b/3b/4b) are NOT part of the
# measured leaderboard. This is the fleet we measure and rank.
OOWM_FLEET = {"30b", "14b", "12b", "8b", "7b"}
def is_oowm(model: str) -> bool:
    """A model is in the OOWM fleet iff it matches one of the big sizes and is not a
    known tiny/mock tag. Exact-name match on the fleet sizes (30b/14b/12b/8b/7b)."""
    return any(s in model for s in OOWM_FLEET)

def build_axis_elo_from_bench(bench_files, banks):
    """Derive per-axis per-model pass-rate + a quasi-Elo from bench grade counts."""
    axis_model_grade = defaultdict(lambda: defaultdict(lambda: [0, 0]))  # axis->model->[pass,total]
    for bf in bench_files:
        for l in open(bf):
            l = l.strip()
            if not l: continue
            try:
                d = json.loads(l)
            except Exception:
                continue
            axis, model, resp = d.get("axis"), d.get("model"), d.get("response", "")
            if not axis or not model:
                continue
            # grade against the axis's bank expected/must_inc
            items = banks.get(axis)
            if not items:
                continue
            # a bench record doesn't carry the item text; grade on a reference probe set
            # using bank keywords best-effort. If no keyword, skip.
            for it in items:
                g = grade(resp, it.get("expected") and [str(it["expected"])],
                          it.get("must_inc"))
                if g is not None:
                    axis_model_grade[axis][model][1] += 1
                    axis_model_grade[axis][model][0] += g
                    break
    out = {}
    for axis, ms in axis_model_grade.items():
        model_stats = {}
        for m, (p, t) in ms.items():
            if t == 0: continue
            # OOWM fleet only — exclude the banned tiny models from the measured board.
            if not is_oowm(m):
                continue
            model_stats[m] = {"pass": p, "n": t, "rate": round(p / t, 3)}
        if model_stats:
            out[axis] = {"n_rounds": sum(v["n"] for v in model_stats.values()),
                         "models": model_stats}
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rounds", default="/workspace/arena_rounds.jsonl")
    ap.add_argument("--bench", action="append", default=[])
    ap.add_argument("--benchdir", default="/workspace/bench")
    ap.add_argument("--key", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--pg", default=None)
    args = ap.parse_args()

    banks = load_banks_grades()

    rounds = []
    if os.path.exists(args.rounds):
        for l in open(args.rounds):
            l = l.strip()
            if l:
                try: rounds.append(json.loads(l))
                except Exception: pass

    bfiles = list(args.bench)
    if os.path.isdir(args.benchdir):
        bfiles += sorted(glob.glob(f"{args.benchdir}/*.jsonl"))
    bench_axes = build_axis_elo_from_bench(bfiles, banks)

    body = {
        "schema": "csoai.signed-arena-leaderboard/0.1",
        "generation": "2026-08-23-b",
        "as_of": max((r.get("ts", "") for r in rounds), default="") or None,
        "n_rounds": len(rounds),
        "bench_sources": len(bfiles),
        "axis_pass_rates": bench_axes,
        "doctrine": "measurement, not certification — every score carries n; thin-n is insufficient to rank",
    }
    cid = content_id(body)
    body["signature"] = {"content_id": cid, "sig": sign(cid, Path(args.key)),
                         "kid": "did:web:csoai.org#card-attestation-1"}
    if args.pg:
        body["signature"]["pubkey"] = args.pg
    Path(args.out).write_text(json.dumps(body, indent=2))
    print(f"PUBLISHED -> {args.out} | content_id={cid[:16]} | rounds={len(rounds)} bench={len(bfiles)}")

if __name__ == "__main__":
    main()
