"""GSPC get_card for Dify. Generated by scripts/harness-x/render.mjs — do not hand-edit."""
import json
import urllib.request
from collections.abc import Generator
from typing import Any

from dify_plugin import Tool
from dify_plugin.entities.tool import ToolInvokeMessage

DOOR = "https://councilof.ai/mcp/free"


class GetCardTool(Tool):
    def _invoke(self, tool_parameters: dict[str, Any]) -> Generator[ToolInvokeMessage, None, None]:
        args = {k: v for k, v in tool_parameters.items() if v not in (None, "")}
        body = json.dumps({"jsonrpc": "2.0", "id": 1, "method": "tools/call", "params": {"name": "get_card", "arguments": args}}).encode()
        req = urllib.request.Request(DOOR, data=body, headers={"content-type": "application/json", "accept": "application/json, text/event-stream"})
        with urllib.request.urlopen(req, timeout=60) as r:
            text = r.read().decode("utf-8")
        frames = [line[5:].strip() for line in text.splitlines() if line.startswith("data:")]
        msg = json.loads(frames[-1] if frames else text)
        result = msg.get("result") or {}
        yield self.create_json_message(result.get("structuredContent") or {"error": msg.get("error")})
