import { Toaster } from "@/components/ui/sonner";
import { TooltipProvider } from "@/components/ui/tooltip";
import NotFound from "@/pages/NotFound";
import { Route, Switch, useLocation, Redirect } from "wouter";
import { useEffect, lazy, Suspense } from "react";
import ErrorBoundary from "./components/ErrorBoundary";
import { SectionLoader } from "./components/PageLoader";
const SovOS = lazy(() => import("./pages/SovOS"));
import { ThemeProvider } from "./contexts/ThemeContext";
import { AuthProvider } from "./contexts/AuthContext";
import { Header } from "./components/Header";
import { Footer } from "./components/Footer";
import WidgetLayout from "./components/widget/WidgetLayout";
import WidgetCourses from "./components/widget/WidgetCourses";
import WidgetCoursePlayer from "./components/widget/WidgetCoursePlayer";
import { SkipNavigation } from "./components/SkipNavigation";
const Landing = lazy(() => import("./pages/Landing"));
const CouncilConsole = lazy(() => import("./components/CouncilConsole"));
const CouncilLobby = lazy(() => import("./components/lobby/CouncilLobby"));
const AgUiBridge = lazy(() => import("./pages/AgUiBridge"));
const RankingsBridge = lazy(() =>
  import("./pages/AgUiBridge").then((m) => ({ default: m.RankingsBridge })),
);
const ModelRegistry = lazy(() => import("./pages/ModelRegistry"));
const ToolCommons = lazy(() => import("./pages/ToolCommons"));
const Workbench = lazy(() => import("./pages/Workbench"));
const Ecosystem = lazy(() => import("./pages/Ecosystem"));
const Dashboard = lazy(() => import("./pages/Dashboard"));
const AssessTool = lazy(() => import("./pages/AssessTool"));
const Watchdog = lazy(() => import("./pages/Watchdog"));
const GspcScoreboard = lazy(() => import("./pages/GspcScoreboard"));
const GSPCVerify = lazy(() => import("./pages/GSPCVerify"));
const CouncilSpace = lazy(() => import("./pages/CouncilSpace"));
const Methodology = lazy(() => import("./pages/Methodology"));
const Honesty = lazy(() => import("./pages/Honesty"));
const Login = lazy(() => import("./pages/Login"));
const NewHomeV3 = lazy(() => import("./pages/NewHome-v3"));
const NotFoundPage = lazy(() => import("./pages/NotFound"));
import { ThemeProvider as TP } from "./contexts/ThemeContext";
