import { createElement } from "react";
import { Route, Redirect } from "wouter";
import {
  AISystems,
  Academy,
  AccountBrief,
  Accreditation,
  ActSummary,
  ActTimeline,
  Admin,
  AgentCouncil,
  AgentCouncilFeature,
  AgentGovernance,
  AgentRegistry,
  Agents,
  AiActFaq,
  AiGovernanceHub,
  ApiDocs,
  ApiKeys,
  Article50,
  Article50Pack,
  AssessTool,
  BadgesPage,
  Billing,
  Blog,
  BulkAISystemImport,
  CaseStudies,
  CertificateVerification,
  CertificationExam,
  CertificationResults,
  CertificationV2,
  CharterArticle,
  Compare,
  ComparisonPage,
  Compliance,
  ComplianceMonitoring,
  ComplianceScorecard,
  ConformityAssessment,
  CookiePolicy,
  Council,
  CouncilOsRefinery,
  CoursePlayer,
  Courses,
  Cra,
  Crosswalk,
  Crosswalks,
  Dashboard,
  DashboardMeasurement,
  DataProcessingAgreement,
  Disclaimers,
  Dora,
  Dragonfly,
  DriftProduct,
  Enterprise,
  EnterpriseDashboard,
  EnterpriseOnboarding,
  EuActClassifier,
  EuActVsGdpr,
  EvidenceHub,
  ExamReview,
  FAQ,
  Fedramp,
  FoundingCouncilAgreement,
  FoundingMembers,
  FreeCoursePlayer,
  GlobalAIRegulation,
  GlobalRegulationTracker,
  Glossary,
  Gone,
  GovGraph,
  GovernanceLayer,
  GovernmentDashboard,
  HighRiskSystems,
  IncidentReport,
  IndustrySolutions,
  Integrations,
  Intel,
  Iso42001VsEuAct,
  Jobs,
  KnowledgeBase,
  Landing,
  LegacyBridge,
  LicensingAgreement,
  Lineage,
  MembershipAgreement,
  MyApplications,
  MyCertificates,
  MyCourses,
  Nis2,
  NistVsEuAct,
  NotFound,
  NotificationSettings,
  OnboardOS,
  OpenMedia,
  OscalStudio,
  PDCACycles,
  PDCAFrameworkFeature,
  PDCASimulator,
  PartnersAdvisory,
  Penalties,
  PlansPage,
  Playbooks,
  PocShowcase,
  Pressroom,
  Pricing,
  PrivacyPolicy,
  ProsperityFund,
  PublicDashboard,
  PublicHome,
  PublicWatchdog,
  ROICalculator,
  Readiness,
  ReadinessAssessment,
  RealWorldMap,
  Recommendations,
  RegionsMap,
  RegistryAll,
  RegulatorDashboard,
  RelevanceMap,
  Reports,
  RiskAssessment,
  RiskHeatmap,
  SOAIPDCAFramework,
  SectorsAtlas,
  ServiceLevelAgreement,
  Settings,
  SocialConnect,
  SovereignHub,
  SovereignMinds,
  StatusPage,
  StudentProgress,
  Technology,
  Temples,
  TermsOfService,
  ToolCommons,
  Traction,
  TrainingCertificationFeature,
  TrainingHub,
  TrainingV2,
  TrustCenter,
  VerifyCertificate,
  VulnerabilityDisclosure,
  Watchdog,
  WatchdogJobsFeature,
  WatchdogLeaderboard,
  WatchdogMap,
  WatchdogSignup,
  Webhooks,
  Workbench,
  WorkspacePage
} from "./AppLazy";

export function AppRoutesB() {
  return [
    <Route path="/ai-act-faq" component={AiActFaq} />,
    <Route path="/eu-ai-act-faq" component={AiActFaq} />,
    <Route path="/conformity-assessment" component={ConformityAssessment} />,
    <Route path="/ai-governance" component={AiGovernanceHub} />,
    <Route path="/ai-governance-guide" component={AiGovernanceHub} />,
    <Route path="/high-risk-ai-systems" component={HighRiskSystems} />,
    <Route path="/classifier" component={EuActClassifier} />,
    <Route path="/report" component={IncidentReport} />,
    <Route path="/high-risk-ai" component={HighRiskSystems} />,
    <Route path="/ai-act-summary" component={ActSummary} />,
    <Route path="/eu-ai-act-explained" component={ActSummary} />,
    <Route path="/colorado-ai-act">{() => <UsStateAct state="colorado" />}</Route>,
    <Route path="/texas-ai-act">{() => <UsStateAct state="texas" />}</Route>,
    <Route path="/california-ai-law">{() => <UsStateAct state="california" />}</Route>,
    <Route path="/connect" component={SocialConnect} />,
    <Route path="/sovereign">{() => <Redirect to="/me" />}</Route>,
    <Route path="/me" component={SovereignHub} />,
    <Route path="/nist-vs-eu-ai-act" component={NistVsEuAct} />,
    <Route path="/nist-eu" component={NistVsEuAct} />,
    <Route path="/iso-42001-vs-eu-ai-act" component={Iso42001VsEuAct} />,
    <Route path="/healthcare-ai-act">{() => <SectorAct sector="healthcare" />}</Route>,
    <Route path="/finance-ai-act">{() => <SectorAct sector="finance" />}</Route>,
    <Route path="/hr-ai-act">{() => <SectorAct sector="hr" />}</Route>,
    <Route path="/energy-ai-act">{() => <SectorAct sector="energy" />}</Route>,
    <Route path="/pharma-ai-act">{() => <SectorAct sector="pharma" />}</Route>,
    <Route path="/defence-ai-act">{() => <SectorAct sector="defence" />}</Route>,
    <Route path="/vanta-alternative">{() => <AltPage comp="vanta" />}</Route>,
    <Route path="/onetrust-alternative">{() => <AltPage comp="onetrust" />}</Route>,
    <Route path="/credo-ai-alternative">{() => <AltPage comp="credo" />}</Route>,
    <Route path="/eu-ai-act-vs-gdpr" component={EuActVsGdpr} />,
    <Route path="/ai-act-vs-gdpr" component={EuActVsGdpr} />,
    <Route path="/eu-ai-act-timeline" component={ActTimeline} />,
    <Route path="/ai-act-timeline" component={ActTimeline} />,
    <Route path="/iso-eu" component={Iso42001VsEuAct} />,
    <Route path="/fines" component={Penalties} />,
    <Route path="/all" component={RegistryAll} />,
    <Route path="/bft">{() => <Redirect to="/council" />}</Route>,
    <Route path="/consensus">{() => <Redirect to="/council" />}</Route>,
    <Route path="/world">{() => <Redirect to="/gspc-arena?view=globe" />}</Route>,
    <Route path="/map-regions" component={RegionsMap} />,
    <Route path="/compare" component={Compare} />,
    <Route path="/vs" component={Compare} />,
    <Route path="/vs/:slug">{(p: any) => <Compare focus={p.slug} />}</Route>,
    <Route path="/vs-competitors" component={Compare} />,
    <Route path="/rfc-0024" component={Fedramp} />,
    <Route path="/aug-2026" component={Readiness} />,
    <Route path="/governance-council" component={Agents} />,
    <Route path="/council-vs-agents" component={Agents} />,
    <Route path="/fedramp" component={Fedramp} />,
    <Route path="/oscal-readiness" component={Fedramp} />,
    <Route path="/readiness" component={Readiness} />,
    <Route path="/agents" component={Agents} />,
    <Route path="/press" component={Pressroom} />,
    <Route path="/pressroom" component={Pressroom} />,
    <Route path="/sector-atlas" component={SectorsAtlas} />,
    <Route path="/learn" component={Academy} />,
    <Route path="/tracks" component={Academy} />,
    <Route path="/four-wings" component={Dragonfly} />,
    <Route path="/industry-playbooks" component={Playbooks} />,
    <Route path="/framework-temples" component={Temples} />,
    <Route path="/relevance-map" component={RelevanceMap} />,
    <Route path="/rediscovered" component={Lineage} />,
    <Route path="/voice" component={SovereignMinds} />,
    <Route path="/sov-towns">{() => <Redirect to="/gspc-arena?view=towns" />}</Route>,
    <Route path="/crown-jewels">{() => <Redirect to="/" />}</Route>,
    <Route path="/cobol" component={LegacyBridge} />,
    <Route path="/risk-heatmap" component={RiskHeatmap} />,
    <Route path="/webhooks" component={Webhooks} />,
    <Route path="/evidence" component={EvidenceHub} />,
    <Route path="/oscal" component={OscalStudio} />,
    <Route path="/sovereign-town">{() => <Redirect to="/gspc-arena?view=towns" />}</Route>,
    <Route path="/prosperity" component={ProsperityFund} />,
    <Route path="/prosperity-fund" component={ProsperityFund} />,
    <Route path="/founding-members" component={FoundingMembers} />,
    <Route path="/byzantine">{() => <Redirect to="/council" />}</Route>,
    <Route path="/council" component={Council} />,
    <Route path="/public-watchdog" component={PublicWatchdog} />,
    <Route path="/government" component={GovernmentDashboard} />,
    <Route path="/government-dashboard" component={GovernmentDashboard} />,
    <Route path="/landing" component={Landing} />,
    <Route path="/dashboard/measurement" component={DashboardMeasurement} />,
    <Route path="/dashboard" component={Dashboard} />,
    <Route path="/ai-systems" component={AISystems} />,
    <Route path="/risk-assessment" component={RiskAssessment} />,
    <Route path="/assess" component={AssessTool} />,
    <Route path="/compliance" component={Compliance} />,
    <Route path="/agent-council" component={AgentCouncil} />,
    <Route path="/watchdog" component={Watchdog} />,
    <Route path="/watchdog-map" component={WatchdogMap} />,
    <Route path="/heatmap" component={WatchdogMap} />,
    <Route path="/watchdog-heatmap" component={WatchdogMap} />,
    <Route path="/poc" component={PocShowcase} />,
    <Route path="/humanoids-poc" component={PocShowcase} />,
    <Route path="/one-os" component={PocShowcase} />,
    <Route path="/reports" component={Reports} />,
    <Route path="/settings" component={Settings} />,
    <Route path="/settings/billing" component={Billing} />,
    <Route path="/settings/notifications" component={NotificationSettings} />,
    <Route path="/watchdog-signup" component={WatchdogSignup} />,
    <Route path="/training-hub" component={TrainingHub} />,
    <Route path="/drift-product" component={DriftProduct} />,
    <Route path="/training" component={TrainingV2} />,
    <Route path="/courses" component={Courses} />,
    <Route path="/my-courses" component={MyCourses} />,
    <Route path="/dashboard/progress" component={StudentProgress} />,
    <Route path="/courses/:id/learn" component={CoursePlayer} />,
    <Route path="/free-course/:courseId" component={FreeCoursePlayer} />,
    <Route path="/verify-certificate/:id" component={VerifyCertificate} />,
    <Route path="/features/33-agent-council" component={AgentCouncilFeature} />,
    <Route path="/features/pdca-framework" component={PDCAFrameworkFeature} />,
    <Route path="/features/training-certification" component={TrainingCertificationFeature} />,
    <Route path="/features/watchdog-jobs" component={WatchdogJobsFeature} />,
    <Route path="/certification" component={CertificationV2} />,
    <Route path="/certification/exam" component={CertificationExam} />,
    <Route path="/certification/results" component={CertificationResults} />,
    <Route path="/certificates" component={MyCertificates} />,
    <Route path="/certification/review" component={ExamReview} />,
    <Route path="/workbench" component={Workbench} />,
    <Route path="/jobs" component={Jobs} />,
    <Route path="/my-applications" component={MyApplications} />,
    <Route path="/public" component={PublicHome} />,
    <Route path="/admin" component={Admin} />,
    <Route path="/api-docs" component={ApiDocs} />,
    <Route path="/api-keys" component={ApiKeys} />,
    <Route path="/pdca" component={PDCACycles} />,
    <Route path="/transparency" component={PublicDashboard} />,
    <Route path="/public-dashboard">{() => <Redirect to="/transparency" />}</Route>,
    <Route path="/scorecard/:systemId" component={ComplianceScorecard} />,
    <Route path="/knowledge-base" component={KnowledgeBase} />,
    <Route path="/enterprise-onboarding" component={EnterpriseOnboarding} />,
    <Route path="/pricing" component={PlansPage} />,
    <Route path="/pricing-legacy" component={Pricing} />,
    <Route path="/leaderboard" component={WatchdogLeaderboard} />,
    <Route path="/regulator" component={RegulatorDashboard} />,
    <Route path="/blog" component={Blog} />,
    <Route path="/recommendations" component={Recommendations} />,
    <Route path="/accreditation" component={Accreditation} />,
    <Route path="/soai-pdca" component={SOAIPDCAFramework} />,
    <Route path="/pdca-simulator" component={PDCASimulator} />,
    <Route path="/verify-certificate" component={CertificateVerification} />,
    <Route path="/enterprise" component={Enterprise} />,
    <Route path="/enterprise-dashboard" component={EnterpriseDashboard} />,
    <Route path="/compliance-monitoring" component={ComplianceMonitoring} />,
    <Route path="/bulk-import" component={BulkAISystemImport} />,
    <Route path="/membership-agreement" component={MembershipAgreement} />,
    <Route path="/legal/membership" component={MembershipAgreement} />,
    <Route path="/founding-council-agreement" component={FoundingCouncilAgreement} />,
    <Route path="/legal/founding-council" component={FoundingCouncilAgreement} />,
    <Route path="/licensing-agreement" component={LicensingAgreement} />,
    <Route path="/legal/licensing" component={LicensingAgreement} />,
    <Route path="/privacy-policy" component={PrivacyPolicy} />,
    <Route path="/privacy" component={PrivacyPolicy} />,
    <Route path="/legal/privacy" component={PrivacyPolicy} />,
    <Route path="/terms-of-service" component={TermsOfService} />,
    <Route path="/terms" component={TermsOfService} />,
    <Route path="/legal/terms" component={TermsOfService} />,
    <Route path="/disclaimers" component={Disclaimers} />,
    <Route path="/legal/disclaimers" component={Disclaimers} />,
    <Route path="/dpa" component={DataProcessingAgreement} />,
    <Route path="/data-processing-agreement" component={DataProcessingAgreement} />,
    <Route path="/legal/dpa" component={DataProcessingAgreement} />,
    <Route path="/cookies" component={CookiePolicy} />,
    <Route path="/cookie-policy" component={CookiePolicy} />,
    <Route path="/legal/cookies" component={CookiePolicy} />,
    <Route path="/sla" component={ServiceLevelAgreement} />,
    <Route path="/service-level-agreement" component={ServiceLevelAgreement} />,
    <Route path="/legal/sla" component={ServiceLevelAgreement} />,
    <Route path="/global-regulations" component={GlobalRegulationTracker} />,
    <Route path="/regulation-tracker" component={GlobalRegulationTracker} />,
    <Route path="/faq" component={FAQ} />,
    <Route path="/frequently-asked-questions" component={FAQ} />,
    <Route path="/glossary" component={Glossary} />,
    <Route path="/ai-glossary" component={Glossary} />,
    <Route path="/readiness-assessment" component={ReadinessAssessment} />,
    <Route path="/assessment" component={ReadinessAssessment} />,
    <Route path="/industry-solutions" component={IndustrySolutions} />,
    <Route path="/industries" component={IndustrySolutions} />,
    <Route path="/partners" component={PartnersAdvisory} />,
    <Route path="/advisory" component={PartnersAdvisory} />,
    <Route path="/case-studies" component={CaseStudies} />,
    <Route path="/trust-center" component={TrustCenter} />,
    <Route path="/security" component={TrustCenter} />,
    <Route path="/traction" component={Traction} />,
    <Route path="/comparison" component={ComparisonPage} />,
    <Route path="/roi-calculator" component={ROICalculator} />,
    <Route path="/roi" component={ROICalculator} />,
    <Route path="/technology" component={Technology} />,
    <Route path="/architecture" component={Technology} />,
    <Route path="/integrations" component={Integrations} />,
    <Route path="/ecosystem" component={Integrations} />,
    <Route path="/crosswalks" component={Crosswalks} />,
    <Route path="/crosswalk" component={Crosswalk} />,
    <Route path="/agent-governance" component={AgentGovernance} />,
    <Route path="/agent-registry" component={AgentRegistry} />,
    <Route path="/global-ai-regulation" component={GlobalAIRegulation} />,
    <Route path="/cra" component={Cra} />,
    <Route path="/nis2" component={Nis2} />,
    <Route path="/vulnerability-disclosure" component={VulnerabilityDisclosure} />,
    <Route path="/intel" component={Intel} />,
    <Route path="/workspace" component={WorkspacePage} />,
    <Route path="/os" component={CouncilOsRefinery} />,
    <Route path="/brief" component={AccountBrief} />,
    <Route path="/article-50" component={Article50} />,
    <Route path="/packs/eu-article-50" component={Article50Pack} />,
    <Route path="/governance-layer" component={GovernanceLayer} />,
    <Route path="/dora" component={Dora} />,
    <Route path="/framework-crosswalks" component={Crosswalks} />,
    <Route path="/charter/article/:id" component={CharterArticle} />,
    <Route path="/404" component={NotFound} />,
    <Route path="/gone-space" component={Gone} />,
    <Route path="/sov-space">{() => <Redirect to="/gone-space" />}</Route>,
    <Route path="/sovereign-space">{() => <Redirect to="/gone-space" />}</Route>,
    <Route path="/stripe-checkout.js" component={Gone} />,
    <Route path="/simulate">{() => <Redirect to="/gspc-arena" />}</Route>,
    <Route path="/badges" component={BadgesPage} />,
    <Route path="/authority" component={BadgesPage} />,
    <Route path="/world-3d" component={RealWorldMap} />,
    <Route path="/real-world" component={RealWorldMap} />,
    <Route path="/plans">{() => <Redirect to="/pricing" />}</Route>,
    <Route path="/sovereign-pricing">{() => <Redirect to="/pricing" />}</Route>,
    <Route path="/start" component={OnboardOS} />,
    <Route path="/onboard" component={OnboardOS} />,
    <Route path="/open-media" component={OpenMedia} />,
    <Route path="/commons" component={OpenMedia} />,
    <Route path="/status" component={StatusPage} />,
    <Route path="/system" component={StatusPage} />,
    <Route path="/graph" component={GovGraph} />,
    <Route path="/governance-graph" component={GovGraph} />,
    <Route path="/world-data" component={GovGraph} />,
    <Route path="/tools" component={ToolCommons} />,
    <Route path="/tool-commons" component={ToolCommons} />,
    <Route path="/mcp-tools" component={ToolCommons} />,
    <Route path="/sovereign-twin">{() => <Redirect to="/me" />}</Route>,
    <Route component={NotFound} />
  ];
}
