import { createElement } from "react";
import { Route, Redirect } from "wouter";
import {
  ABTesting,
  About,
  AboutCEASAI,
  Accessibility,
  AccountabilityLoop,
  AgUiBridge,
  AgentRunbook,
  AiActBenchmark,
  AiTransparency,
  AnalyticsDashboard,
  ArenaHarness,
  AustraliaAIGovernance,
  AustraliaAIGovernanceCompliance,
  BenchmarkIndex,
  BenchmarkQuality,
  Benchmarks,
  BondVenturi,
  CEASAITraining,
  CanadaAIAct,
  CanadaAIActCompliance,
  Careers,
  CertificateVerification,
  CertificationHowItWorks,
  Charter,
  Coliseum,
  Competitors,
  ComplianceCommandCenter,
  ComplianceHowItWorks,
  ConformityRoute,
  Contact,
  CouncilDetail,
  CouncilLicensingLanding,
  CouncilSpace,
  CourseDetail,
  CyberScan,
  DashboardHowItWorks,
  DemoOS,
  Dispute,
  Distribution,
  Documentation,
  Dragonfly,
  DriftProduct,
  EI3,
  EUAIActClassifier,
  EUAIActCompliance,
  EUAIActGuide,
  EUAIActUrgency,
  EUActChecklist,
  EarlyAccessLanding,
  EastWest,
  Ecosystem,
  EngineAxis,
  EnterpriseHowItWorks,
  EstateAudit,
  EvidenceRail,
  FirewallCharter,
  FrameworkCatalog,
  FrameworkHive,
  GSPCAnchors,
  GSPCGapMap,
  GSPCVerify,
  GlobalAISafetyInitiative,
  GovBench,
  GovernancePulse,
  GovernmentLinks,
  GovernmentPortal,
  GpaiObligations,
  GspcScoreboard,
  HelpCenter,
  HiveModel,
  Home,
  Honesty,
  HorusIntel,
  HowItWorks,
  ISO42001Guide,
  Instrument,
  InstrumentDetail,
  InstrumentsCatalog,
  Insurers,
  Landscape,
  Layer0,
  LegacyBridge,
  Library,
  Lineage,
  LiveLedger,
  LiveTraining,
  Login,
  MCPDetail,
  MCPRegistry,
  MarketingHome,
  MaternalCovenant,
  McpFleet,
  MeokLaw,
  Methodology,
  Metrology,
  ModelRegistry,
  MotionLab,
  NISTAIRMFCompliance,
  NISTAIRMFGuide,
  NetworkPage,
  NewHomeV2,
  NewHomeV3,
  Ontology,
  OpenGridWorks,
  OpenSourceFramework,
  OsEnter,
  Outreach,
  OwnershipPlan,
  Payg,
  Penalties,
  Playbooks,
  PolicyGenerator,
  PoweredBy,
  Protect,
  ProvBench,
  ProvenanceFinding,
  PublicWatchdogHub,
  ReceiptSpec,
  ReceiptSpecLaunch,
  RefutationLedger,
  RegionSettings,
  RegionalAnalytics,
  RegionsMap,
  RegistryAll,
  RegulationFeed,
  RegulationRadar,
  RegulatorAtlas,
  RegulatoryAuthority,
  RegulatoryCompliance,
  RelevanceMap,
  RemediationPartners,
  ResearchTransparency,
  Resources,
  SectorsAtlas,
  Services,
  Signup,
  SocialOS,
  Sov3ModelCard,
  Sov3SystemCard,
  Sov3Whitepaper,
  SovereignAcademy,
  SovereignHives,
  SovereignMinds,
  SovereignRegistry,
  SovereignTour,
  Standards,
  Status,
  StatuteToPredicate,
  Support,
  SystemCard,
  TC260Compliance,
  TC260Guide,
  Temples,
  TrainingHowItWorks,
  TryCouncil,
  UKAIBill,
  UKAIBillCompliance,
  VerifiableTrust,
  VerifyCertificate,
  WatchdogHelpProtectHumanity,
  WatchdogIncidentReport,
  WatchdogLeaderboard,
  Welcome,
  WhereTheRecordLives,
  WhyCSOAI,
  Workbench
} from "./AppLazy";

export function AppRoutesA() {
  return [
    <Route path="/" component={NewHomeV3} />,
    <Route path="/home-v2" component={NewHomeV2} />,
    <Route path="/home-v3" component={NewHomeV3} />,
    <Route path="/motion-lab" component={MotionLab} />,
    <Route path="/remediation-partners" component={RemediationPartners} />,
    <Route path="/login" component={Login} />,
    <Route path="/signup" component={Signup} />,
    <Route path="/welcome" component={Welcome} />,
    <Route path="/hive/:slug" component={FrameworkHive} />,
    <Route path="/hive" component={FrameworkHive} />,
    <Route path="/system-card" component={SystemCard} />,
    <Route path="/assurance" component={SystemCard} />,
    <Route path="/systemcard" component={SystemCard} />,
    <Route path="/council-model-card" component={Sov3ModelCard} />,
    <Route path="/council-system-card" component={Sov3SystemCard} />,
    <Route path="/workbench-paper" component={Sov3Whitepaper} />,
    <Route path="/sov3-model-card">{() => <Redirect to="/council-model-card" />}</Route>,
    <Route path="/sov3-system-card">{() => <Redirect to="/council-system-card" />}</Route>,
    <Route path="/sov3-whitepaper">{() => <Redirect to="/workbench-paper" />}</Route>,
    <Route path="/research-transparency" component={ResearchTransparency} />,
    <Route path="/provenance-finding" component={ProvenanceFinding} />,
    <Route path="/ai-transparency" component={AiTransparency} />,
    <Route path="/ab-testing" component={ABTesting} />,
    <Route path="/about-credential" component={AboutCEASAI} />,
    <Route path="/about-ceasai">{() => <Redirect to="/about-credential" />}</Route>,
    <Route path="/accessibility" component={Accessibility} />,
    <Route path="/analytics" component={AnalyticsDashboard} />,
    <Route path="/byzantine-consensus">{() => <Redirect to="/council" />}</Route>,
    <Route path="/credential-training" component={CEASAITraining} />,
    <Route path="/ceasai-training">{() => <Redirect to="/credential-training" />}</Route>,
    <Route path="/certificate-verification" component={CertificateVerification} />,
    <Route path="/compliance/australia-ai-governance" component={AustraliaAIGovernanceCompliance} />,
    <Route path="/compliance/canada-ai-act" component={CanadaAIActCompliance} />,
    <Route path="/compliance/eu-ai-act" component={EUAIActCompliance} />,
    <Route path="/compliance/nist-ai-rmf" component={NISTAIRMFCompliance} />,
    <Route path="/compliance/tc260" component={TC260Compliance} />,
    <Route path="/compliance/uk-ai-bill" component={UKAIBillCompliance} />,
    <Route path="/conformity-route" component={ConformityRoute} />,
    <Route path="/contact" component={Contact} />,
    <Route path="/council-detail" component={CouncilDetail} />,
    <Route path="/council-licensing" component={CouncilLicensingLanding} />,
    <Route path="/courses/:id" component={CourseDetail} />,
    <Route path="/docs" component={Documentation} />,
    <Route path="/early-access" component={EarlyAccessLanding} />,
    <Route path="/ei3" component={EI3} />,
    <Route path="/enterprise-plans">{() => <Redirect to="/pricing" />}</Route>,
    <Route path="/eu-ai-act-classifier" component={EUAIActClassifier} />,
    <Route path="/eu-ai-act-urgency" component={EUAIActUrgency} />,
    <Route path="/feed" component={RegulationFeed} />,
    <Route path="/frameworks/australia-ai" component={AustraliaAIGovernance} />,
    <Route path="/frameworks/canada-ai-act" component={CanadaAIAct} />,
    <Route path="/frameworks/uk-ai-bill" component={UKAIBill} />,
    <Route path="/global-ai-safety-initiative" component={GlobalAISafetyInitiative} />,
    <Route path="/govbench" component={GovBench} />,
    <Route path="/drift-audit" component={DriftProduct} />,
    <Route path="/sov-town-lab">{() => <Redirect to="/gspc-arena?view=towns" />}</Route>,
    <Route path="/government-links" component={GovernmentLinks} />,
    <Route path="/government-portal" component={GovernmentPortal} />,
    <Route path="/help" component={HelpCenter} />,
    <Route path="/help-center" component={HelpCenter} />,
    <Route path="/horus" component={HorusIntel} />,
    <Route path="/how-it-works/certification" component={CertificationHowItWorks} />,
    <Route path="/how-it-works/compliance" component={ComplianceHowItWorks} />,
    <Route path="/how-it-works/dashboard" component={DashboardHowItWorks} />,
    <Route path="/how-it-works/enterprise" component={EnterpriseHowItWorks} />,
    <Route path="/how-it-works/training" component={TrainingHowItWorks} />,
    <Route path="/landscape" component={Landscape} />,
    <Route path="/mcp" component={MCPRegistry} />,
    <Route path="/mcp/:slug" component={MCPDetail} />,
    <Route path="/mcps" component={MCPRegistry} />,
    <Route path="/old-home" component={Home} />,
    <Route path="/opengridworks" component={OpenGridWorks} />,
    <Route path="/outreach" component={Outreach} />,
    <Route path="/radar" component={RegulationRadar} />,
    <Route path="/region-settings" component={RegionSettings} />,
    <Route path="/regional-analytics" component={RegionalAnalytics} />,
    <Route path="/regulatory-authority" component={RegulatoryAuthority} />,
    <Route path="/regulatory-compliance" component={RegulatoryCompliance} />,
    <Route path="/soai-pdca/government" component={GovernmentPortal} />,
    <Route path="/support" component={Support} />,
    <Route path="/system-status" component={Status} />,
    <Route path="/verify/:certificateNumber" component={VerifyCertificate} />,
    <Route path="/watchdog-hub" component={PublicWatchdogHub} />,
    <Route path="/watchdog-leaderboard" component={WatchdogLeaderboard} />,
    <Route path="/watchdog/help-protect-humanity" component={WatchdogHelpProtectHumanity} />,
    <Route path="/watchdog/incident" component={WatchdogIncidentReport} />,
    <Route path="/watchdog/report" component={PublicWatchdogHub} />,
    <Route path="/benchmarks" component={Benchmarks} />,
    <Route path="/benchmark-index" component={BenchmarkIndex} />,
    <Route path="/benchmark-quality" component={BenchmarkQuality} />,
    <Route path="/library" component={Library} />,
    <Route path="/library/:sector" component={Library} />,
    <Route path="/honesty" component={Honesty} />,
    <Route path="/dispute" component={Dispute} />,
    <Route path="/firewall-charter" component={FirewallCharter} />,
    <Route path="/gspc-scoreboard" component={GspcScoreboard} />,
    <Route path="/insurers" component={Insurers} />,
    <Route path="/instrument" component={Instrument} />,
    <Route path="/refutation-ledger" component={RefutationLedger} />,
    <Route path="/live-ledger" component={LiveLedger} />,
    <Route path="/coliseum" component={Coliseum} />,
    <Route path="/open-source" component={OpenSourceFramework} />,
    <Route path="/verifiable-trust" component={VerifiableTrust} />,
    <Route path="/evidence-rail" component={EvidenceRail} />,
    <Route path="/metrology" component={Metrology} />,
    <Route path="/accountability-loop" component={AccountabilityLoop} />,
    <Route path="/where-the-record-lives" component={WhereTheRecordLives} />,
    <Route path="/statute-to-predicate" component={StatuteToPredicate} />,
    <Route path="/gspc-gap-map" component={GSPCGapMap} />,
    <Route path="/gspc-arena" component={CouncilSpace} />,
    <Route path="/gspc-anchors" component={GSPCAnchors} />,
    <Route path="/gspc-verify" component={GSPCVerify} />,
    <Route path="/ag-ui" component={AgUiBridge} />,
    <Route path="/agent-runbook" component={AgentRunbook} />,
    <Route path="/receipt-spec" component={ReceiptSpec} />,
    <Route path="/ownership" component={OwnershipPlan} />,
    <Route path="/arena-harness" component={ArenaHarness} />,
    <Route path="/blog/receipt-spec-0-1" component={ReceiptSpecLaunch} />,
    <Route path="/methodology" component={Methodology} />,
    <Route path="/ai-act-benchmark" component={AiActBenchmark} />,
    <Route path="/provbench" component={ProvBench} />,
    <Route path="/layer0" component={Layer0} />,
    <Route path="/safe-space" component={Ecosystem} />,
    <Route path="/governance-commons" component={Ecosystem} />,
    <Route path="/protect" component={Protect} />,
    <Route path="/personal-protection" component={Protect} />,
    <Route path="/deepfake-protection" component={Protect} />,
    <Route path="/ontology" component={Ontology} />,
    <Route path="/network" component={NetworkPage} />,
    <Route path="/sovereign-network">{() => <Redirect to="/network" />}</Route>,
    <Route path="/agents-network" component={NetworkPage} />,
    <Route path="/regulators" component={RegulatorAtlas} />,
    <Route path="/regulator-atlas" component={RegulatorAtlas} />,
    <Route path="/scan" component={CyberScan} />,
    <Route path="/gods-eye" component={CyberScan} />,
    <Route path="/cyber-scan" component={CyberScan} />,
    <Route path="/usp" component={WhyCSOAI} />,
    <Route path="/competitors" component={Competitors} />,
    <Route path="/battlecards" component={Competitors} />,
    <Route path="/marketing" component={MarketingHome} />,
    <Route path="/standards" component={Standards} />,
    <Route path="/resources" component={Resources} />,
    <Route path="/payg" component={Payg} />,
    <Route path="/powered-by" component={PoweredBy} />,
    <Route path="/white-label" component={PoweredBy} />,
    <Route path="/about" component={About} />,
    <Route path="/careers" component={Careers} />,
    <Route path="/charter" component={Charter} />,
    <Route path="/maternal-covenant" component={MaternalCovenant} />,
    <Route path="/covenant" component={MaternalCovenant} />,
    <Route path="/why-csoai" component={WhyCSOAI} />,
    <Route path="/our-difference" component={WhyCSOAI} />,
    <Route path="/why" component={WhyCSOAI} />,
    <Route path="/eu-ai-act" component={EUAIActGuide} />,
    <Route path="/frameworks/eu-ai-act" component={EUAIActGuide} />,
    <Route path="/nist-ai-rmf" component={NISTAIRMFGuide} />,
    <Route path="/frameworks/nist" component={NISTAIRMFGuide} />,
    <Route path="/iso-42001" component={ISO42001Guide} />,
    <Route path="/frameworks/iso-42001" component={ISO42001Guide} />,
    <Route path="/tc260" component={TC260Guide} />,
    <Route path="/frameworks/tc260" component={TC260Guide} />,
    <Route path="/guides/eu-ai-act" component={EUAIActGuide} />,
    <Route path="/guides/nist-ai-rmf" component={NISTAIRMFGuide} />,
    <Route path="/guides/iso-42001" component={ISO42001Guide} />,
    <Route path="/guides/tc260" component={TC260Guide} />,
    <Route path="/frameworks/:slug">{(p: any) => <ContentPage dataset={frameworksdata} slug={p.slug} />}</Route>,
    <Route path="/sectors/:slug">{(p: any) => <ContentPage dataset={sectorsdata} slug={p.slug} />}</Route>,
    <Route path="/industries/:slug">{(p: any) => <IndustryTemplate slug={p.slug} />}</Route>,
    <Route path="/blog/:slug">{(p: any) => <ContentPage dataset={blogdata} slug={p.slug} />}</Route>,
    <Route path="/models" component={ModelRegistry} />,
    <Route path="/instruments" component={InstrumentsCatalog} />,
    <Route path="/instruments/:layer/:slug" component={InstrumentDetail} />,
    <Route path="/router">{() => <Redirect to="/instruments" />}</Route>,
    <Route path="/framework-catalog" component={FrameworkCatalog} />,
    <Route path="/command-center" component={ComplianceCommandCenter} />,
    <Route path="/policy-generator" component={PolicyGenerator} />,
    <Route path="/mcp-fleet" component={McpFleet} />,
    <Route path="/os-demo">{() => <Redirect to="/os" />}</Route>,
    <Route path="/workbench" component={Workbench} />,
    <Route path="/sov3">{() => <Redirect to="/workbench" />}</Route>,
    <Route path="/demo" component={DemoOS} />,
    <Route path="/os-demo" component={DemoOS} />,
    <Route path="/enter" component={OsEnter} />,
    <Route path="/tour" component={SovereignTour} />,
    <Route path="/academy" component={SovereignAcademy} />,
    <Route path="/live-training" component={LiveTraining} />,
    <Route path="/estate" component={EstateAudit} />,
    <Route path="/east-west/desks/:deskId" component={EastWest} />,
    <Route path="/east-west/*?" component={EastWest} />,
    <Route path="/east-west" component={EastWest} />,
    <Route path="/challenge">{() => <Redirect to="/east-west/challenge" />}</Route>,
    <Route path="/register" component={SovereignRegistry} />,
    <Route path="/hives" component={SovereignHives} />,
    <Route path="/pulse" component={GovernancePulse} />,
    <Route path="/join" component={SovereignRegistry} />,
    <Route path="/distribution" component={Distribution} />,
    <Route path="/legacy" component={LegacyBridge} />,
    <Route path="/venturi" component={BondVenturi} />,
    <Route path="/bond-router" component={BondVenturi} />,
    <Route path="/engine-axis" component={EngineAxis} />,
    <Route path="/social" component={SocialOS} />,
    <Route path="/jewels">{() => <Redirect to="/" />}</Route>,
    <Route path="/towns">{() => <Redirect to="/gspc-arena?view=towns" />}</Route>,
    <Route path="/minds" component={SovereignMinds} />,
    <Route path="/try" component={TryCouncil} />,
    <Route path="/lineage" component={Lineage} />,
    <Route path="/map" component={RelevanceMap} />,
    <Route path="/temples" component={Temples} />,
    <Route path="/playbooks" component={Playbooks} />,
    <Route path="/dragonfly" component={Dragonfly} />,
    <Route path="/meok-law" component={MeokLaw} />,
    <Route path="/law" component={MeokLaw} />,
    <Route path="/hive-model" component={HiveModel} />,
    <Route path="/services" component={Services} />,
    <Route path="/how" component={HowItWorks} />,
    <Route path="/how-it-works" component={HowItWorks} />,
    <Route path="/sectors" component={SectorsAtlas} />,
    <Route path="/regions" component={RegionsMap} />,
    <Route path="/globe">{() => <Redirect to="/gspc-arena?view=globe" />}</Route>,
    <Route path="/registry" component={RegistryAll} />,
    <Route path="/eu-ai-act-checklist" component={EUActChecklist} />,
    <Route path="/checklist" component={EUActChecklist} />,
    <Route path="/gpai" component={GpaiObligations} />,
    <Route path="/foundation-models" component={GpaiObligations} />,
    <Route path="/penalties" component={Penalties} />,
    <Route path="/uk-ai-regulation">{() => <JurisdictionAct jx="uk" />}</Route>,
    <Route path="/canada-aida">{() => <JurisdictionAct jx="canada" />}</Route>,
    <Route path="/china-ai-law">{() => <JurisdictionAct jx="china" />}</Route>,
    <Route path="/singapore-ai-governance">{() => <JurisdictionAct jx="singapore" />}</Route>,
    <Route path="/south-korea-ai-act">{() => <JurisdictionAct jx="korea" />}</Route>,
    <Route path="/us-ai-regulation">{() => <JurisdictionAct jx="usfederal" />}</Route>,
    <Route path="/sec-disclosure">{() => <SECDisclosure />}</Route>,
    <Route path="/sec-ai-disclosure">{() => <SECDisclosure />}</Route>,
    <Route path="/for/:persona">{(params: any) => <PersonaRouter persona={params.persona} />}</Route>
  ];
}
