import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import {tmpdir} from 'node:os';import {boardCounts,makeBoardReference,captureBoardReference,finishBoardReference,verifyBoardReference} from './render-board-reference.mjs';
const raw=(n=2,m=1)=>Buffer.from(JSON.stringify({axes:Array.from({length:n},(_,i)=>({axis:'axis-'+i,status:i<m?'MEASURED':'UNMEASURED'})),totals:{axes:n,measured_axes:m,public_count:n+' axes'}}));
function setup(t){const dir=fs.mkdtempSync(path.join(tmpdir(),'board-reference-fixture-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const dist=path.join(dir,'dist');fs.mkdirSync(path.join(dist,'assets'),{recursive:true});fs.writeFileSync(path.join(dist,'assets/main.js'),'fixture bytes');fs.writeFileSync(path.join(dist,'root.json'),'fixture root');const file=path.join(dir,'reference.json'),report=path.join(dir,'report.json');fs.writeFileSync(file,JSON.stringify(makeBoardReference(raw(),dist,'http://127.0.0.1:1/api/gspc')));fs.writeFileSync(report,JSON.stringify([{route:'/',ok:true}]));return {dir,dist,file,report};}
test('counts independently match rows',()=>assert.deepEqual(boardCounts(raw()),{axes:2,measured_axes:1,public_count:'2 axes'}));
test('total inflation is rejected',()=>{const d=JSON.parse(raw());d.totals.axes=22;assert.throws(()=>boardCounts(Buffer.from(JSON.stringify(d))),/TOTALS/);});
test('measured inflation is rejected',()=>{const d=JSON.parse(raw());d.totals.measured_axes=2;assert.throws(()=>boardCounts(Buffer.from(JSON.stringify(d))),/TOTALS/);});
test('duplicate identities rejected',()=>{const d=JSON.parse(raw());d.axes[1].axis=d.axes[0].axis;assert.throws(()=>boardCounts(Buffer.from(JSON.stringify(d))),/AXIS/);});
test('completed receipt binds immutable render inputs',t=>{const s=setup(t);finishBoardReference(s.file,s.report);assert.equal(verifyBoardReference(s.file,s.dist).counts.axes,2);});
test('capture alone is not a completed render',t=>{const s=setup(t);assert.throws(()=>verifyBoardReference(s.file,s.dist),/NOT_COMPLETED/);});
test('failed render cannot be blessed',t=>{const s=setup(t);fs.writeFileSync(s.report,JSON.stringify([{route:'/',err:'failed'}]));assert.throws(()=>finishBoardReference(s.file,s.report),/INCOMPLETE/);});
test('changed bundle fails even if report is kept',t=>{const s=setup(t);finishBoardReference(s.file,s.report);fs.writeFileSync(path.join(s.dist,'assets/main.js'),'changed');assert.throws(()=>verifyBoardReference(s.file,s.dist),/BUILD_MISMATCH/);});
test('changed signed-root file fails',t=>{const s=setup(t);finishBoardReference(s.file,s.report);fs.writeFileSync(path.join(s.dist,'root.json'),'changed');assert.throws(()=>verifyBoardReference(s.file,s.dist),/ROOT_MISMATCH/);});
test('changed completed report fails',t=>{const s=setup(t);finishBoardReference(s.file,s.report);fs.writeFileSync(s.report,'[]');assert.throws(()=>verifyBoardReference(s.file,s.dist),/REPORT_MISMATCH/);});
test('changed board body fails',t=>{const s=setup(t);finishBoardReference(s.file,s.report);const d=JSON.parse(fs.readFileSync(s.file));d.board_base64=raw(3,2).toString('base64');fs.writeFileSync(s.file,JSON.stringify(d));assert.throws(()=>verifyBoardReference(s.file,s.dist),/DIGEST_MISMATCH/);});
test('credentials cannot enter source metadata',t=>{const s=setup(t);assert.throws(()=>makeBoardReference(raw(),s.dist,'https://user:pass@example.com/api/gspc'),/ORIGIN/);});
test('HTTP failure has no stale fallback',async t=>{const s=setup(t);await assert.rejects(captureBoardReference(s.dist,'https://example.com/api/gspc',s.file,{fetcher:async()=>new Response('unavailable',{status:503})}),/HTTP/);});
test('successful HTML still rejected',async t=>{const s=setup(t);await assert.rejects(captureBoardReference(s.dist,'https://example.com/api/gspc',s.file,{fetcher:async()=>new Response('<html>shell</html>',{headers:{'content-type':'text/html'}})}),/CONTENT_TYPE/);});
test('only one board fetch is performed',async t=>{const s=setup(t);let n=0;await captureBoardReference(s.dist,'https://example.com/api/gspc',s.file,{fetcher:async()=>{n++;return new Response(raw(),{headers:{'content-type':'application/json'}});}});assert.equal(n,1);});
