import { chromium } from 'playwright-core';
const BASE='http://localhost:5301';
const b=await chromium.launch();
const p=await (await b.newContext({viewport:{width:1440,height:1200}})).newPage();
const resp=[];
p.on('response', async r=>{ const u=r.url().replace(BASE,''); if(/\/api\//.test(u)){ let body=''; try{body=(await r.text()).slice(0,400);}catch(e){body='<unreadable>';} resp.push(`${r.status()} ${r.request().method()} ${u}\n    BODY: ${body.replace(/\n/g,' ')}`);} });
await p.goto(BASE+'/gspc-arena',{waitUntil:'domcontentloaded',timeout:60000});
await p.waitForTimeout(6000);
resp.length=0;
await p.locator('textarea').first().fill('A city council wants to deploy live facial recognition in a public square to reduce theft.');
await p.getByRole('button',{name:/Run experiment/i}).click();
await p.waitForTimeout(40000);
console.log('=== API RESPONSES ===');
console.log(resp.join('\n'));
const t=await p.evaluate(()=>document.body.innerText);
const i=t.indexOf('COUNCIL');
console.log('=== PAGE TEXT (verdict region) ===');
console.log(t.slice(t.indexOf('Your experiment')>=0?t.indexOf('Your experiment'):0, 6500));
await p.screenshot({path:'/tmp/claude-501/-Users-nicholas/34f0c79c-80a5-4c86-9f75-90b79401a44a/scratchpad/shot-verdict.png',fullPage:true});
await b.close();
