#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 CSOAI Ltd
"""OpenShell sandbox policy (YAML, `version: 1`) -> Cedar policies, v0.  Our example; not part of OpenShell.

The one rule that everything else serves: nothing this translator does not fully understand becomes an
allow. Every element is either TRANSLATED or UNCHECKABLE, and the report names each UNCHECKABLE element
with its reason.

  permits are emitted only when they are at most as wide as the OpenShell rule they come from;
  forbids are emitted at least as wide as the OpenShell deny they come from (widened, never dropped);
  an unknown field, a known field this v0 does not model, an unsupported glob, a protocol other than
  REST, `enforcement: audit` on a REST endpoint, and `network_middlewares` all make the element
  UNCHECKABLE and it contributes no permit.

Cedar is default-deny, as OpenShell's network policy is. What an UNCHECKABLE element loses is access,
never containment.

  python3 translate.py POLICY.yaml --out DIR [--workdir /sandbox]
  -> DIR/<name>.cedar, DIR/<name>.report.json, DIR/openshell.cedarschema

Request shape the policies expect (see openshell.cedarschema):
  principal  OpenShell::Binary::"<exe path>"   {path}          for connect and http_request
             OpenShell::Sandbox::"sandbox"                       for fs_read and fs_write
  resource   OpenShell::Endpoint::"<id>"  {host (lower case, no trailing dot), port, ip? (resolved)}
             OpenShell::File::"<path>"    {path}
  context    http_request: {method (upper case), path}
For an IP-literal host, the caller sets `ip` to that address.

Exit codes: 0 every element TRANSLATED, 3 at least one element UNCHECKABLE, 2 input error.
"""

from __future__ import annotations

import argparse
import ipaddress
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
for _p in (HERE, os.path.join(HERE, "..", "openshell-adapter")):
    if os.path.exists(os.path.join(_p, "adapter.py")) and _p not in sys.path:
        sys.path.insert(0, os.path.abspath(_p))
import adapter as A  # noqa: E402

TRANSLATOR = {"name": "openshell-yaml-to-cedar", "version": "0.1.0"}
TRANSLATED, UNCHECKABLE = "TRANSLATED", "UNCHECKABLE"

# fields this v0 turns into Cedar; every other field is UNCHECKABLE (known-but-unmodelled or unknown)
MODELLED_ENDPOINT_FIELDS = {"host", "port", "ports", "allowed_ips", "protocol", "enforcement", "access", "rules",
                            "deny_rules"}
MODELLED_RULE_FIELDS = {"name", "endpoints", "binaries"}
MODELLED_REQUEST_FIELDS = {"method", "path"}
MODELLED_FS_FIELDS = {"read_only", "read_write", "include_workdir"}
MODELLED_LANDLOCK_FIELDS = {"compatibility"}
KNOWN_TOP = A.TOP_LEVEL_FIELDS

SCHEMA = """// SPDX-License-Identifier: Apache-2.0
// Cedar schema for policies generated by openshell-yaml-to-cedar v0 (our example; not part of OpenShell).
namespace OpenShell {
  entity Binary = { path: String };
  entity Sandbox;
  entity Endpoint = { host: String, port: Long, ip?: ipaddr };
  entity File = { path: String };
  action connect appliesTo { principal: [Binary], resource: [Endpoint] };
  action http_request appliesTo {
    principal: [Binary],
    resource: [Endpoint],
    context: { method: String, path: String }
  };
  action fs_read, fs_write appliesTo { principal: [Sandbox], resource: [File] };
}
"""


def q(s: str) -> str:
    """A Cedar string literal."""
    return json.dumps(s, ensure_ascii=False)


def like_lit(s: str) -> str:
    """A literal fragment inside a Cedar `like` pattern (only `*` and `\\` are special)."""
    return s.replace("\\", "\\\\").replace("*", "\\*")


def _has_glob(s: str) -> bool:
    return any(c in s for c in "*?[")


# ------------------------------------------------------------------ matchers -> Cedar expressions (or None)
def path_expr(var: str, pattern: str) -> str | None:
    """OpenShell path glob -> an exactly equivalent Cedar expression, or None if v0 cannot express it."""
    if not _has_glob(pattern):
        return f"{var} == {q(pattern)}"
    if pattern.endswith("/**") and not _has_glob(pattern[:-3]):
        # whole trailing segment `**`: any run after the slash, separators included (matches `/` for `/**`)
        return f'{var} like "{like_lit(pattern[:-2])}*"'
    return None


def host_expr(var: str, pattern: str) -> str | None:
    p = str(pattern).lower().rstrip(".")
    if not _has_glob(p):
        return f"{var} == {q(p)}"
    if p.startswith("**.") and not _has_glob(p[3:]):
        return f'{var} like "*.{like_lit(p[3:])}"'
    if p.startswith("*.") and not _has_glob(p[2:]):
        # one label: `*` never crosses a dot, so exclude anything with a further label in front
        return f'({var} like "*.{like_lit(p[2:])}" && !({var} like "*.*.{like_lit(p[2:])}"))'
    return None


def binary_expr(paths: list[str]) -> tuple[str | None, list[str]]:
    """(expression over principal.path, unsupported patterns). None expression = no binary can match."""
    parts, bad = [], []
    for b in paths:
        e = path_expr("principal.path", b)
        (parts.append(e) if e else bad.append(b))
    if not parts:
        return None, bad
    return "(" + " || ".join(parts) + ")", bad


def under_expr(var: str, root: str) -> str:
    root = root.rstrip("/") or "/"
    if root == "/":
        return "true"
    return f'({var} == {q(root)} || {var} like "{like_lit(root)}/*")'


ALWAYS_BLOCKED = (
    'resource has ip && (resource.ip.isLoopback() || resource.ip.isInRange(ip("169.254.0.0/16")) || '
    'resource.ip.isInRange(ip("fe80::/10")) || resource.ip.isInRange(ip("0.0.0.0/32")) || '
    'resource.ip.isInRange(ip("::/128")))'
)


# ------------------------------------------------------------------ translation
class Out:
    def __init__(self):
        self.policies: list[str] = []
        self.elements: list[dict] = []
        self.n = 0

    def add(self, effect: str, action: str, cond: str, source: str, note: str | None = None):
        self.n += 1
        pid = f"p{self.n:03d}"
        ann = [f'@id({q(pid)})', f'@source({q(source)})']
        if note:
            ann.append(f'@note({q(note)})')
        head = f"{effect} (principal, action == OpenShell::Action::{q(action)}, resource)"
        self.policies.append("\n".join(ann) + f"\n{head}\nwhen {{ {cond} }};")
        return pid

    def element(self, source: str, status: str, reason: str | None = None, policies=None, **extra):
        e = {"source": source, "status": status}
        if reason:
            e["reason"] = reason
        if policies:
            e["policies"] = policies
        e.update(extra)
        self.elements.append(e)


def _endpoint_match(ep: dict) -> tuple[str | None, str | None]:
    """(condition on resource, reason if not expressible)."""
    conds = []
    if "host" in ep:
        h = host_expr("resource.host", ep["host"])
        if h is None:
            return None, f"host pattern {ep['host']!r} is not expressible in v0"
        conds.append(h)
    ports = ep.get("ports") or ([ep["port"]] if "port" in ep else [])
    if not ports or not all(isinstance(p, int) for p in ports):
        return None, "endpoint has no integer port"
    conds.append(f"resource.port == {ports[0]}" if len(ports) == 1 else f"[{', '.join(map(str, ports))}].contains(resource.port)")
    if ep.get("allowed_ips"):
        rng = []
        for c in ep["allowed_ips"]:
            try:
                rng.append(f'resource.ip.isInRange(ip({q(str(ipaddress.ip_network(c, strict=False)))}))')
            except ValueError:
                return None, f"allowed_ips entry {c!r} is not a CIDR"
        conds.append("(resource has ip && (" + " || ".join(rng) + "))")
    return " && ".join(conds), None


def _widened_endpoint_match(ep: dict) -> str:
    """For forbids: the same match, widened (never narrowed) where v0 cannot express a part."""
    ports = ep.get("ports") or ([ep["port"]] if "port" in ep else [])
    conds = []
    if "host" in ep:
        h = host_expr("resource.host", ep["host"])
        if h:
            conds.append(h)
    if ports and all(isinstance(p, int) for p in ports):
        conds.append(f"[{', '.join(map(str, ports))}].contains(resource.port)")
    return " && ".join(conds) or "true"


def _request_expr(r: dict, for_forbid: bool = False) -> tuple[str | None, str | None]:
    """A request matcher (`method` + `path`) -> Cedar condition on context.

    An allow needs both fields, an upper-case method (or `*`) and an expressible path glob, or it is not
    emitted. A deny that v0 cannot express exactly is returned as None; the caller widens it."""
    extra = set(r) - MODELLED_REQUEST_FIELDS
    if extra:
        return None, f"request matcher field(s) {sorted(extra)} not modelled in v0"
    if "method" not in r or "path" not in r:
        return None, "request matcher without both `method` and `path`"
    m = str(r["method"])
    if m != "*" and m != m.upper():
        return None, f"method {m!r} is not upper case"
    pe = path_expr("context.path", str(r["path"]))
    if pe is None:
        return None, f"path glob {r['path']!r} is not expressible in v0"
    return (pe if m == "*" else f"context.method == {q(m)} && {pe}"), None


def _overlap(a: str, b: str) -> bool:
    a, b = str(a).lower(), str(b).lower()
    return a == b or _has_glob(a) or _has_glob(b)


def translate(doc: dict, workdir: str | None = "/sandbox") -> tuple[str, dict]:
    o = Out()
    top_unknown = sorted(set(doc) - KNOWN_TOP)

    # platform denies, always emitted (they only ever narrow)
    o.element("platform:always-blocked-addresses", TRANSLATED, policies=[
        o.add("forbid", "connect", ALWAYS_BLOCKED, "platform:always-blocked-addresses"),
        o.add("forbid", "http_request", ALWAYS_BLOCKED, "platform:always-blocked-addresses"),
        o.add("forbid", "connect", 'resource.host == "localhost"', "platform:always-blocked-addresses"),
        o.add("forbid", "http_request", 'resource.host == "localhost"', "platform:always-blocked-addresses")])
    cp = "[" + ", ".join(map(str, sorted(A.CONTROL_PLANE_PORTS))) + "].contains(resource.port)"
    o.element("platform:control-plane-ports", TRANSLATED, policies=[
        o.add("forbid", "connect", cp, "platform:control-plane-ports"),
        o.add("forbid", "http_request", cp, "platform:control-plane-ports")],
        note="widened: OpenShell applies this to exact-host, IP and allowed_ips endpoints; v0 applies it to all")

    if top_unknown:
        o.element("policy", UNCHECKABLE, f"UNKNOWN_FIELD: top-level field(s) {top_unknown} (OpenShell itself rejects "
                  "such a policy); nothing in it is translated to an allow")
        return "\n\n".join(o.policies) + "\n", _report(doc, o)
    if doc.get("version") != 1:
        o.element("policy", UNCHECKABLE, f"version {doc.get('version')!r} is not 1; nothing translated to an allow")
        return "\n\n".join(o.policies) + "\n", _report(doc, o)

    # ---------------------------------------------------------------- network
    rules = doc.get("network_policies") or {}
    if doc.get("network_middlewares"):
        o.element("network_middlewares", UNCHECKABLE, "KNOWN_FIELD_NOT_MODELLED: middlewares can change requests; "
                  "no network permit is emitted while they are present")
    net_ok = not doc.get("network_middlewares")

    # which endpoints are REST-inspected, to find host/port shared with an uninspected endpoint
    inspected, plain = [], []
    for key, rule in rules.items():
        if not isinstance(rule, dict):
            continue
        for i, ep in enumerate(rule.get("endpoints") or []):
            if isinstance(ep, dict):
                (inspected if ep.get("protocol") else plain).append((key, i, ep))

    def shares(ep, others):
        pe = set(ep.get("ports") or ([ep["port"]] if "port" in ep else []))
        for _k, _i, o2 in others:
            po = set(o2.get("ports") or ([o2["port"]] if "port" in o2 else []))
            if pe & po and _overlap(ep.get("host", "*"), o2.get("host", "*")):
                return True
        return False

    for key, rule in rules.items():
        src = f"network_policies.{key}"
        if not isinstance(rule, dict):
            o.element(src, UNCHECKABLE, "rule is not a mapping")
            continue
        unknown_rule = sorted(set(rule) - MODELLED_RULE_FIELDS)
        bins = [b.get("path", "") for b in (rule.get("binaries") or []) if isinstance(b, dict)]
        bexpr, bad_bins = binary_expr(bins)
        wide_b = "true"  # forbids are scoped to any binary when the rule's binaries cannot be expressed exactly
        if bexpr and not bad_bins:
            wide_b = bexpr
        rule_permits_ok = net_ok and not unknown_rule
        if unknown_rule:
            o.element(src, UNCHECKABLE, f"UNKNOWN_FIELD: rule field(s) {unknown_rule}; no permit from this rule")
        if bad_bins:
            o.element(src + ".binaries", UNCHECKABLE, f"binary pattern(s) {bad_bins} not expressible in v0; "
                      "permits use only the exact ones, forbids apply to every binary")
        if not bins:
            o.element(src + ".binaries", TRANSLATED, "empty binaries list matches no binary: no permit")
        for i, ep in enumerate(rule.get("endpoints") or []):
            esrc = f"{src}.endpoints[{i}]"
            if not isinstance(ep, dict):
                o.element(esrc, UNCHECKABLE, "endpoint is not a mapping")
                continue
            proto = ep.get("protocol")
            enforcement = ep.get("enforcement", "audit")
            extra = set(ep) - MODELLED_ENDPOINT_FIELDS
            unknown = sorted(extra - A.ENDPOINT_FIELDS)
            known_unmodelled = sorted(extra & A.ENDPOINT_FIELDS)
            match, why = _endpoint_match(ep)
            reasons = []
            if unknown:
                reasons.append(f"UNKNOWN_FIELD: {unknown}")
            if known_unmodelled:
                reasons.append(f"KNOWN_FIELD_NOT_MODELLED: {known_unmodelled}")
            if proto not in (None, "rest"):
                reasons.append(f"PROTOCOL_NOT_MODELLED: {proto}")
            if proto == "rest" and enforcement != "enforce":
                reasons.append("AUDIT_MODE: the declared REST rules are logged, not enforced")
            if why:
                reasons.append(why)
            if "access" in ep and ep["access"] not in A.PRESETS:
                reasons.append(f"unknown access preset {ep['access']!r}")
            forbids = []
            # deny_rules become forbids, widened where needed, whatever else is wrong with the endpoint
            if proto in ("rest", "websocket"):  # the declared denies, whatever the enforcement mode
                for j, dr in enumerate(ep.get("deny_rules") or []):
                    dsrc = f"{esrc}.deny_rules[{j}]"
                    rexpr, rwhy = _request_expr(dr if isinstance(dr, dict) else {"?": 1})
                    if rexpr is None:
                        m = dr.get("method") if isinstance(dr, dict) else None
                        exact_m = isinstance(m, str) and m != "*" and m == m.upper()
                        rexpr = f"context.method == {q(m)}" if exact_m else "true"
                        o.element(dsrc, UNCHECKABLE, f"{rwhy}; forbid widened to every path"
                                  + ("" if exact_m else " and every method"))
                    forbids.append(o.add("forbid", "http_request",
                                         f"{wide_b} && {_widened_endpoint_match(ep)} && {rexpr}", dsrc))
            if reasons or not rule_permits_ok or bexpr is None:
                if reasons:
                    o.element(esrc, UNCHECKABLE, "; ".join(reasons) + "; no permit from this endpoint",
                              policies=forbids or None)
                continue
            base = f"{bexpr} && {match}"
            permits = [o.add("permit", "connect", base, esrc)]
            if proto is None:
                if shares(ep, inspected):
                    o.element(esrc, UNCHECKABLE, "HOST_PORT_ALSO_INSPECTED: an uninspected endpoint shares a host and "
                              "port with a REST endpoint; request permits are not emitted", policies=permits)
                    continue
                permits.append(o.add("permit", "http_request", base, esrc, "endpoint without request inspection"))
                o.element(esrc, TRANSLATED, policies=permits)
                continue
            # REST, enforce
            if shares(ep, plain):
                o.element(esrc, UNCHECKABLE, "HOST_PORT_ALSO_UNINSPECTED: request permits are not emitted",
                          policies=permits + forbids)
                continue
            status, why2 = TRANSLATED, []
            if "access" in ep:
                allowed = A.PRESETS[ep["access"]]
                cond = "true" if allowed is None else "[" + ", ".join(q(m) for m in sorted(allowed)) + "].contains(context.method)"
                permits.append(o.add("permit", "http_request", f"{base} && {cond}", esrc + ".access"))
            for j, r in enumerate(ep.get("rules") or []):
                rsrc = f"{esrc}.rules[{j}]"
                allow = r.get("allow") if isinstance(r, dict) and set(r) == {"allow"} else None
                if not isinstance(allow, dict):
                    status = UNCHECKABLE
                    why2.append(f"{rsrc}: rule shape not modelled")
                    continue
                rexpr, rwhy = _request_expr(allow)
                if rexpr is None:
                    status = UNCHECKABLE
                    why2.append(f"{rsrc}: {rwhy}")
                    continue
                permits.append(o.add("permit", "http_request", f"{base} && {rexpr}", rsrc))
            o.element(esrc, status, "; ".join(why2) + "; those allows are not emitted" if why2 else None,
                      policies=permits + forbids)

    # ---------------------------------------------------------------- filesystem (Landlock)
    fs = doc.get("filesystem_policy")
    fs_extra = sorted(set(fs or {}) - MODELLED_FS_FIELDS)
    ll_extra = sorted(set(doc.get("landlock") or {}) - MODELLED_LANDLOCK_FIELDS)
    if fs_extra:
        o.element("filesystem_policy", UNCHECKABLE, f"UNKNOWN_FIELD: {fs_extra}; no filesystem permit is emitted")
    else:
        D = A.Declared(doc, workdir)
        ro, rw = D.fs_lists()
        nested = sorted({r for r in ro for w in rw if A.path_under(r, w) and r.rstrip("/") != w.rstrip("/")})
        deep = [w for w in rw for r in nested if A.path_under(w, r) and w.rstrip("/") != r.rstrip("/")]
        pols = []
        for p in ro + rw:
            pols.append(o.add("permit", "fs_read", under_expr("resource.path", p), f"filesystem:{p}"))
        for p in rw:
            if p in deep:
                continue
            pols.append(o.add("permit", "fs_write", under_expr("resource.path", p), f"filesystem:{p}"))
        for r in nested:
            pols.append(o.add("forbid", "fs_write", under_expr("resource.path", r), f"filesystem:{r}",
                              "read-only path inside a read-write path"))
        if deep:
            o.element("filesystem_policy", UNCHECKABLE, f"FS_NESTED_OVERRIDE: read-write {deep} inside read-only "
                      f"{nested} inside read-write; those writes are not permitted", policies=pols)
        else:
            o.element("filesystem_policy", TRANSLATED, policies=pols,
                      note="baseline paths are included as the adapter model adds them")
    if ll_extra:
        o.element("landlock", UNCHECKABLE, f"UNKNOWN_FIELD: {ll_extra}")
    if (doc.get("landlock") or {}).get("compatibility") == "best_effort":
        o.element("landlock.compatibility", UNCHECKABLE, "best_effort: the kernel may start the sandbox without the "
                  "filesystem rules; the Cedar policies state the declaration only")
    if doc.get("process") is not None:
        o.element("process", UNCHECKABLE, "KNOWN_FIELD_NOT_MODELLED: process identity has no Cedar action in v0")
    return "\n\n".join(o.policies) + "\n", _report(doc, o)


def _report(doc: dict, o: Out) -> dict:
    unc = [e for e in o.elements if e["status"] == UNCHECKABLE]
    return {
        "translator": TRANSLATOR, "openshell_pin": A.OPENSHELL_PIN,
        "status": UNCHECKABLE if unc else TRANSLATED,
        "counts": {"policies": o.n, "elements": len(o.elements), "uncheckable": len(unc)},
        "elements": o.elements,
        "rule": "Nothing UNCHECKABLE contributes a permit. Forbids are never dropped, only widened.",
    }


def load(path: str) -> dict:
    """Strict YAML (duplicate keys rejected) WITHOUT rejecting unknown fields: the translator reports them."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    doc = json.loads(text) if path.endswith(".json") else A._yaml_strict(text)
    if not isinstance(doc, dict):
        raise A.PolicyError("policy is not a mapping")
    return doc


def main(argv=None) -> int:
    p = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    p.add_argument("policy")
    p.add_argument("--out", required=True)
    p.add_argument("--name")
    p.add_argument("--workdir", default="/sandbox")
    a = p.parse_args(argv)
    try:
        doc = load(a.policy)
    except (A.PolicyError, OSError, ValueError) as e:
        print(f"input error: {e}", file=sys.stderr)
        return 2
    cedar, rep = translate(doc, a.workdir)
    rep["input"] = {"file": os.path.basename(a.policy), "sha256": A.sha256_file(a.policy)}
    name = a.name or os.path.splitext(os.path.basename(a.policy))[0]
    os.makedirs(a.out, exist_ok=True)
    with open(os.path.join(a.out, name + ".cedar"), "w", encoding="utf-8") as fh:
        fh.write(f"// SPDX-License-Identifier: Apache-2.0\n// generated by {TRANSLATOR['name']} {TRANSLATOR['version']} "
                 f"from {rep['input']['file']} (sha256 {rep['input']['sha256']})\n\n" + cedar)
    with open(os.path.join(a.out, name + ".report.json"), "w", encoding="utf-8") as fh:
        json.dump(rep, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    with open(os.path.join(a.out, "openshell.cedarschema"), "w", encoding="utf-8") as fh:
        fh.write(SCHEMA)
    for e in rep["elements"]:
        if e["status"] == UNCHECKABLE:
            print(f"UNCHECKABLE {e['source']}: {e.get('reason')}")
    print(f"{rep['status']}  policies={rep['counts']['policies']} uncheckable={rep['counts']['uncheckable']}")
    return 0 if rep["status"] == TRANSLATED else 3


if __name__ == "__main__":
    sys.exit(main())
