// Generated by scripts/harness-x/render.mjs — do not hand-edit.
import { tool } from "ai";
import { z } from "zod";
import { callGspc, TOOL_DESCRIPTION } from "./gspc-client.js";

export * from "./gspc-client.js";

/** Vercel AI SDK (v5+) tool: live GSPC board totals. */
export function gspcBoardTotals(opts = {}) {
  return tool({
    description: TOOL_DESCRIPTION,
    inputSchema: z.object({}),
    execute: async () => callGspc("board_totals", {}, opts),
  });
}

export const gspcTools = (opts = {}) => ({ gspc_board_totals: gspcBoardTotals(opts) });
