"""Shared reader: the live GSPC board through csoai-gspc. Generated by scripts/harness-x/render.mjs."""
from __future__ import annotations

from typing import Optional

from csoai_gspc import BOARD_URL, fetch_board, get_axis, totals

DOCTRINE_SHA256 = "845fc1d200eb9e867fc8d682750409d6725084bac632726187759f8fefdfbe0a"
DOCTRINE_SOURCE = "docs/DOCTRINE.md"
TOOL_NAME = "gspc_board"
TOOL_DESCRIPTION = "Read the live Council of AI GSPC board (https://councilof.ai/api/gspc). With no axis, returns the board totals verbatim; with an axis name, returns that one axis row. Quote totals.public_count exactly as printed; never add or re-derive a count. If the board cannot be fetched the state is UNREACHABLE and no number is returned. Measurement only: a card is evidence, never a grade, mark or endorsement. Verification is free."


def read_board(axis: Optional[str] = None) -> dict:
    """Return the live board totals, or one axis row. Three outcomes: LIVE, ABSENT, UNREACHABLE."""
    base = {"source": BOARD_URL, "doctrine_sha256": DOCTRINE_SHA256}
    try:
        board = fetch_board()
    except Exception as exc:  # network, HTTP or JSON failure: say so, never substitute a number
        return {**base, "state": "UNREACHABLE", "error": type(exc).__name__}
    if axis is None:
        return {**base, "state": "LIVE", "totals": totals(board)}
    row = get_axis(axis, board)
    if row is None:
        return {**base, "state": "ABSENT", "axis": axis}
    return {**base, "state": "LIVE", "axis_row": row}
