"""LangChain BaseTool for the GSPC board. Generated by scripts/harness-x/render.mjs."""
from __future__ import annotations

from typing import Optional, Type, Union

from langchain_core.tools import BaseTool
from pydantic import BaseModel, Field

from ._board import TOOL_DESCRIPTION, TOOL_NAME, VERIFY_TOOL_DESCRIPTION, VERIFY_TOOL_NAME, read_board, read_verify


class GSPCBoardInput(BaseModel):
    axis: Optional[str] = Field(default=None, description="Axis name or alias (case-insensitive, e.g. governance or gov) for one board row; omit for the board totals.")


class VerifyCardInput(BaseModel):
    card_id: Optional[str] = Field(default=None, description="The card's full id: 64 hex characters.")
    card: Optional[Union[dict, str]] = Field(default=None, description="Alternatively the card JSON (object or string).")


class GSPCBoardTool(BaseTool):
    name: str = TOOL_NAME
    description: str = TOOL_DESCRIPTION
    args_schema: Type[BaseModel] = GSPCBoardInput

    def _run(self, axis: Optional[str] = None, run_manager=None) -> dict:  # noqa: ARG002
        return read_board(axis)


class VerifyCardTool(BaseTool):
    name: str = VERIFY_TOOL_NAME
    description: str = VERIFY_TOOL_DESCRIPTION
    args_schema: Type[BaseModel] = VerifyCardInput

    def _run(self, card_id: Optional[str] = None, card: Optional[Union[dict, str]] = None, run_manager=None) -> dict:  # noqa: ARG002
        return read_verify(card_id, card)
