import { useEffect, useRef, useState, lazy, Suspense } from "react";
import { Link, useSearch } from "wouter";
import { chargeSovereign } from "../lib/sovCharge";
import { sovActions } from "../lib/sovAgent";
import { detectLocale, REGIONS } from "../lib/locale";
import { flyAndConvene, neutralize } from "../lib/globeDrive";
import CouncilNav from "../components/CouncilNav";
import { setMetaDescription } from "@/lib/utils";
import AISystemNotice from "../components/AISystemNotice";
import { personaSpeak, stopVoice } from "../lib/sovPersona";
import { useLedger, type DecisionRecord } from "../hooks/useLedger";
import JSpaceTimeline, { type TimelineEvent } from "../components/JSpaceTimeline";
import CouncilGalaxy, { type FlywheelPlanet, type HiveLayer, type CitizenNode } from "../components/CouncilGalaxy";

// SOV SPACE is the container OS — the arena, the globe and the towns live
// INSIDE it as layers, not as separate products (Nick's unification law,
// 2026-08-01). The old routes redirect here with ?view=.
const ArenaView = lazy(() => import("./GSPCArena"));
const TownsView = lazy(() => import("./SovereignTown"));
const BenchmarkView = lazy(() => import("./BenchmarkView"));

function GlobeView() {
  const search = useSearch();
  const ask = new URLSearchParams(search).get("ask") || "";
  const frameRef = useRef<HTMLIFrameElement | null>(null);
  function onLoad() {
    if (!ask) return;
    const code = ssGlobeCode(ask);
    const prof = (code && REGIONS[code]) ? REGIONS[code] : REGIONS.GLOBAL;
    const [lng, lat] = prof.globe;
    flyAndConvene(frameRef.current?.contentWindow, lng, lat, { spiral: true });
  }
  return (
    <div className="mx-auto max-w-6xl px-6 pb-10">
      <div className="overflow-hidden rounded-2xl border border-sky-500/25">
        <div className="flex items-center justify-between bg-[#05140d] px-4 py-2">
          <div className="font-mono text-[10px] uppercase tracking-[2px] text-sky-300/70">The Council Globe — the GLOBE AI OS, living inside Council Space{ask ? " · flown to your scenario" : ""}</div>
          <a href="/globe3d.html" className="text-[11px] font-semibold text-sky-200 hover:underline">Open full screen →</a>
        </div>
        <iframe ref={frameRef} onLoad={onLoad} src="/globe3d.html" title="Council 3D Governance Earth" loading="lazy" className="block h-[70vh] w-full" style={{ border: 0 }} />
      </div>
    </div>
  );
}

import { SOV_ARENA_V2 } from "../data/arena.generated";
import { useGeolibre } from "../lib/geolibre";
import { emitCard, promoteCard, subscribeCards, getCards, type AiCard } from "../lib/aiCardBus";

function cardToTimeline(c: AiCard): TimelineEvent {
  return {
    id: c.id,
    ts: c.ts,
    tag: c.kind.toUpperCase().replace(/-/g, " "),
    verdict: c.space === "J" ? "CONFIRMED" : "ACTION",
    claim: c.summary,
    evidence: c.evidence ?? c.detail ?? "",
    weight: c.space === "J" ? 0.95 : 0.6,
    space: c.space,
  };
}

function ArenaEvidenceStrip() {
  const sources = (SOV_ARENA_V2 as any).sources ?? [];
  const geo = useGeolibre();
  return (
    <div className="mx-auto max-w-6xl px-6 pb-4">
      <div className="rounded-2xl border border-emerald-500/25 bg-[#05140d] px-4 py-3">
        <div className="font-mono text-[10px] uppercase tracking-[2px] text-emerald-300/70">
          signed fixture set · {String((SOV_ARENA_V2 as any).schema).replace(/^sov\./, "")} · generated by {(SOV_ARENA_V2 as any).generated_by}
        </div>
        <div className="mt-1 text-[11px] text-emerald-100/70">{(SOV_ARENA_V2 as any).law}</div>
        {geo.enabled && (
          <div className="mt-1 text-[11px] text-sky-200/80">
            ⬡ local shard: {geo.region.label} ({geo.source === "ip" ? "IP-resolved" : "manual"}) — governing frameworks: {geo.region.frameworks.join(" · ")}
          </div>
        )}
        <div className="mt-2 flex flex-wrap gap-2">
          {sources.map((s: any) => (
            <span key={s.file} className="rounded-full border border-emerald-500/25 px-2 py-0.5 font-mono text-[10px] text-emerald-300/75" title={`${s.schema} · ${s.timestamp}`}>
              {s.file} · sha256:{String(s.sha256).slice(0, 10)}…
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

const SS_VIEWS = [
  { id: "console", label: "🎛 Console", href: "/gspc-arena" },
  { id: "arena", label: "🏟 Arena", href: "/gspc-arena?view=arena" },
  { id: "globe", label: "🌍 Globe", href: "/gspc-arena?view=globe" },
  { id: "towns", label: "🇦 Towns", href: "/gspc-arena?view=towns" },
  { id: "benchmarks", label: "📊 Benchmarks", href: "/gspc-arena?view=benchmarks" },
] as const;

type SovViewId = (typeof SS_VIEWS)[number]["id"];

function ViewSwitcher({ view }: { view: string }) {
  return (
    <div className="flex flex-wrap items-center gap-2 pb-4">
      <span className="font-mono text-[10px] uppercase tracking-[2px] text-sky-300/55">OS layers ·</span>
      {SS_VIEWS.map((v) => {
        const active = view === v.id;
        return (
          <Link key={v.id} href={v.href} className={"rounded-full border px-3 py-1 text-[11px] font-bold transition " + (active ? "border-sky-400 bg-sky-500/20 text-sky-100" : "border-sky-400/25 text-sky-300/75 hover:bg-sky-500/10")}>{v.label}</Link>
        );
      })}
    </div>
  );
}

const SS_GLOBE_CODE: Record<string, string> = { EU: "EU", UK: "UK", US: "US", CANADA: "CA", JAPAN: "JP", KOREA: "KR", CHINA: "CN", SINGAPORE: "SG", INDIA: "IN" };
function ssGlobeCode(text: string): string { const r = sovActions(text).find((a) => a.kind === "region"); return r && r.kind === "region" ? (SS_GLOBE_CODE[r.region] || "") : ""; }

type Step = { t: string; phase: number };
const SAMPLE = "A hospital wants to deploy an AI triage model in the EU that ranks ER patients by urgency.";

const HIVE: HiveLayer[] = [
  { id: "eu-ai-act", name: "EU AI Act", count: 113, description: "frozen provisions across 113 articles" },
  { id: "gdpr", name: "GDPR", count: 99, description: "data-protection obligations" },
  { id: "cra", name: "Cyber Resilience Act", count: 71, description: "vulnerability handling, secure-by-default" },
  { id: "dora", name: "DORA", count: 64, description: "digital operational resilience for financial services" },
  { id: "nis2", name: "NIS2", count: 46, description: "essential-entity security duties" },
  { id: "csrd", name: "CSRD", count: 11, description: "sustainability reporting scope" },
  { id: "iso-42001", name: "ISO 42001", count: 8, description: "AI management system controls" },
  { id: "nist-ai-rmf", name: "NIST AI RMF", count: 7, description: "govern / map / measure / manage" },
  { id: "annexes", name: "Annexes", count: 13, description: "annex III high-risk + annex IV technical docs" },
];

const FLYWHEELS: FlywheelPlanet[] = [
  { id: "find-besT", name: "find_besT", axis: "care", phase: "honey", description: "21-subject Day-1 sweep, care_cost joint scoring", metric: "composite=3.1564 (unified fine-tune)", last_run_iso: "2026-07-30T11:17:00Z" },
  { id: "n-eff", name: "n_eff_diversity", axis: "continuity", phase: "milk", description: "pairwise ρ + Kish n_eff across council roster", metric: "n_eff=1.285 · gate failed (>2.0 required)", last_run_iso: "2026-07-30T11:25:00Z" },
  { id: "provbench", name: "ProvBench", axis: "provenance", phase: "honey", description: "0/20 C2PA markings survive binding-intact", metric: "0 of 20 · one-sided 95% CP upper = 13.9% (rule-of-three: 15.0%)", last_run_iso: "2026-07-30T11:00:00Z" },
  { id: "defbench", name: "DefBench", axis: "safety", phase: "honey", description: "45-item care battery, 33 harmful / 12 benign", metric: "1 of 4 axes resolved (with gate)", last_run_iso: "2026-07-30T09:35:00Z" },
  { id: "govbench", name: "GovBench", axis: "governance", phase: "honey", description: "193 samples, 26 dimensions, cluster-robust", metric: "composed +6.63 [+1.05, +12.21]", last_run_iso: "2026-07-30T09:46:00Z" },
  { id: "pqcbench", name: "PQCBench", axis: "continuity", phase: "water", description: "25 criteria for PQC-ready signing chains", metric: "1 of 25 criteria pass · ML-DSA-65 needed", last_run_iso: "2026-07-30T08:00:00Z" },
  { id: "flywheel-daily", name: "flywheel-daily", axis: "care", phase: "honey", description: "cron — daily drift, salted PRACTICE/HELD_OUT split", metric: "selftest 9/9 · salt=csoai-flywheel-v1", last_run_iso: "2026-07-30T03:00:00Z" },
  { id: "honey-pipe", name: "honey_pipeline", axis: "care", phase: "honey", description: "KB harvest → honey cache → cite-on-serve", metric: "83 verified entries · 87KB", last_run_iso: "2026-07-30T05:00:00Z" },
  { id: "production-ready", name: "production_ready", axis: "care", phase: "honey", description: "signed care_cost evidence pack for marketing", metric: "Ed25519 signature · care_score=0.7891", last_run_iso: "2026-07-30T12:00:00Z" },
];

const GW: string = ((import.meta as any).env && (import.meta as any).env.VITE_KNOWLEDGE_BASE) || "/api";
const LOCAL_GW: string = ((import.meta as any).env && (import.meta as any).env.VITE_LOCAL_GATEWAY) || GW;
const SS_INDUSTRIES = ["healthcare","health","hospital","clinical","triage","pharma","biotech","finance","fintech","banking","insurance","lending","credit","education","edtech","retail","ecommerce","legal","government","public sector","defense","energy","utilities","automotive","telecom","manufacturing","logistics","hr","recruiting","hiring","media","gaming","agriculture","transport","aviation","real estate","crypto","web3","marketing"];
function ssIndustry(q: string) { const s = (q || "").toLowerCase(); return SS_INDUSTRIES.find((w) => new RegExp("\\b" + w + "\\b").test(s)) || null; }
function ssRegion(q: string) {
  const s = " " + (q || "").toLowerCase() + " ";
  if (/\bus\b|\busa\b|\bamerica|\bcalifornia\b|\btexas\b|\bcolorado\b|\bnew york\b/.test(s)) return "the United States (NIST AI RMF + state law)";
  if (/\beu\b|\beurope|\bgerman|\bfrance\b|\bspain\b|\bitaly\b|\bireland\b|\bparis\b|\bberlin\b/.test(s)) return "the European Union (EU AI Act)";
  if (/\bchina\b|\bbeijing\b/.test(s)) return "China (TC260)";
  if (/\bsingapore\b/.test(s)) return "Singapore (Model AI Governance)";
  if (/\buk\b|\bbritain\b|\blondon\b/.test(s)) return "the United Kingdom (UK AI regulation)";
  return "a global footprint (ISO 42001)";
}
async function ssGovern(ind: string): Promise<any | null> {
  try { const r = await fetch(GW + "/govern?q=" + encodeURIComponent(ind)); if (r.ok) { const d = await r.json(); if (d && d.matched && d.frameworks && d.frameworks.length) return d; } } catch (e) {}
  return null;
}
async function ssVerdict(scenario: string): Promise<string> {
  try {
    const r = await fetch(GW + "/chat", { method: "POST", headers: { "content-type": "text/plain" }, body: JSON.stringify({ message: "You are the CSOAI multi-agent governance council. In 3 sentences, deliver a verdict on this AI system: is it permitted, and under what key conditions (risk tier, human oversight, transparency, data duties)? System: " + scenario }) });
    if (r.ok) { const d = await r.json(); if (d && d.response && d.model !== "idle" && !/travell?er|companion|walks beside|i'?m sorry|can'?t help|on your journey|dear friend|kindred|as an ai language|remembering/i.test(String(d.response))) return String(d.response); }
  } catch (e) {}
  return "";
}

type KbMatch = { dimension: string; question: string; delta: number; sha256: string; source_clan?: string };
async function ssLookupKB(query: string): Promise<KbMatch[]> {
  try {
    const params = new URLSearchParams({ limit: "3", min_delta: "15", verified_only: "true" });
    const r = await fetch(LOCAL_GW + "/kb?" + params.toString());
    if (!r.ok) return [];
    const d = await r.json();
    const entries: any[] = Array.isArray(d.entries) ? d.entries : [];
    const q = query.toLowerCase();
    const tokens = q.split(/\W+/).filter(t => t.length > 3);
    return entries
      .map((e: any) => {
        const text = ((e.question ?? "") + " " + (e.answer_preview ?? "")).toLowerCase();
        const score = tokens.reduce((acc, t) => acc + (text.includes(t) ? 1 : 0), 0);
        return { score, entry: e };
      })
      .filter((x: any) => x.score > 0)
      .sort((a: any, b: any) => b.score - a.score)
      .slice(0, 3)
      .map((x: any) => ({
        dimension: x.entry.dimension,
        question: x.entry.question,
        delta: x.entry.delta,
        sha256: x.entry.sha256,
        source_clan: x.entry.source_clan,
      }));
  } catch (e) {
    return [];
  }
}

type KbStats = { total_entries: number; verified: number; by_dimension: Record<string, number> };
async function ssKBStats(): Promise<KbStats | null> {
  try {
    const r = await fetch(LOCAL_GW + "/kb/stats");
    if (!r.ok) return null;
    const d = await r.json();
    return {
      total_entries: d.total_entries ?? 0,
      verified: d.verified ?? 0,
      by_dimension: d.by_dimension ?? {},
    };
  } catch (e) {
    return null;
  }
}

function buildRun(scenario: string): Step[] {
  const s = (scenario || "").trim() || SAMPLE;
  const head = s.slice(0, 88) + (s.length > 88 ? "..." : "");
  return [
    { t: "Ingesting your scenario into Council Space: \"" + head + "\"", phase: 1 },
    { t: "Classifying the system - risk tier and applicable regimes detected (EU AI Act, NIST AI RMF, ISO 42001).", phase: 1 },
    { t: "Convening the council - council agents, designed multi-agent review. Quorum forming...", phase: 2 },
    { t: "Agents deliberating - mapping controls, fairness checks, human-oversight duties, transparency obligations.", phase: 2 },
    { t: "Crosswalking once -> EU AI Act, NIST, ISO 42001 and TC260 satisfied from one evidence set.", phase: 3 },
    { t: "Consensus reached. Read the J-space panel below for the signed historical record; this run is a narrated simulation, not a signed probe.", phase: 4 },
  ];
}

function convertToTimeline(records: DecisionRecord[]): TimelineEvent[] {
  return records.map((r) => {
    const w =
      r.verdict === "REFUTED" || r.verdict === "CONFIRMED" || r.verdict === "SETTLED"
        ? 1.0
        : r.verdict === "OPEN"
        ? 0.6
        : 0.7;
    return {
      id: r.id,
      ts: r.decided_on,
      tag: r.tag,
      verdict: r.verdict,
      claim: r.claim,
      evidence: r.evidence,
      sigil: r.sigil_link,
      weight: w,
      space: "J",
    };
  });
}

export default function CouncilSpace() {
  const search = useSearch();
  const view = (new URLSearchParams(search).get("view") || "console") as SovViewId | string;
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const phaseRef = useRef<number>(0);
  const [scenario, setScenario] = useState("");
  const [log, setLog] = useState<string[]>([]);
  const [running, setRunning] = useState(false);
  const [done, setDone] = useState(false);
  const [verdictText, setVerdictText] = useState("");
  const [voiceOn, setVoiceOn] = useState(true);
  const [loc] = useState(() => detectLocale());
  const [cSpaceEvents, setCSpaceEvents] = useState<TimelineEvent[]>([]);
  const [busEvents, setBusEvents] = useState<TimelineEvent[]>(() => getCards().map(cardToTimeline));
  useEffect(() => subscribeCards((cs) => setBusEvents(cs.map(cardToTimeline))), []);
  const [kbMatches, setKbMatches] = useState<KbMatch[]>([]);
  const [flywheels, setFlywheels] = useState<FlywheelPlanet[]>(FLYWHEELS);
  const [citizens, setCitizens] = useState<CitizenNode[]>([]);
  const [kbStats, setKbStats] = useState<KbStats | null>(null);
  const [kbOnline, setKbOnline] = useState<boolean | null>(null);
  const [gwOnline, setGwOnline] = useState<boolean | null>(null);
  const [ledgerOnline, setLedgerOnline] = useState<boolean | null>(null);
  const [ledgerCount, setLedgerCount] = useState<number>(0);
  const [stamps, setStamps] = useState<Array<{ id: string; kind: string; region: string; lng: number; lat: number; claim: string; ts: number; scenario?: string; tag?: string; weight?: number; space?: string }>>([]);
  const [selectedStamp, setSelectedStamp] = useState<{ id: string; kind: string; region: string; lng: number; lat: number; claim: string; ts: number; scenario?: string; tag?: string; weight?: number; space?: string } | null>(null);
  const globeRef = useRef<HTMLIFrameElement | null>(null);
  const { data: ledger, loading: ledgerLoading, error: ledgerError, fetchedAt: ledgerFetchedAt } = useLedger();
  const jrecords = (ledger?.records || []).slice(0, 3);
  const jrecordsErr = ledgerError;
  const jfetchedAt = ledgerFetchedAt ? new Date(ledgerFetchedAt).toISOString() : "";

  useEffect(() => {
    let alive = true;
    ssKBStats().then((s) => {
      if (!alive) return;
      setKbStats(s);
      setKbOnline(s !== null);
    });
    return () => { alive = false; };
  }, []);

  useEffect(() => {
    let alive = true;
    let timer: ReturnType<typeof setTimeout> | null = null;
    async function tick() {
      try {
        const r = await fetch(LOCAL_GW + "/sov-time");
        if (!alive) return;
        if (r.ok) {
          const d = await r.json();
          setLedgerCount(d.total ?? 0);
          setLedgerOnline(true);
        } else {
          setLedgerOnline(false);
        }
      } catch {
        if (alive) setLedgerOnline(false);
      }
      if (alive) timer = setTimeout(tick, 5000);
    }
    tick();
    return () => { alive = false; if (timer) clearTimeout(timer); };
  }, []);

  useEffect(() => {
    const q = scenario.trim();
    if (q.length < 12) { setKbMatches([]); return; }
    const t = setTimeout(async () => {
      const matches = await ssLookupKB(q);
      setKbMatches(matches);
    }, 350);
    return () => clearTimeout(t);
  }, [scenario]);

  function stampPresence(reason: string, extra: Record<string, unknown> = {}) {
    const code = ssGlobeCode(scenario);
    const prof = (code && REGIONS[code]) ? REGIONS[code] : REGIONS.GLOBAL;
    const [lng, lat] = prof.globe;
    fetch(LOCAL_GW + "/sov-time", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        kind: "presence",
        space: "P",
        reason,
        region: code || "GLOBAL",
        lng, lat,
        ...extra,
      }),
    }).catch(() => { });
  }

  useEffect(() => {
    let alive = true;
    let timer: ReturnType<typeof setTimeout> | null = null;
    async function tick() {
      try {
        const r = await fetch(LOCAL_GW + "/sov-time");
        if (!alive) return;
        if (r.ok) {
          const d = await r.json();
          const events = Array.isArray(d.events) ? d.events : [];
          const mapped = events.map((e: any) => {
            const p = e.payload ?? {};
            const region = p.region || "GLOBAL";
            const prof = (REGIONS as any)[region] || REGIONS.GLOBAL;
            const [lng, lat] = (p.lng != null && p.lat != null) ? [p.lng, p.lat] : prof.globe;
            return {
              id: e.id,
              kind: p.kind || e.kind || "cspace",
              region,
              lng,
              lat,
              claim: p.claim || p.scenario || `${region} ${p.kind ?? ""}`.trim(),
              ts: e.ts,
              scenario: p.scenario,
              tag: p.tag,
              weight: p.weight,
              space: p.space || "C",
            };
          });
          setStamps(mapped);
          setLedgerCount(d.total ?? 0);
          setLedgerOnline(true);
          const win = globeRef.current?.contentWindow;
          if (win) {
            win.postMessage({ cmd: "stampsClear" }, "*");
            if (mapped.length > 0) {
              win.postMessage({ cmd: "stamps", stamps: mapped }, "*");
            }
          }
        } else {
          setLedgerOnline(false);
        }
      } catch {
        if (alive) setLedgerOnline(false);
      }
      if (alive) timer = setTimeout(tick, 5000);
    }
    tick();
    return () => { alive = false; if (timer) clearTimeout(timer); };
  }, []);

  useEffect(() => {
    function onMessage(ev: MessageEvent) {
      const d = ev.data;
      if (!d || d.cmd !== "stampClick" || !d.payload) return;
      setSelectedStamp(d.payload);
    }
    window.addEventListener("message", onMessage);
    return () => window.removeEventListener("message", onMessage);
  }, []);
  function flyToScenario(text: string) {
    const code = ssGlobeCode(text);
    const prof = (code && REGIONS[code]) ? REGIONS[code] : REGIONS.GLOBAL;
    const [lng, lat] = prof.globe;
    const win = globeRef.current?.contentWindow;
    flyAndConvene(win, lng, lat, { spiral: true });
    if (sovActions(text).some((a) => a.kind === "threat")) window.setTimeout(() => neutralize(win), 6600);
  }
  const [globeRegion, setGlobeRegion] = useState(() => (loc.region.code === "GLOBAL" ? "" : loc.region.code));
  const endRef = useRef<HTMLDivElement | null>(null);
  const timers = useRef<any[]>([]);

  useEffect(() => {
    document.title = "Council Space | CSOAI";
    setMetaDescription("Council Space — the Council of AI's live simulation arena: model versus model on frozen benchmarks, every round emitted as signed evidence. Live board counts: GET /api/gspc.");
    try { const q = new URLSearchParams(window.location.search).get("q"); if (q) { setScenario(q); setGlobeRegion(ssGlobeCode(q)); } } catch (e) {}
  }, []);
  useEffect(() => { const d = new URLSearchParams(window.location.search).get("demo"); if (d) { setScenario(d); const t = setTimeout(() => run(d), 700); return () => clearTimeout(t); } }, []);
  useEffect(() => { if (endRef.current) endRef.current.scrollIntoView({ behavior: "smooth" }); }, [log]);
  useEffect(() => () => { timers.current.forEach(clearTimeout); stopVoice(); }, []);

  useEffect(() => {
    let cancelled = false;
    fetch("/flywheel-snapshot.json")
      .then((r) => (r.ok ? r.json() : null))
      .then((snap: { planets?: FlywheelPlanet[]; citizens?: CitizenNode[] } | null) => {
        if (cancelled || !snap) return;
        if (Array.isArray(snap.planets) && snap.planets.length > 0) setFlywheels(snap.planets);
        if (Array.isArray(snap.citizens)) setCitizens(snap.citizens);
      })
      .catch(() => {});
    return () => { cancelled = true; };
  }, []);

  useEffect(() => {
    const cv = canvasRef.current; if (!cv) return;
    const ctx = cv.getContext("2d"); if (!ctx) return;
    let raf = 0; const DPR = Math.min(window.devicePixelRatio || 1, 2);
    function size() { const r = cv.getBoundingClientRect(); cv.width = r.width * DPR; cv.height = r.height * DPR; }
    size(); window.addEventListener("resize", size);
    const N = 33; let tick = 0;
    function frame() {
      tick += 1; const w = cv.width, h = cv.height, cx = w / 2, cy = h / 2;
      const ph = phaseRef.current;
      ctx.clearRect(0, 0, w, h);
      ctx.fillStyle = "#03110b"; ctx.fillRect(0, 0, w, h);
      const R = Math.min(w, h) * 0.34;
      for (let i = 0; i < N; i++) {
        const a = (i / N) * Math.PI * 2 + tick * 0.002;
        const x = cx + Math.cos(a) * R, y = cy + Math.sin(a) * R;
        const lit = ph >= 2 && ((tick * 0.6 + i * 7) % N) < (ph * 6);
        ctx.beginPath(); ctx.arc(x, y, lit ? 5 * DPR : 3 * DPR, 0, Math.PI * 2);
        ctx.fillStyle = lit ? "#34d399" : "rgba(16,185,129,0.35)"; ctx.fill();
        if (ph >= 3) { ctx.strokeStyle = "rgba(16,185,129," + (0.05 + 0.05 * Math.sin(tick * 0.05 + i)) + ")"; ctx.beginPath(); ctx.moveTo(cx, cy); ctx.lineTo(x, y); ctx.stroke(); }
      }
      if (ph >= 1) { for (let k = 0; k < 26; k++) { const p = ((tick * 4 + k * 30) % 300) / 300; const x = 20 * DPR + p * (cx - 20 * DPR); const y = cy + Math.sin(k + tick * 0.04) * 26 * DPR; ctx.fillStyle = "rgba(110,231,183," + (1 - p) + ")"; ctx.fillRect(x, y, 2.4 * DPR, 2.4 * DPR); } }
      const pulse = 1 + 0.08 * Math.sin(tick * 0.08);
      const grd = ctx.createRadialGradient(cx, cy, 2, cx, cy, 46 * DPR * pulse);
      grd.addColorStop(0, ph >= 4 ? "#a7f3d0" : "#10b981"); grd.addColorStop(1, "rgba(4,120,87,0)");
      ctx.fillStyle = grd; ctx.beginPath(); ctx.arc(cx, cy, 46 * DPR * pulse, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = "#05140d"; ctx.beginPath(); ctx.arc(cx, cy, 20 * DPR, 0, Math.PI * 2); ctx.fill();
      ctx.fillStyle = "#6ee7b7"; ctx.font = (14 * DPR) + "px ui-monospace, monospace"; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.fillText(String.fromCharCode(9673), cx, cy);
      raf = requestAnimationFrame(frame);
    }
    frame();
    return () => { cancelAnimationFrame(raf); window.removeEventListener("resize", size); };
  }, []);

  function speak(t: string) { if (!voiceOn) return; personaSpeak(t); }

  function playSteps(steps: Step[], verdict?: string) {
    let i = 0;
    const runStart = Date.now();
    const play = () => {
      if (i >= steps.length) {
        phaseRef.current = 4;
        if (verdict) { setVerdictText(verdict); setLog((l) => l.concat("Verdict: " + verdict)); }
        setRunning(false); setDone(true);
        const cEvent: TimelineEvent = {
          id: "c-v-" + runStart.toString(36),
          ts: Date.now(),
          tag: "ACTION",
          verdict: "COMPLETE",
          claim: verdict ? verdict.slice(0, 140) : "Run completed — verdict pending",
          evidence: "C-space: council verdict reached.",
          weight: 0.95,
          space: "C",
        };
        setCSpaceEvents((prev) => [cEvent, ...prev].slice(0, 50));
        const vCard = emitCard({ kind: "council-verdict", summary: cEvent.claim, detail: "multi-agent council deliberation on: " + scenario.slice(0, 140), axis: "governance", source: verdict ? "live" : "local-sim" });
        fetch(LOCAL_GW + "/sov-time", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            kind: "cspace-verdict",
            space: "C",
            claim: cEvent.claim,
            tag: cEvent.tag,
            verdict: cEvent.verdict,
            weight: cEvent.weight,
          }),
        })
          .then((r) => {
            if (r.ok) promoteCard(vCard.id, "sov-time ledger · cspace-verdict");
          })
          .catch(() => { });
        return;
      }
      const st = steps[i++]; phaseRef.current = st.phase; setLog((l) => l.concat(st.t)); speak(st.t);
      const phaseTag = st.phase === 1 ? "OPEN" : st.phase === 2 ? "ACTION" : st.phase === 3 ? "CONFIRMED" : "ACTION";
      const phaseWeight = st.phase === 1 ? 0.4 : st.phase === 2 ? 0.55 : st.phase === 3 ? 0.7 : 0.9;
      const stepEvent: TimelineEvent = {
        id: "c-s-" + runStart.toString(36) + "-" + i,
        ts: Date.now(),
        tag: phaseTag,
        verdict: st.phase === 4 ? "COMPLETE" : "PENDING",
        claim: st.t.slice(0, 120),
        evidence: "C-space: phase " + st.phase + " step.",
        weight: phaseWeight,
        space: "C",
      };
      setCSpaceEvents((prev) => [stepEvent, ...prev].slice(0, 50));
      fetch(LOCAL_GW + "/sov-time", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          kind: "cspace-step",
          space: "C",
          phase: st.phase,
          claim: stepEvent.claim,
          tag: stepEvent.tag,
          weight: stepEvent.weight,
        }),
      }).catch(() => { });
      const id = setTimeout(play, 1050); timers.current.push(id);
    };
    play();
  }

  function buildLiveRun(scenario: string, region: string, fwNames: string[], bridges: string[], ind: string | null): Step[] {
    const s = (scenario || "").trim() || SAMPLE;
    const head = s.slice(0, 88) + (s.length > 88 ? "..." : "");
    const fwList = fwNames.length ? fwNames.join(", ") : "EU AI Act, NIST AI RMF, ISO 42001";
    return [
      { t: "Ingesting your scenario into Council Space: \"" + head + "\"", phase: 1 },
      { t: "Classifying the system - jurisdiction: " + region + (ind ? "; sector: " + ind : "") + ".", phase: 1 },
      { t: "Applicable regimes detected: " + fwList + ".", phase: 1 },
      { t: "Convening the council - council agents, designed multi-agent review. Quorum forming...", phase: 2 },
      { t: "Agents deliberating - risk tier, fairness checks, human-oversight duties, transparency obligations.", phase: 2 },
      { t: "Crosswalking once -> " + fwList + " satisfied from one evidence set." + (bridges.length ? " Legacy bridge: " + bridges.join(", ") + "." : ""), phase: 3 },
      { t: "Consensus reached. Read the J-space panel below for the signed historical record; this run is a narrated simulation, not a signed probe.", phase: 4 },
    ];
  }

  async function run(override?: string) {
    timers.current.forEach(clearTimeout); timers.current = [];
    if (override) setScenario(override);
    setGlobeRegion(ssGlobeCode(override ?? scenario));
    flyToScenario(override ?? scenario);
    setLog(["Convening the council over your scenario..."]); setVerdictText(""); setDone(false); setRunning(true); phaseRef.current = 2; chargeSovereign(10);
    const scen = ((override ?? scenario) || "").trim() || SAMPLE;
    const ind = ssIndustry(scen);
    const region = ssRegion(scen);
    const kbP = ssLookupKB(scen).then((m) => setKbMatches(m)).catch(() => {});
    stampPresence("scenario-run", { scenario: scen.slice(0, 140), region, ind });
    try {
      const [gov, verdict] = await Promise.all([ind ? ssGovern(ind) : Promise.resolve(null), ssVerdict(scen), kbP]);
      setGwOnline(true);
      const fwNames: string[] = gov && Array.isArray(gov.frameworks) ? gov.frameworks.map((f: any) => f.name) : [];
      const bridges: string[] = gov && Array.isArray(gov.bridges) ? gov.bridges : [];
      setLog([]);
      playSteps(buildLiveRun(scen, region, fwNames, bridges, ind), verdict || "Permitted with conditions - high-risk controls, human oversight, and transparency required.");
      return;
    } catch (e) {
      setGwOnline(false);
      setLog((l) => l.concat("Live gateway unavailable - running local simulation."));
    }
    playSteps(buildRun(scen), "Compliant with conditions - signed and ledgered.");
  }
  function reset() { timers.current.forEach(clearTimeout); stopVoice(); phaseRef.current = 0; setLog([]); setRunning(false); setDone(false); setVerdictText(""); }

  if (view !== "console") {
    return (
      <div className="min-h-screen bg-[#03110b] text-emerald-50">
        <section className="relative mx-auto max-w-6xl px-6 pt-14 pb-2">
          <CouncilNav />
          <ViewSwitcher view={view} />
        </section>
        <Suspense fallback={<div className="mx-auto max-w-6xl px-6 py-16 font-mono text-sm text-emerald-300/60">loading the {view} layer…</div>}>
          {view === "arena" && (<><ArenaEvidenceStrip /><ArenaView /></>)}
          {view === "globe" && <GlobeView />}
          {view === "towns" && <TownsView />}
          {view === "benchmarks" && <BenchmarkView />}
          {view !== "arena" && view !== "globe" && view !== "towns" && view !== "benchmarks" && (
            <div className="mx-auto max-w-6xl px-6 py-16 text-emerald-300/60">Unknown layer “{view}” — pick one above.</div>
          )}
        </Suspense>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#03110b] text-emerald-50">
      <section className="relative overflow-hidden mx-auto max-w-6xl px-6 pt-14 pb-6">
        <div className="pointer-events-none absolute inset-0" style={{ background: "radial-gradient(800px 380px at 30% -10%, rgba(16,185,129,.18), transparent 60%)" }} />
        <div className="relative"><CouncilNav /><ViewSwitcher view={view} /></div>
        <p className="relative font-mono text-[11px] uppercase tracking-[3px] text-emerald-300/70">CSOAI OS - Council Space</p>
        <h1 className="relative mt-2 text-5xl sm:text-6xl font-black tracking-tight">Measure. <span className="bg-gradient-to-r from-emerald-300 via-emerald-400 to-teal-300 bg-clip-text text-transparent">Record.</span></h1>
        <p className="mt-3 max-w-2xl text-emerald-100/80">Feed a real-world scenario - data or text - into the AI-OS. Watch the multi-agent council deliberate live while your Council assistant narrates and speaks every step. This is the web preview of the immersive Unreal Engine 5 world; the full OS pixel-streams the same flow from UE5.</p>
        <div className="relative mt-4 max-w-2xl"><AISystemNotice route="/simulate" /></div>
        <div className="relative mt-4 inline-flex max-w-2xl flex-wrap items-center gap-x-2 gap-y-1 rounded-xl border border-emerald-500/20 bg-black/25 px-3 py-2 text-sm">
          <span className="font-semibold text-emerald-200">{loc.greeting}</span>
          <span className="text-emerald-100/40">·</span>
          <span className="text-emerald-100/75">{loc.region.label}: {loc.region.frameworks.slice(0, 3).join(", ")}</span>
          <span className="text-emerald-100/40">·</span>
          <span className={kbOnline === null ? "text-emerald-100/40" : kbOnline ? "text-amber-200" : "text-rose-300/80"} title="Knowledge base status">
            KB: {kbOnline ? (kbStats ? `${kbStats.verified} verified` : "online") : "offline"}
          </span>
          <span className="text-emerald-100/40">·</span>
          <span className={ledgerOnline === null ? "text-emerald-100/40" : ledgerOnline ? "text-sky-200" : "text-rose-300/80"} title="Council Space event ledger">
            Ledger: {ledgerOnline ? `${ledgerCount} events` : "offline"}
          </span>
        </div>
      </section>
      <section className="mx-auto grid max-w-6xl gap-5 px-6 pb-12 lg:grid-cols-[1.1fr_1fr]">
        <div className="relative overflow-hidden rounded-2xl border border-emerald-500/20">
          <canvas ref={canvasRef} className="h-[420px] w-full block" />
          <div className="absolute left-3 top-3 rounded-md bg-black/40 px-2 py-1 font-mono text-[10px] uppercase tracking-[2px] text-emerald-300/80">{running ? "council deliberating" : done ? "council complete - verdict below" : "council space - idle"}</div>
          <div className={"absolute right-3 top-3 rounded-md px-2 py-1 font-mono text-[10px] uppercase tracking-[2px] " + (gwOnline === null ? "bg-slate-500/20 text-slate-200" : gwOnline ? "bg-emerald-500/20 text-emerald-200" : "bg-rose-500/20 text-rose-200")} title="Honest state of the Council gateway — set by your last run, never hardcoded">
            {gwOnline === null ? "gateway · untested" : gwOnline ? "LIVE - Council gateway" : "gateway offline - local sim"}
          </div>
        </div>
        <div className="flex flex-col rounded-2xl border border-emerald-500/20 bg-[#05140d] p-4">
          <label className="text-xs font-bold text-emerald-200/80">Your experiment</label>
          <textarea value={scenario} onChange={(e) => setScenario(e.target.value)} placeholder={SAMPLE} rows={3} className="mt-2 resize-none rounded-xl border border-emerald-500/25 bg-black/30 p-3 text-sm text-emerald-50 placeholder-emerald-300/30 focus:outline-none" />
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <button onClick={() => run()} disabled={running} className="rounded-xl bg-emerald-500 px-4 py-2 text-sm font-bold text-[#03110b] hover:bg-emerald-400 disabled:opacity-50">{running ? "Running..." : "Run experiment"}</button>
            <button onClick={reset} className="rounded-xl border border-emerald-400/40 px-3 py-2 text-sm font-semibold text-emerald-100 hover:bg-white/5">Reset</button>
            <button onClick={() => { setVoiceOn((x) => !x); stopVoice(); }} className="rounded-xl border border-emerald-400/40 px-3 py-2 text-sm text-emerald-100 hover:bg-white/5">{voiceOn ? "Voice on" : "Voice off"}</button>
            <a href={"/gspc-arena?view=globe" + (scenario ? "&ask=" + encodeURIComponent(scenario) : "")} className="rounded-xl border border-sky-400/40 px-3 py-2 text-sm font-semibold text-sky-100 hover:bg-white/5">See it on the Council Globe →</a>
            <button onClick={() => stampPresence("walk-around", { pov: "all", zoom: "all" })} className="rounded-xl border border-amber-400/40 px-3 py-2 text-sm font-semibold text-amber-100 hover:bg-white/5" title="Stamp your POV as 'all-of-data'">EAT ALL</button>
          </div>
          <div role="status" aria-live="polite" className="mt-3 rounded-md border border-amber-400/35 bg-amber-400/10 px-3 py-1.5 text-[11px] font-semibold text-amber-100">
            You are interacting with an AI system.
          </div>
          <div className="mt-3 flex-1 space-y-2 overflow-y-auto rounded-xl border border-emerald-500/10 bg-black/20 p-3 text-sm" style={{ minHeight: 180 }}>
            {log.length === 0 && <div className="text-emerald-300/40">The Council assistant will narrate here as your experiment runs.</div>}
            {log.map((m, i) => (<div key={i} className="flex gap-2"><span className="text-emerald-400">{String.fromCharCode(9673)}</span><span className="text-emerald-50/90">{m}</span></div>))}
            {done && <div className="mt-2 rounded-lg border border-emerald-400/30 bg-emerald-500/10 px-3 py-2 text-emerald-100">{verdictText ? <div className="mb-2 leading-relaxed"><b className="text-emerald-200">Council verdict:</b> {verdictText}</div> : <div className="mb-2"><b>Verdict:</b> simulation complete.</div>}<div className="mt-3 flex flex-wrap gap-2"><a href="/system-card" className="rounded-lg border border-amber-400/40 bg-amber-400/10 px-3 py-1.5 text-xs font-bold text-amber-100 hover:bg-amber-400/20">Get a signed System Card →</a><a href={"/hive?q=" + encodeURIComponent(scenario)} className="rounded-lg border border-emerald-400/40 px-3 py-1.5 text-xs font-semibold text-emerald-100 hover:bg-white/5">Collect the frameworks →</a><a href="/try" className="rounded-lg border border-emerald-400/40 px-3 py-1.5 text-xs font-semibold text-emerald-100 hover:bg-white/5">Inspect on the live Council →</a></div></div>}
            <div ref={endRef} />
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-8">
        <div className="overflow-hidden rounded-2xl border border-sky-500/25 bg-[#05140d]">
          <div className="flex items-center justify-between border-b border-sky-500/15 px-4 py-2">
            <div>
              <div className="font-mono text-[10px] uppercase tracking-[2px] text-sky-300/70">Council Space · 5D layered view</div>
              <div className="text-sm font-bold text-sky-100">Hive → C-space → J-space → flywheels → live data — the estate as a galaxy</div>
            </div>
            <div className="text-right font-mono text-[10px] text-sky-300/60">zoom: ∞ · flywheels: {flywheels.length}</div>
          </div>
          <div className="p-2">
            <CouncilGalaxy hive={HIVE} cspace={cSpaceEvents.length} jspace={jrecords.length} flywheels={flywheels} citizens={citizens} height={520} />
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 pb-8">
        <div className="rounded-2xl border border-emerald-500/25 bg-[#05140d] p-5">
          <div className="flex items-center justify-between border-b border-emerald-500/15 pb-3">
            <div>
              <div className="font-mono text-[10px] uppercase tracking-[2px] text-emerald-300/70">J-space · C-space · infinite timeline</div>
              <div className="text-sm font-bold text-emerald-100">The Moat, Visible — every event recorded in time</div>
            </div>
            <div className="text-right">
              <div className="font-mono text-[10px] text-emerald-300/60">{jfetchedAt ? "current as of " + new Date(jfetchedAt).toUTCString().replace("GMT", "UTC") : "loading…"}</div>
              <a href="/live-ledger" className="text-[11px] font-semibold text-emerald-200 hover:underline">Open the full ledger →</a>
            </div>
          </div>
          {jrecordsErr && (
            <div className="mt-3 rounded border border-rose-500/30 bg-rose-500/10 p-3 text-xs text-rose-200">
              Upstream unavailable ({jrecordsErr}). The moat is not visible right now — this is rendered honestly, not simulated.
            </div>
          )}
          {(jrecords.length > 0 || cSpaceEvents.length > 0 || busEvents.length > 0) && (
            <div className="mt-4">
              <JSpaceTimeline events={[...convertToTimeline(jrecords), ...busEvents, ...cSpaceEvents]} onSelect={(ev) => { if (ev.space !== "C") setScenario((q) => q + (q ? " — " : "") + ev.claim); }} />
            </div>
          )}
        </div>
      </section>
      <section className="mx-auto max-w-6xl px-6 pb-8">
        <div className="overflow-hidden rounded-2xl border border-sky-500/25">
          <div className="flex items-center justify-between bg-[#05140d] px-4 py-2">
            <div className="font-mono text-[10px] uppercase tracking-[2px] text-sky-300/70">The Council Globe — {globeRegion ? "flown to " + globeRegion + " for your scenario" : "one Council, one world — run a scenario to fly it"}</div>
            <a href={"/gspc-arena?view=globe" + (scenario ? "&ask=" + encodeURIComponent(scenario) : "")} className="text-[11px] font-semibold text-sky-200 hover:underline">Open the full globe →</a>
          </div>
          <iframe ref={globeRef} src={"/globe3d.html" + (loc.region.code !== "GLOBAL" ? "?region=" + loc.region.code : "")} title="Council globe" loading="lazy" className="block h-[360px] w-full" style={{ border: 0 }} />
          {selectedStamp && (
            <div className="border-t border-sky-500/15 px-4 py-3">
              <div className="flex items-center justify-between">
                <div className="font-mono text-[10px] uppercase tracking-[2px] text-sky-300/70">Stamp · {selectedStamp.kind} · {selectedStamp.region}</div>
                <button onClick={() => setSelectedStamp(null)} className="font-mono text-[10px] text-sky-300/50 hover:text-sky-100">✕ close</button>
              </div>
              <div className="mt-2 text-[12px] text-sky-100/90"><strong className="text-sky-200">{selectedStamp.claim || "(no claim)"}</strong></div>
            </div>
          )}
          {!selectedStamp && stamps.length > 0 && (
            <div className="border-t border-sky-500/15 px-4 py-2 text-[10px] font-mono text-sky-300/50">{stamps.length} stamp{stamps.length === 1 ? "" : "s"} on the dome · click any glyph to inspect</div>
          )}
        </div>
      </section>
      <section className="mx-auto max-w-6xl px-6 pb-16">
        <div className="grid gap-4 sm:grid-cols-3">
          <a href="/try" className="rounded-2xl border border-emerald-500/20 bg-[#05140d] p-5 hover:border-emerald-400/40"><div className="text-lg font-bold">Ask the live Council</div><p className="mt-1 text-sm text-emerald-100/70">Take a real question to the the council and get a verdict.</p></a>
          <a href="/academy" className="rounded-2xl border border-emerald-500/20 bg-[#05140d] p-5 hover:border-emerald-400/40"><div className="text-lg font-bold">Training, not certification</div><p className="mt-1 text-sm text-emerald-100/70">Learn the living board. Completion attests training, not conformity.</p></a>
          <a href="/charter" className="rounded-2xl border border-emerald-500/20 bg-[#05140d] p-5 hover:border-emerald-400/40"><div className="text-lg font-bold">The Council Charter</div><p className="mt-1 text-sm text-emerald-100/70">The constitution the OS is governed by - read and align.</p></a>
        </div>
      </section>
    </div>
  );
}
