import { useEffect, useRef, useState, lazy, Suspense } from "react";
import { Link, useSearch } from "wouter";
import { chargeSovereign } from "../lib/sovCharge";
import { sovActions } from "../lib/sovAgent";
import { detectLocale, REGIONS } from "../lib/locale";
import { flyAndConvene, neutralize } from "../lib/globeDrive";
import CouncilNav from "../components/CouncilNav";
import { setMetaDescription } from "@/lib/utils";
import AISystemNotice from "../components/AISystemNotice";
import { personaSpeak, stopVoice } from "../lib/sovPersona";
import { useLedger, type DecisionRecord } from "../hooks/useLedger";
import JSpaceTimeline, { type TimelineEvent } from "../components/JSpaceTimeline";
import CouncilGalaxy, { type FlywheelPlanet, type HiveLayer, type CitizenNode } from "../components/CouncilGalaxy";

// SOV SPACE is the container OS — the arena, the globe and the towns live
// INSIDE it as layers, not as separate products (Nick's unification law,
// 2026-08-01). The old routes redirect here with ?view=.
const ArenaView = lazy(() => import("./GSPCArena"));
const TownsView = lazy(() => import("./SovereignTown"));

function GlobeView() {
  const search = useSearch();
  const ask = new URLSearchParams(search).get("ask") || "";
  const frameRef = useRef<HTMLIFrameElement | null>(null);
  function onLoad() {
    if (!ask) return;
    const code = ssGlobeCode(ask);
    const prof = (code && REGIONS[code]) ? REGIONS[code] : REGIONS.GLOBAL;
    const [lng, lat] = prof.globe;
    flyAndConvene(frameRef.current?.contentWindow, lng, lat, { spiral: true });
  }
  return (
    <div className="mx-auto max-w-6xl px-6 pb-10">
      <div className="overflow-hidden rounded-2xl border border-sky-500/25">
        <div className="flex items-center justify-between bg-[#05140d] px-4 py-2">
          <div className="font-mono text-[10px] uppercase tracking-[2px] text-sky-300/70">The Council Globe — the GLOBE AI OS, living inside Council Space{ask ? " · flown to your scenario" : ""}</div>
          <a href="/globe3d.html" className="text-[11px] font-semibold text-sky-200 hover:underline">Open full screen →</a>
        </div>
        <iframe ref={frameRef} onLoad={onLoad} src="/globe3d.html" title="Council 3D Governance Earth" loading="lazy" className="block h-[70vh] w-full" style={{ border: 0 }} />
      </div>
    </div>
  );
}

import { SOV_ARENA_V2 } from "../data/arena.generated";
import { useGeolibre } from "../lib/geolibre";
import { emitCard, promoteCard, subscribeCards, getCards, type AiCard } from "../lib/aiCardBus";

function cardToTimeline(c: AiCard): TimelineEvent {
  return {
    id: c.id,
    ts: c.ts,
    tag: c.kind.toUpperCase().replace(/-/g, " "),
    verdict: c.space === "J" ? "CONFIRMED" : "ACTION",
    claim: c.summary,
    evidence: c.evidence ?? c.detail ?? "",
    weight: c.space === "J" ? 0.95 : 0.6,
    space: c.space,
  };
}

function ArenaEvidenceStrip() {
  const sources = (SOV_ARENA_V2 as any).sources ?? [];
  const geo = useGeolibre();
  return (
    <div className="mx-auto max-w-6xl px-6 pb-4">
      <div className="rounded-2xl border border-emerald-500/25 bg-[#05140d] px-4 py-3">
        <div className="font-mono text-[10px] uppercase tracking-[2px] text-emerald-300/70">
          signed fixture set · {(SOV_ARENA_V2 as any).schema} · generated by {(SOV_ARENA_V2 as any).generated_by}
        </div>
        <div className="mt-1 text-[11px] text-emerald-100/70">{(SOV_ARENA_V2 as any).law}</div>
        {geo.enabled && (
          <div className="mt-1 text-[11px] text-sky-200/80">
            ⬡ local shard: {geo.region.label} ({geo.source === "ip" ? "IP-resolved" : "manual"}) — governing frameworks: {geo.region.frameworks.join(" · ")}
          </div>
        )}
        <div className="mt-2 flex flex-wrap gap-2">
          {sources.map((s: any) => (
            <span key={s.file} className="rounded-full border border-emerald-500/25 px-2 py-0.5 font-mono text-[10px] text-emerald-300/75" title={`${s.schema} · ${s.timestamp}`}>
              {s.file} · sha256:{String(s.sha256).slice(0, 10)}…
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

const SS_VIEWS = [
  { id: "console", label: "🎛 Console", href: "/gspc-arena" },
  { id: "arena", label: "🏟 Arena", href: "/gspc-arena?view=arena" },
  { id: "globe", label: "🌍 Globe", href: "/gspc-arena?view=globe" },
  { id: "towns", label: "🇦 Towns", href: "/gspc-arena?view=towns" },
] as const;

type SovViewId = (typeof SS_VIEWS)[number]["id"];

function ViewSwitcher({ view }: { view: string }) {
  return (
    <div className="flex flex-wrap items-center gap-2 pb-4">
      <span className="font-mono text-[10px] uppercase tracking-[2px] text-sky-300/55">OS layers ·</span>
      {SS_VIEWS.map((v) => {
        const active = view === v.id;
        return (
          <Link key={v.id} href={v.href} className={"rounded-full border px-3 py-1 text-[11px] font-bold transition " + (active ? "border-sky-400 bg-sky-500/20 text-sky-100" : "border-sky-400/25 text-sky-300/75 hover:bg-sky-500/10")}>{v.label}</Link>
        );
      })}
    </div>
  );
}

const SS_GLOBE_CODE: Record<string, string> = { EU: "EU", UK: "UK", US: "US", CANADA: "CA", JAPAN: "JP", KOREA: "KR", CHINA: "CN", SINGAPORE: "SG", INDIA: "IN" };
function ssGlobeCode(text: string): string { const r = sovActions(text).find((a) => a.kind === "region"); return r && r.kind === "region" ? (SS_GLOBE_CODE[r.region] || "") : ""; }

type Step = { t: string; phase: number };
const SAMPLE = "A hospital wants to deploy an AI triage model in the EU that ranks ER patients by urgency.";

const HIVE: HiveLayer[] = [
  { id: "eu-ai-act", name: "EU AI Act", count: 113, description: "frozen provisions across 113 articles" },
  { id: "gdpr", name: "GDPR", count: 99, description: "data-protection obligations" },
  { id: "cra", name: "Cyber Resilience Act", count: 71, description: "vulnerability handling, secure-by-default" },
  { id: "dora", name: "DORA", count: 64, description: "digital operational resilience for financial services" },
  { id: "nis2", name: "NIS2", count: 46, description: "essential-entity security duties" },
  { id: "csrd", name: "CSRD", count: 11, description: "sustainability reporting scope" },
  { id: "iso-42001", name: "ISO 42001", count: 8, description: "AI management system controls" },
  { id: "nist-ai-rmf", name: "NIST AI RMF", count: 7, description: "govern / map / measure / manage" },
  { id: "annexes", name: "Annexes", count: 13, description: "annex III high-risk + annex IV technical docs" },
];

const FLYWHEELS: FlywheelPlanet[] = [
  { id: "find-besT", name: "find_besT", axis: "care", phase: "honey", description: "21-subject Day-1 sweep, care_cost joint scoring", metric: "composite=3.1564 (sov33-unified)", last_run_iso: "2026-07-30T11:17:00Z" },
  { id: "n-eff", name: "n_eff_diversity", axis: "continuity", phase: "milk", description: "pairwise ρ + Kish n_eff across council roster", metric: "n_eff=1.285 · gate failed (>2.0 required)", last_run_iso: "2026-07-30T11:25:00Z" },
  { id: "provbench", name: "ProvBench", axis: "provenance", phase: "honey", description: "0/20 C2PA markings survive binding-intact", metric: "0 of 20 · one-sided 95% CP upper = 13.9% (rule-of-three: 15.0%)", last_run_iso: "2026-07-30T11:00:00Z" },
  { id: "defbench", name: "DefBench", axis: "safety", phase: "honey", description: "45-item care battery, 33 harmful / 12 benign", metric: "1 of 4 axes resolved (with gate)", last_run_iso: "2026-07-30T09:35:00Z" },
  { id: "govbench", name: "GovBench", axis: "governance", phase: "honey", description: "193 samples, 26 dimensions, cluster-robust", metric: "composed +6.63 [+1.05, +12.21]", last_run_iso: "2026-07-30T09:46:00Z" },
  { id: "pqcbench", name: "PQCBench", axis: "continuity", phase: "water", description: "25 criteria for PQC-ready signing chains", metric: "1 of 25 criteria pass · ML-DSA-65 needed", last_run_iso: "2026-07-30T08:00:00Z" },
  { id: "flywheel-daily", name: "flywheel-daily", axis: "care", phase: "honey", description: "cron — daily drift, salted PRACTICE/HELD_OUT split", metric: "selftest 9/9 · salt=csoai-flywheel-v1", last_run_iso: "2026-07-30T03:00:00Z" },
  { id: "honey-pipe", name: "honey_pipeline", axis: "care", phase: "honey", description: "KB harvest → honey cache → cite-on-serve", metric: "83 verified entries · 87KB", last_run_iso: "2026-07-30T05:00:00Z" },
  { id: "production-ready", name: "production_ready", axis: "care", phase: "honey", description: "signed care_cost evidence pack for marketing", metric: "Ed25519 signature · care_score=0.7891", last_run_iso: "2026-07-30T12:00:00Z" },
];

const GW: string = ((import.meta as any).env && (import.meta as any).env.VITE_KNOWLEDGE_BASE) || "/api";
const LOCAL_GW: string = ((import.meta as any).env && (import.meta as any).env.VITE_LOCAL_GATEWAY) || GW;
const SS_INDUSTRIES = ["healthcare","health","hospital","clinical","triage","pharma","biotech","finance","fintech","banking","insurance","lending","credit","education","edtech","retail","ecommerce","legal","government","public sector","defense","energy","utilities","automotive","telecom","manufacturing","logistics","hr","recruiting","hiring","media","gaming","agriculture","transport","aviation","real estate","crypto","web3","marketing"];
function ssIndustry(q: string) { const s = (q || "").toLowerCase(); return SS_INDUSTRIES.find((w) => new RegExp("\\b" + w + "\\b").test(s)) || null; }
function ssRegion(q: string) {
  const s = " " + (q || "").toLowerCase() + " ";
  if (/\bus\b|\busa\b|\bamerica|\bcalifornia\b|\btexas\b|\bcolorado\b|\bnew york\b/.test(s)) return "the United States (NIST AI RMF + state law)";
  if (/\beu\b|\beurope|\bgerman|\bfrance\b|\bspain\b|\bitaly\b|\bireland\b|\bparis\b|\bberlin\b/.test(s)) return "the European Union (EU AI Act)";
  if (/\bchina\b|\bbeijing\b/.test(s)) return "China (TC260)";
  if (/\bsingapore\b/.test(s)) return "Singapore (Model AI Governance)";
  if (/\buk\b|\bbritain\b|\blondon\b/.test(s)) return "the United Kingdom (UK AI regulation)";
  return "a global footprint (ISO 42001)";
}
