import { useEffect, useState } from "react";
import { chargeSovereign } from "../lib/sovCharge";
import AISystemNotice from "../components/AISystemNotice";
const GW: string = ((import.meta as any).env && (import.meta as any).env.VITE_KNOWLEDGE_BASE) || "/api";
const FW = [{ name: "EU AI Act", href: "/eu-ai-act-checklist" }, { name: "NIST AI RMF", href: "/nist-vs-eu-ai-act" }, { name: "ISO 42001", href: "/iso-42001-vs-eu-ai-act" }, { name: "GDPR", href: "/eu-ai-act-vs-gdpr" }];
const EXAMPLES = ["a hospital in Texas", "a fintech in Singapore", "an HR recruiting tool", "Germany"];
const INDUSTRIES = ["healthcare","health","hospital","clinical","pharma","biotech","finance","fintech","banking","insurance","education","edtech","retail","ecommerce","legal","government","public sector","defense","energy","utilities","automotive","telecom","manufacturing","logistics","supply chain","hr","recruiting","hiring","media","gaming","agriculture","transport","aviation","real estate","crypto","web3","marketing"];
function detectIndustry(q: string) { const s = (q || "").toLowerCase(); return INDUSTRIES.find((w) => new RegExp("\\b" + w + "\\b").test(s)) || null; }
function jurisdiction(q: string) {
  const s = " " + (q || "").toLowerCase() + " ";
  // Word-boundary matches so substrings like "hospital" don't trigger "ital"->Italy.
  if (/\bus\b|\busa\b|\bu\.s\.|\bamerica|\bcalifornia\b|\btexas\b|\bcolorado\b|\bnew york\b|\bflorida\b|\bopenai\b|\banthropic\b/.test(s)) return { region: "United States", primary: "NIST AI RMF + state laws", href: "/colorado-ai-act" };
  if (/\beu\b|\beurope|\bgerman|\bfrance\b|\bfrench\b|\bspain\b|\bspanish\b|\bitaly\b|\bitalian\b|\bdublin\b|\bireland\b|\bnetherland|\bbrussels\b|\bparis\b|\bberlin\b|\bmadrid\b|\brome\b/.test(s)) return { region: "European Union", primary: "EU AI Act", href: "/eu-ai-act-checklist" };
  if (/\bchina\b|\bchinese\b|\bbeijing\b|\bshanghai\b|\bshenzhen\b/.test(s)) return { region: "China", primary: "TC260", href: "/china-ai-law" };
  if (/\bsingapore\b/.test(s)) return { region: "Singapore", primary: "Singapore AI governance", href: "/singapore-ai-governance" };
  if (/\buk\b|\bu\.k\.|\bbritain\b|\bbritish\b|\bengland\b|\blondon\b|\bscotland\b/.test(s)) return { region: "United Kingdom", primary: "UK AI regulation", href: "/uk-ai-regulation" };
  return { region: "Global", primary: "ISO 42001", href: "/iso-42001-vs-eu-ai-act" };
}
export default function GovGraph() {
  const [q, setQ] = useState(""); const [res, setRes] = useState<any>(null); const [kn, setKn] = useState<any>(null); const [gov, setGov] = useState<any>(null); const [read, setRead] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { document.title = "Governance Graph - the governed Google | CSOAI"; }, []);
  useEffect(() => { const d = new URLSearchParams(window.location.search).get("demo"); if (d) { const t = setTimeout(() => run(d), 500); return () => clearTimeout(t); } }, []);
  async function run(query?: string) {
    const term = (query !== undefined ? query : q).trim(); if (!term) return;
    setQ(term); setRes({ q: term, j: jurisdiction(term) }); setKn(null); setGov(null); setRead(""); setLoading(true); chargeSovereign(6);
    const ind = detectIndustry(term);
    const jobs: Promise<void>[] = [];
    jobs.push((async () => { try { const r = await fetch(GW + "/knowledge?q=" + encodeURIComponent(term)); if (r.ok) setKn(await r.json()); } catch (e) {} })());
    if (ind) jobs.push((async () => { try { const r = await fetch(GW + "/govern?q=" + encodeURIComponent(ind)); if (r.ok) { const d = await r.json(); if (d && d.matched) setGov(d); } } catch (e) {} })());
    jobs.push((async () => { try { const r = await fetch(GW + "/chat", { method: "POST", headers: { "content-type": "text/plain" }, body: JSON.stringify({ message: "In 2 sentences, what does the law require for: " + term + "? Focus on AI governance and the key obligations." }) }); if (r.ok) { const d = await r.json(); if (d && d.response && d.model !== "idle" && !/travell?er|companion|walks beside|i'?m sorry|can'?t help|on your journey|dear friend|kindred|as an ai language|remembering/i.test(String(d.response))) setRead(String(d.response)); } } catch (e) {} })());
    await Promise.all(jobs);
    setLoading(false);
  }
  return (
    <div className="min-h-screen bg-[#03110b] text-emerald-50">
      <section className="relative overflow-hidden border-b border-emerald-500/15">
        <div className="pointer-events-none absolute inset-0" style={{ background: "radial-gradient(800px 380px at 50% -10%, rgba(16,185,129,.20), transparent 60%)" }} />
        <div className="relative mx-auto max-w-3xl px-6 pt-16 pb-10 text-center">
          <p className="font-mono text-[11px] uppercase tracking-[3px] text-emerald-300/70">CSOAI OS - Governance Graph</p>
          <h1 className="mt-3 text-4xl sm:text-5xl font-black tracking-tight">The governed <span className="bg-gradient-to-r from-emerald-300 via-emerald-400 to-teal-300 bg-clip-text text-transparent">Google.</span></h1>
          <p className="mt-4 mx-auto max-w-xl text-lg text-emerald-100/80">A search box tells you what something <i>is</i>. This tells you what the <b className="text-emerald-200">law requires</b> - jurisdiction, frameworks, and a path to a signed verdict. Live world data meets governance.</p>
          <div className="mt-6 mx-auto max-w-xl text-left"><AISystemNotice route="/governance-graph" /></div>
          <div className="mt-7 flex gap-2">
            <input value={q} onChange={(e) => setQ(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") run(); }} placeholder="Ask about any company, place, or AI system..." className="flex-1 rounded-xl border border-emerald-500/30 bg-black/40 px-5 py-4 text-base text-emerald-50 placeholder-emerald-300/30 focus:border-emerald-400 focus:outline-none" />
            <button onClick={() => run()} className="rounded-xl bg-emerald-500 px-6 py-4 text-base font-bold text-[#03110b] hover:bg-emerald-400">{loading ? "..." : "Map it"}</button>
          </div>
          <div className="mt-3 flex flex-wrap justify-center gap-2">
            {EXAMPLES.map((e) => (<button key={e} onClick={() => run(e)} className="rounded-full border border-emerald-400/25 bg-emerald-500/5 px-3 py-1 text-xs text-emerald-200/80 hover:bg-emerald-500/15">{e}</button>))}
          </div>
        </div>
      </section>
      {res && (<section className="mx-auto max-w-3xl px-6 py-8 space-y-4">
        <div className="rounded-2xl border border-emerald-400/40 bg-gradient-to-br from-emerald-500/15 to-transparent p-6"><div className="text-xs uppercase tracking-wide text-emerald-300/70">For "{res.q}"</div><div className="mt-1 text-2xl font-black">Jurisdiction: {res.j.region}</div><p className="mt-1 text-sm text-emerald-100/80">Primary regime <a href={res.j.href} className="font-bold text-emerald-300 underline">{res.j.primary}</a> - comply once, the Council assistant crosswalks it across every framework below.</p></div>
        {loading && !read && (<div className="rounded-2xl border border-emerald-500/20 bg-[#05140d] p-6"><div className="flex items-center gap-2 text-sm text-emerald-300/80"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-400" style={{ boxShadow: "0 0 8px #34d399" }} />The Council assistant is reasoning over live world data…</div><div className="mt-3 space-y-2"><div className="h-3 w-3/4 animate-pulse rounded bg-white/5" /><div className="h-3 w-2/3 animate-pulse rounded bg-white/5" /><div className="h-3 w-1/2 animate-pulse rounded bg-white/5" /></div></div>)}
        {kn && kn.facts && (kn.facts.label || kn.facts.population) && (<div className="rounded-2xl border border-emerald-500/20 bg-[#05140d] p-6"><div className="flex items-baseline justify-between"><div className="text-xl font-bold">{kn.facts.label || res.q}</div><span className="font-mono text-[10px] uppercase tracking-wide text-emerald-300/40">live - wikidata</span></div>{kn.facts.desc && <div className="text-sm text-emerald-300/70">{kn.facts.desc}</div>}<div className="mt-4 grid gap-3 sm:grid-cols-3">{kn.facts.population ? <div className="rounded-xl bg-black/30 p-3"><div className="text-2xl font-black text-emerald-300">{Number(kn.facts.population).toLocaleString()}</div><div className="text-[11px] uppercase tracking-wide text-emerald-300/50">population</div></div> : null}{kn.facts.founded ? <div className="rounded-xl bg-black/30 p-3"><div className="text-2xl font-black text-emerald-300">{kn.facts.founded}</div><div className="text-[11px] uppercase tracking-wide text-emerald-300/50">founded</div></div> : null}{kn.facts.website ? <a href={kn.facts.website} className="rounded-xl bg-black/30 p-3 hover:bg-black/50"><div className="truncate text-sm font-bold text-emerald-300">Official site</div><div className="truncate text-[11px] text-emerald-300/50">{kn.facts.website}</div></a> : null}</div></div>)}
        {kn && Array.isArray(kn.results) && kn.results.length > 0 && (<div className="rounded-2xl border border-emerald-500/20 bg-[#05140d] p-6"><div className="text-lg font-bold">Knowledge</div><div className="mt-3 space-y-2">{kn.results.slice(0, 4).map((it: any, i: number) => (<a key={i} href={it.url} target="_blank" rel="noopener" className="flex gap-3 rounded-xl border border-emerald-500/10 p-2.5 hover:bg-white/5">{it.thumb ? <img src={it.thumb} alt="" className="h-11 w-11 rounded object-cover" /> : null}<div className="min-w-0"><div className="text-sm font-semibold text-emerald-100">{it.title}</div><div className="truncate text-xs text-emerald-300/60">{it.excerpt || it.desc}</div></div></a>))}</div></div>)}
        {read && (<div className="rounded-2xl border border-emerald-400/30 bg-[#05140d] p-6"><div className="flex items-baseline justify-between"><div className="text-lg font-bold">The Council assistant's read</div><span className="font-mono text-[10px] uppercase tracking-wide text-emerald-300/40">live reasoning</span></div><p className="mt-2 text-sm leading-relaxed text-emerald-100/85">{read}</p></div>)}
        <div className="rounded-2xl border border-emerald-500/20 bg-[#05140d] p-6"><div className="flex items-baseline justify-between"><div className="text-lg font-bold">Frameworks that apply{gov ? " to " + gov.industry : ""}</div>{gov ? <span className="font-mono text-[10px] uppercase tracking-wide text-emerald-300/40">live - Council gateway</span> : null}</div>
          {gov && Array.isArray(gov.frameworks) ? (<div className="mt-3 space-y-2">{gov.frameworks.map((f: any, i: number) => (<div key={i} className="rounded-xl border border-emerald-500/15 bg-black/25 p-3"><div className="text-sm font-bold text-emerald-200">{f.name}</div><div className="text-xs text-emerald-100/70">{f.why}</div></div>))}{gov.bridges && gov.bridges.length ? (<div className="pt-1 text-xs text-emerald-300/70">Legacy bridge: <span className="font-semibold text-emerald-200">{gov.bridges.join(", ")}</span> - MEOK signs every governed action.</div>) : null}</div>) : (<div className="mt-3 flex flex-wrap gap-2">{FW.map((f) => (<a key={f.name} href={f.href} className="rounded-full border border-emerald-400/30 bg-emerald-500/10 px-4 py-1.5 text-sm font-semibold text-emerald-100 hover:bg-emerald-500/20">{f.name}</a>))}</div>)}
        </div>
        <div className="rounded-2xl border border-emerald-400/30 bg-gradient-to-br from-emerald-500/15 to-transparent p-6 text-center"><div className="text-xl font-bold">Now the Council assistant does the work</div><p className="mt-1 text-sm text-emerald-100/70">Simulate it, get the collected obligations, run the signed council verdict, and prove it - all carrying "{res.q}" with you.</p><div className="mt-4 flex flex-wrap justify-center gap-2"><a href={"/gspc-arena?demo=" + encodeURIComponent(res.q)} className="rounded-xl bg-emerald-500 px-5 py-2.5 text-sm font-bold text-[#03110b] hover:bg-emerald-400">▶ Simulate in Council Space</a><a href={"/try?demo=" + encodeURIComponent(res.q)} className="rounded-xl border border-emerald-400/40 px-5 py-2.5 text-sm font-semibold text-emerald-100 hover:bg-white/5">Ask the Council</a><a href="/hive" className="rounded-xl border border-emerald-400/40 px-5 py-2.5 text-sm font-semibold text-emerald-100 hover:bg-white/5">Open the Hive</a><a href="/system-card" className="rounded-xl border border-amber-400/40 bg-amber-400/10 px-5 py-2.5 text-sm font-bold text-amber-100 hover:bg-amber-400/20">Get a signed proof</a></div></div>
      </section>)}
      {!res && (<section className="mx-auto max-w-4xl px-6 py-12"><div className="grid gap-4 sm:grid-cols-3">{[["Breadth", "Live world data - Wikipedia, Wikidata, and Google sources behind one query."], ["Law", "Jurisdiction + every applicable framework, mapped automatically."], ["Proof", "A path to a real Ed25519-signed council verdict - not just an answer."]].map((c) => (<div key={c[0]} className="rounded-2xl border border-emerald-500/15 bg-[#05140d] p-5"><div className="text-lg font-bold text-emerald-200">{c[0]}</div><p className="mt-1 text-sm text-emerald-100/70">{c[1]}</p></div>))}</div><div className="mt-6 flex flex-wrap justify-center gap-2"><a href="/globe3d.html" className="rounded-xl border border-amber-400/30 bg-amber-400/10 px-4 py-2 text-sm font-semibold text-amber-100 hover:bg-amber-400/20">🟡 See the AI economy on the globe</a><a href="/network" className="rounded-xl border border-cyan-400/30 bg-cyan-500/10 px-4 py-2 text-sm font-semibold text-cyan-100 hover:bg-cyan-500/20">🩵 The Council network</a><a href="/watchdog-map" className="rounded-xl border border-emerald-400/30 px-4 py-2 text-sm font-semibold text-emerald-100 hover:bg-white/5">◎ The live Watchdog</a></div></section>)}
      <section className="mx-auto max-w-3xl px-6 pb-16"><p className="text-center text-xs text-emerald-300/50">Live world knowledge via the CSOAI Council gateway. Your data stays yours. MIT-licensed core.</p></section>
    </div>
  );
}
