import { useEffect, useState } from "react";

// CSOAI AI Policy Generator — HUNT_24 Tier-2 #13 ("highest-ROI AI use case in compliance").
// Generates a tailored AI governance policy document from a few inputs, mapped to the
// frameworks the org certifies against. Fully client-side; downloads as Markdown.

const FRAMEWORKS = ["EU AI Act", "NIST AI RMF", "ISO 42001", "SOC 2", "GDPR", "NYC LL144"];
const TIERS = ["High", "Limited", "Minimal"] as const;

const FRAMEWORK_CLAUSES: Record<string, string> = {
  "EU AI Act": "Maintain a risk-management system (Art. 9), data governance records (Art. 10), event logging (Art. 12) and transparency disclosures (Art. 50) for all in-scope systems.",
  "NIST AI RMF": "Apply the GOVERN, MAP, MEASURE and MANAGE functions; document context, measure trustworthiness characteristics, and manage identified risks.",
  "ISO 42001": "Operate an AI Management System with impact assessments (8.3) and monitoring, measurement, analysis and evaluation (9.1).",
  "SOC 2": "Maintain Trust Services Criteria controls; collect continuous evidence for security, availability and confidentiality.",
  "GDPR": "Establish a lawful basis, honor data-subject rights, and complete DPIAs for high-risk processing.",
  "NYC LL144": "Conduct an independent bias audit of automated employment decision tools within the prior 12 months and publish a summary.",
};

export default function PolicyGenerator() {
  const saved = (() => { try { return JSON.parse(localStorage.getItem("csoai_policy") || "{}"); } catch { return {}; } })();
  const [org, setOrg] = useState<string>(saved.org ?? "Acme AI");
  const [tier, setTier] = useState<(typeof TIERS)[number]>(saved.tier ?? "High");
  const [useCase, setUseCase] = useState<string>(saved.useCase ?? "customer-facing decision support");
  const [picked, setPicked] = useState<string[]>(saved.picked ?? ["EU AI Act", "NIST AI RMF", "ISO 42001"]);
  const [out, setOut] = useState("");
  useEffect(() => { try { localStorage.setItem("csoai_policy", JSON.stringify({ org, tier, useCase, picked })); } catch {} }, [org, tier, useCase, picked]);

  function toggle(f: string) {
    setPicked((p) => (p.includes(f) ? p.filter((x) => x !== f) : [...p, f]));
  }

  function generate() {
    const date = new Date().toISOString().slice(0, 10);
    const md = `# ${org} — AI Governance Policy

**Version:** 1.0  **Effective:** ${date}  **Owner:** Chief AI Governance Officer
**Generated with CSOAI**

## 1. Purpose
This policy establishes how ${org} governs the design, development, deployment and monitoring of artificial-intelligence systems — specifically ${useCase} — to ensure they are lawful, safe, transparent and accountable.

## 2. Scope
Applies to all employees, contractors and vendors involved with AI systems classified as **${tier}-risk**. Systems are inventoried in the CSOAI Model Registry with a documented model card.

## 3. Roles & responsibilities
- **AI Governance Officer** — owns this policy, approves high-risk deployments.
- **Model owners** — maintain model cards, evidence and fairness audits.
- **Human reviewers** — exercise meaningful oversight before consequential decisions.

## 4. Risk management
Every system receives a risk classification before deployment. ${tier}-risk systems require: documented impact assessment, pre-deployment evaluation, continuous monitoring, and a human-in-the-loop control. Findings are tracked to remediation.

## 5. Data governance
Training, validation and test data are documented for relevance, representativeness and provenance. Protected attributes are excluded from features and used only for fairness testing. Personal data is processed per applicable privacy law.

## 6. Transparency & human oversight
Users are informed when they interact with an AI system. Consequential outputs are explainable and subject to human review and appeal.

## 7. Monitoring & assurance
Performance, drift and fairness metrics are monitored continuously. Compliance evidence is collected automatically through the CSOAI Evidence Hub and exported in OSCAL where required.

## 8. Incident response
AI incidents (harmful output, bias breach, security event) are logged, triaged and — where regulation requires — reported within mandated timeframes. Webhooks notify Security and Legal in real time.

## 9. Framework mappings
${picked.map((f) => `### ${f}\n${FRAMEWORK_CLAUSES[f] || "Controls mapped in the CSOAI Framework Catalog."}`).join("\n\n")}

## 10. Review
This policy is reviewed at least annually and upon any material regulatory change tracked by CSOAI.

---
*Generated by CSOAI AI Policy Generator. Review with qualified counsel before adoption.*
`;
    setOut(md);
  }

  function download() {
    const blob = new Blob([out], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = org.toLowerCase().replace(/\s+/g, "-") + "-ai-policy.md";
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="min-h-screen bg-white">
      <section className="bg-gradient-to-br from-emerald-900 via-teal-900 to-green-900 text-white py-20">
        <div className="max-w-5xl mx-auto px-6">
          <p className="text-emerald-300 font-semibold tracking-wide uppercase text-sm">Policy &amp; training</p>
          <h1 className="mt-3 text-4xl sm:text-4xl font-black tracking-tight">AI Policy Generator</h1>
          <p className="mt-5 text-lg text-emerald-50 max-w-2xl">Draft a board-ready AI governance policy in seconds — tailored to your risk tier and mapped to the frameworks you certify against.</p>
        </div>
      </section>

      <section className="max-w-5xl mx-auto px-6 py-12 grid gap-8 lg:grid-cols-2">
        <div className="rounded-2xl border border-gray-200 bg-white p-6">
          <h2 className="text-xl font-bold text-gray-900">Inputs</h2>
          <label className="mt-4 block text-sm font-medium text-gray-700">Organization
            <input value={org} onChange={(e) => setOrg(e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-emerald-400 focus:outline-none" />
          </label>
          <label className="mt-4 block text-sm font-medium text-gray-700">Primary use case
            <input value={useCase} onChange={(e) => setUseCase(e.target.value)} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:border-emerald-400 focus:outline-none" />
          </label>
          <div className="mt-4 text-sm font-medium text-gray-700">Risk tier</div>
          <div className="mt-1 flex gap-2">
            {TIERS.map((t) => (
              <button key={t} onClick={() => setTier(t)} className={`rounded-lg px-3 py-1.5 text-sm font-medium ${tier === t ? "bg-emerald-600 text-white" : "border border-gray-200 text-gray-600 hover:bg-gray-50"}`}>{t}</button>
            ))}
          </div>
          <div className="mt-4 text-sm font-medium text-gray-700">Frameworks</div>
          <div className="mt-1 flex flex-wrap gap-2">
            {FRAMEWORKS.map((f) => (
              <button key={f} onClick={() => toggle(f)} className={`rounded-full px-3 py-1 text-xs font-medium ${picked.includes(f) ? "bg-emerald-600 text-white" : "border border-gray-200 text-gray-600 hover:bg-gray-50"}`}>{f}</button>
            ))}
          </div>
          <button onClick={generate} className="mt-6 w-full rounded-lg bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white hover:bg-emerald-500">Generate policy</button>
        </div>

        <div className="rounded-2xl border border-gray-200 bg-white p-6">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-bold text-gray-900">Policy</h2>
            {out && <button onClick={download} className="rounded-lg bg-gray-900 px-3 py-1.5 text-sm font-semibold text-white hover:bg-gray-800">↓ .md</button>}
          </div>
          {out ? (
            <pre className="mt-4 h-[28rem] overflow-auto whitespace-pre-wrap rounded-lg bg-gray-50 p-4 text-xs text-gray-700">{out}</pre>
          ) : (
            <p className="mt-4 text-sm text-gray-500">Set your inputs and click <strong>Generate policy</strong> — a complete, framework-mapped document appears here, ready to download.</p>
          )}
        </div>
      </section>
    </div>
  );
}
