// Generated by scripts/harness-x/render.mjs — do not hand-edit.
// Minimal MCP-over-HTTP client for the Council of AI door. Zero dependencies.
// Optional: pass { layer0 } (an @csoai/layer0 Layer0 instance) to run each call through
// Layer0.governed() — gate, run, attest. Without it, the call goes straight to the door.

export const DOOR = "https://councilof.ai/mcp";
export const DOCTRINE_SHA256 = "845fc1d200eb9e867fc8d682750409d6725084bac632726187759f8fefdfbe0a";
export const FREE_TOOLS = ["board_totals","get_axis","verify_card","list_cards","get_root","get_card","verify_inclusion","x402_trust","mcp_trust","measurement_index","verify_capsule","server_evidence","evidence_bundle_preview","route"];
export const PAID_TOOLS = ["commission_card","art50_marking_evidence","rwa_evidence","receipts_batch","evidence_bundle"];
export const TOOL_DESCRIPTION = "Live Council of AI GSPC board totals via the board_totals MCP tool. Quote public_count exactly as printed; never add or re-derive a count. UNREACHABLE means the door could not be read and no number is returned. Measurement only: a card is evidence, never a grade, mark or endorsement. Verification is free.";

function parseRpc(text) {
  const t = text.trim();
  if (t.startsWith("{")) return JSON.parse(t);
  const data = t.split("\n").filter((l) => l.startsWith("data:"));
  if (!data.length) throw new Error("no JSON-RPC message in response");
  return JSON.parse(data[data.length - 1].slice(5));
}

export async function callGspc(name, args = {}, { door = DOOR, layer0, fetchImpl = globalThis.fetch } = {}) {
  const run = async () => {
    let res;
    try {
      res = await fetchImpl(door, {
        method: "POST",
        headers: { "content-type": "application/json", accept: "application/json, text/event-stream" },
        body: JSON.stringify({ jsonrpc: "2.0", id: 1, method: "tools/call", params: { name, arguments: args } }),
      });
    } catch (e) {
      return { state: "UNREACHABLE", door, tool: name, error: String((e && e.name) || e), doctrine_sha256: DOCTRINE_SHA256 };
    }
    if (!res.ok) return { state: "UNREACHABLE", door, tool: name, http_status: res.status, doctrine_sha256: DOCTRINE_SHA256 };
    let msg;
    try { msg = parseRpc(await res.text()); } catch (e) {
      return { state: "UNREACHABLE", door, tool: name, error: "unparseable response", doctrine_sha256: DOCTRINE_SHA256 };
    }
    if (msg.error) return { state: "ERROR", door, tool: name, error: msg.error, doctrine_sha256: DOCTRINE_SHA256 };
    return { state: "LIVE", door, tool: name, result: msg.result, doctrine_sha256: DOCTRINE_SHA256 };
  };
  if (!layer0) return run();
  const { result, decision, attestation } = await layer0.governed(`gspc.${name}`, args, run);
  return { ...result, layer0: { decision, attestation } };
}
