// Generated by scripts/harness-x/render.mjs — do not hand-edit.
export declare const DOOR: string;
export declare const DOCTRINE_SHA256: string;
export declare const FREE_TOOLS: string[];
export declare const PAID_TOOLS: string[];
export declare const TOOL_DESCRIPTION: string;
export interface GspcCallOptions { door?: string; layer0?: { governed: (...a: any[]) => Promise<any> }; fetchImpl?: typeof fetch; }
export declare function callGspc(name: string, args?: Record<string, unknown>, opts?: GspcCallOptions): Promise<Record<string, unknown>>;
export declare function makeGspcBoardTotalsTool(opts?: GspcCallOptions): any;
export declare const gspcBoardTotalsTool: any;
