// Generated by scripts/harness-x/render.mjs — do not hand-edit.
import { createTool } from "@mastra/core/tools";
import { z } from "zod";
import { callGspc, TOOL_DESCRIPTION } from "./gspc-client.js";

export * from "./gspc-client.js";

/** Mastra tool: live GSPC board totals. */
export function makeGspcBoardTotalsTool(opts = {}) {
  return createTool({
    id: "gspc-board-totals",
    description: TOOL_DESCRIPTION,
    inputSchema: z.object({}),
    execute: async () => callGspc("board_totals", {}, opts),
  });
}

export const gspcBoardTotalsTool = makeGspcBoardTotalsTool();
