#!/usr/bin/env python3
"""Regenerate capsule-vectors.json from the REFERENCE implementation (the capsule lane's
venturi_capsule.py: canon, capsule_id, merkle_root [v0.2 RFC 6962], merkle_root_v01).
Synthetic capsules only — no census data. The TypeScript readers must reproduce every id and root.

    python3 make_fixture.py /path/to/capsule-lane > capsule-vectors.json
"""
import json, sys
sys.path.insert(0, sys.argv[1])
import venturi_capsule as v

AUTH = "NONE: measurement only; this capsule grants and records no execution authority"


def cap(schema, i, extra):
    c = {"schema": schema, "kind": "measurement.contract_parity", "subject_id": f"https://svc{i}.example/mcp",
         "claim": {"dimension": ["TOOLS", "VERSION", "PROTOCOL"][i % 3], "statement": "fixture"},
         "declared": {"value": f"déclaré ✓ {i}"}, "observed": {"value": i, **extra},
         "differential": {}, "sources": {"record_sha256": "ab" * 32}, "measurement_state": ["CONSISTENT", "INCONSISTENT", "UNCHECKABLE"][i % 3],
         "authority_state": AUTH, "effect_reference": None, "observed_at": "2026-09-26T00:00:00Z", "correction_pointer": None,
         "limitations": ["fixture"]}
    c["capsule_id"] = v.capsule_id(c)
    return c


out = {"note": "generated by make_fixture.py from the reference implementation; synthetic capsules only"}
v02 = [cap("csoai.measurement-capsule/0.2", i, {"n": i * 7}) for i in range(11)]
v01 = [cap("csoai.venturi-capsule/0.1", i, {"accuracy": [0.7812, 1.0, 1e-05, 1.2345678901234567e+19, -0.5][i % 5]}) for i in range(7)]
for name, caps, root_fn in (("v02", v02, v.merkle_root), ("v01", v01, v.merkle_root_v01)):
    ids = sorted(c["capsule_id"] for c in caps)
    out[name] = {"lines": [v.canon(c).decode() for c in caps], "ids": ids, "root": root_fn(ids),
                 "roots_by_size": {str(n): root_fn(ids[:n]) for n in range(1, len(ids) + 1)}}
json.dump(out, sys.stdout, indent=1, ensure_ascii=False)
print()


def bundle(lane_scripts, dest):
    """A synthetic v0.2 layout, built by the reference write_batch/index and then by
    scripts/measurement_capsule_layout.py, bundled as {served path: text} for the reader tests."""
    import argparse, pathlib, subprocess, tempfile
    tmp = pathlib.Path(tempfile.mkdtemp())
    a2a = []
    for i in (1, 4):
        c = {k: val for k, val in cap("csoai.measurement-capsule/0.2", i, {}).items() if k != "capsule_id"}
        c.update(kind="measurement.a2a_card_signature", subject_id=f"https://svc{i}.example/.well-known/agent-card.json",
                 claim={"statement": "the agent card is signed by the key it references"}, measurement_state=["VERIFIED", "FAILED"][i % 2])
        c["capsule_id"] = v.capsule_id(c)
        a2a.append(c)
    v.write_batch(tmp / "b-cp", "contract_parity", "measurement.contract_parity", v02, {"what_this_is": "fixture"})
    v.write_batch(tmp / "b-a2a", "a2a_card", "measurement.a2a_card_signature", a2a, {"what_this_is": "fixture"})
    v.index(argparse.Namespace(file=str(tmp / "index.json"), batches=[str(tmp / "b-cp"), str(tmp / "b-a2a")], pending=None))
    subprocess.run([sys.executable, lane_scripts + "/measurement_capsule_layout.py", "--index", str(tmp / "index.json"),
                    "--out", str(tmp / "site"), "--no-capsules"], check=True, capture_output=True)
    files = {"/measurement-capsules/" + str(p.relative_to(tmp / "site")): p.read_text()
             for p in sorted((tmp / "site").rglob("*")) if p.is_file()}
    pathlib.Path(dest).write_text(json.dumps({"note": "synthetic v0.2 layout (make_fixture.py bundle): reference write_batch + index, then scripts/measurement_capsule_layout.py. Served-path -> bytes.",
                                              "a2a_lines": [v.canon(c).decode() for c in a2a], "files": files}, ensure_ascii=False) + "\n")


if len(sys.argv) > 3:
    import contextlib
    with contextlib.redirect_stdout(sys.stderr):  # the reference index() prints a summary
        bundle(sys.argv[2], sys.argv[3])
