/** GENERATED by scripts/gspc_bank_distinct.py from the published bank files (pinned revision + sha256).
 * Do not edit by hand — re-run the producer. Unsigned: it changes no signed byte. */
export const BANK_DISTINCT = {
  "schema": "csoai.gspc-bank-distinct/0.1",
  "producer": "scripts/gspc_bank_distinct.py",
  "method": "distinct inputs = the number of distinct sha256 digests of the normalised prompt over every graded row of the published bank file (canary rows excluded). The prompt is the field the model is sent. Row ids and labels play no part: two rows with the same prompt are one input, however they are named.",
  "normalisation": "Unicode NFC; every run of whitespace becomes one space; leading and trailing whitespace removed; case and punctuation kept",
  "signed": false,
  "axes": {
    "jail": {
      "dataset": "csoai/gspc-jail-goldbank",
      "revision": "df16e7855ff04b90fea19aa5f11f4b86cb466a47",
      "file": "samples.jsonl",
      "file_sha256": "0b45b620f2277c364275420f812e9415698e3b8bf0b105a7bbb4c2b2627d0f4a",
      "prompt_field": "input",
      "rows": 71,
      "distinct_inputs": 27,
      "repeated_inputs": 16,
      "rows_repeating_an_input": 44,
      "groups": [
        {
          "prompt_sha256": "2c475d0ba8874edcd6400dab4a0adb9dc3a1a808bf3ad288c2e8cd4016c0aa55",
          "rows": 10,
          "ids": [
            "ben-rb-b01",
            "ben-rb-b02",
            "ben-rb-b03",
            "ben-rb-b04",
            "ben-rb-b05",
            "ben-rb-b06",
            "ben-rb-b07",
            "ben-rb-b08",
            "ben-rb-b09",
            "ben-rb-b10"
          ]
        },
        {
          "prompt_sha256": "403fd8dc6244829d2c00d5eeaf9a9be6725d0f142823ea8b770d75fc3fdbdea6",
          "rows": 6,
          "ids": [
            "esc-rb-h01-w1_direct",
            "esc-rb-h02-w1_direct",
            "esc-rb-h03-w1_direct",
            "esc-rb-h04-w1_direct",
            "esc-rb-h05-w1_direct",
            "esc-rb-h06-w1_direct"
          ]
        },
        {
          "prompt_sha256": "8f44c714ec7b6c6243653ca5106ff2f16fe88fdb32b19193ce9ae0477360e88d",
          "rows": 6,
          "ids": [
            "esc-rb-h01-w2_roleplay",
            "esc-rb-h02-w2_roleplay",
            "esc-rb-h03-w2_roleplay",
            "esc-rb-h04-w2_roleplay",
            "esc-rb-h05-w2_roleplay",
            "esc-rb-h06-w2_roleplay"
          ]
        },
        {
          "prompt_sha256": "5779ae008f0676894c5c6c07b16559d159994ca1d1debb71a8ece37a80521b2d",
          "rows": 6,
          "ids": [
            "esc-rb-h01-w3_authority",
            "esc-rb-h02-w3_authority",
            "esc-rb-h03-w3_authority",
            "esc-rb-h04-w3_authority",
            "esc-rb-h05-w3_authority",
            "esc-rb-h06-w3_authority"
          ]
        },
        {
          "prompt_sha256": "b71f64893fbccdb04d8ee520ed563e34dcbd577c04b560f5cc1df3f0e02446eb",
          "rows": 6,
          "ids": [
            "esc-rb-h01-w4_escalation",
            "esc-rb-h02-w4_escalation",
            "esc-rb-h03-w4_escalation",
            "esc-rb-h04-w4_escalation",
            "esc-rb-h05-w4_escalation",
            "esc-rb-h06-w4_escalation"
          ]
        },
        {
          "prompt_sha256": "0109fe65203f923dc4a2df1679c1f0c9530c0157b4e8b95d51c3ce38e36d81f8",
          "rows": 6,
          "ids": [
            "esc-rb-h01-w5_encoded",
            "esc-rb-h02-w5_encoded",
            "esc-rb-h03-w5_encoded",
            "esc-rb-h04-w5_encoded",
            "esc-rb-h05-w5_encoded",
            "esc-rb-h06-w5_encoded"
          ]
        },
        {
          "prompt_sha256": "97d74e3d1ad592ab9fd65f06ce987a198905d37b99e11e128b2584a5238a6d12",
          "rows": 2,
          "ids": [
            "ben-pad-10",
            "ben-pad-20"
          ]
        },
        {
          "prompt_sha256": "7028f8d730b31c439cc4722a1d7edd22c309b7efaa049416fe2e217a7d7a347d",
          "rows": 2,
          "ids": [
            "ben-pad-11",
            "ben-pad-21"
          ]
        },
        {
          "prompt_sha256": "baadef012e51d2bdb8278ad05da3d250f01dc50bbd20981de477a55955c6e3d8",
          "rows": 2,
          "ids": [
            "ben-pad-12",
            "ben-pad-22"
          ]
        },
        {
          "prompt_sha256": "c4ccfc46936177cb6e630078c23f2fb79013b18ef2b16bb56b41f58c0a61ec95",
          "rows": 2,
          "ids": [
            "ben-pad-13",
            "ben-pad-23"
          ]
        },
        {
          "prompt_sha256": "08e06156b42b66f5db9bdd7abf514ec81dfd78648414d7a99fbea9baa2f1c356",
          "rows": 2,
          "ids": [
            "ben-pad-14",
            "ben-pad-24"
          ]
        },
        {
          "prompt_sha256": "924c3908556d4fd8a221389957e0d4c5a119417e5bc631a0a197541bce4458db",
          "rows": 2,
          "ids": [
            "ben-pad-15",
            "ben-pad-25"
          ]
        },
        {
          "prompt_sha256": "cdd9f52a3936a0e7322869de755196c23c03d956eeef99539c2e457d179258c9",
          "rows": 2,
          "ids": [
            "ben-pad-16",
            "ben-pad-26"
          ]
        },
        {
          "prompt_sha256": "42e879f2c8aa881de7cb51247fd9d76976dd0325a27e4bbb96a78cec4312cf3c",
          "rows": 2,
          "ids": [
            "ben-pad-17",
            "ben-pad-27"
          ]
        },
        {
          "prompt_sha256": "43e237086bf4cbcd37ef50ad0f82c3a32e812e9ce9b509a1180c2ba19ac1bd2a",
          "rows": 2,
          "ids": [
            "ben-pad-18",
            "ben-pad-28"
          ]
        },
        {
          "prompt_sha256": "32fa32c2d7bdbc4c71ba7db11d51b3e18cea76976d5eafce4b532edf983a6d99",
          "rows": 2,
          "ids": [
            "ben-pad-19",
            "ben-pad-29"
          ]
        }
      ]
    },
    "swarm": {
      "dataset": "csoai/gspc-swarm",
      "revision": "32cfaa0e2e7de4a62eee85ab79aa72dd5df01e4a",
      "file": "samples.jsonl",
      "file_sha256": "2d5a791f971f98a83fd34b38a12cd222386a076fbf0dc46a4c8ebad2839dd26f",
      "prompt_field": "input",
      "rows": 37,
      "distinct_inputs": 37,
      "repeated_inputs": 0,
      "rows_repeating_an_input": 0,
      "groups": []
    }
  }
} as const;
