// Private module — board honesty (2026-09-28): distinct_items, the minimum detectable effect (MDE)
// of the board's own separation test, the fleet sentence counted from the rows, and the
// owner-gated UNDERPOWERED state (HELD, default OFF).
//
// WHY. A TIE says the fixed test (exact McNemar, leader vs best base, p<0.05) did not separate two
// models. It does not say how large a difference the test could have seen. On a 32-item bank the
// answer can be "none it could reliably see": publishing the MDE beside every TIE is the honest
// reading of a small n, and hiding it is not.
//
// Nothing here is typed. distinct_items, the discordance rate and the MDE are read from
// _gspc_rows_power.ts, which scripts/gspc_separation_from_rows.py --power GENERATES from the
// published per-item rows (hash-bound, the same rows the separation test reads). Where the served
// bank has no published paired rows (jail; swarm, whose published rows are a retired bank) the
// item count is the axis's own n, labelled as such, and the MDE is UNMEASURED with its reason.
import { ROWS_POWER } from "./_gspc_rows_power";
import { ROWS_SEPARATION } from "./_gspc_rows_separation";

// ── OWNER-GATED: the public state name UNDERPOWERED ─────────────────────────────────────────────
// HELD 2026-09-28. A new public state name needs the owner's ruling (NEXT-LEVEL-PLAN-2026-09-28 #5,
// owner decision 6). Until then `enabled` stays false and the served payload carries no such word.
// When enabled, a TIE whose MDE is NOT_REACHABLE or UNDEFINED (no difference up to the observed
// discordance reaches 80% power) is published as UNDERPOWERED instead of TIE; the test's own verdict
// is kept beside it (separation_test_verdict). `mde_threshold` is an optional owner number (as a
// proportion, e.g. 0.10 for ten accuracy points): when set, a TIE whose MDE exceeds it is also
// UNDERPOWERED. null means only the threshold-free rule applies. Never invent the threshold.
export interface UnderpoweredFlag {
  enabled: boolean;
  mde_threshold: number | null;
}
export const UNDERPOWERED_STATE: UnderpoweredFlag & { held: string } = {
  enabled: false,
  mde_threshold: null,
  held: "HELD 2026-09-28: UNDERPOWERED is a new public state name and waits for the owner's ruling.",
};

type PowerAxisEntry = {
  file: string;
  sha256: string;
  leader: string;
  next_best: string;
  mcnemar_p: number | null;
  verdict: string;
  distinct_items: number;
  paired_items: number;
  discordant_items: number;
  discordance_rate: number;
  mde: number | null;
  mde_state: "MEASURED" | "NOT_REACHABLE" | "UNDEFINED";
};
export const POWER_AXES = ROWS_POWER.axes as unknown as Record<string, PowerAxisEntry>;
const SEP_AXES = ROWS_SEPARATION.axes as unknown as Record<string, { untested_reason_code?: string }>;

export const MDE_STATES = ["MEASURED", "NOT_REACHABLE", "UNDEFINED", "UNMEASURED"] as const;
export type MdeState = (typeof MDE_STATES)[number];

export interface MdeBlock {
  value: number | null;
  state: MdeState;
  reason_code?: "NO_PAIRED_ROWS" | "NO_PAIRED_ROWS_FOR_SERVED_BANK";
  reason?: string;
  unit: string;
  alpha: number;
  power: number;
  paired_items?: number;
  discordance_rate?: number;
  test: string;
  source: string;
}

type Axisish = {
  axis: string;
  kind: string;
  n: number;
  separation?: string;
  per_model?: Record<string, unknown>;
  family?: string;
};

const MDE_COMMON = {
  unit: "accuracy difference (proportion), leader minus the best base model",
  alpha: ROWS_POWER.alpha,
  power: ROWS_POWER.power,
  test: "exact two-sided McNemar on the discordant items, leader vs the best base model (the board's separation test, rule fixed 2026-08-13)",
};
const POWER_SOURCE =
  `functions/api/_gspc_rows_power.ts, generated by ${ROWS_POWER.producer} from ${ROWS_POWER.dataset} ` +
  `(revision ${ROWS_POWER.dataset_revision}, peritem_sha256 ${ROWS_POWER.peritem_sha256.slice(0, 16)}…)`;

/** The rows describe the SERVED bank unless the separation producer says they are a retired one. */
const rowsServeTheBank = (axis: string): boolean =>
  !!POWER_AXES[axis] && SEP_AXES[axis]?.untested_reason_code !== "ROWS_ARE_A_RETIRED_BANK";

export type PowerFields = {
  distinct_items: number;
  distinct_items_source: string;
  mde: MdeBlock;
};

/** distinct_items + MDE for one model-comparison axis; undefined for every other kind. */
export function powerFields(a: Axisish): PowerFields | undefined {
  if (a.kind !== "model-comparison") return undefined;
  const p = POWER_AXES[a.axis];
  if (p && rowsServeTheBank(a.axis)) {
    return {
      distinct_items: p.distinct_items,
      distinct_items_source: `distinct item ids in the published per-item rows (${p.file})`,
      mde: {
        value: p.mde,
        state: p.mde_state,
        ...(p.mde_state === "NOT_REACHABLE"
          ? { reason: `No difference up to the observed discordance (${p.discordant_items} of ${p.paired_items} paired items) reaches ${ROWS_POWER.power * 100}% power with this test.` }
          : {}),
        ...(p.mde_state === "UNDEFINED" ? { reason: "No paired item is discordant, so the test has nothing to count." } : {}),
        ...MDE_COMMON,
        paired_items: p.paired_items,
        discordance_rate: p.discordance_rate,
        source: POWER_SOURCE,
      },
    };
  }
  // No published paired rows for the served bank: the item count is the axis's own n, said so.
  const retired = p
    ? ` The only published per-item rows for this axis are a retired bank (${p.distinct_items} distinct items, ${p.file}); on those rows the MDE is ${p.mde_state}.`
    : "";
  return {
    distinct_items: a.n,
    distinct_items_source: "the axis's own n (the served bank's item count); its paired per-item rows are not published",
    mde: {
      value: null,
      state: "UNMEASURED",
      reason_code: p ? "NO_PAIRED_ROWS_FOR_SERVED_BANK" : "NO_PAIRED_ROWS",
      reason: "The MDE needs the discordance rate between two models, which needs paired per-item rows for the served bank." + retired,
      ...MDE_COMMON,
      source: POWER_SOURCE,
    },
  };
}

export const withPower = <T extends Axisish>(a: T): T | (T & PowerFields) => {
  const f = powerFields(a);
  return f ? { ...a, ...f } : a;
};

/** Pure: would this axis read UNDERPOWERED under `flag`? Only a TIE can; UNTESTED keeps its own reason. */
export function isUnderpowered(a: Axisish & { mde?: MdeBlock }, flag: UnderpoweredFlag): boolean {
  if (!flag.enabled || a.kind !== "model-comparison" || a.separation !== "TIE" || !a.mde) return false;
  if (a.mde.state === "NOT_REACHABLE" || a.mde.state === "UNDEFINED") return true;
  return (
    a.mde.state === "MEASURED" &&
    typeof flag.mde_threshold === "number" &&
    typeof a.mde.value === "number" &&
    a.mde.value > flag.mde_threshold
  );
}

export function applyUnderpowered<T extends Axisish & { mde?: MdeBlock }>(a: T, flag: UnderpoweredFlag = UNDERPOWERED_STATE): T {
  if (!isUnderpowered(a, flag)) return a;
  const why =
    a.mde?.state === "MEASURED"
      ? `The test's MDE here is ${a.mde.value} (accuracy difference at ${ROWS_POWER.power * 100}% power), above the owner threshold ${flag.mde_threshold}.`
      : `The test could not reach ${ROWS_POWER.power * 100}% power at any difference on this bank (MDE ${a.mde?.state}).`;
  return {
    ...a,
    separation: "UNDERPOWERED",
    separation_test_verdict: a.separation,
    separation_underpowered_reason:
      `${why} A TIE here would read as "no difference"; the bank is too small to say that. Not a tie, not a win.`,
  } as T;
}

/**
 * measured_on.model, derived — replaces the typed "19-model fleet (8 tuned council specialists +
 * 6 base models + frontier cross-lab models)". The rows hold 19 model ids: 6 base models and 13 of
 * our own fine-tunes, and no other model (no frontier or cross-lab model is in them).
 */
export function measuredOnModel(axes: readonly Axisish[]): string {
  const f = ROWS_POWER.fleet as unknown as {
    models_in_rows: number; base_count: number; base_models: readonly string[];
    own_count: number; other_count: number; other_models: readonly string[];
  };
  const cmp = axes.filter((a) => a.kind === "model-comparison");
  const rowAxes = Object.keys(POWER_AXES).filter((k) => cmp.some((a) => a.axis === k));
  const retired = rowAxes.filter((k) => !rowsServeTheBank(k));
  const outside = cmp.filter((a) => !POWER_AXES[a.axis]);
  const fin = axes.filter((a) => a.family === "financial").length;
  const others = f.other_count
    ? ` and ${f.other_count} other ${f.other_count === 1 ? "model" : "models"} (${f.other_models.join(", ")})`
    : "; no other model is in the rows";
  const outsideText = outside
    .map((a) => {
      const k = a.per_model ? Object.keys(a.per_model).length : 0;
      return k ? `${a.axis}: ${k}-model fleet, stated on the axis` : `${a.axis}: fleet stated on the axis`;
    })
    .join("; ");
  return (
    `Behavioural (model-comparison) axis with published per-item rows: ${rowAxes.length} of ${cmp.length} ` +
    `(${ROWS_POWER.dataset}). The rows hold a ${f.models_in_rows}-model fleet: ${f.base_count} base models, compared ` +
    `(${f.base_models.join(", ")}), and ${f.own_count} CSOAI own fine-tunes, excluded before comparison and never ` +
    `counted in a comparison${others}. Counted from the rows, not typed. ` +
    (retired.length
      ? `${retired.join(", ")}: the published rows are a retired bank; the served row states its own fleet on the axis. `
      : "") +
    (outsideText ? `Not in the rows — ${outsideText}; never conflated with the rows fleet. ` : "") +
    `Financial/domain axis (${fin}): not a model comparison — measured as deterministic facts ` +
    `(issuer-account reads + public series), with no fleet, no leader and no accuracy.`
  );
}
