/** GENERATED by scripts/gspc_separation_from_rows.py from the published per-item rows
 * (csoai/gspc-peritem-rows-2026-08-12@294e4cf9e8b72a00aa50de024b3ed3e7ab0b3361). Do not edit by hand — re-run the producer. */
export const ROWS_SEPARATION = {
  "schema": "csoai.gspc-peritem-rows/0.1",
  "record_id": "gspc-peritem-rows-2026-08-12",
  "created_utc": "2026-09-27T04:38:00Z",
  "dataset": "csoai/gspc-peritem-rows-2026-08-12",
  "dataset_url": "https://huggingface.co/datasets/csoai/gspc-peritem-rows-2026-08-12",
  "dataset_revision": "294e4cf9e8b72a00aa50de024b3ed3e7ab0b3361",
  "licence": "CC-BY-4.0",
  "peritem_sha256": "0d8dacfbe7384a5d2f6a83e7455482ab75f935366bbb6e18da61cfdac8890dec",
  "peritem_sha256_is": "sha256 of the dataset's SHA256SUMS file bytes — one line '<sha256>  rows/<file>' per row file, sorted by file name. Recompute: sha256sum rows/*.jsonl > SHA256SUMS; sha256sum SHA256SUMS.",
  "files": {
    "peritem_affect.jsonl": "7e8a612889d486df40ba638e36ba976cd2820460272fe65c0202e271c95e99e7",
    "peritem_agi.jsonl": "b70ccaa015668a80aeb50196623e8a138b6238e023b6cdff4308ee4fd592b2cb",
    "peritem_art5.jsonl": "950861961ed3e1d0481c4577850b908b41ef696785b500956f11c502015cf1a3",
    "peritem_asi.jsonl": "f90910c6cede5f97a1158226535020c17cf6f7f22a19ce65201511b179ef9e40",
    "peritem_care.jsonl": "888f230b58e5d78a8570244b9e8374c9740f24c3d6fd9f45d67b372db25f27b2",
    "peritem_det.jsonl": "665e358bedbaf899620fd5119a2a9d9b1415eb91396a463955c0e667c21b94a3",
    "peritem_gov.jsonl": "3a1d3193d3651448dd311efe4c7efcbdffb19e07fba06c15e628b844bfbfa2a5",
    "peritem_mach.jsonl": "d3133100c2889cf259f2faa5390c69ccd3c71ac157fbb4ccd369b3c679996a0b",
    "peritem_mcp.jsonl": "9ac4db30d9d0039555702445ab940346974da36b4b1d8de58dc775849caa26da",
    "peritem_oss.jsonl": "f04421a8a8b4a6f01d79dfe771ede8ef40de4338955dcb64a48244df9008685f",
    "peritem_prv.jsonl": "fb9efe3afda9d075cf38607c53f1c6a8044909b642e58747b9559a87fcc83237",
    "peritem_swarm.jsonl": "0a54c4abae07d638d25e7121771500dfc3f40ad0a40a46279a1b6a4dc17f6212",
    "peritem_xr.jsonl": "34758dd55d2b632e8a2a26390c3f1e01d7044a92e8c38d7ee76bd0386bcc8a6a"
  },
  "rows_total": 15580,
  "frozen_manifests_note": "The signed 2026-08-13 board-freeze manifests carry peritem_sha256: null (the rows were not published then). They stay as signed; this record binds the rows by hash instead of editing them.",
  "rule": "Leader vs best base model; SEPARATED iff exact McNemar p<0.05 on discordant items, else TIE (decided 2026-08-13). Wilson 95% intervals are annotation only.",
  "own_model_exclusion": "CSOAI's own fine-tunes (sov6-*-v3-light in the rows; council-*-v3-light on the board) are removed before ranking. Base fleet of 6.",
  "producer": "scripts/gspc_separation_from_rows.py",
  "publication_rule": "A determination is published only on an axis that carries signed cards in /signed/card_index.json and whose rows are the bank the board row serves. Elsewhere the axis stays UNTESTED with its reason.",
  "axes": {
    "governance": {
      "file": "peritem_gov.jsonl",
      "sha256": "3a1d3193d3651448dd311efe4c7efcbdffb19e07fba06c15e628b844bfbfa2a5",
      "rows": 4503,
      "distinct_items": 237,
      "determination": "TIE",
      "card_keys": [
        "gspc-governance",
        "gov"
      ],
      "leader_card": {
        "state": "CARD_RECORDS_A_DIFFERENT_MEASUREMENT",
        "card": "cfba2ad1aaf8c3586d692a3b1f138f5e86f2adb0ac84f49353482c6fe8640b73",
        "card_url": "/signed/cards/cfba2ad1aaf8c3586d692a3b1f138f5e86f2adb0ac84f49353482c6fe8640b73.json",
        "card_accuracy": 0.0,
        "note": "leader shown from per-item rows; no signed per-model card yet for this run — the signed card for mistral:7b on this axis records a different measurement (accuracy 0.0), so it does not back the number shown"
      },
      "test": {
        "leader": {
          "model": "mistral:7b",
          "k": 139,
          "n": 237,
          "accuracy": 0.5865,
          "interval": [
            0.523,
            0.647
          ]
        },
        "runner_up": {
          "model": "deepseek-r1:8b",
          "k": 128,
          "n": 237,
          "accuracy": 0.5401,
          "interval": [
            0.476,
            0.602
          ]
        },
        "paired_items": 237,
        "b10": 70,
        "c01": 59,
        "mcnemar_p": 0.3787,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.001,
        "shuffle_fixed_pair_separated_rate": 0.044
      },
      "sentence": "No model separated from the next best on this axis (exact McNemar, p≥0.05, n=237; p=0.3787)."
    },
    "safety": {
      "file": "peritem_agi.jsonl",
      "sha256": "b70ccaa015668a80aeb50196623e8a138b6238e023b6cdff4308ee4fd592b2cb",
      "rows": 684,
      "distinct_items": 36,
      "determination": "TIE",
      "card_keys": [
        "gspc-safety"
      ],
      "leader_card": {
        "state": "NO_SIGNED_PER_MODEL_CARD",
        "note": "leader shown from per-item rows; no signed per-model card yet"
      },
      "test": {
        "leader": {
          "model": "gemma3:12b",
          "k": 34,
          "n": 36,
          "accuracy": 0.9444,
          "interval": [
            0.819,
            0.985
          ]
        },
        "runner_up": {
          "model": "qwen2.5:3b",
          "k": 32,
          "n": 36,
          "accuracy": 0.8889,
          "interval": [
            0.747,
            0.956
          ]
        },
        "paired_items": 36,
        "b10": 4,
        "c01": 2,
        "mcnemar_p": 0.6875,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.004,
        "shuffle_fixed_pair_separated_rate": 0.029
      },
      "sentence": "No model separated from the next best on this axis (exact McNemar, p≥0.05, n=36; p=0.6875)."
    },
    "continuity": {
      "file": "peritem_asi.jsonl",
      "sha256": "f90910c6cede5f97a1158226535020c17cf6f7f22a19ce65201511b179ef9e40",
      "rows": 627,
      "distinct_items": 33,
      "determination": "TIE",
      "card_keys": [
        "gspc-continuity"
      ],
      "leader_card": {
        "state": "NO_SIGNED_PER_MODEL_CARD",
        "note": "leader shown from per-item rows; no signed per-model card yet"
      },
      "test": {
        "leader": {
          "model": "gemma3:12b",
          "k": 20,
          "n": 33,
          "accuracy": 0.6061,
          "interval": [
            0.437,
            0.753
          ]
        },
        "runner_up": {
          "model": "deepseek-r1:8b",
          "k": 18,
          "n": 33,
          "accuracy": 0.5455,
          "interval": [
            0.38,
            0.702
          ]
        },
        "paired_items": 33,
        "b10": 4,
        "c01": 2,
        "mcnemar_p": 0.6875,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.0,
        "shuffle_fixed_pair_separated_rate": 0.034
      },
      "sentence": "No model separated from the next best on this axis (exact McNemar, p≥0.05, n=33; p=0.6875)."
    },
    "provenance": {
      "file": "peritem_prv.jsonl",
      "sha256": "fb9efe3afda9d075cf38607c53f1c6a8044909b642e58747b9559a87fcc83237",
      "rows": 608,
      "distinct_items": 32,
      "determination": "TIE",
      "card_keys": [
        "gspc-provenance"
      ],
      "leader_card": {
        "state": "CARD_RECORDS_A_DIFFERENT_MEASUREMENT",
        "card": "62123d93724144cdfec5497af3984fa22d8ce749a4f2d0710b774c6614d8ed72",
        "card_url": "/signed/cards/62123d93724144cdfec5497af3984fa22d8ce749a4f2d0710b774c6614d8ed72.json",
        "card_accuracy": 0.8,
        "note": "leader shown from per-item rows; no signed per-model card yet for this run — the signed card for llama3.2:3b on this axis records a different measurement (accuracy 0.8), so it does not back the number shown"
      },
      "test": {
        "leader": {
          "model": "llama3.2:3b",
          "k": 23,
          "n": 32,
          "accuracy": 0.7188,
          "interval": [
            0.546,
            0.844
          ]
        },
        "runner_up": {
          "model": "gemma3:12b",
          "k": 22,
          "n": 32,
          "accuracy": 0.6875,
          "interval": [
            0.514,
            0.82
          ]
        },
        "paired_items": 32,
        "b10": 6,
        "c01": 5,
        "mcnemar_p": 1.0,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.001,
        "shuffle_fixed_pair_separated_rate": 0.016
      },
      "sentence": "No model separated from the next best on this axis (exact McNemar, p≥0.05, n=32; p=1.0)."
    },
    "cross-reality": {
      "file": "peritem_xr.jsonl",
      "sha256": "34758dd55d2b632e8a2a26390c3f1e01d7044a92e8c38d7ee76bd0386bcc8a6a",
      "rows": 608,
      "distinct_items": 32,
      "determination": "UNTESTED",
      "untested_reason_code": "NO_SIGNED_CARD_FOR_AXIS",
      "untested_reason": "The published rows give TIE (exact McNemar p=0.0654, n=32), but this axis has no signed card of any model in the public card index (/signed/card_index.json). The board publishes a separation determination only on axes that carry signed cards, so this one stays UNTESTED rather than resting on rows alone.",
      "test": {
        "leader": {
          "model": "mistral:7b",
          "k": 26,
          "n": 32,
          "accuracy": 0.8125,
          "interval": [
            0.647,
            0.911
          ]
        },
        "runner_up": {
          "model": "llama3.2:3b",
          "k": 19,
          "n": 32,
          "accuracy": 0.5938,
          "interval": [
            0.423,
            0.745
          ]
        },
        "paired_items": 32,
        "b10": 9,
        "c01": 2,
        "mcnemar_p": 0.0654,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.002,
        "shuffle_fixed_pair_separated_rate": 0.012
      }
    },
    "detector-interop": {
      "file": "peritem_det.jsonl",
      "sha256": "665e358bedbaf899620fd5119a2a9d9b1415eb91396a463955c0e667c21b94a3",
      "rows": 627,
      "distinct_items": 33,
      "determination": "UNTESTED",
      "untested_reason_code": "NO_SIGNED_CARD_FOR_AXIS",
      "untested_reason": "The published rows give TIE (exact McNemar p=0.4531, n=33), but this axis has no signed card of any model in the public card index (/signed/card_index.json). The board publishes a separation determination only on axes that carry signed cards, so this one stays UNTESTED rather than resting on rows alone.",
      "test": {
        "leader": {
          "model": "deepseek-r1:8b",
          "k": 29,
          "n": 33,
          "accuracy": 0.8788,
          "interval": [
            0.727,
            0.952
          ]
        },
        "runner_up": {
          "model": "mistral:7b",
          "k": 26,
          "n": 33,
          "accuracy": 0.7879,
          "interval": [
            0.622,
            0.893
          ]
        },
        "paired_items": 33,
        "b10": 5,
        "c01": 2,
        "mcnemar_p": 0.4531,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.0,
        "shuffle_fixed_pair_separated_rate": 0.021
      }
    },
    "art5-safeguard": {
      "file": "peritem_art5.jsonl",
      "sha256": "950861961ed3e1d0481c4577850b908b41ef696785b500956f11c502015cf1a3",
      "rows": 684,
      "distinct_items": 36,
      "determination": "UNTESTED",
      "untested_reason_code": "NO_SIGNED_CARD_FOR_AXIS",
      "untested_reason": "The published rows give TIE (exact McNemar p=1.0, n=36), but this axis has no signed card of any model in the public card index (/signed/card_index.json). The board publishes a separation determination only on axes that carry signed cards, so this one stays UNTESTED rather than resting on rows alone.",
      "test": {
        "leader": {
          "model": "gemma3:12b",
          "k": 35,
          "n": 36,
          "accuracy": 0.9722,
          "interval": [
            0.858,
            0.995
          ]
        },
        "runner_up": {
          "model": "mistral:7b",
          "k": 34,
          "n": 36,
          "accuracy": 0.9444,
          "interval": [
            0.819,
            0.985
          ]
        },
        "paired_items": 36,
        "b10": 1,
        "c01": 0,
        "mcnemar_p": 1.0,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.001,
        "shuffle_fixed_pair_separated_rate": 0.0
      }
    },
    "care": {
      "file": "peritem_care.jsonl",
      "sha256": "888f230b58e5d78a8570244b9e8374c9740f24c3d6fd9f45d67b372db25f27b2",
      "rows": 3800,
      "distinct_items": 199,
      "determination": "TIE",
      "card_keys": [
        "care"
      ],
      "leader_card": {
        "state": "CARD_RECORDS_A_DIFFERENT_MEASUREMENT",
        "card": "45724650575f8f40363728b42c54c5683fffab59a10d65e2991b666ba4d4a813",
        "card_url": "/signed/cards/45724650575f8f40363728b42c54c5683fffab59a10d65e2991b666ba4d4a813.json",
        "card_accuracy": 0.0,
        "note": "leader shown from per-item rows; no signed per-model card yet for this run — the signed card for qwen2.5:0.5b-instruct on this axis records a different measurement (accuracy 0.0), so it does not back the number shown"
      },
      "test": {
        "leader": {
          "model": "qwen2.5:0.5b-instruct",
          "k": 81,
          "n": 200,
          "accuracy": 0.405,
          "interval": [
            0.339,
            0.474
          ]
        },
        "runner_up": {
          "model": "qwen2.5:3b",
          "k": 74,
          "n": 200,
          "accuracy": 0.37,
          "interval": [
            0.306,
            0.439
          ]
        },
        "paired_items": 199,
        "b10": 32,
        "c01": 25,
        "mcnemar_p": 0.427,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.001,
        "shuffle_fixed_pair_separated_rate": 0.035
      },
      "sentence": "No model separated from the next best on this axis (exact McNemar, p≥0.05, n=200; p=0.427)."
    },
    "conformance": {
      "file": "peritem_mcp.jsonl",
      "sha256": "9ac4db30d9d0039555702445ab940346974da36b4b1d8de58dc775849caa26da",
      "rows": 665,
      "distinct_items": 35,
      "determination": "TIE",
      "card_keys": [
        "gspc-conformance"
      ],
      "leader_card": {
        "state": "NO_SIGNED_PER_MODEL_CARD",
        "note": "leader shown from per-item rows; no signed per-model card yet"
      },
      "test": {
        "leader": {
          "model": "mistral:7b",
          "k": 25,
          "n": 35,
          "accuracy": 0.7143,
          "interval": [
            0.549,
            0.837
          ]
        },
        "runner_up": {
          "model": "llama3.2:3b",
          "k": 23,
          "n": 35,
          "accuracy": 0.6571,
          "interval": [
            0.492,
            0.792
          ]
        },
        "paired_items": 35,
        "b10": 3,
        "c01": 1,
        "mcnemar_p": 0.625,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.001,
        "shuffle_fixed_pair_separated_rate": 0.0
      },
      "sentence": "No model separated from the next best on this axis (exact McNemar, p≥0.05, n=35; p=0.625)."
    },
    "openness": {
      "file": "peritem_oss.jsonl",
      "sha256": "f04421a8a8b4a6f01d79dfe771ede8ef40de4338955dcb64a48244df9008685f",
      "rows": 608,
      "distinct_items": 32,
      "determination": "TIE",
      "card_keys": [
        "gspc-openness"
      ],
      "leader_card": {
        "state": "NO_SIGNED_PER_MODEL_CARD",
        "note": "leader shown from per-item rows; no signed per-model card yet"
      },
      "test": {
        "leader": {
          "model": "gemma3:12b",
          "k": 27,
          "n": 32,
          "accuracy": 0.8438,
          "interval": [
            0.682,
            0.931
          ]
        },
        "runner_up": {
          "model": "mistral:7b",
          "k": 23,
          "n": 32,
          "accuracy": 0.7188,
          "interval": [
            0.546,
            0.844
          ]
        },
        "paired_items": 32,
        "b10": 9,
        "c01": 5,
        "mcnemar_p": 0.424,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.001,
        "shuffle_fixed_pair_separated_rate": 0.016
      },
      "sentence": "No model separated from the next best on this axis (exact McNemar, p≥0.05, n=32; p=0.424)."
    },
    "machinery-conformity": {
      "file": "peritem_mach.jsonl",
      "sha256": "d3133100c2889cf259f2faa5390c69ccd3c71ac157fbb4ccd369b3c679996a0b",
      "rows": 627,
      "distinct_items": 33,
      "determination": "UNTESTED",
      "untested_reason_code": "NO_SIGNED_CARD_FOR_AXIS",
      "untested_reason": "The published rows give TIE (exact McNemar p=0.5811, n=33), but this axis has no signed card of any model in the public card index (/signed/card_index.json). The board publishes a separation determination only on axes that carry signed cards, so this one stays UNTESTED rather than resting on rows alone.",
      "test": {
        "leader": {
          "model": "llama3.2:3b",
          "k": 18,
          "n": 33,
          "accuracy": 0.5455,
          "interval": [
            0.38,
            0.702
          ]
        },
        "runner_up": {
          "model": "qwen2.5:0.5b-instruct",
          "k": 15,
          "n": 33,
          "accuracy": 0.4545,
          "interval": [
            0.298,
            0.62
          ]
        },
        "paired_items": 33,
        "b10": 8,
        "c01": 5,
        "mcnemar_p": 0.5811,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.0,
        "shuffle_fixed_pair_separated_rate": 0.021
      }
    },
    "swarm": {
      "file": "peritem_swarm.jsonl",
      "sha256": "0a54c4abae07d638d25e7121771500dfc3f40ad0a40a46279a1b6a4dc17f6212",
      "rows": 760,
      "distinct_items": 3,
      "determination": "UNTESTED",
      "untested_reason_code": "ROWS_ARE_A_RETIRED_BANK",
      "untested_reason": "The published swarm rows are the retired 3-prompt PROTOCOL bank (40 rows per model over 3 distinct items), not the wave-2b bank the board's swarm row serves; rows from one bank cannot decide a separation determination about another.",
      "test": {
        "leader": {
          "model": "qwen2.5:0.5b-instruct",
          "k": 39,
          "n": 40,
          "accuracy": 0.975,
          "interval": [
            0.871,
            0.996
          ]
        },
        "runner_up": {
          "model": "gemma3:12b",
          "k": 19,
          "n": 40,
          "accuracy": 0.475,
          "interval": [
            0.329,
            0.625
          ]
        },
        "paired_items": 3,
        "b10": 1,
        "c01": 0,
        "mcnemar_p": 1.0,
        "ci_disjoint": true,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.0,
        "shuffle_fixed_pair_separated_rate": 0.0
      }
    },
    "affect": {
      "file": "peritem_affect.jsonl",
      "sha256": "7e8a612889d486df40ba638e36ba976cd2820460272fe65c0202e271c95e99e7",
      "rows": 779,
      "distinct_items": 41,
      "determination": "UNTESTED",
      "untested_reason_code": "NO_SIGNED_CARD_FOR_AXIS",
      "untested_reason": "The published rows give TIE (exact McNemar p=1.0, n=41), but this axis has no signed card of any model in the public card index (/signed/card_index.json). The board publishes a separation determination only on axes that carry signed cards, so this one stays UNTESTED rather than resting on rows alone.",
      "test": {
        "leader": {
          "model": "gemma3:12b",
          "k": 28,
          "n": 41,
          "accuracy": 0.6829,
          "interval": [
            0.53,
            0.804
          ]
        },
        "runner_up": {
          "model": "qwen2.5:3b",
          "k": 27,
          "n": 41,
          "accuracy": 0.6585,
          "interval": [
            0.505,
            0.784
          ]
        },
        "paired_items": 41,
        "b10": 5,
        "c01": 4,
        "mcnemar_p": 1.0,
        "ci_disjoint": false,
        "verdict": "TIE"
      },
      "control": {
        "nperm": 1000,
        "seed": 20260927,
        "shuffle_reselect_separated_rate": 0.001,
        "shuffle_fixed_pair_separated_rate": 0.032
      }
    }
  },
  "objections": "https://councilof.ai/census/"
} as const;
