// GENERATED by scripts/build-regulatory-inventory.mjs --version. Do not edit by hand.
//
// The stamped regulatory inventory that public/interop/regulatory-inventory-latest.json selects.
// A Pages Function cannot import a JSON file by a path read at run time, so the selection is
// bound here at build time. scripts/regulatory-inventory-gate.mjs (inside build:client) fails
// when this module names any file or digest other than the pointer's, and checks that the
// file's OpenTimestamps proof commits to exactly those bytes.
import inventory from "../../public/interop/regulatory-inventory-2026-10-07-019dca73240b.json";

export const REGULATORY_INVENTORY_PATH = "public/interop/regulatory-inventory-2026-10-07-019dca73240b.json";
export const REGULATORY_INVENTORY_SHA256 = "d8e4b380a2d1319eafa9f971e644509f4ab9ae8b7ee896698e36a0cdf86048f9";
export const REGULATORY_INVENTORY_POINTER = "public/interop/regulatory-inventory-latest.json";
export default inventory;
