// GENERATED by scripts/rulings/produce-ruling.mjs from public/signed/rulings/*.json. Do not edit:
// every record and the index carry a detached signature, and GET /api/rulings verifies them on
// every request, so a hand edit reads STALE or INVALID_SIGNATURE there.
/* eslint-disable */
export const RULINGS: Record<string, unknown>[] = [
  {
    "schema": "csoai.ruling/0.1",
    "reviewers": [],
    "panel_state": "NOT_CONVENED",
    "panel_n_eff": "UNMEASURED",
    "panel_note": "panel not yet convened",
    "binding": "OWNER",
    "decider": "owner",
    "supersedes": null,
    "ruling_id": "R-2026-0928-01",
    "class": "other",
    "question": "What does every lane optimise for when it chooses and finishes work?",
    "rule_applied": {
      "ref": "Owner directive (standing), recorded in the owner-rulings log",
      "text": "A directive on priorities. It changes no rule, no measured state and no public claim; it orders work."
    },
    "evidence": [
      {
        "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/owner-rulings-excerpt-20260929.md",
        "sha256": "55ff6af78139035cea8c1a953b32edd93ea0e73e06744dee32d2c8699374dbee",
        "of": "the committed byte-exact excerpt of the owner-rulings log this record quotes"
      }
    ],
    "rule_output": null,
    "owner_ruling_verbatim": "focus on the PUBLIC END USER and on higher quality and higher results in everything.",
    "owner_ruling_source": {
      "verbatim_status": "AS_RECORDED",
      "where": "owner-rulings log, entry 2026-09-28T14:50Z (OWNER DIRECTIVE); excerpt E1",
      "entry_stamp": "2026-09-28T14:50Z"
    },
    "decided_at": "2026-09-28T14:50Z",
    "decided_at_basis": "the log entry's own timestamp",
    "effective_from": "2026-09-28T14:50Z",
    "correction_ref": null,
    "effect": {
      "writes_measured_state": false,
      "writes_board": false,
      "note": "Orders lane work. Sets no state and publishes nothing."
    },
    "signature": {
      "did": "did:web:csoai.org#board-attestation-1",
      "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
      "attestation": {
        "schema": "csoai.ruling-attestation/0.1",
        "ruling_id": "R-2026-0928-01",
        "class": "other",
        "decided_at": "2026-09-28T14:50Z",
        "content_id": "736e13228ffa80ef87d660021a60085f93a8a94c09f8705b8fd1927c65c4fb8a",
        "content_id_rule": "sha256(RFC 8785 JCS of the record without its 'signature' key)",
        "record_canonical_bytes": 1391,
        "signed_at": "2026-09-29T05:49:21Z"
      },
      "sig_ed25519": "5e9517e4ba2a9d95602c1acd3c16398b11d6d07ddce0b16a6f61953289c00e38d7dfc00a2a033c0b70e52b9795d90ac79bf83176e1b570aaa2809249fee0b00f",
      "signer_auth": "pod-token",
      "note": "Detached Ed25519 over signature.attestation (RFC 8785 JCS; identical to the board signer's sorted-key form for this ASCII object), issued through POST /api/board-sign on the pod caller token. The attestation commits to this record by content_id. The design note proposed a separate ruling key; none is minted, so this names the board key it was signed under."
    }
  },
  {
    "schema": "csoai.ruling/0.1",
    "reviewers": [],
    "panel_state": "NOT_CONVENED",
    "panel_n_eff": "UNMEASURED",
    "panel_note": "panel not yet convened",
    "binding": "OWNER",
    "decider": "owner",
    "supersedes": null,
    "ruling_id": "R-2026-0928-02",
    "class": "naming",
    "question": "May 'SovX' be used publicly as the product name for the wrapped-asset measurements?",
    "rule_applied": {
      "ref": "Naming is a ruling-class question (proposal 4.B); brand-gate codename rule",
      "text": "Product naming is decided by ruling. The brand-gate codename pattern at master does not match 'SovX', so the name passes the existing public-string gate.",
      "uri": "git:councilof-ai@a69392d3c3af76c7be2239f767bca17b49d5b60d:scripts/brand-gate.mjs",
      "sha256": "d26c2dbc2302876d2eefdc33039d00d8920fa0c3a4a1d6c14e16167b7227e705"
    },
    "evidence": [
      {
        "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/owner-rulings-excerpt-20260929.md",
        "sha256": "55ff6af78139035cea8c1a953b32edd93ea0e73e06744dee32d2c8699374dbee",
        "of": "the committed byte-exact excerpt of the owner-rulings log this record quotes"
      },
      {
        "uri": "git:councilof-ai@a69392d3c3af76c7be2239f767bca17b49d5b60d:scripts/brand-gate.mjs",
        "sha256": "d26c2dbc2302876d2eefdc33039d00d8920fa0c3a4a1d6c14e16167b7227e705",
        "of": "the public-string gate the name must pass"
      }
    ],
    "rule_output": null,
    "owner_ruling_verbatim": "\"SovX\" MAY be used publicly as the product name for the wrapper (Venturi) wrapped-asset measurements. Do not strip it.",
    "owner_ruling_source": {
      "verbatim_status": "AS_RECORDED",
      "where": "owner-rulings log, entry 2026-09-28T15:30Z (OWNER RULING); excerpt E2",
      "entry_stamp": "2026-09-28T15:30Z",
      "redaction": "the entry's two further sentences name internal codenames and are omitted, not reworded"
    },
    "decided_at": "2026-09-28T15:30Z",
    "decided_at_basis": "the log entry's own timestamp",
    "effective_from": "2026-09-28T15:30Z",
    "correction_ref": null,
    "effect": {
      "writes_measured_state": false,
      "writes_board": false,
      "note": "Allows a public name on wrapper surfaces. Changes no measurement."
    },
    "signature": {
      "did": "did:web:csoai.org#board-attestation-1",
      "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
      "attestation": {
        "schema": "csoai.ruling-attestation/0.1",
        "ruling_id": "R-2026-0928-02",
        "class": "naming",
        "decided_at": "2026-09-28T15:30Z",
        "content_id": "b1ca3c48728d6e04051a5960f41063612e320d8f95b3a763403fe49b366271aa",
        "content_id_rule": "sha256(RFC 8785 JCS of the record without its 'signature' key)",
        "record_canonical_bytes": 1999,
        "signed_at": "2026-09-29T05:49:21Z"
      },
      "sig_ed25519": "96683a04c990122f0f607e1c43b673637b96946bbe2f066d86210a666e3c9c002c5356235ab3ce479a4920c1cd10060c8c14b1dcb4357e005a1fbe82b40b8b07",
      "signer_auth": "pod-token",
      "note": "Detached Ed25519 over signature.attestation (RFC 8785 JCS; identical to the board signer's sorted-key form for this ASCII object), issued through POST /api/board-sign on the pod caller token. The attestation commits to this record by content_id. The design note proposed a separate ruling key; none is minted, so this names the board key it was signed under."
    }
  },
  {
    "schema": "csoai.ruling/0.1",
    "reviewers": [],
    "panel_state": "NOT_CONVENED",
    "panel_n_eff": "UNMEASURED",
    "panel_note": "panel not yet convened",
    "binding": "OWNER",
    "decider": "owner",
    "supersedes": null,
    "ruling_id": "R-2026-0929-01",
    "class": "publication",
    "question": "Is the paid Paddle issuer withdrawn and /api/certificate-schema retired, landing held commit 88a475f0e?",
    "rule_applied": {
      "ref": "Standing doctrine: we measure, we never certify; verification is free forever; a grade is never sold",
      "text": "A paid issuer contradicts the doctrine, so it is withdrawn and the schema becomes csoai.completion-record/0.1."
    },
    "evidence": [
      {
        "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/owner-rulings-excerpt-20260929.md",
        "sha256": "55ff6af78139035cea8c1a953b32edd93ea0e73e06744dee32d2c8699374dbee",
        "of": "the committed byte-exact excerpt of the owner-rulings log this record quotes"
      },
      {
        "uri": "git:councilof-ai@88a475f0e1009ab5f8cd5794f07976f1594ab06c:functions/api/certificate-schema.ts",
        "sha256": "81edb505c2fbebdda91c410575e3606fe4f3b3526909610ed28cb2a406b49165",
        "of": "the retired schema endpoint in the held commit"
      },
      {
        "uri": "git:councilof-ai@88a475f0e1009ab5f8cd5794f07976f1594ab06c:functions/api/paddle-webhook.ts",
        "sha256": "3b13fc7a2fb6b9dda6a0d3d9b558dbeddb767f7d67616d561783fa97287a3f3f",
        "of": "the withdrawn webhook in the held commit"
      }
    ],
    "rule_output": null,
    "owner_ruling_verbatim": "withdraw Paddle",
    "owner_ruling_source": {
      "verbatim_status": "QUOTED",
      "where": "owner-rulings log, entry 2026-09-29T04:00Z (OWNER RULING); excerpt E3",
      "entry_stamp": "2026-09-29T04:00Z"
    },
    "decided_at": "2026-09-29T04:00Z",
    "decided_at_basis": "the log entry's own timestamp",
    "effective_from": "the landing that deploys commit 88a475f0e; the owner then disables the Paddle webhook destination",
    "correction_ref": null,
    "effect": {
      "writes_measured_state": false,
      "writes_board": false,
      "note": "Withdraws a paid surface. Changes no measurement."
    },
    "signature": {
      "did": "did:web:csoai.org#board-attestation-1",
      "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
      "attestation": {
        "schema": "csoai.ruling-attestation/0.1",
        "ruling_id": "R-2026-0929-01",
        "class": "publication",
        "decided_at": "2026-09-29T04:00Z",
        "content_id": "0d9be062f3b26fef48a8e42a94d1da7d929b12766e731164be967180009d6846",
        "content_id_rule": "sha256(RFC 8785 JCS of the record without its 'signature' key)",
        "record_canonical_bytes": 1936,
        "signed_at": "2026-09-29T05:49:21Z"
      },
      "sig_ed25519": "9cf5387f8cd90a94928eb13f53655bd35ab4305a6048062f324509a5c5494d52e38c8140e9acf2bb3ce7e511502bcc49bff2551b99b9716a175c56a3fed9d90b",
      "signer_auth": "pod-token",
      "note": "Detached Ed25519 over signature.attestation (RFC 8785 JCS; identical to the board signer's sorted-key form for this ASCII object), issued through POST /api/board-sign on the pod caller token. The attestation commits to this record by content_id. The design note proposed a separate ruling key; none is minted, so this names the board key it was signed under."
    }
  },
  {
    "schema": "csoai.ruling/0.1",
    "reviewers": [],
    "panel_state": "NOT_CONVENED",
    "panel_n_eff": "UNMEASURED",
    "panel_note": "panel not yet convened",
    "binding": "OWNER",
    "decider": "owner",
    "supersedes": null,
    "ruling_id": "R-2026-0929-02",
    "class": "other",
    "question": "Do the watchers adopt the two harness-router winners (multiset claim-diff; fetch_ok gate with two-fetch confirmation)?",
    "rule_applied": {
      "ref": "Harness router pre-registered tasks (router.json); rules are adopted, not voted",
      "text": "The router scored candidate rules on frozen fixtures; the ruling adopts the winners as the watchers' rules. Change detection: false-change rate 0.000 against 0.931 for the naive hash compare, as recorded in the adopting commit."
    },
    "evidence": [
      {
        "uri": "git:councilof-ai@08d03825f0e697e381606c97060ecdda42f501a2:scripts/reg-watch-policy.mjs",
        "sha256": "c397f85a2f416ccbced04af63cf6e8d20c24adcf10ba9d3ab90a7bbc07943d7d",
        "of": "the adopted change-detection rule, whose header records the owner words"
      },
      {
        "uri": "git:councilof-ai@08d03825f0e697e381606c97060ecdda42f501a2:scripts/watch/fixtures/harness-router-20260929/claim_diff.json",
        "sha256": "e5421f9677574db1eda00ab2627664565398f56289c5f9d6b897a4550bea22ea",
        "of": "frozen router fixture, claim-diff task"
      },
      {
        "uri": "git:councilof-ai@08d03825f0e697e381606c97060ecdda42f501a2:scripts/watch/fixtures/harness-router-20260929/change_detect.json",
        "sha256": "742df1baf0803a355a4d79889e2020730cafdc958bc6bb041ac5a1944be79849",
        "of": "frozen router fixture, change-detection task"
      }
    ],
    "rule_output": null,
    "owner_ruling_verbatim": "adopt the winners",
    "owner_ruling_source": {
      "verbatim_status": "QUOTED",
      "where": "commit 08d03825f message and scripts/reg-watch-policy.mjs header; excerpt E6",
      "entry_stamp": "2026-09-29T04:27:17Z"
    },
    "decided_at": "2026-09-29",
    "decided_at_basis": "not after 2026-09-29T04:27:17Z, the commit that records the words",
    "effective_from": "the landing of lane/adopt-winners-20260929 @ 08d03825f",
    "correction_ref": null,
    "effect": {
      "writes_measured_state": false,
      "writes_board": false,
      "note": "Changes how watchers decide a source changed. Sets no board state."
    },
    "signature": {
      "did": "did:web:csoai.org#board-attestation-1",
      "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
      "attestation": {
        "schema": "csoai.ruling-attestation/0.1",
        "ruling_id": "R-2026-0929-02",
        "class": "other",
        "decided_at": "2026-09-29",
        "content_id": "7dc94b0de6835b83282132067c2d9751e88b1826c9fa19a4e542e4ac548436be",
        "content_id_rule": "sha256(RFC 8785 JCS of the record without its 'signature' key)",
        "record_canonical_bytes": 2076,
        "signed_at": "2026-09-29T05:49:21Z"
      },
      "sig_ed25519": "5e7c2cfc3fb23ce296108f7387fedb3be81ef9b306d153688e3f0782435a4d74fde6949b0cf3b9fdc330d6fd1c772a1184021c88e94179a9633c0715a2056703",
      "signer_auth": "pod-token",
      "note": "Detached Ed25519 over signature.attestation (RFC 8785 JCS; identical to the board signer's sorted-key form for this ASCII object), issued through POST /api/board-sign on the pod caller token. The attestation commits to this record by content_id. The design note proposed a separate ruling key; none is minted, so this names the board key it was signed under."
    }
  },
  {
    "schema": "csoai.ruling/0.1",
    "reviewers": [],
    "panel_state": "NOT_CONVENED",
    "panel_n_eff": "UNMEASURED",
    "panel_note": "panel not yet convened",
    "binding": "OWNER",
    "decider": "owner",
    "supersedes": null,
    "ruling_id": "R-2026-0929-03",
    "class": "publication",
    "question": "Are the four Zenodo DOIs minted (claim-maintenance v0.2, capsule companion, signed-receipts draft 0.3, board snapshot with corrections ledger)?",
    "rule_applied": {
      "ref": "Publication approval is a ruling-class question (proposal 4.B)",
      "text": "Publishing an archival deposit is approved by ruling. The deposits carry what is already public; they add no measurement."
    },
    "evidence": [
      {
        "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/owner-rulings-excerpt-20260929.md",
        "sha256": "55ff6af78139035cea8c1a953b32edd93ea0e73e06744dee32d2c8699374dbee",
        "of": "the committed byte-exact excerpt of the owner-rulings log this record quotes"
      },
      {
        "uri": "git:councilof-ai@b4382609c308ee64668721e99b0af335ebf54eaa:public/spec/claim-maintenance/v0.2/deposit.json",
        "sha256": "4db322c9e1a57a45360511b673b5eb4c63a6aef4cc29dcad7073327a0828bb1d",
        "of": "deposit record, claim-maintenance v0.2 (10.5281/zenodo.23030504)"
      },
      {
        "uri": "git:councilof-ai@b4382609c308ee64668721e99b0af335ebf54eaa:public/spec/signed-receipts/v1/draft-0.3/deposit.json",
        "sha256": "7f1dd182793b8d84ad2d21cb2afd58cc7923c738d5a3e84ba4b91eaec2c4b08d",
        "of": "deposit record, signed-receipts draft 0.3 (10.5281/zenodo.23030508)"
      },
      {
        "uri": "git:councilof-ai@b4382609c308ee64668721e99b0af335ebf54eaa:CITATION.cff",
        "sha256": "c946dd486105d1052eaea4844c844b44fa3760d895a42ada04846ecb1fab71ac",
        "of": "citation file carrying all four DOIs"
      }
    ],
    "rule_output": null,
    "owner_ruling_verbatim": "yes mint all 4 DOIs",
    "owner_ruling_source": {
      "verbatim_status": "QUOTED",
      "where": "owner-rulings log, entry 2026-09-29T05:20Z (LAND doi-mint-20260929); excerpt E4",
      "entry_stamp": "2026-09-29T05:20Z"
    },
    "decided_at": "2026-09-29",
    "decided_at_basis": "not after 2026-09-29T05:20Z, the log entry that records the approval",
    "effective_from": "2026-09-29T05:20Z",
    "correction_ref": null,
    "effect": {
      "writes_measured_state": false,
      "writes_board": false,
      "note": "Archival publication of existing material. Changes no measurement."
    },
    "signature": {
      "did": "did:web:csoai.org#board-attestation-1",
      "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
      "attestation": {
        "schema": "csoai.ruling-attestation/0.1",
        "ruling_id": "R-2026-0929-03",
        "class": "publication",
        "decided_at": "2026-09-29",
        "content_id": "0dba8f607b47c189ddb9873d54e8b1ac41042a7a5564f41feaf9198a0ea327d8",
        "content_id_rule": "sha256(RFC 8785 JCS of the record without its 'signature' key)",
        "record_canonical_bytes": 2212,
        "signed_at": "2026-09-29T05:49:21Z"
      },
      "sig_ed25519": "b9de0be99b1fadf805762ecc2aa0ed5474a988b4a55cd06112c450455e4a06126cad55675e5a9031a4c51e387d3614d2942d93bc2c496af815ac24e36053f003",
      "signer_auth": "pod-token",
      "note": "Detached Ed25519 over signature.attestation (RFC 8785 JCS; identical to the board signer's sorted-key form for this ASCII object), issued through POST /api/board-sign on the pod caller token. The attestation commits to this record by content_id. The design note proposed a separate ruling key; none is minted, so this names the board key it was signed under."
    }
  },
  {
    "schema": "csoai.ruling/0.1",
    "reviewers": [],
    "panel_state": "NOT_CONVENED",
    "panel_n_eff": "UNMEASURED",
    "panel_note": "panel not yet convened",
    "binding": "OWNER",
    "decider": "owner",
    "supersedes": null,
    "ruling_id": "R-2026-0929-04",
    "class": "board-change",
    "question": "Is the rule-computed jail separation, UNTESTED at the prompt level, served on the signed board in place of TIE at the next re-sign?",
    "rule_applied": {
      "ref": "Proposal 4.A: rules decide measured states; the owner rules only on serving a rule-computed change",
      "text": "The prompt-level method was pre-registered in e95c14cf4 before it ran and computed in 0c9e93d11. The ruling approves serving that output through the normal signing path; it does not author it.",
      "uri": "git:councilof-ai@e95c14cf4cbeb70f149a939913ab74bdab1df5f5:scripts/gspc_jail_prompt_interval.py",
      "sha256": "4fc629863327e06edf5cefd09f2b3f54f713fc1bd5e8d92b958b671148ee2c4d"
    },
    "evidence": [
      {
        "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/owner-rulings-excerpt-20260929.md",
        "sha256": "55ff6af78139035cea8c1a953b32edd93ea0e73e06744dee32d2c8699374dbee",
        "of": "the committed byte-exact excerpt of the owner-rulings log this record quotes"
      },
      {
        "uri": "https://huggingface.co/datasets/csoai/gspc-jail-goldbank/resolve/df16e7855ff04b90fea19aa5f11f4b86cb466a47/samples.jsonl",
        "sha256": "0b45b620f2277c364275420f812e9415698e3b8bf0b105a7bbb4c2b2627d0f4a",
        "of": "the served jail bank (71 rows, 27 distinct prompts)"
      },
      {
        "uri": "https://huggingface.co/datasets/csoai/gspc-jail-goldbank/resolve/df16e7855ff04b90fea19aa5f11f4b86cb466a47/gold_results.json",
        "sha256": "199781285d5a7056b981874bb7b7ffcd5dd85283b16d19b4f7d7cc601a3512b2",
        "of": "the board run's per-model TP/FP/TN/FN (no per-row answers)"
      },
      {
        "uri": "git:councilof-ai@e95c14cf4cbeb70f149a939913ab74bdab1df5f5:scripts/gspc_jail_prompt_interval.py",
        "sha256": "4fc629863327e06edf5cefd09f2b3f54f713fc1bd5e8d92b958b671148ee2c4d",
        "of": "the pre-registered method"
      },
      {
        "uri": "git:councilof-ai@0c9e93d111354479ad883e834e78651b6db7c0bb:functions/api/_gspc_jail_prompt_interval.ts",
        "sha256": "84cd59037eac11fb4d964fe02ae13a1e83992b6a059672f6352020dd0f78fca6",
        "of": "the computed prompt-level output"
      },
      {
        "uri": "git:councilof-ai@0c9e93d111354479ad883e834e78651b6db7c0bb:docs/corrections-drafts/jail-count-fix-2026-09-29.DRAFT.json",
        "sha256": "02fbc187c577009900d0eb63be754ab1ec248fa49ea9916d5cc6c7d45c31ddc5",
        "of": "the draft correction C-2026-0929-02"
      }
    ],
    "rule_output": {
      "origin": "rule",
      "value": "UNTESTED (NO_PER_ROW_RESULTS) over 27 distinct prompts; the signed row-level result was TIE",
      "computed_by": "git:councilof-ai@0c9e93d111354479ad883e834e78651b6db7c0bb:functions/api/_gspc_jail_prompt_interval.ts"
    },
    "owner_ruling_verbatim": "OWNER RULING: jail axis moves from TIE to UNTESTED at the next re-sign.",
    "owner_ruling_source": {
      "verbatim_status": "AS_RECORDED",
      "where": "owner-rulings log, entry 2026-09-29T06:40Z (OWNER RULING); excerpt E5",
      "entry_stamp": "2026-09-29T06:40Z"
    },
    "decided_at": "2026-09-29T06:40Z",
    "decided_at_basis": "the log entry's own timestamp",
    "effective_from": "the next board re-sign (POST /api/board-sign), recorded as C-2026-0929-02 with old and new values",
    "correction_ref": "C-2026-0929-02",
    "effect": {
      "writes_measured_state": false,
      "writes_board": false,
      "note": "Approves serving a rule's output at the next re-sign. This record writes nothing to the board; the board changes only through its own producer and signature."
    },
    "signature": {
      "did": "did:web:csoai.org#board-attestation-1",
      "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
      "attestation": {
        "schema": "csoai.ruling-attestation/0.1",
        "ruling_id": "R-2026-0929-04",
        "class": "board-change",
        "decided_at": "2026-09-29T06:40Z",
        "content_id": "b3040810e17d49a9a922bd7d1672ef836462996400070f13c7e73393e590a341",
        "content_id_rule": "sha256(RFC 8785 JCS of the record without its 'signature' key)",
        "record_canonical_bytes": 3411,
        "signed_at": "2026-09-29T05:49:21Z"
      },
      "sig_ed25519": "f04d03c2a27e6bdcda600eb9d97221cf791be3733efffa87dcded6114d8d5ee76e134ac57710177bfba9e931071ddd07cf6b98166eca67404de3c27fadc70d0a",
      "signer_auth": "pod-token",
      "note": "Detached Ed25519 over signature.attestation (RFC 8785 JCS; identical to the board signer's sorted-key form for this ASCII object), issued through POST /api/board-sign on the pod caller token. The attestation commits to this record by content_id. The design note proposed a separate ruling key; none is minted, so this names the board key it was signed under."
    }
  },
  {
    "schema": "csoai.ruling/0.1",
    "reviewers": [],
    "panel_state": "NOT_CONVENED",
    "panel_n_eff": "UNMEASURED",
    "panel_note": "panel not yet convened",
    "binding": "OWNER",
    "decider": "owner",
    "supersedes": null,
    "ruling_id": "R-2026-0929-05",
    "class": "publication",
    "question": "Is the SovX wrapped-asset measurement dataset published on Kaggle, as one of the N sites it is distributed to?",
    "rule_applied": {
      "ref": "Publication approval is a ruling-class question (proposal 4.B); follows R-2026-0928-02 (the name)",
      "text": "The name was ruled public on 28 Sep. This records the separate approval to publish the SovX dataset on Kaggle, one of many distribution sites. Every published state still comes from the wrapper producers."
    },
    "evidence": [
      {
        "uri": "git:councilof-ai@40926efafcb50a3382e56804c1f6c759ae2ea0af:council-os/rulings/sources/owner-chat-publish-sovx-20260929.md",
        "sha256": "9ce47c39cce2ff8f3cfc7aa1d083834527d118a63bc9d11a2367dd060e5c76a3",
        "of": "the committed owner words for this ruling, relayed verbatim from chat"
      },
      {
        "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/owner-rulings-excerpt-20260929.md",
        "sha256": "55ff6af78139035cea8c1a953b32edd93ea0e73e06744dee32d2c8699374dbee",
        "of": "the committed byte-exact excerpt of the owner-rulings log this record quotes"
      },
      {
        "uri": "git:councilof-ai@a69392d3c3af76c7be2239f767bca17b49d5b60d:functions/api/wrapper.ts",
        "sha256": "1983ec802d9b3015d16413ca581ab1cb332b75ef61d48f6c0d9f72b84b651fc6",
        "of": "the wrapper measurement surface at master"
      }
    ],
    "rule_output": null,
    "owner_ruling_verbatim": "gooo land round 3 and publish SovX dataset on Kaggle It's just one flywheel. Kaggle is one of many N sites",
    "owner_ruling_source": {
      "verbatim_status": "QUOTED",
      "where": "owner chat 2026-09-29 ~05:40 BST, relayed verbatim by the lane coordinator; council-os/rulings/sources/owner-chat-publish-sovx-20260929.md",
      "entry_stamp": "2026-09-29 ~04:40Z (approximate)"
    },
    "decided_at": "2026-09-29",
    "decided_at_basis": "owner chat at about 05:40 BST (about 04:40Z); the minute is approximate, so only the date is recorded",
    "effective_from": "2026-09-29",
    "correction_ref": null,
    "effect": {
      "writes_measured_state": false,
      "writes_board": false,
      "note": "Publication of the SovX dataset on Kaggle. Changes no measurement."
    },
    "signature": {
      "did": "did:web:csoai.org#board-attestation-1",
      "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
      "attestation": {
        "schema": "csoai.ruling-attestation/0.1",
        "ruling_id": "R-2026-0929-05",
        "class": "publication",
        "decided_at": "2026-09-29",
        "content_id": "beaf235aabf7267378c38d6d24d56af301eb809889012f331d5d1f6f3910a87d",
        "content_id_rule": "sha256(RFC 8785 JCS of the record without its 'signature' key)",
        "record_canonical_bytes": 2248,
        "signed_at": "2026-09-29T05:54:37Z"
      },
      "sig_ed25519": "2be10394d5df0123296328b67dcf17539b95b38198e28ca26e35a60bf5759dd595912d659ae0b31947eeae3d1fd3fa980b2e0543fbb0d7ce62fe1b5a6e274709",
      "signer_auth": "pod-token",
      "note": "Detached Ed25519 over signature.attestation (RFC 8785 JCS; identical to the board signer's sorted-key form for this ASCII object), issued through POST /api/board-sign on the pod caller token. The attestation commits to this record by content_id. The design note proposed a separate ruling key; none is minted, so this names the board key it was signed under."
    }
  },
  {
    "schema": "csoai.ruling/0.1",
    "reviewers": [],
    "panel_state": "NOT_CONVENED",
    "panel_n_eff": "UNMEASURED",
    "panel_note": "panel not yet convened",
    "binding": "OWNER",
    "decider": "owner",
    "supersedes": null,
    "ruling_id": "R-2026-0929-06",
    "class": "other",
    "question": "Are rulings kept as signed csoai.ruling/0.1 records, with an advisory reviewer panel and the owner binding until measured panel independence reaches n_eff 2?",
    "rule_applied": {
      "ref": "Proposal section 4 (A to E) of the council-mechanism note",
      "text": "Fixed rules alone set measured states. Ruling-class questions become signed records. The panel is advisory until its measured n_eff is at least 2.",
      "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/COUNCIL-MECHANISM-PROPOSAL-2026-09-29.md",
      "sha256": "a8c507c14ff1c744f625f1561ca9c6fbbfadfe3cc9ea4a49d795ed7a50841fd4"
    },
    "evidence": [
      {
        "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/COUNCIL-MECHANISM-PROPOSAL-2026-09-29.md",
        "sha256": "a8c507c14ff1c744f625f1561ca9c6fbbfadfe3cc9ea4a49d795ed7a50841fd4",
        "of": "the committed proposal section that defines csoai.ruling/0.1"
      },
      {
        "uri": "git:councilof-ai@2fe8f822cc0e4464a942262c0991c29227913b15:council-os/rulings/sources/owner-rulings-excerpt-20260929.md",
        "sha256": "55ff6af78139035cea8c1a953b32edd93ea0e73e06744dee32d2c8699374dbee",
        "of": "the committed byte-exact excerpt of the owner-rulings log this record quotes"
      }
    ],
    "rule_output": null,
    "owner_ruling_verbatim": "adopt the ruling records",
    "owner_ruling_source": {
      "verbatim_status": "QUOTED",
      "where": "the owner words relayed in the 29 Sep ruling-records lane brief; excerpt E6"
    },
    "decided_at": "2026-09-29",
    "decided_at_basis": "the date of the brief; no time recorded",
    "effective_from": "2026-09-29",
    "correction_ref": null,
    "effect": {
      "writes_measured_state": false,
      "writes_board": false,
      "note": "Adopts the record format. Sets no state; the records it creates set none either."
    },
    "signature": {
      "did": "did:web:csoai.org#board-attestation-1",
      "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
      "attestation": {
        "schema": "csoai.ruling-attestation/0.1",
        "ruling_id": "R-2026-0929-06",
        "class": "other",
        "decided_at": "2026-09-29",
        "content_id": "4d1942d82f85f44c7bd2c33d91b446493f7f0b55d4d4c9345c6319fd15a39991",
        "content_id_rule": "sha256(RFC 8785 JCS of the record without its 'signature' key)",
        "record_canonical_bytes": 1937,
        "signed_at": "2026-09-29T05:49:21Z"
      },
      "sig_ed25519": "05e77d630dfd3706828a944c83ec1ed5ad124859243cd231d624b69df44aeecc7510a66ce6ac95b7d814ae14e6d979c5339f1414b54341b67d1c7172a2858707",
      "signer_auth": "pod-token",
      "note": "Detached Ed25519 over signature.attestation (RFC 8785 JCS; identical to the board signer's sorted-key form for this ASCII object), issued through POST /api/board-sign on the pod caller token. The attestation commits to this record by content_id. The design note proposed a separate ruling key; none is minted, so this names the board key it was signed under."
    }
  }
];

export const RULINGS_INDEX: Record<string, unknown> = {
  "schema": "csoai.rulings-index/0.1",
  "read_only": true,
  "count": 8,
  "rulings": [
    {
      "ruling_id": "R-2026-0928-01",
      "class": "other",
      "decided_at": "2026-09-28T14:50Z",
      "content_id": "736e13228ffa80ef87d660021a60085f93a8a94c09f8705b8fd1927c65c4fb8a",
      "path": "/signed/rulings/R-2026-0928-01.json"
    },
    {
      "ruling_id": "R-2026-0928-02",
      "class": "naming",
      "decided_at": "2026-09-28T15:30Z",
      "content_id": "b1ca3c48728d6e04051a5960f41063612e320d8f95b3a763403fe49b366271aa",
      "path": "/signed/rulings/R-2026-0928-02.json"
    },
    {
      "ruling_id": "R-2026-0929-01",
      "class": "publication",
      "decided_at": "2026-09-29T04:00Z",
      "content_id": "0d9be062f3b26fef48a8e42a94d1da7d929b12766e731164be967180009d6846",
      "path": "/signed/rulings/R-2026-0929-01.json"
    },
    {
      "ruling_id": "R-2026-0929-02",
      "class": "other",
      "decided_at": "2026-09-29",
      "content_id": "7dc94b0de6835b83282132067c2d9751e88b1826c9fa19a4e542e4ac548436be",
      "path": "/signed/rulings/R-2026-0929-02.json"
    },
    {
      "ruling_id": "R-2026-0929-03",
      "class": "publication",
      "decided_at": "2026-09-29",
      "content_id": "0dba8f607b47c189ddb9873d54e8b1ac41042a7a5564f41feaf9198a0ea327d8",
      "path": "/signed/rulings/R-2026-0929-03.json"
    },
    {
      "ruling_id": "R-2026-0929-04",
      "class": "board-change",
      "decided_at": "2026-09-29T06:40Z",
      "content_id": "b3040810e17d49a9a922bd7d1672ef836462996400070f13c7e73393e590a341",
      "path": "/signed/rulings/R-2026-0929-04.json"
    },
    {
      "ruling_id": "R-2026-0929-05",
      "class": "publication",
      "decided_at": "2026-09-29",
      "content_id": "beaf235aabf7267378c38d6d24d56af301eb809889012f331d5d1f6f3910a87d",
      "path": "/signed/rulings/R-2026-0929-05.json"
    },
    {
      "ruling_id": "R-2026-0929-06",
      "class": "other",
      "decided_at": "2026-09-29",
      "content_id": "4d1942d82f85f44c7bd2c33d91b446493f7f0b55d4d4c9345c6319fd15a39991",
      "path": "/signed/rulings/R-2026-0929-06.json"
    }
  ],
  "signature": {
    "did": "did:web:csoai.org#board-attestation-1",
    "key_ed25519_hex": "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170",
    "attestation": {
      "schema": "csoai.rulings-index-attestation/0.1",
      "content_id": "fd6a28f979c4f1a8254b2d7b11ed9e509703a84c4aa3367ebbc54f0927c3e010",
      "content_id_rule": "sha256(RFC 8785 JCS of the index without its 'signature' key)",
      "count": 8,
      "latest_ruling_id": "R-2026-0929-06",
      "signed_at": "2026-09-29T05:54:38Z"
    },
    "sig_ed25519": "8ca472c5f70834ccee2a80452f0b8404a963efea6e25b425260475899f0bb8cddbbb6486ba34e9e341caaeb4133709d71c0e4942f938cd17babde3c0aea9480a",
    "signer_auth": "pod-token"
  }
};
