/**
 * The thirteen per-tool cards under /.well-known/agents/ and the doors they name (2026-09-22).
 *
 * WHY THIS EXISTS. Every card in public/.well-known/agents/*.json declared
 * supportedInterfaces[0].url = https://councilof.ai/api/a2a and an example of
 * `SendMessage with Part.data {"skill":"<tool>","input":{}}`, while functions/api/a2a.ts
 * SKILL_IDS never held a tool name. A caller following a card got "unknown skill" from the door
 * the card named — verified live on 2026-09-22. functions/api/a2a.test.ts only compared the
 * PUBLIC card (/.well-known/agent-card.json) with SKILL_IDS; nothing read the per-tool cards.
 *
 * The rule (memory: an A2A skill lives in four places — card, alias, SKILL_IDS, directory
 * recount): a card may name the A2A door for a skill iff the router accepts that skill. The
 * per-tool cards are MCP tools, served by tools/call at the door the fleet lock names, so they
 * now say that, and they are generated by scripts/a2a-tool-cards.mjs so the manifests, the lock
 * and the cards cannot drift apart. This file goes red if any of that stops being true.
 */
import { describe, expect, it } from "vitest";
import { readdirSync, readFileSync } from "node:fs";
import { resolve } from "node:path";
import { SKILL_IDS, onRequestPost } from "./a2a";
import LOCK from "../mcp/tool-fleet.lock.json";
// @ts-expect-error — plain ESM producer, no declaration file; vitest loads it as-is.
import { buildCards, render, A2A_DOOR } from "../../scripts/a2a-tool-cards.mjs";

const AGENTS_DIR = resolve(__dirname, "../../public/.well-known/agents");
const LOCK_ALL: string[] = [...LOCK.free, ...LOCK.paid];
const sorted = (xs: readonly string[]) => [...xs].sort();

type Iface = { url: string; protocolBinding: string; protocolVersion: string };
type Skill = { id: string; name: string; description: string; examples?: string[] };
type Card = {
  description: string;
  supportedInterfaces: Iface[];
  skills: Skill[];
  mcp_tool: string;
  paid: boolean;
  mcp_input_schema?: { required?: string[] };
};

const cardFiles = readdirSync(AGENTS_DIR).filter((f) => f.endsWith(".json") && f !== "index.json");
const cards = new Map<string, Card>(
  cardFiles.map((f) => [f, JSON.parse(readFileSync(resolve(AGENTS_DIR, f), "utf8")) as Card]),
);
const namesA2aDoor = (card: Card) => card.supportedInterfaces.some((i) => i.url === A2A_DOOR);

/** Ask the in-process router whether it accepts a skill id at all (any error other than the selector one counts as accepted). */
async function routerAccepts(skill: string): Promise<boolean> {
  const res = await onRequestPost({
    request: new Request("https://councilof.ai/api/a2a", {
      method: "POST",
      headers: { "content-type": "application/json", "a2a-version": "1.0" },
      body: JSON.stringify({
        jsonrpc: "2.0", id: 1, method: "SendMessage",
        params: { message: { messageId: `card-${skill}`, role: "ROLE_USER", parts: [{ data: { skill, input: {} } }] } },
      }),
    }),
  } as never);
  const body = (await res.json()) as { error?: { message?: string } };
  return !String(body.error?.message ?? "").startsWith("unknown skill");
}

describe("the per-tool cards are exactly the fleet lock, by name", () => {
  it("one card file per locked tool, no strays", () => {
    expect(sorted(cardFiles.map((f) => f.replace(/\.json$/, "")))).toEqual(sorted(LOCK_ALL));
  });

  it("each card's skill id, mcp_tool and file name agree, and paid matches the lock", () => {
    for (const [file, card] of cards) {
      const id = file.replace(/\.json$/, "");
      expect(card.mcp_tool, file).toBe(id);
      expect(card.skills.map((s) => s.id), file).toEqual([id]);
      expect(card.paid, `${file} paid flag`).toBe(LOCK.paid.includes(id));
    }
  });
});

describe("a card names the A2A door for a skill iff the router accepts that skill", () => {
  it("every skill on a card that names /api/a2a is in SKILL_IDS", () => {
    const lying: string[] = [];
    for (const [file, card] of cards) {
      if (!namesA2aDoor(card)) continue;
      for (const s of card.skills) if (!(SKILL_IDS as readonly string[]).includes(s.id)) lying.push(`${file}:${s.id}`);
    }
    expect(lying, "cards that point a skill at /api/a2a which the router rejects").toEqual([]);
  });

  it("the in-process router agrees with each card about whether its skill is served on /api/a2a", async () => {
    const disagreements: string[] = [];
    for (const [file, card] of cards) {
      for (const s of card.skills) {
        const accepted = await routerAccepts(s.id);
        if (accepted !== namesA2aDoor(card)) {
          disagreements.push(`${file}: router ${accepted ? "accepts" : "rejects"} ${s.id} but the card ${namesA2aDoor(card) ? "names" : "does not name"} ${A2A_DOOR}`);
        }
      }
    }
    expect(disagreements).toEqual([]);
  });

  it("a card that does not name /api/a2a carries no SendMessage example and names the locked MCP door with the MCP binding", () => {
    for (const [file, card] of cards) {
      if (namesA2aDoor(card)) continue;
      for (const s of card.skills) {
        for (const ex of s.examples ?? []) {
          expect(ex, `${file} shows an A2A SendMessage example for a skill /api/a2a does not serve`).not.toContain("SendMessage with Part.data");
        }
      }
      expect(card.supportedInterfaces.length, file).toBeGreaterThan(0);
      for (const iface of card.supportedInterfaces) {
        // A2A v1.0 §8.3.1: each interface MUST accurately declare its transport and URL. The
        // 2026-09-05 defect was /mcp declared as an A2A JSONRPC interface; it does not speak A2A.
        expect(iface.url, file).toBe(LOCK.door);
        expect(iface.protocolBinding, file).toBe("MCP");
        expect(iface.protocolVersion, file).toBeTruthy();
      }
    }
  });
});

describe("the cards are the generator's output, and the generator reads the manifests the door serves", () => {
  it("committed bytes equal scripts/a2a-tool-cards.mjs output for every card and the index", () => {
    const generated = buildCards() as Map<string, unknown>;
    const drift: string[] = [];
    for (const [file, doc] of generated) {
      const have = readFileSync(resolve(AGENTS_DIR, file), "utf8");
      if (have !== render(doc)) drift.push(file);
    }
    expect(drift, "run: node scripts/a2a-tool-cards.mjs --write").toEqual([]);
    expect(sorted([...generated.keys()])).toEqual(sorted([...cardFiles, "index.json"]));
  });

  it("each tools/call example carries every REQUIRED argument of the tool's own inputSchema", () => {
    for (const [file, card] of cards) {
      const required = card.mcp_input_schema?.required ?? [];
      const example = card.skills[0].examples?.[0] ?? "";
      expect(example, file).toContain(`"method":"tools/call"`);
      expect(example, file).toContain(`"name":"${card.mcp_tool}"`);
      for (const key of required) expect(example, `${file} example omits required ${key}`).toContain(`"${key}":"<${key}>"`);
    }
  });
});
