/**
 * GET /api/claim-maintenance-reaction — deterministic category-reaction index.
 *
 * ONE SET OF BYTES. This route serves the committed reaction-index JSON generated by
 * scripts/claim_maintenance_reaction.py from the pinned market-signal snapshot.
 * It computes no market score and makes no trademark, ownership, infringement,
 * endorsement or equivalence claim. Primitive overlap is not full-stack equivalence.
 */
import reaction from "../../public/spec/claim-maintenance/reaction-index.json";

const HEADERS = {
  "content-type": "application/json; charset=utf-8",
  "cache-control": "public, max-age=300",
  "access-control-allow-origin": "*",
  link: '<https://councilof.ai/claim-maintenance/>; rel="describedby"; type="text/html"',
  "x-claim-maintenance-spec": "https://councilof.ai/spec/claim-maintenance/v0.2/",
};

export const onRequestGet: PagesFunction = async () =>
  new Response(JSON.stringify(reaction, null, 2), {
    status: 200,
    headers: HEADERS,
  });

export const onRequestOptions: PagesFunction = async () =>
  new Response(null, {
    status: 204,
    headers: {
      ...HEADERS,
      "access-control-allow-methods": "GET, OPTIONS",
      "access-control-allow-headers": "*",
    },
  });
