"""Kaggle adapter: real committed lock -> INDEXED envelopes; kernel harvest -> QUARANTINED; replay is identical.

Run: python3 -m pytest scripts/adapters/test_kaggle_envelopes.py -q
 or: python3 -m unittest discover -s scripts/adapters -p test_kaggle_envelopes.py
"""
from __future__ import annotations

import hashlib
import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]
sys.path.insert(0, str(HERE.parent))

from adapters import kaggle_envelopes as ke  # noqa: E402
from adapters.connector_envelope import validate  # noqa: E402

FIXTURE = HERE / "fixtures" / "kaggle-envelopes" / "fleet-lock.json"
LOCK = ROOT / ke.LOCK_REL
PINNED_REVISION = "UNCHECKABLE"  # fixture pins bytes independent of edits to the adapter source


def load_kernel():
    """The kernel's own card maker, so harvest inputs are the producer's shape, not a guess."""
    path = ROOT / "gpu-offload" / "kaggle-community-cells" / "kaggle_community_cells.py"
    spec = importlib.util.spec_from_file_location("kaggle_community_cells", path)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def fixture_document(raw: bytes) -> dict:
    envs = ke.envelopes_from_lock(raw, ke.LOCK_REL, revision=PINNED_REVISION)
    counts: dict[str, int] = {}
    for e in envs:
        counts[e["lifecycle_state"]] = counts.get(e["lifecycle_state"], 0) + 1
    return {
        "note": "Generated by scripts/adapters/test_kaggle_envelopes.py from the committed lock bytes "
                "(producer_revision pinned to UNCHECKABLE). INDEXED is not MEASURED: the lock is a queue.",
        "input": {"path": ke.LOCK_REL, "sha256": hashlib.sha256(raw).hexdigest(), "bytes": len(raw)},
        "n_envelopes": len(envs),
        "lifecycle_counts": counts,
        "envelopes_jsonl_sha256": hashlib.sha256(ke.to_jsonl(envs)).hexdigest(),
        "first": envs[:3],
    }


class FromCommittedLock(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.raw = LOCK.read_bytes()
        cls.lock = json.loads(cls.raw)
        cls.envs = ke.envelopes_from_lock(cls.raw)

    def test_one_envelope_per_row_all_valid(self):
        self.assertEqual(len(self.envs), len(self.lock["models"]))
        self.assertEqual(len(self.envs), self.lock["n_locked"])
        for e in self.envs:
            self.assertEqual(validate(e), [], e["subject"]["id"])

    def test_index_only_nothing_measured(self):
        self.assertEqual(self.lock["n_measured"], 0)
        self.assertEqual({e["lifecycle_state"] for e in self.envs}, {"INDEXED"})
        self.assertTrue(all(e["measurement"] is None and e["error"] is None for e in self.envs))

    def test_artifact_hash_is_the_real_bytes(self):
        want = hashlib.sha256(self.raw).hexdigest()
        self.assertTrue(all(e["artifact"]["sha256"] == want for e in self.envs))
        self.assertTrue(all(e["artifact"]["bytes"] == len(self.raw) for e in self.envs))

    def test_observed_at_is_the_lock_time_not_now(self):
        self.assertEqual({e["observed_at"] for e in self.envs}, {self.lock["as_of"]})

    def test_pointer_resolves_to_the_row(self):
        for e in self.envs[:25]:
            idx = int(e["artifact"]["pointer"].rsplit("/", 1)[1])
            self.assertEqual(e["subject"]["id"], "kaggle:" + self.lock["models"][idx]["ref"])

    def test_idempotency_keys_unique_per_subject(self):
        keys = [e["idempotency_key"] for e in self.envs]
        refs = [m["ref"] for m in self.lock["models"]]
        self.assertEqual(len(set(keys)), len(set(refs)))

    def test_fixture_matches_committed_bytes(self):
        want = json.loads(FIXTURE.read_text())
        self.assertEqual(fixture_document(self.raw), want,
                         "fixture drifted; regenerate: python3 scripts/adapters/test_kaggle_envelopes.py --write-fixture")

    def test_internal_lock_shape_also_reads(self):
        other = ROOT / "locks" / "KAGGLE.lock.json"
        envs = ke.envelopes_from_lock(other.read_bytes(), "locks/KAGGLE.lock.json")
        self.assertEqual(len(envs), json.loads(other.read_bytes())["n_locked"])
        self.assertEqual({e["lifecycle_state"] for e in envs}, {"INDEXED"})
        self.assertTrue(all(validate(e) == [] for e in envs))


class Replay(unittest.TestCase):
    def test_twice_identical_envelopes_and_keys(self):
        raw = LOCK.read_bytes()
        a = ke.envelopes_from_lock(raw)
        b = ke.envelopes_from_lock(raw)
        self.assertEqual(ke.to_jsonl(a), ke.to_jsonl(b))
        self.assertEqual([e["idempotency_key"] for e in a], [e["idempotency_key"] for e in b])

    def test_cli_twice_byte_identical(self):
        with tempfile.TemporaryDirectory() as d:
            outs = []
            for n in (1, 2):
                out = Path(d) / f"run{n}.jsonl"
                p = subprocess.run([sys.executable, str(HERE / "kaggle_envelopes.py"), "--out", str(out)],
                                   capture_output=True, text=True)
                self.assertEqual(p.returncode, 0, p.stderr)
                outs.append(out.read_bytes())
            self.assertEqual(outs[0], outs[1])
            self.assertEqual(outs[0].count(b"\n"), json.loads(LOCK.read_bytes())["n_locked"])


class LockControls(unittest.TestCase):
    def lock_bytes(self, **row_over):
        lock = json.loads(LOCK.read_bytes())
        lock["models"] = [dict(lock["models"][0], **row_over)]
        return json.dumps(lock).encode()

    def test_row_claiming_measurement_becomes_uncheckable(self):
        [e] = ke.envelopes_from_lock(self.lock_bytes(status="MEASURED"))
        self.assertEqual(e["lifecycle_state"], "UNCHECKABLE")
        self.assertEqual(e["error"]["code"], "LOCK_ROW_CLAIMS_MEASUREMENT")
        self.assertIsNone(e["measurement"])
        self.assertEqual(validate(e), [])

    def test_row_without_ref(self):
        [e] = ke.envelopes_from_lock(self.lock_bytes(ref=""))
        self.assertEqual(e["error"]["code"], "ROW_WITHOUT_REF")
        self.assertEqual(validate(e), [])

    def test_whole_input_refusals(self):
        lock = json.loads(LOCK.read_bytes())
        for broken in (b"not json", json.dumps(dict(lock, fleet="HF2200")).encode(),
                       json.dumps(dict(lock, as_of="yesterday")).encode(),
                       json.dumps(dict(lock, models=[])).encode()):
            with self.assertRaises(ke.InputRefused):
                ke.envelopes_from_lock(broken)


class FromKernelHarvest(unittest.TestCase):
    """No harvested kernel output is committed; inputs come from the kernel's own make_unsigned."""

    @classmethod
    def setUpClass(cls):
        cls.kernel = load_kernel()

    def harvest(self, d: Path, cards: dict[str, bytes], listed: list[str] | None = None):
        for name, raw in cards.items():
            (d / name).write_bytes(raw)
        report = {"kind": "csoai.kaggle-community-cells/0.1", "generated_at": "2026-09-14T10:11:12.345678+00:00",
                  "cards": listed if listed is not None else sorted(cards)}
        (d / ke.HARVEST_REPORT).write_text(json.dumps(report))

    def card(self, **over):
        k = self.kernel
        kw = dict(axis="jail", model="kaggle:gemma-2b", n=20, accuracy=0.55, route="kaggle-community")
        kw.update(over)
        wrap = k.make_unsigned(**kw)
        return k.filename_for(wrap), (json.dumps(wrap, separators=(",", ":")) + "\n").encode()

    def test_honest_card_is_quarantined_with_hash_and_no_value(self):
        name, raw = self.card()
        with tempfile.TemporaryDirectory() as d:
            self.harvest(Path(d), {name: raw})
            [e] = ke.envelopes_from_harvest(Path(d), "kaggle-harvest/run1")
            again = ke.envelopes_from_harvest(Path(d), "kaggle-harvest/run1")
        self.assertEqual(validate(e), [])
        self.assertEqual(e["lifecycle_state"], "QUARANTINED")
        self.assertIsNone(e["error"])
        self.assertIsNone(e["measurement"])
        self.assertEqual(e["artifact"]["sha256"], hashlib.sha256(raw).hexdigest())
        self.assertEqual(e["observed_at"], "2026-09-14T10:11:12.345678Z")
        self.assertEqual(e["subject"]["id"], "kaggle-community:kaggle:gemma-2b#jail")
        self.assertEqual(ke.to_jsonl([e]), ke.to_jsonl(again))

    def test_committed_hf_router_fixture_is_not_a_kaggle_result(self):
        src = ROOT / "gpu-offload" / "kaggle-community-cells" / "fixtures" / "unsigned-sample.json"
        with tempfile.TemporaryDirectory() as d:
            self.harvest(Path(d), {"unsigned-affect-sample.json": src.read_bytes()})
            [e] = ke.envelopes_from_harvest(Path(d), "kaggle-harvest/run1")
        self.assertEqual((e["lifecycle_state"], e["error"]["code"]), ("QUARANTINED", "NOT_KAGGLE_ROUTE"))
        self.assertEqual(validate(e), [])

    def test_tampered_body_rejected(self):
        name, raw = self.card()
        wrap = json.loads(raw)
        wrap["body"]["accuracy"] = 0.99
        with tempfile.TemporaryDirectory() as d:
            self.harvest(Path(d), {name: json.dumps(wrap).encode()})
            [e] = ke.envelopes_from_harvest(Path(d), "kaggle-harvest/run1")
        self.assertEqual(e["error"]["code"], "CARD_REJECTED")
        self.assertIn("!= id", e["error"]["detail"])
        self.assertEqual(validate(e), [])

    def test_listed_but_missing_card(self):
        with tempfile.TemporaryDirectory() as d:
            self.harvest(Path(d), {}, listed=["unsigned-jail-000000000000.json"])
            [e] = ke.envelopes_from_harvest(Path(d), "kaggle-harvest/run1")
        self.assertEqual((e["lifecycle_state"], e["error"]["code"]), ("UNCHECKABLE", "CARD_MISSING"))
        self.assertIsNone(e["artifact"]["sha256"])
        self.assertEqual(validate(e), [])

    def test_path_escape_refused(self):
        with tempfile.TemporaryDirectory() as d:
            self.harvest(Path(d), {}, listed=["../unsigned-x.json"])
            [e] = ke.envelopes_from_harvest(Path(d), "kaggle-harvest/run1")
        self.assertEqual(e["error"]["code"], "CARD_NAME_REFUSED")

    def test_report_without_utc_time_refused(self):
        with tempfile.TemporaryDirectory() as d:
            (Path(d) / ke.HARVEST_REPORT).write_text(json.dumps(
                {"kind": "csoai.kaggle-community-cells/0.1", "generated_at": "2026-09-14 10:00", "cards": []}))
            with self.assertRaises(ke.InputRefused):
                ke.envelopes_from_harvest(Path(d), "kaggle-harvest/run1")


if __name__ == "__main__":
    if sys.argv[1:] == ["--write-fixture"]:
        FIXTURE.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE.write_text(json.dumps(fixture_document(LOCK.read_bytes()), indent=2, ensure_ascii=False) + "\n")
        print(f"wrote {FIXTURE.relative_to(ROOT)}")
    else:
        unittest.main()
