#!/usr/bin/env python3
"""generate-body-runbook.py — H4: the body that runs itself, DERIVED from .github/workflows.

Reads the actual workflows (via git objects so it works in sparse worktrees),
maps them onto the measurement pipeline stages, and writes
docs/operations/BODY-RUNBOOK.md. Every row: workflow name, mechanism, cadence,
the stage it serves. No invented cron.
"""

from __future__ import annotations

import json
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2] if __file__.startswith("/") else Path.cwd()
OUT = ROOT / "docs" / "operations" / "BODY-RUNBOOK.md"


def git_lines(*args: str) -> list[str]:
    out = subprocess.run(["git", *args], capture_output=True, text=True, timeout=30)
    return out.stdout.splitlines()


def head_text(rel: str) -> str:
    out = subprocess.run(["git", "show", f"HEAD:{rel}"], capture_output=True, text=True, timeout=30)
    return out.stdout if out.returncode == 0 else ""


# stage -> workflow-name matchers (by keywords in workflow names)
STAGES = {
    "measure": ["hf", "mill", "mine", "eat", "census", "watch", "provider"],
    "sign": ["sign", "claims", "e2e", "verify", "reject"],
    "flip": ["flip", "land", "hub-queue"],
    "anchor": ["root", "watcher-pub", "witness"],
    "deliver": ["deploy", "csoai-site"],
    "ledger": ["evidence", "protect", "drift", "inspect", "honest", "registration"],
    "report": ["nightly", "report", "board", "regulator", "reg-watch", "printer"],
    "guard": ["guard", "gate", "selftest", "crawler"],
}


def stage_for(name: str) -> str:
    low = name.lower()
    for stage, kws in STAGES.items():
        if any(k in low for k in kws):
            return stage
    return "other"


def main() -> None:
    rels = git_lines("ls-tree", "-r", "--name-only", "HEAD", ".github/workflows/")
    rows = []
    for rel in rels:
        if not rel.endswith(".yml"):
            continue
        text = head_text(rel)
        name_m = re.search(r"^name:\s*(.+)$", text, re.M)
        name = name_m.group(1).strip() if name_m else rel.split("/")[-1]
        # cadence
        cron_m = re.findall(r"cron:\s*['\"]?([^'\"\n]+)['\"]?", text)
        schedule = cron_m[0].strip() if cron_m else ""
        period = re.search(r"periodic:\s*([\w-]+)", text)
        cadence = f"cron {schedule}" if schedule else (f"periodic {period.group(1)}" if period else "on push / manual")
        on_m = re.search(r"on:\s*\n\s*(push|pull_request|schedule|workflow_dispatch)", text) or re.search(r"on:\s*(push|pull_request)", text)
        trigger = on_m.group(1) if on_m else "push"
        stage = stage_for(name)
        rows.append({"file": rel, "name": name, "cadence": cadence, "trigger": trigger, "stage": stage})

    rows.sort(key=lambda r: (list(STAGES.keys()).index(r["stage"]) if r["stage"] in STAGES else 99, r["name"]))

    md = [
        "# BODY-RUNBOOK — the estate that runs itself (derived from .github/workflows)",
        "",
        f"> Generated by scripts/badger/generate-body-runbook.py on {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}.",
        "> Row-by-row: workflow file (HEAD), cadence read from the file, the pipeline stage it serves.",
        "> Nothing here is typed from memory. Rerun the generator after any workflow change.",
        "",
        "| stage | workflow | cadence | trigger | file |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        md.append(f"| {r['stage']} | {r['name']} | {r['cadence']} | {r['trigger']} | `{r['file']}` |")

    md += [
        "",
        "## Pipeline the workflows serve",
        "",
        "request (free door/402) → measure → sign → flip → anchor → deliver → ledger → report",
        "",
        "- **measure** — the mills and censuses (HF inference mill, hub-queue mill, mine-harness, auto-eat-sign, census-delta, provider-watch, reg-watch).",
        "- **sign** — OIDC signer + claims/e2e + reject-335 (serious: protects verified corpus).",
        "- **flip** — hub-queue-flip/land: promote staged leaves into the published queue.",
        "- **anchor** — public-root (+ watcher): 4×/day root ceremony; witness integrity fails closed.",
        "- **deliver** — deploy (Build + deploy site, both domains; scheduled cron 20 */3 * * *) + csoai-site-deploy.",
        "- **ledger** — evidence-smoke, drift-guard, protect-verified-*, inspect-adoption, honest-board-floor.",
        "- **report** — nightly_board, regulator-axis-map, reg-watch, printer-board, provider-watch.",
        "- **guard** — lane-guard, conflict-guard, one-door-guard, crawler-view, claims-e2e, eval-ci, selftest.",
        "",
        "## How to read a row",
        "",
        "1. `cadence` is read from the workflow's own `schedule:`/`periodic:` block — if a stage shows",
        "   'on push / manual' it was never scheduled; that is honest, not a gap.",
        "2. `trigger` is the `on:` key. `schedule` workflows only run at their cron.",
        "3. Live status per workflow: `curl https://councilof.ai/api/body-state` (last run, last success, last failure).",
        "",
        "## Stage truth",
        "",
        "- The 402 rail answers at `/api/x402` (free door `/.well-known/x402`). Paid artefacts unlock on settle.",
        "- `measurement, not certification` — every stage publishes evidence, never conclusions.",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(md))
    print(f"BODY-RUNBOOK written: {OUT}")
    print(f"  workflows: {len(rows)}")
    for r in rows:
        print(f"  [{r['stage']:<7}] {r['name'][:48]:<48} {r['cadence']}")


if __name__ == "__main__":
    main()
