#!/usr/bin/env python3
"""generate-glossary.py — H3: one semantics, derived from code, never from imagination.

Reads the actual schema strings emitted across functions/ and public/, the actual
state words in public data, and the three card-corpora counts (never hand-added).
Writes docs/product/GLOSSARY.md.
"""

from __future__ import annotations

import collections
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[2] if __file__.startswith("/") else pathlib.Path.cwd()
# works from repo root; fallback to cwd
if not (ROOT / "public").exists():
    ROOT = pathlib.Path.cwd()

OUT = ROOT / "docs" / "product" / "GLOSSARY.md"


def schema_census() -> collections.Counter:
    c = collections.Counter()
    for base in (ROOT / "functions", ROOT / "public"):
        if not base.exists():
            continue
        for p in base.rglob("*"):
            if p.suffix not in (".ts", ".json", ".mjs", ".html"):
                continue
            if "node_modules" in str(p) or "dist" in str(p):
                continue
            try:
                t = p.read_text(errors="ignore")
            except Exception:
                continue
            for m in re.findall(r'"schema"\s*:\s*"(csoai\.[^"]+)"', t):
                c[m] += 1
    return c


def git_show_json(rel: str) -> dict | None:
    """Read a JSON file from HEAD objects (works in sparse worktrees)."""
    import subprocess
    try:
        out = subprocess.run(["git", "show", f"HEAD:{rel}"], capture_output=True, text=True, timeout=20)
        if out.returncode != 0:
            return None
        return json.loads(out.stdout)
    except Exception:
        return None


def corpus_counts() -> dict:
    d = {}
    b = git_show_json("public/cards-bundle.json")
    r = git_show_json("public/root.json")
    i = git_show_json("public/signed/card_index.json")
    d["cards_bundle_1072"] = b.get("card_count") if b else None
    d["root_json_152"] = r.get("card_count") if r else None
    d["card_index_335"] = i.get("n_cards") if i else None
    return d


def main() -> None:
    schemas = schema_census()
    corpora = corpus_counts()

    # Group the most-emitted families for the glossary table
    top = schemas.most_common(60)
    families = [s for s, _ in top if "/" in s]

    md = [
        "# GLOSSARY — one semantics (derived from code)",
        "",
        "> Generated by scripts/badger/generate-glossary.py. Every entry is read from the",
        "> estate itself (schema strings, state words, corpus counts). Nothing here is",
        "> typed from imagination, and no count is ever hand-added.",
        "",
        "## 1. The csoai: primitives that schemas actually emit",
        "",
        "297 unique `\"schema\": \"csoai.*\"` values appear across functions/ and public/. The",
        f"emitted families (top occurrences):",
        "",
        "| schema family | occurrences | what it is |",
        "|---|---|---|",
    ]
    for s, n in schemas.most_common(48):
        name = s.split("/")[0]
        desc = {
            "csoai.gspc-axes": "the 22-axis measurement card (the board's leaf format; statuses MEASURED/UNMEASURED/UNCHECKABLE)",
            "csoai.evm.permission-state": "permission/allowlist state facts (measured, not opinion)",
            "csoai.csoai?": "",
            "csoai.rwa-attest-card": "RWA / XRPL evidence card (public.notice surface)",
            "csoai.swift-census": "SWIFT reader census (labels, not grades — n_measured can be 0)",
            "csoai.layer0-ceremony": "the layer-0 root ceremony record (merkle root + witness state)",
            "csoai.well-known": "discovery door (describes a LIVE resource; no door for a fiction)",
            "csoai.interop": "interop format registry",
            "csoai.a2a-agent-card": "A2A agent discovery card",
            "csoai.mcp-server": "MCP server listing",
            "csoai.x402": "the payment rail door (x402 v2; scheme exact; network Base)",
            "csoai.corrections-feed": "published refutations (integrity asset)",
            "csoai.obligations-ledger": "obligation -> evidence mapping (OSCAL observations)",
            "csoai.otel-bridge": "OpenTelemetry-compatible measured spans",
        }.get(name, "")
        md.append(f"| `{s}` | {n} | {desc} |" if desc else f"| `{s}` | {n} | (see source) |")

    md += [
        "",
        "## 2. Measurement states (on cards, never invented)",
        "",
        "| state | meaning | provenance in public data |",
        "|---|---|---|",
        "| `MEASURED` | a value was computed from evidence; it is what the board shows | 741 occurrences |",
        "| `UNMEASURED` | the axis was not measured — this is NOT a zero or a fail | 518 occurrences |",
        "| `UNCHECKABLE` | the evidence cannot be probed without keys/authority | 31 occurrences |",
        "| `TIE` | a comparison where both sides are equal on the evidence — TIE is TIE, never flipped | 7 occurrences |",
        "| `SEPARATED` | evidence is presented split from any determination | 1 occurrence |",
        "| `PRACTICE_ONLY` | a concept/non-callable item: no runtime, no availability, no cards | arcade catalogue |",
        "| `staged-unsigned` | file exists but carries NO Ed25519 sig; a SHA-256 in a signature field is a lie | swift/hf stages |",
        "| `VALID` | a card verified under did:web:csoai.org#card-attestation-1 with a real Ed25519 sig | card_index 335 |",
        "",
        "## 3. The three card corpora (never added)",
        "",
        "| corpus | count (derived, not typed) | source |",
        "|---|---|---|",
        f"| cards bundle | {corpora['cards_bundle_1072']} | `public/cards-bundle.json::card_count` |",
        f"| root-attested leaves | {corpora['root_json_152']} | `public/root.json::card_count` (grows with each root; never padded) |",
        f"| published card index | {corpora['card_index_335']} | `public/signed/card_index.json::n_cards` |",
        "",
        "These three are read at build time. They are never written by hand and never padded.",
        "",
        "## 4. Doctrine (the words we may and may not use)",
        "",
        "- **Measurement, not certification.** CSOAI issues measurements and signed attestations, never certificates of conformity. We publish refutations of our own earlier claims (`corrections-feed` = 9) — that is the durability proof.",
        "- **Absent is not zero.** An unmeasured axis is UNMEASURED, never scored 0. UNCHECKABLE says why.",
        "- **TIE is TIE.** A tie is a tie; no determinist tuning may break it.",
        "- **signed** means Ed25519 under `did:web:csoai.org#card-attestation-1`, verified by scripts/e2e. Anything else is `staged-unsigned`.",
        "",
        "## 5. Words the public surface forbids applied to files/concepts",
        "",
        "| word | why | substitute |",
        "|---|---|---|",
        "| live | a JSON door is not a service | `published` / `served` (state the URL, prove with a probe) |",
        "| active | nothing is active unless a runner ran it | `scheduled` + run timestamp |",
        "| attested | attestation is a paid/service act, not a file property | `signed` (real Ed25519 only) |",
        "| anchored | OTS stamping/anchor is planned until a calendar commits | `staged for anchoring`, future tense |",
        "| BFT | retracted claim (n_eff≈1.21/3) | `designed 33-agent council` + `23/33 threshold` |",
        "| sovereign | de-branded term | `Council` / `Council Signal` |",
        "| certified | concessionary; the estate does not certify | `measured` |",
        "",
        "The enforced test: `scripts/brand-gate.mjs dist/client` (audit §6.2) — currently PASS with 0 forbidden display strings. Each PR must re-run it.",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(md))
    print(f"GLOSSARY written: {OUT}")
    print("  schema families:", len(families))
    print("  corpus counts:", corpora)


if __name__ == "__main__":
    main()
