#!/usr/bin/env python3
"""generate-bank-api.py — build /api/bank-complete + /api/eu-ai-act readers.

Zero-drift pattern: the function file embeds the REAL registry snapshot at build
time (same convention as _obligations.ts). Functions:
  - functions/api/_bank-registry-snapshot.ts  (data as TS constant)
  - functions/api/bank-complete.ts            (GET -> snapshot + provenance)
  - functions/api/eu-ai-act.ts                (GET -> evidence summary, honest labels)
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REGISTRY = ROOT / "public" / "interop" / "bank-registry.json"
FN = ROOT / "functions" / "api"

DATA = json.loads(REGISTRY.read_text())
banks = DATA.get("banks", [])
total = DATA.get("total_banks", len(banks))
records = DATA.get("total_records", 0)

# _bank-registry-snapshot.ts
snap_ts = "// Generated by scripts/badger/generate-bank-api.py — do not edit by hand.\n" \
          "// Zero-drift: matches public/interop/bank-registry.json at generation time.\n\n" \
          "export const BANK_REGISTRY_SNAPSHOT = " + json.dumps(DATA, indent=2) + " as const;\n"
(FN / "_bank-registry-snapshot.ts").write_text(snap_ts)
print(f"✓ functions/api/_bank-registry-snapshot.ts ({total} banks, {records} records)")

# bank-complete.ts
bank_fn = '''/**
 * /api/bank-complete — evidence-derived reader for the bank × chain × stablecoin census.
 * Data is embedded at build time (zero-drift with public/interop/bank-registry.json).
 */
import { BANK_REGISTRY_SNAPSHOT as d } from "./_bank-registry-snapshot";

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body, null, 2), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
      "access-control-allow-origin": "*",
    },
  });

export const onRequestGet: PagesFunction = async () => {
  return json({
    schema: "csoai.bank-complete/0.1",
    status: "READER",
    writes_board: false,
    total_banks: d.total_banks,
    total_records: d.total_records,
    banks: d.banks,
    verify: "https://councilof.ai/gspc-verify",
    honesty: "Measurement, not certification. Verification is free forever.",
  });
};

export const onRequestOptions: PagesFunction = async () => {
  return new Response(null, { status: 204 });
};
'''
(FN / "bank-complete.ts").write_text(bank_fn)
print(f"✓ functions/api/bank-complete.ts")

# eu-ai-act.ts
eu_fn = '''/**
 * /api/eu-ai-act — evidence summary for the EU AI Act regime (Art 50, high-risk, GPAI).
 * Obligation map is the same one the evidence-bundle assembler uses (see ./_obligations).
 */
import { OBLIGATIONS } from "./_obligations";

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body, null, 2), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
      "access-control-allow-origin": "*",
    },
  });

export const onRequestGet: PagesFunction = async () => {
  const items = Object.values(OBLIGATIONS).map((o) => ({
    id: o.id,
    control_id: o.control_id,
    title: o.title,
    regulator: o.regulator,
    counsel_confirmed: o.counsel_confirmed,
    honesty: o.honesty || null,
  }));
  return json({
    schema: "csoai.eu-ai-act/0.1",
    status: "READER",
    writes_board: false,
    total_obligations: items.length,
    obligations: items,
    doors: [
      "https://councilof.ai/.well-known/eu-ai-act.json",
      "https://councilof.ai/.well-known/eu-ai-act-art50.json",
      "https://councilof.ai/.well-known/eu-ai-act-high-risk.json",
      "https://councilof.ai/.well-known/eu-ai-act-gpai.json",
    ],
    honesty: "Evidence bundles attach cards as OSCAL observations, never as satisfied/not-satisfied findings.",
  });
};

export const onRequestOptions: PagesFunction = async () => {
  return new Response(null, { status: 204 });
};
'''
(FN / "eu-ai-act.ts").write_text(eu_fn)
print(f"✓ functions/api/eu-ai-act.ts")

print("done")
