#!/usr/bin/env python3
"""Truth gate for the API capability records generated by monorepo-fill."""

from __future__ import annotations

import json
import os
import re
import runpy
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
INTEROP = ROOT / "public" / "interop"
GENERATOR = ROOT / "scripts" / "badger" / "csoai-monorepo-fill.py"

EXPECTED = {
    "anchor.json": ("NOT_IMPLEMENTED", [], None),
    "feed.json": ("LIVE", ["GET"], "/api/feed.xml"),
    "revenue-all.json": ("NOT_IMPLEMENTED", [], None),
    "revenue-month.json": ("NOT_IMPLEMENTED", [], None),
    "revenue-today.json": ("NOT_IMPLEMENTED", [], None),
    "revenue-week.json": ("NOT_IMPLEMENTED", [], None),
    "checkout.json": ("NOT_CONFIGURED", ["POST"], "/api/checkout"),
    "report.json": ("NOT_IMPLEMENTED", ["GET", "POST"], "/api/report"),
    "verify-batch.json": ("NOT_IMPLEMENTED", ["GET"], "/api/verify-batch"),
    "verify-card.json": ("NOT_IMPLEMENTED", ["GET"], "/api/verify-card"),
    "decide.json": ("NOT_IMPLEMENTED", ["GET"], "/api/decide"),
    "include.json": ("NOT_IMPLEMENTED", ["GET"], "/api/include"),
    "otel.json": ("UNCHECKABLE", ["GET"], "/api/otel"),
    "compute.json": ("UNCHECKABLE", ["GET"], "/api/compute"),
    "challenge.json": ("NOT_CONFIGURED", ["GET", "POST"], "/api/challenge"),
}

HANDLERS = {
    "feed.json": "functions/api/feed.xml.ts",
    "checkout.json": "functions/api/checkout.ts",
    "report.json": "functions/api/report.ts",
    "verify-batch.json": "functions/api/verify-batch.ts",
    "verify-card.json": "functions/api/verify-card.ts",
    "decide.json": "functions/api/decide.ts",
    "include.json": "functions/api/include.ts",
    "otel.json": "functions/api/otel.ts",
    "compute.json": "functions/api/compute.ts",
    "challenge.json": "functions/api/challenge.ts",
}


class InteropApiContractTruthTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        original_cwd = Path.cwd()
        try:
            os.chdir(ROOT)
            cls.generator = runpy.run_path(str(GENERATOR))
        finally:
            os.chdir(original_cwd)

    def test_generator_and_checked_in_set_are_exactly_the_audited_set(self) -> None:
        self.assertEqual(set(EXPECTED), set(self.generator["AUDITED_API_CONTRACTS"]))

        build = self.generator["build_audited_api_spec"]
        for slug in EXPECTED:
            with self.subTest(slug=slug):
                document = json.loads((INTEROP / slug).read_text(encoding="utf-8"))
                self.assertRegex(document["as_of"], r"^\d{8}T\d{6}Z$")
                self.assertEqual(document, build(slug, document["as_of"]))

    def test_lifecycle_methods_and_paths_match_reviewed_handlers(self) -> None:
        for slug, (state, methods, path) in EXPECTED.items():
            with self.subTest(slug=slug):
                document = json.loads((INTEROP / slug).read_text(encoding="utf-8"))
                self.assertEqual("csoai.api-capability-state/0.2", document["schema"])
                self.assertEqual(state, document["state"])
                self.assertEqual(methods, document["transport"]["methods"])
                self.assertEqual(path, document["transport"]["path"])
                self.assertEqual(
                    "api-contract" if state == "LIVE" else "quarantined-api-capability",
                    document["kind"],
                )

        for slug, relative_handler in HANDLERS.items():
            with self.subTest(handler=relative_handler):
                source = (ROOT / relative_handler).read_text(encoding="utf-8")
                exported_methods = sorted(re.findall(r"export const onRequest(Get|Post)", source))
                self.assertEqual(sorted(EXPECTED[slug][1]), [method.upper() for method in exported_methods])

        for slug in set(EXPECTED) - set(HANDLERS):
            with self.subTest(absent_handler=slug):
                self.assertFalse((ROOT / "functions" / "api" / slug.replace(".json", ".ts")).exists())

    def test_quarantined_records_do_not_advertise_success_payment_or_proofs(self) -> None:
        for slug, (state, _, _) in EXPECTED.items():
            document = json.loads((INTEROP / slug).read_text(encoding="utf-8"))
            capabilities = document["capabilities"]
            with self.subTest(slug=slug):
                self.assertFalse(capabilities["persists_requests"])
                self.assertFalse(capabilities["signed_output"])
                self.assertFalse(capabilities["anchors_output"])
                self.assertFalse(capabilities["payment_required"])
                self.assertFalse(capabilities["writes_measurement_board"])

                statuses = {
                    outcome["http_status"]
                    for outcome in document["transport"]["outcomes"]
                    if "http_status" in outcome
                }
                self.assertNotIn(402, statuses)
                if state != "LIVE":
                    self.assertNotIn(200, statuses)

        feed = json.loads((INTEROP / "feed.json").read_text(encoding="utf-8"))
        self.assertEqual({200}, {item["http_status"] for item in feed["transport"]["outcomes"]})
        self.assertEqual("application/rss+xml; charset=utf-8", feed["transport"]["outcomes"][0]["media_type"])

        challenge = json.loads((INTEROP / "challenge.json").read_text(encoding="utf-8"))
        self.assertTrue(challenge["capabilities"]["accepts_writes"])
        self.assertFalse(challenge["output"]["stored"])
        self.assertFalse(challenge["output"]["publicly_verifiable_signature"])


if __name__ == "__main__":
    unittest.main()
