"""LlamaIndex tool spec for the GSPC board. Generated by scripts/harness-x/render.mjs."""
from __future__ import annotations

from typing import Optional

from llama_index.core.tools.tool_spec.base import BaseToolSpec

from ._board import TOOL_DESCRIPTION, read_board


class CSOAIGSPCToolSpec(BaseToolSpec):
    spec_functions = ["gspc_board"]

    def gspc_board(self, axis: Optional[str] = None) -> dict:
        return read_board(axis)

    gspc_board.__doc__ = TOOL_DESCRIPTION
