#!/usr/bin/env node
/**
 * build.mjs — the ONE build step, and it is tiny.
 *
 * The extension verifies cards with the repo's single shared implementation,
 * functions/_lib/cardVerify.ts (the same module /gspc-verify and the /mcp
 * `verify_card` tool use). That file is TypeScript; a Chrome extension loads
 * plain JS. So this script transpiles it — nothing else — into lib/cardVerify.mjs.
 *
 * No bundling of third-party code, no minification, no other inputs. The output
 * is committed so `Load unpacked` works from a clean checkout; test/twin.test.mjs
 * rebuilds it into a temp dir and fails if the committed bytes have drifted from
 * the source, so the copy can never silently diverge from the site's verifier.
 *
 *   node extensions/chrome-gspc-verify/scripts/build.mjs [--out <dir>]
 */
import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
export const EXT_ROOT = path.resolve(here, "..");
export const REPO_ROOT = path.resolve(EXT_ROOT, "../..");
export const SOURCE = path.join(REPO_ROOT, "functions/_lib/cardVerify.ts");

export async function buildVerifier(outDir = path.join(EXT_ROOT, "lib")) {
  const outfile = path.join(outDir, "cardVerify.mjs");
  await build({
    absWorkingDir: REPO_ROOT, // deterministic: esbuild writes input paths relative to this
    entryPoints: [SOURCE],
    outfile,
    format: "esm",
    platform: "browser",
    target: "es2022",
    bundle: true, // cardVerify.ts imports nothing; bundle:true only strips the TS types
    minify: false,
    sourcemap: false,
    legalComments: "inline",
    banner: {
      js:
        "// GENERATED by extensions/chrome-gspc-verify/scripts/build.mjs from\n" +
        "// functions/_lib/cardVerify.ts — do not edit; edit the source and rebuild.\n",
    },
    logLevel: "silent",
  });
  return outfile;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const i = process.argv.indexOf("--out");
  const out = i > 0 ? path.resolve(process.argv[i + 1]) : undefined;
  const f = await buildVerifier(out);
  console.log("built", path.relative(process.cwd(), f));
}
