#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
/**
 * Producer for the panel bundle.
 *   1. vendor public/signed/verify-card.mjs (everything above its CLI block) into
 *      src/verify-card.vendored.js, so the browser runs the SAME verifier the site publishes;
 *   2. bundle src/index.js with esbuild (ESM, minified, no eval, no external imports);
 *   3. refuse if the gzipped bundle is over 60 KB;
 *   4. write the published copy to public/panel/gspc-panel.js and its sha256 beside it.
 * `--check` rebuilds in memory and fails if either committed file differs (drift guard).
 */
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { gzipSync } from "node:zlib";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkg = resolve(here, "..");
const repo = resolve(pkg, "../..");
const check = process.argv.includes("--check");
const LIMIT = 60 * 1024;
const sha = (b) => createHash("sha256").update(b).digest("hex");

const verifierSrcPath = resolve(repo, "public/signed/verify-card.mjs");
const verifierSrc = readFileSync(verifierSrcPath, "utf8");
const cut = verifierSrc.indexOf("// ---------------------------------------------------------------- CLI");
if (cut < 0) throw new Error("verify-card.mjs: CLI marker not found; the vendoring rule needs updating");
const vendored =
  `// GENERATED by packages/gspc-panel/scripts/build.mjs from public/signed/verify-card.mjs\n` +
  `// (source sha256 ${sha(verifierSrc)}), everything above its CLI block. Do not hand-edit.\n` +
  verifierSrc.slice(0, cut).replace(/^#!.*\n/, "");
const vendoredPath = resolve(pkg, "src/verify-card.vendored.js");

let failed = false;
if (check) {
  if (!existsSync(vendoredPath) || readFileSync(vendoredPath, "utf8") !== vendored) {
    console.error("DRIFT: src/verify-card.vendored.js differs from public/signed/verify-card.mjs — run the build");
    failed = true;
  }
} else writeFileSync(vendoredPath, vendored);

const res = await build({
  entryPoints: [resolve(pkg, "src/index.js")],
  bundle: true,
  format: "esm",
  minify: true,
  target: "es2020",
  write: false,
  legalComments: "none",
  banner: { js: "/* @csoai/gspc-panel — Apache-2.0 — Evidence by GSPC · Council of AI — https://councilof.ai/panel/ */" },
});
const bundle = res.outputFiles[0].contents;
const gz = gzipSync(bundle, { level: 9 }).length;
const text = Buffer.from(bundle).toString("utf8");
for (const bad of ["eval(", "new Function", "innerHTML"]) if (text.includes(bad)) { console.error(`bundle contains ${bad}`); failed = true; }
const hosts = [...new Set((text.match(/https?:\/\/[a-z0-9.-]+/gi) ?? []).map((u) => u.toLowerCase()))];
console.log(`bundle ${bundle.length} B, gzip ${gz} B (limit ${LIMIT}); url hosts in bundle: ${hosts.join(", ")}`);
if (gz > LIMIT) { console.error("OVER THE 60 KB GZIP LIMIT"); failed = true; }

const outPath = resolve(repo, "public/panel/gspc-panel.js");
const shaPath = resolve(repo, "public/panel/gspc-panel.js.sha256");
if (check) {
  if (!existsSync(outPath) || sha(readFileSync(outPath)) !== sha(bundle)) {
    console.error("DRIFT: public/panel/gspc-panel.js is not the current build of packages/gspc-panel");
    failed = true;
  }
} else {
  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, bundle);
  writeFileSync(shaPath, `${sha(bundle)}  gspc-panel.js\n`);
  mkdirSync(resolve(pkg, "dist"), { recursive: true });
  writeFileSync(resolve(pkg, "dist/gspc-panel.js"), bundle);
  writeFileSync(resolve(pkg, "dist/size.json"), JSON.stringify({ bytes: bundle.length, gzip_bytes: gz, limit_gzip_bytes: LIMIT, sha256: sha(bundle) }, null, 2) + "\n");
}
process.exit(failed ? 1 : 0);
