#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Render provider-sandbox.yaml: the remote::csoai Llama Stack eval provider
(packages/llama-stack-provider-csoai) as namespace-scoped objects only — a ConfigMap holding the
package's own files, a Deployment on the stock UBI 9 Python 3.12 image that installs it at start,
and a ClusterIP Service. No image build, no registry, nothing cluster-wide.

  python3 render.py            write provider-sandbox.yaml
  python3 render.py --check    fail if the committed YAML is not what the package renders to

The fixtures it serves are signed with a PUBLISHED TEST KEY and attest nothing (see the package README).
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.normpath(os.path.join(HERE, "../../../../packages/llama-stack-provider-csoai"))
OUT = os.path.join(HERE, "provider-sandbox.yaml")
NAME = "llama-stack-csoai"
SEP = "-.-"  # "/" in a ConfigMap key; never occurs in the package's file names
key = lambda f: f.replace("/", SEP)
FILES = [
    "pyproject.toml", "run.yaml",
    "src/llama_stack_provider_csoai/__init__.py", "src/llama_stack_provider_csoai/config.py",
    "src/llama_stack_provider_csoai/eval.py", "src/llama_stack_provider_csoai/provider.py",
    "src/llama_stack_provider_csoai/verify.py",
    "fixtures/benchmark.json", "fixtures/job.json", "fixtures/test-did.json",
] + [f"fixtures/{d}/{f}" for d in ("fx-valid", "fx-tampered", "fx-unknown-key") for f in ("batch.json", "batch.signed.json", "events.jsonl")]

# Same start sequence the package README gives, with the dependency pin it documents (mcp<2).
START = r"""set -eu
APP=/tmp/app; rm -rf "$APP"; mkdir -p "$APP"
for k in /cfg/*; do p="$APP/$(basename "$k" | sed 's#-\.-#/#g')"; mkdir -p "$(dirname "$p")"; cp "$k" "$p"; done
cd "$APP"
python3 -m venv /tmp/venv && . /tmp/venv/bin/activate
pip install --no-cache-dir --quiet "llama-stack==0.7.3" "mcp<2" "cryptography>=41" && pip install --no-cache-dir --quiet --no-deps -e .
export SQLITE_STORE_DIR=/tmp/store CSOAI_DID_JSON=./fixtures/test-did.json
mkdir -p "$SQLITE_STORE_DIR"
exec llama stack run run.yaml --port 8321
"""


def block(text, indent):
    pad = " " * indent
    return "\n".join(pad + l if l else "" for l in text.rstrip("\n").split("\n"))


def render():
    out = ["# GENERATED by deploy/llama-stack-provider/render.py from packages/llama-stack-provider-csoai. Do not hand-edit.",
           "# Namespace-scoped only. Fixtures are signed with a PUBLISHED TEST KEY and attest nothing.",
           "apiVersion: v1", "kind: ConfigMap", "metadata:", f"  name: {NAME}-files",
           f"  labels: {{app: {NAME}, app.kubernetes.io/part-of: gspc-evidence}}", "data:"]
    for f in FILES:
        with open(os.path.join(PKG, f), encoding="utf-8") as fh:
            body = fh.read()
        # Byte-exact: signed files are verified over their bytes, so each value is a JSON string
        # (valid YAML) rather than a block scalar, which could drop or add a trailing newline.
        out.append(f"  {key(f)}: {json.dumps(body, ensure_ascii=False)}")
    out.append(f"  start.sh: |-\n{block(START, 4)}")
    out += ["---", "apiVersion: apps/v1", "kind: Deployment", "metadata:", f"  name: {NAME}",
            f"  labels: {{app: {NAME}, app.kubernetes.io/part-of: gspc-evidence}}", "spec:", "  replicas: 1",
            f"  selector: {{matchLabels: {{app: {NAME}}}}}", "  template:", "    metadata:",
            f"      labels: {{app: {NAME}, app.kubernetes.io/part-of: gspc-evidence}}", "    spec:",
            "      securityContext: {runAsNonRoot: true, seccompProfile: {type: RuntimeDefault}}",
            "      containers:", f"        - name: {NAME}",
            "          image: registry.access.redhat.com/ubi9/python-312:latest",
            '          command: ["/bin/bash", "/cfg-start/start.sh"]',
            "          ports: [{containerPort: 8321, protocol: TCP}]",
            "          readinessProbe: {tcpSocket: {port: 8321}, initialDelaySeconds: 30, periodSeconds: 10, failureThreshold: 60}",
            "          securityContext: {allowPrivilegeEscalation: false, capabilities: {drop: [ALL]}}",
            "          resources: {requests: {cpu: 100m, memory: 384Mi}, limits: {cpu: '1', memory: 1Gi}}",
            "          volumeMounts:",
            "            - {name: files, mountPath: /cfg, readOnly: true}",
            "            - {name: start, mountPath: /cfg-start, readOnly: true}",
            "      volumes:",
            f"        - name: files",
            f"          configMap: {{name: {NAME}-files, items: [" + ", ".join(f"{{key: {key(f)}, path: {key(f)}}}" for f in FILES) + "]}",
            f"        - name: start",
            f"          configMap: {{name: {NAME}-files, items: [{{key: start.sh, path: start.sh}}]}}",
            "---", "apiVersion: v1", "kind: Service", "metadata:", f"  name: {NAME}",
            f"  labels: {{app: {NAME}, app.kubernetes.io/part-of: gspc-evidence}}", "spec:",
            f"  selector: {{app: {NAME}}}", "  ports: [{name: http, port: 8321, targetPort: 8321, protocol: TCP}]", ""]
    return "\n".join(out)


if __name__ == "__main__":
    text = render()
    if "--check" in sys.argv:
        ok = os.path.exists(OUT) and open(OUT, encoding="utf-8").read() == text
        print("provider-sandbox.yaml " + ("matches" if ok else "DRIFT: re-run render.py"))
        sys.exit(0 if ok else 1)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {OUT} ({len(text)} bytes, {len(FILES)} files)")
