// GENERATED by scripts/generate-route-manifest.mjs — do not hand-edit.
// Snapshot of App.tsx routes for the Library IA: path + source component + derived title.
export interface RouteEntry { path: string; comp: string; title: string }
export const ROUTE_MANIFEST: RouteEntry[] = [
 {
  "path": "/",
  "comp": "NewHomeV3",
  "title": "New Home"
 },
 {
  "path": "/404",
  "comp": "NotFound",
  "title": "Not Found"
 },
 {
  "path": "/ab-testing",
  "comp": "ABTesting",
  "title": "ABTesting"
 },
 {
  "path": "/about",
  "comp": "About",
  "title": "About"
 },
 {
  "path": "/about-ceasai",
  "comp": "Redirect",
  "title": "About Ceasai"
 },
 {
  "path": "/about-credential",
  "comp": "AboutCEASAI",
  "title": "About CEASAI"
 },
 {
  "path": "/academy",
  "comp": "SovereignAcademy",
  "title": "Sovereign Academy"
 },
 {
  "path": "/accessibility",
  "comp": "Accessibility",
  "title": "Accessibility"
 },
 {
  "path": "/accountability-loop",
  "comp": "AccountabilityLoop",
  "title": "Accountability Loop"
 },
 {
  "path": "/accreditation",
  "comp": "Accreditation",
  "title": "Accreditation"
 },
 {
  "path": "/admin",
  "comp": "RequireAuth",
  "title": "Admin"
 },
 {
  "path": "/advisory",
  "comp": "PartnersAdvisory",
  "title": "Partners Advisory"
 },
 {
  "path": "/ag-ui",
  "comp": "AgUiBridge",
  "title": "Ag Ui Bridge"
 },
 {
  "path": "/agent-council",
  "comp": "AgentCouncil",
  "title": "Agent Council"
 },
 {
  "path": "/agent-governance",
  "comp": "AgentGovernance",
  "title": "Agent Governance"
 },
 {
  "path": "/agent-registry",
  "comp": "AgentRegistry",
  "title": "Agent Registry"
 },
 {
  "path": "/agents",
  "comp": "Agents",
  "title": "Agents"
 },
 {
  "path": "/agents-network",
  "comp": "NetworkPage",
  "title": "Network Page"
 },
 {
  "path": "/ai-act-benchmark",
  "comp": "AiActBenchmark",
  "title": "Ai Act Benchmark"
 },
 {
  "path": "/ai-act-faq",
  "comp": "AiActFaq",
  "title": "Ai Act Faq"
 },
 {
  "path": "/ai-act-summary",
  "comp": "ActSummary",
  "title": "Act Summary"
 },
 {
  "path": "/ai-act-timeline",
  "comp": "ActTimeline",
  "title": "Act Timeline"
 },
 {
  "path": "/ai-act-vs-gdpr",
  "comp": "EuActVsGdpr",
  "title": "Eu Act Vs Gdpr"
 },
 {
  "path": "/ai-glossary",
  "comp": "Glossary",
  "title": "Glossary"
 },
 {
  "path": "/ai-governance",
  "comp": "AiGovernanceHub",
  "title": "Ai Governance Hub"
 },
 {
  "path": "/ai-governance-guide",
  "comp": "AiGovernanceHub",
  "title": "Ai Governance Hub"
 },
 {
  "path": "/ai-systems",
  "comp": "AISystems",
  "title": "AISystems"
 },
 {
  "path": "/ai-transparency",
  "comp": "AiTransparency",
  "title": "Ai Transparency"
 },
 {
  "path": "/all",
  "comp": "RegistryAll",
  "title": "Registry All"
 },
 {
  "path": "/analytics",
  "comp": "AnalyticsDashboard",
  "title": "Analytics Dashboard"
 },
 {
  "path": "/api-docs",
  "comp": "ApiDocs",
  "title": "Api Docs"
 },
 {
  "path": "/api-keys",
  "comp": "RequireAuth",
  "title": "Api Keys"
 },
 {
  "path": "/architecture",
  "comp": "Technology",
  "title": "Technology"
 },
 {
  "path": "/arena-scoreboard",
  "comp": "ArenaScoreboard",
  "title": "Arena Scoreboard"
 },
 {
  "path": "/article-50",
  "comp": "Article50",
  "title": "Article50"
 },
 {
  "path": "/assess",
  "comp": "RequireAuth",
  "title": "Assess"
 },
 {
  "path": "/assessment",
  "comp": "ReadinessAssessment",
  "title": "Readiness Assessment"
 },
 {
  "path": "/assurance",
  "comp": "SystemCard",
  "title": "System Card"
 },
 {
  "path": "/aug-2026",
  "comp": "Readiness",
  "title": "Readiness"
 },
 {
  "path": "/authority",
  "comp": "BadgesPage",
  "title": "Badges Page"
 },
 {
  "path": "/badges",
  "comp": "BadgesPage",
  "title": "Badges Page"
 },
 {
  "path": "/battlecards",
  "comp": "Competitors",
  "title": "Competitors"
 },
 {
  "path": "/benchmark-index",
  "comp": "BenchmarkIndex",
  "title": "Benchmark Index"
 },
 {
  "path": "/benchmark-quality",
  "comp": "BenchmarkQuality",
  "title": "Benchmark Quality"
 },
 {
  "path": "/benchmarks",
  "comp": "Benchmarks",
  "title": "Benchmarks"
 },
 {
  "path": "/bft",
  "comp": "Redirect",
  "title": "Bft"
 },
 {
  "path": "/blog",
  "comp": "Blog",
  "title": "Blog"
 },
 {
  "path": "/brief",
  "comp": "AccountBrief",
  "title": "Account Brief"
 },
 {
  "path": "/bulk-import",
  "comp": "BulkAISystemImport",
  "title": "Bulk AISystem Import"
 },
 {
  "path": "/byzantine",
  "comp": "Redirect",
  "title": "Byzantine"
 },
 {
  "path": "/byzantine-consensus",
  "comp": "Redirect",
  "title": "Byzantine Consensus"
 },
 {
  "path": "/california-ai-law",
  "comp": "UsStateAct",
  "title": "California Ai Law"
 },
 {
  "path": "/canada-aida",
  "comp": "JurisdictionAct",
  "title": "Canada Aida"
 },
 {
  "path": "/careers",
  "comp": "Careers",
  "title": "Careers"
 },
 {
  "path": "/case-studies",
  "comp": "CaseStudies",
  "title": "Case Studies"
 },
 {
  "path": "/catalog",
  "comp": "Redirect",
  "title": "Catalog"
 },
 {
  "path": "/ceasai-training",
  "comp": "Redirect",
  "title": "Ceasai Training"
 },
 {
  "path": "/certificate-verification",
  "comp": "CertificateVerification",
  "title": "Certificate Verification"
 },
 {
  "path": "/certificates",
  "comp": "MyCertificates",
  "title": "My Certificates"
 },
 {
  "path": "/certification",
  "comp": "CertificationV2",
  "title": "Certification"
 },
 {
  "path": "/certification/exam",
  "comp": "CertificationExam",
  "title": "Certification Exam"
 },
 {
  "path": "/certification/results",
  "comp": "CertificationResults",
  "title": "Certification Results"
 },
 {
  "path": "/certification/review",
  "comp": "ExamReview",
  "title": "Exam Review"
 },
 {
  "path": "/challenge",
  "comp": "Challenge",
  "title": "Challenge"
 },
 {
  "path": "/charter",
  "comp": "Charter",
  "title": "Charter"
 },
 {
  "path": "/chat",
  "comp": "AgUiBridge",
  "title": "Ag Ui Bridge"
 },
 {
  "path": "/checklist",
  "comp": "EUActChecklist",
  "title": "EUAct Checklist"
 },
 {
  "path": "/china-ai-law",
  "comp": "JurisdictionAct",
  "title": "China Ai Law"
 },
 {
  "path": "/claims-register",
  "comp": "ClaimsRegister",
  "title": "Claims Register"
 },
 {
  "path": "/classifier",
  "comp": "EuActClassifier",
  "title": "Eu Act Classifier"
 },
 {
  "path": "/cobol",
  "comp": "LegacyBridge",
  "title": "Legacy Bridge"
 },
 {
  "path": "/cobolbridge",
  "comp": "CobolBridge",
  "title": "Cobol Bridge"
 },
 {
  "path": "/coliseum",
  "comp": "Coliseum",
  "title": "Coliseum"
 },
 {
  "path": "/colorado-ai-act",
  "comp": "UsStateAct",
  "title": "Colorado Ai Act"
 },
 {
  "path": "/command-center",
  "comp": "ComplianceCommandCenter",
  "title": "Compliance Command Center"
 },
 {
  "path": "/commons",
  "comp": "OpenMedia",
  "title": "Open Media"
 },
 {
  "path": "/compare",
  "comp": "Compare",
  "title": "Compare"
 },
 {
  "path": "/comparison",
  "comp": "ComparisonPage",
  "title": "Comparison Page"
 },
 {
  "path": "/competitors",
  "comp": "Competitors",
  "title": "Competitors"
 },
 {
  "path": "/compliance",
  "comp": "Compliance",
  "title": "Compliance"
 },
 {
  "path": "/compliance-monitoring",
  "comp": "ComplianceMonitoring",
  "title": "Compliance Monitoring"
 },
 {
  "path": "/compliance/australia-ai-governance",
  "comp": "AustraliaAIGovernanceCompliance",
  "title": "Australia AIGovernance Compliance"
 },
 {
  "path": "/compliance/canada-ai-act",
  "comp": "CanadaAIActCompliance",
  "title": "Canada AIAct Compliance"
 },
 {
  "path": "/compliance/eu-ai-act",
  "comp": "EUAIActCompliance",
  "title": "EUAIAct Compliance"
 },
 {
  "path": "/compliance/nist-ai-rmf",
  "comp": "NISTAIRMFCompliance",
  "title": "NISTAIRMFCompliance"
 },
 {
  "path": "/compliance/tc260",
  "comp": "TC260Compliance",
  "title": "TC260 Compliance"
 },
 {
  "path": "/compliance/uk-ai-bill",
  "comp": "UKAIBillCompliance",
  "title": "UKAIBill Compliance"
 },
 {
  "path": "/conformity-assessment",
  "comp": "ConformityAssessment",
  "title": "Conformity Assessment"
 },
 {
  "path": "/conformity-route",
  "comp": "ConformityRoute",
  "title": "Conformity Route"
 },
 {
  "path": "/connect",
  "comp": "SocialConnect",
  "title": "Social Connect"
 },
 {
  "path": "/consensus",
  "comp": "Redirect",
  "title": "Consensus"
 },
 {
  "path": "/contact",
  "comp": "Contact",
  "title": "Contact"
 },
 {
  "path": "/cookie-policy",
  "comp": "CookiePolicy",
  "title": "Cookie Policy"
 },
 {
  "path": "/cookies",
  "comp": "CookiePolicy",
  "title": "Cookie Policy"
 },
 {
  "path": "/council",
  "comp": "Council",
  "title": "Council"
 },
 {
  "path": "/council-detail",
  "comp": "CouncilDetail",
  "title": "Council Detail"
 },
 {
  "path": "/council-licensing",
  "comp": "CouncilLicensingLanding",
  "title": "Council Licensing Landing"
 },
 {
  "path": "/council-model-card",
  "comp": "CouncilModelCard",
  "title": "Council Model Card"
 },
 {
  "path": "/council-system-card",
  "comp": "CouncilSystemCard",
  "title": "Council System Card"
 },
 {
  "path": "/council-vs-agents",
  "comp": "Agents",
  "title": "Agents"
 },
 {
  "path": "/courses",
  "comp": "Courses",
  "title": "Courses"
 },
 {
  "path": "/covenant",
  "comp": "MaternalCovenant",
  "title": "Maternal Covenant"
 },
 {
  "path": "/cra",
  "comp": "Cra",
  "title": "Cra"
 },
 {
  "path": "/cra-readiness",
  "comp": "CraReadinessKit",
  "title": "Cra Readiness Kit"
 },
 {
  "path": "/credential-training",
  "comp": "CEASAITraining",
  "title": "CEASAITraining"
 },
 {
  "path": "/credo-ai-alternative",
  "comp": "AltPage",
  "title": "Credo Ai Alternative"
 },
 {
  "path": "/crosswalk",
  "comp": "Crosswalk",
  "title": "Crosswalk"
 },
 {
  "path": "/crosswalks",
  "comp": "Crosswalks",
  "title": "Crosswalks"
 },
 {
  "path": "/crown-jewels",
  "comp": "Redirect",
  "title": "Crown Jewels"
 },
 {
  "path": "/csoai-law",
  "comp": "MeokLaw",
  "title": "Meok Law"
 },
 {
  "path": "/cyber-scan",
  "comp": "CyberScan",
  "title": "Cyber Scan"
 },
 {
  "path": "/dashboard",
  "comp": "Dashboard",
  "title": "Dashboard"
 },
 {
  "path": "/dashboard/progress",
  "comp": "StudentProgress",
  "title": "Student Progress"
 },
 {
  "path": "/data-processing-agreement",
  "comp": "DataProcessingAgreement",
  "title": "Data Processing Agreement"
 },
 {
  "path": "/deepfake-protection",
  "comp": "Protect",
  "title": "Protect"
 },
 {
  "path": "/defence-ai-act",
  "comp": "SectorAct",
  "title": "Defence Ai Act"
 },
 {
  "path": "/demo",
  "comp": "DemoOS",
  "title": "Demo OS"
 },
 {
  "path": "/disclaimers",
  "comp": "Disclaimers",
  "title": "Disclaimers"
 },
 {
  "path": "/dispute",
  "comp": "Dispute",
  "title": "Dispute"
 },
 {
  "path": "/distribution",
  "comp": "Distribution",
  "title": "Distribution"
 },
 {
  "path": "/distribution-integrity",
  "comp": "DistributionIntegrity",
  "title": "Distribution Integrity"
 },
 {
  "path": "/docs",
  "comp": "Documentation",
  "title": "Documentation"
 },
 {
  "path": "/dora",
  "comp": "Dora",
  "title": "Dora"
 },
 {
  "path": "/dpa",
  "comp": "DataProcessingAgreement",
  "title": "Data Processing Agreement"
 },
 {
  "path": "/dragonfly",
  "comp": "Dragonfly",
  "title": "Dragonfly"
 },
 {
  "path": "/drift-audit",
  "comp": "DriftProduct",
  "title": "Drift Product"
 },
 {
  "path": "/drift-product",
  "comp": "DriftProduct",
  "title": "Drift Product"
 },
 {
  "path": "/early-access",
  "comp": "EarlyAccessLanding",
  "title": "Early Access Landing"
 },
 {
  "path": "/east-west",
  "comp": "EastWest",
  "title": "East West"
 },
 {
  "path": "/ecosystem",
  "comp": "Integrations",
  "title": "Integrations"
 },
 {
  "path": "/ei3",
  "comp": "EI3",
  "title": "EI3"
 },
 {
  "path": "/embed",
  "comp": "EmbedPage",
  "title": "Embed Page"
 },
 {
  "path": "/energy-ai-act",
  "comp": "SectorAct",
  "title": "Energy Ai Act"
 },
 {
  "path": "/enter",
  "comp": "OsEnter",
  "title": "Os Enter"
 },
 {
  "path": "/enterprise",
  "comp": "Enterprise",
  "title": "Enterprise"
 },
 {
  "path": "/enterprise-dashboard",
  "comp": "EnterpriseDashboard",
  "title": "Enterprise Dashboard"
 },
 {
  "path": "/enterprise-onboarding",
  "comp": "EnterpriseOnboarding",
  "title": "Enterprise Onboarding"
 },
 {
  "path": "/enterprise-plans",
  "comp": "Redirect",
  "title": "Enterprise Plans"
 },
 {
  "path": "/eu-ai-act",
  "comp": "EUAIActGuide",
  "title": "EUAIAct Guide"
 },
 {
  "path": "/eu-ai-act-checklist",
  "comp": "EUActChecklist",
  "title": "EUAct Checklist"
 },
 {
  "path": "/eu-ai-act-classifier",
  "comp": "EUAIActClassifier",
  "title": "EUAIAct Classifier"
 },
 {
  "path": "/eu-ai-act-explained",
  "comp": "ActSummary",
  "title": "Act Summary"
 },
 {
  "path": "/eu-ai-act-faq",
  "comp": "AiActFaq",
  "title": "Ai Act Faq"
 },
 {
  "path": "/eu-ai-act-timeline",
  "comp": "ActTimeline",
  "title": "Act Timeline"
 },
 {
  "path": "/eu-ai-act-urgency",
  "comp": "EUAIActUrgency",
  "title": "EUAIAct Urgency"
 },
 {
  "path": "/eu-ai-act-vs-gdpr",
  "comp": "EuActVsGdpr",
  "title": "Eu Act Vs Gdpr"
 },
 {
  "path": "/eunomia",
  "comp": "Eunomia",
  "title": "Eunomia"
 },
 {
  "path": "/eunomia-catalog",
  "comp": "EunomiaCatalog",
  "title": "Eunomia Catalog"
 },
 {
  "path": "/eunomia-crosswalk",
  "comp": "EunomiaCrosswalk",
  "title": "Eunomia Crosswalk"
 },
 {
  "path": "/eunomia-data",
  "comp": "EunomiaData",
  "title": "Eunomia Data"
 },
 {
  "path": "/evidence",
  "comp": "EvidenceHub",
  "title": "Evidence Hub"
 },
 {
  "path": "/evidence-rail",
  "comp": "EvidenceRail",
  "title": "Evidence Rail"
 },
 {
  "path": "/faq",
  "comp": "FAQ",
  "title": "FAQ"
 },
 {
  "path": "/features/33-agent-council",
  "comp": "AgentCouncilFeature",
  "title": "Agent Council Feature"
 },
 {
  "path": "/features/pdca-framework",
  "comp": "PDCAFrameworkFeature",
  "title": "PDCAFramework Feature"
 },
 {
  "path": "/features/training-certification",
  "comp": "TrainingCertificationFeature",
  "title": "Training Certification Feature"
 },
 {
  "path": "/features/watchdog-jobs",
  "comp": "WatchdogJobsFeature",
  "title": "Watchdog Jobs Feature"
 },
 {
  "path": "/fedramp",
  "comp": "Fedramp",
  "title": "Fedramp"
 },
 {
  "path": "/feed",
  "comp": "RegulationFeed",
  "title": "Regulation Feed"
 },
 {
  "path": "/finance-ai-act",
  "comp": "SectorAct",
  "title": "Finance Ai Act"
 },
 {
  "path": "/financial-axes",
  "comp": "FinancialAxes",
  "title": "Financial Axes"
 },
 {
  "path": "/fines",
  "comp": "Penalties",
  "title": "Penalties"
 },
 {
  "path": "/firewall-charter",
  "comp": "FirewallCharter",
  "title": "Firewall Charter"
 },
 {
  "path": "/first-fine-watch",
  "comp": "FirstFineWatch",
  "title": "First Fine Watch"
 },
 {
  "path": "/foundation-models",
  "comp": "GpaiObligations",
  "title": "Gpai Obligations"
 },
 {
  "path": "/founding-council-agreement",
  "comp": "FoundingCouncilAgreement",
  "title": "Founding Council Agreement"
 },
 {
  "path": "/founding-members",
  "comp": "FoundingMembers",
  "title": "Founding Members"
 },
 {
  "path": "/four-wings",
  "comp": "Dragonfly",
  "title": "Dragonfly"
 },
 {
  "path": "/framework-catalog",
  "comp": "FrameworkCatalog",
  "title": "Framework Catalog"
 },
 {
  "path": "/framework-crosswalks",
  "comp": "Crosswalks",
  "title": "Crosswalks"
 },
 {
  "path": "/framework-temples",
  "comp": "Temples",
  "title": "Temples"
 },
 {
  "path": "/frameworks/australia-ai",
  "comp": "AustraliaAIGovernance",
  "title": "Australia AIGovernance"
 },
 {
  "path": "/frameworks/canada-ai-act",
  "comp": "CanadaAIAct",
  "title": "Canada AIAct"
 },
 {
  "path": "/frameworks/eu-ai-act",
  "comp": "EUAIActGuide",
  "title": "EUAIAct Guide"
 },
 {
  "path": "/frameworks/iso-42001",
  "comp": "ISO42001Guide",
  "title": "ISO42001 Guide"
 },
 {
  "path": "/frameworks/nist",
  "comp": "NISTAIRMFGuide",
  "title": "NISTAIRMFGuide"
 },
 {
  "path": "/frameworks/tc260",
  "comp": "TC260Guide",
  "title": "TC260 Guide"
 },
 {
  "path": "/frameworks/uk-ai-bill",
  "comp": "UKAIBill",
  "title": "UKAIBill"
 },
 {
  "path": "/frequently-asked-questions",
  "comp": "FAQ",
  "title": "FAQ"
 },
 {
  "path": "/global-ai-regulation",
  "comp": "GlobalAIRegulation",
  "title": "Global AIRegulation"
 },
 {
  "path": "/global-ai-safety-initiative",
  "comp": "GlobalAISafetyInitiative",
  "title": "Global AISafety Initiative"
 },
 {
  "path": "/global-regulations",
  "comp": "GlobalRegulationTracker",
  "title": "Global Regulation Tracker"
 },
 {
  "path": "/globe",
  "comp": "Redirect",
  "title": "Globe"
 },
 {
  "path": "/glossary",
  "comp": "Glossary",
  "title": "Glossary"
 },
 {
  "path": "/gods-eye",
  "comp": "CyberScan",
  "title": "Cyber Scan"
 },
 {
  "path": "/gone-space",
  "comp": "Gone",
  "title": "Gone"
 },
 {
  "path": "/govbench",
  "comp": "GovBench",
  "title": "Gov Bench"
 },
 {
  "path": "/governance-commons",
  "comp": "Ecosystem",
  "title": "Ecosystem"
 },
 {
  "path": "/governance-council",
  "comp": "Agents",
  "title": "Agents"
 },
 {
  "path": "/governance-graph",
  "comp": "GovGraph",
  "title": "Gov Graph"
 },
 {
  "path": "/governance-layer",
  "comp": "GovernanceLayer",
  "title": "Governance Layer"
 },
 {
  "path": "/government",
  "comp": "GovernmentDashboard",
  "title": "Government Dashboard"
 },
 {
  "path": "/government-dashboard",
  "comp": "GovernmentDashboard",
  "title": "Government Dashboard"
 },
 {
  "path": "/government-links",
  "comp": "GovernmentLinks",
  "title": "Government Links"
 },
 {
  "path": "/government-portal",
  "comp": "GovernmentPortal",
  "title": "Government Portal"
 },
 {
  "path": "/gpai",
  "comp": "GpaiObligations",
  "title": "Gpai Obligations"
 },
 {
  "path": "/gpai-evidence",
  "comp": "GpaiEvidencePack",
  "title": "Gpai Evidence Pack"
 },
 {
  "path": "/graph",
  "comp": "GovGraph",
  "title": "Gov Graph"
 },
 {
  "path": "/gspc-anchors",
  "comp": "GSPCAnchors",
  "title": "GSPCAnchors"
 },
 {
  "path": "/gspc-arena",
  "comp": "CouncilSpace",
  "title": "Council Space"
 },
 {
  "path": "/gspc-gap-map",
  "comp": "GSPCGapMap",
  "title": "GSPCGap Map"
 },
 {
  "path": "/gspc-scoreboard",
  "comp": "GspcScoreboard",
  "title": "Gspc Scoreboard"
 },
 {
  "path": "/gspc-verify",
  "comp": "GSPCVerify",
  "title": "GSPCVerify"
 },
 {
  "path": "/guides/eu-ai-act",
  "comp": "EUAIActGuide",
  "title": "EUAIAct Guide"
 },
 {
  "path": "/guides/iso-42001",
  "comp": "ISO42001Guide",
  "title": "ISO42001 Guide"
 },
 {
  "path": "/guides/nist-ai-rmf",
  "comp": "NISTAIRMFGuide",
  "title": "NISTAIRMFGuide"
 },
 {
  "path": "/guides/tc260",
  "comp": "TC260Guide",
  "title": "TC260 Guide"
 },
 {
  "path": "/healthcare-ai-act",
  "comp": "SectorAct",
  "title": "Healthcare Ai Act"
 },
 {
  "path": "/heatmap",
  "comp": "WatchdogMap",
  "title": "Watchdog Map"
 },
 {
  "path": "/help",
  "comp": "HelpCenter",
  "title": "Help Center"
 },
 {
  "path": "/help-center",
  "comp": "HelpCenter",
  "title": "Help Center"
 },
 {
  "path": "/high-risk-ai",
  "comp": "HighRiskSystems",
  "title": "High Risk Systems"
 },
 {
  "path": "/high-risk-ai-systems",
  "comp": "HighRiskSystems",
  "title": "High Risk Systems"
 },
 {
  "path": "/hive",
  "comp": "FrameworkHive",
  "title": "Framework Hive"
 },
 {
  "path": "/hive-model",
  "comp": "HiveModel",
  "title": "Hive Model"
 },
 {
  "path": "/hives",
  "comp": "SovereignHives",
  "title": "Sovereign Hives"
 },
 {
  "path": "/home-v2",
  "comp": "NewHomeV2",
  "title": "New Home"
 },
 {
  "path": "/home-v3",
  "comp": "NewHomeV3",
  "title": "New Home"
 },
 {
  "path": "/honesty",
  "comp": "Honesty",
  "title": "Honesty"
 },
 {
  "path": "/horus",
  "comp": "HorusIntel",
  "title": "Horus Intel"
 },
 {
  "path": "/how",
  "comp": "HowItWorks",
  "title": "How It Works"
 },
 {
  "path": "/how-it-works",
  "comp": "HowItWorks",
  "title": "How It Works"
 },
 {
  "path": "/how-it-works/certification",
  "comp": "CertificationHowItWorks",
  "title": "Certification How It Works"
 },
 {
  "path": "/how-it-works/compliance",
  "comp": "ComplianceHowItWorks",
  "title": "Compliance How It Works"
 },
 {
  "path": "/how-it-works/dashboard",
  "comp": "DashboardHowItWorks",
  "title": "Dashboard How It Works"
 },
 {
  "path": "/how-it-works/enterprise",
  "comp": "EnterpriseHowItWorks",
  "title": "Enterprise How It Works"
 },
 {
  "path": "/how-it-works/training",
  "comp": "TrainingHowItWorks",
  "title": "Training How It Works"
 },
 {
  "path": "/hr-ai-act",
  "comp": "SectorAct",
  "title": "Hr Ai Act"
 },
 {
  "path": "/humanoids-poc",
  "comp": "PocShowcase",
  "title": "Poc Showcase"
 },
 {
  "path": "/industries",
  "comp": "IndustrySolutions",
  "title": "Industry Solutions"
 },
 {
  "path": "/industry-playbooks",
  "comp": "Playbooks",
  "title": "Playbooks"
 },
 {
  "path": "/industry-solutions",
  "comp": "IndustrySolutions",
  "title": "Industry Solutions"
 },
 {
  "path": "/instrument",
  "comp": "Instrument",
  "title": "Instrument"
 },
 {
  "path": "/insurers",
  "comp": "Insurers",
  "title": "Insurers"
 },
 {
  "path": "/integrations",
  "comp": "Integrations",
  "title": "Integrations"
 },
 {
  "path": "/intel",
  "comp": "Intel",
  "title": "Intel"
 },
 {
  "path": "/iso-42001",
  "comp": "ISO42001Guide",
  "title": "ISO42001 Guide"
 },
 {
  "path": "/iso-42001-vs-eu-ai-act",
  "comp": "Iso42001VsEuAct",
  "title": "Iso42001 Vs Eu Act"
 },
 {
  "path": "/iso-eu",
  "comp": "Iso42001VsEuAct",
  "title": "Iso42001 Vs Eu Act"
 },
 {
  "path": "/jewels",
  "comp": "Redirect",
  "title": "Jewels"
 },
 {
  "path": "/jobs",
  "comp": "Jobs",
  "title": "Jobs"
 },
 {
  "path": "/join",
  "comp": "SovereignRegistry",
  "title": "Sovereign Registry"
 },
 {
  "path": "/knowledge-base",
  "comp": "KnowledgeBase",
  "title": "Knowledge Base"
 },
 {
  "path": "/landing",
  "comp": "Landing",
  "title": "Landing"
 },
 {
  "path": "/landscape",
  "comp": "Landscape",
  "title": "Landscape"
 },
 {
  "path": "/law",
  "comp": "MeokLaw",
  "title": "Meok Law"
 },
 {
  "path": "/layer0",
  "comp": "Layer0",
  "title": "Layer0"
 },
 {
  "path": "/leaderboard",
  "comp": "WatchdogLeaderboard",
  "title": "Watchdog Leaderboard"
 },
 {
  "path": "/learn",
  "comp": "Academy",
  "title": "Academy"
 },
 {
  "path": "/legacy",
  "comp": "LegacyBridge",
  "title": "Legacy Bridge"
 },
 {
  "path": "/legal/cookies",
  "comp": "CookiePolicy",
  "title": "Cookie Policy"
 },
 {
  "path": "/legal/disclaimers",
  "comp": "Disclaimers",
  "title": "Disclaimers"
 },
 {
  "path": "/legal/dpa",
  "comp": "DataProcessingAgreement",
  "title": "Data Processing Agreement"
 },
 {
  "path": "/legal/founding-council",
  "comp": "FoundingCouncilAgreement",
  "title": "Founding Council Agreement"
 },
 {
  "path": "/legal/licensing",
  "comp": "LicensingAgreement",
  "title": "Licensing Agreement"
 },
 {
  "path": "/legal/membership",
  "comp": "MembershipAgreement",
  "title": "Membership Agreement"
 },
 {
  "path": "/legal/privacy",
  "comp": "PrivacyPolicy",
  "title": "Privacy Policy"
 },
 {
  "path": "/legal/sla",
  "comp": "ServiceLevelAgreement",
  "title": "Service Level Agreement"
 },
 {
  "path": "/legal/terms",
  "comp": "TermsOfService",
  "title": "Terms Of Service"
 },
 {
  "path": "/library",
  "comp": "Library",
  "title": "Library"
 },
 {
  "path": "/licensing-agreement",
  "comp": "LicensingAgreement",
  "title": "Licensing Agreement"
 },
 {
  "path": "/lineage",
  "comp": "Lineage",
  "title": "Lineage"
 },
 {
  "path": "/live-ledger",
  "comp": "LiveLedger",
  "title": "Live Ledger"
 },
 {
  "path": "/login",
  "comp": "Login",
  "title": "Login"
 },
 {
  "path": "/map",
  "comp": "RelevanceMap",
  "title": "Relevance Map"
 },
 {
  "path": "/map-regions",
  "comp": "RegionsMap",
  "title": "Regions Map"
 },
 {
  "path": "/marketing",
  "comp": "MarketingHome",
  "title": "Marketing Home"
 },
 {
  "path": "/maternal-covenant",
  "comp": "MaternalCovenant",
  "title": "Maternal Covenant"
 },
 {
  "path": "/mcp",
  "comp": "MCPRegistry",
  "title": "MCPRegistry"
 },
 {
  "path": "/mcp-fleet",
  "comp": "McpFleet",
  "title": "Mcp Fleet"
 },
 {
  "path": "/mcp-tools",
  "comp": "ToolCommons",
  "title": "Tool Commons"
 },
 {
  "path": "/mcps",
  "comp": "MCPRegistry",
  "title": "MCPRegistry"
 },
 {
  "path": "/me",
  "comp": "SovereignHub",
  "title": "Sovereign Hub"
 },
 {
  "path": "/membership-agreement",
  "comp": "MembershipAgreement",
  "title": "Membership Agreement"
 },
 {
  "path": "/meok-law",
  "comp": "MeokLaw",
  "title": "Meok Law"
 },
 {
  "path": "/methodology",
  "comp": "Methodology",
  "title": "Methodology"
 },
 {
  "path": "/metrology",
  "comp": "Metrology",
  "title": "Metrology"
 },
 {
  "path": "/minds",
  "comp": "SovereignMinds",
  "title": "Sovereign Minds"
 },
 {
  "path": "/models",
  "comp": "ModelRegistry",
  "title": "Model Registry"
 },
 {
  "path": "/motion-lab",
  "comp": "MotionLab",
  "title": "Motion Lab"
 },
 {
  "path": "/my-applications",
  "comp": "RequireAuth",
  "title": "My Applications"
 },
 {
  "path": "/my-courses",
  "comp": "RequireAuth",
  "title": "My Courses"
 },
 {
  "path": "/network",
  "comp": "NetworkPage",
  "title": "Network Page"
 },
 {
  "path": "/nis2",
  "comp": "Nis2",
  "title": "Nis2"
 },
 {
  "path": "/nist-ai-rmf",
  "comp": "NISTAIRMFGuide",
  "title": "NISTAIRMFGuide"
 },
 {
  "path": "/nist-eu",
  "comp": "NistVsEuAct",
  "title": "Nist Vs Eu Act"
 },
 {
  "path": "/nist-vs-eu-ai-act",
  "comp": "NistVsEuAct",
  "title": "Nist Vs Eu Act"
 },
 {
  "path": "/old-home",
  "comp": "Home",
  "title": "Home"
 },
 {
  "path": "/onboard",
  "comp": "OnboardOS",
  "title": "Onboard OS"
 },
 {
  "path": "/one-os",
  "comp": "PocShowcase",
  "title": "Poc Showcase"
 },
 {
  "path": "/onetrust-alternative",
  "comp": "AltPage",
  "title": "Onetrust Alternative"
 },
 {
  "path": "/ontology",
  "comp": "Ontology",
  "title": "Ontology"
 },
 {
  "path": "/open-media",
  "comp": "OpenMedia",
  "title": "Open Media"
 },
 {
  "path": "/open-source",
  "comp": "OpenSourceFramework",
  "title": "Open Source Framework"
 },
 {
  "path": "/opengridworks",
  "comp": "OpenGridWorks",
  "title": "Open Grid Works"
 },
 {
  "path": "/os",
  "comp": "OsLauncher",
  "title": "Os Launcher"
 },
 {
  "path": "/os-demo",
  "comp": "DemoOS",
  "title": "Demo OS"
 },
 {
  "path": "/oscal",
  "comp": "OscalStudio",
  "title": "Oscal Studio"
 },
 {
  "path": "/oscal-readiness",
  "comp": "Fedramp",
  "title": "Fedramp"
 },
 {
  "path": "/our-difference",
  "comp": "WhyCSOAI",
  "title": "Why CSOAI"
 },
 {
  "path": "/outreach",
  "comp": "Outreach",
  "title": "Outreach"
 },
 {
  "path": "/packs/eu-article-50",
  "comp": "Article50Pack",
  "title": "Article50 Pack"
 },
 {
  "path": "/partners",
  "comp": "PartnersAdvisory",
  "title": "Partners Advisory"
 },
 {
  "path": "/payg",
  "comp": "Payg",
  "title": "Payg"
 },
 {
  "path": "/pdca",
  "comp": "PDCACycles",
  "title": "PDCACycles"
 },
 {
  "path": "/pdca-simulator",
  "comp": "PDCASimulator",
  "title": "PDCASimulator"
 },
 {
  "path": "/penalties",
  "comp": "Penalties",
  "title": "Penalties"
 },
 {
  "path": "/personal-protection",
  "comp": "Protect",
  "title": "Protect"
 },
 {
  "path": "/pharma-ai-act",
  "comp": "SectorAct",
  "title": "Pharma Ai Act"
 },
 {
  "path": "/plans",
  "comp": "Redirect",
  "title": "Plans"
 },
 {
  "path": "/playbooks",
  "comp": "Playbooks",
  "title": "Playbooks"
 },
 {
  "path": "/poc",
  "comp": "PocShowcase",
  "title": "Poc Showcase"
 },
 {
  "path": "/policy-generator",
  "comp": "PolicyGenerator",
  "title": "Policy Generator"
 },
 {
  "path": "/press",
  "comp": "Pressroom",
  "title": "Pressroom"
 },
 {
  "path": "/pressroom",
  "comp": "Pressroom",
  "title": "Pressroom"
 },
 {
  "path": "/pricing",
  "comp": "PlansPage",
  "title": "Plans Page"
 },
 {
  "path": "/pricing-legacy",
  "comp": "Pricing",
  "title": "Pricing"
 },
 {
  "path": "/privacy",
  "comp": "PrivacyPolicy",
  "title": "Privacy Policy"
 },
 {
  "path": "/privacy-policy",
  "comp": "PrivacyPolicy",
  "title": "Privacy Policy"
 },
 {
  "path": "/products",
  "comp": "Products",
  "title": "Products"
 },
 {
  "path": "/prosperity",
  "comp": "ProsperityFund",
  "title": "Prosperity Fund"
 },
 {
  "path": "/prosperity-fund",
  "comp": "ProsperityFund",
  "title": "Prosperity Fund"
 },
 {
  "path": "/protect",
  "comp": "Protect",
  "title": "Protect"
 },
 {
  "path": "/provbench",
  "comp": "ProvBench",
  "title": "Prov Bench"
 },
 {
  "path": "/provenance-finding",
  "comp": "ProvenanceFinding",
  "title": "Provenance Finding"
 },
 {
  "path": "/public",
  "comp": "PublicHome",
  "title": "Public Home"
 },
 {
  "path": "/public-dashboard",
  "comp": "Redirect",
  "title": "Public Dashboard"
 },
 {
  "path": "/public-watchdog",
  "comp": "PublicWatchdog",
  "title": "Public Watchdog"
 },
 {
  "path": "/pulse",
  "comp": "GovernancePulse",
  "title": "Governance Pulse"
 },
 {
  "path": "/radar",
  "comp": "RegulationRadar",
  "title": "Regulation Radar"
 },
 {
  "path": "/rankings",
  "comp": "RankingsBridge",
  "title": "Rankings Bridge"
 },
 {
  "path": "/rating-the-raters",
  "comp": "RatingTheRaters",
  "title": "Rating The Raters"
 },
 {
  "path": "/readiness",
  "comp": "Readiness",
  "title": "Readiness"
 },
 {
  "path": "/readiness-assessment",
  "comp": "ReadinessAssessment",
  "title": "Readiness Assessment"
 },
 {
  "path": "/real-world",
  "comp": "RealWorldMap",
  "title": "Real World Map"
 },
 {
  "path": "/recommendations",
  "comp": "Recommendations",
  "title": "Recommendations"
 },
 {
  "path": "/rediscovered",
  "comp": "Lineage",
  "title": "Lineage"
 },
 {
  "path": "/refutation-ledger",
  "comp": "RefutationLedger",
  "title": "Refutation Ledger"
 },
 {
  "path": "/region-settings",
  "comp": "RegionSettings",
  "title": "Region Settings"
 },
 {
  "path": "/regional-analytics",
  "comp": "RegionalAnalytics",
  "title": "Regional Analytics"
 },
 {
  "path": "/regions",
  "comp": "RegionsMap",
  "title": "Regions Map"
 },
 {
  "path": "/register",
  "comp": "SovereignRegistry",
  "title": "Sovereign Registry"
 },
 {
  "path": "/registers",
  "comp": "Registers",
  "title": "Registers"
 },
 {
  "path": "/registry",
  "comp": "RegistryAll",
  "title": "Registry All"
 },
 {
  "path": "/regulation-tracker",
  "comp": "GlobalRegulationTracker",
  "title": "Global Regulation Tracker"
 },
 {
  "path": "/regulator",
  "comp": "RegulatorDashboard",
  "title": "Regulator Dashboard"
 },
 {
  "path": "/regulator-atlas",
  "comp": "RegulatorAtlas",
  "title": "Regulator Atlas"
 },
 {
  "path": "/regulator-findings",
  "comp": "RegulatorFindings",
  "title": "Regulator Findings"
 },
 {
  "path": "/regulators",
  "comp": "RegulatorAtlas",
  "title": "Regulator Atlas"
 },
 {
  "path": "/regulatory-authority",
  "comp": "RegulatoryAuthority",
  "title": "Regulatory Authority"
 },
 {
  "path": "/regulatory-compliance",
  "comp": "RegulatoryCompliance",
  "title": "Regulatory Compliance"
 },
 {
  "path": "/relevance-map",
  "comp": "RelevanceMap",
  "title": "Relevance Map"
 },
 {
  "path": "/remediation-partners",
  "comp": "RemediationPartners",
  "title": "Remediation Partners"
 },
 {
  "path": "/report",
  "comp": "IncidentReport",
  "title": "Incident Report"
 },
 {
  "path": "/reports",
  "comp": "Reports",
  "title": "Reports"
 },
 {
  "path": "/research-transparency",
  "comp": "ResearchTransparency",
  "title": "Research Transparency"
 },
 {
  "path": "/resources",
  "comp": "Resources",
  "title": "Resources"
 },
 {
  "path": "/rfc-0024",
  "comp": "Fedramp",
  "title": "Fedramp"
 },
 {
  "path": "/risk-assessment",
  "comp": "RiskAssessment",
  "title": "Risk Assessment"
 },
 {
  "path": "/risk-heatmap",
  "comp": "RiskHeatmap",
  "title": "Risk Heatmap"
 },
 {
  "path": "/roi",
  "comp": "ROICalculator",
  "title": "ROICalculator"
 },
 {
  "path": "/roi-calculator",
  "comp": "ROICalculator",
  "title": "ROICalculator"
 },
 {
  "path": "/safe-space",
  "comp": "Ecosystem",
  "title": "Ecosystem"
 },
 {
  "path": "/scan",
  "comp": "CyberScan",
  "title": "Cyber Scan"
 },
 {
  "path": "/sec-ai-disclosure",
  "comp": "SECDisclosure",
  "title": "Sec Ai Disclosure"
 },
 {
  "path": "/sec-disclosure",
  "comp": "SECDisclosure",
  "title": "Sec Disclosure"
 },
 {
  "path": "/sector-atlas",
  "comp": "SectorsAtlas",
  "title": "Sectors Atlas"
 },
 {
  "path": "/sectors",
  "comp": "SectorsAtlas",
  "title": "Sectors Atlas"
 },
 {
  "path": "/security",
  "comp": "TrustCenter",
  "title": "Trust Center"
 },
 {
  "path": "/service-level-agreement",
  "comp": "ServiceLevelAgreement",
  "title": "Service Level Agreement"
 },
 {
  "path": "/services",
  "comp": "Services",
  "title": "Services"
 },
 {
  "path": "/settings",
  "comp": "RequireAuth",
  "title": "Settings"
 },
 {
  "path": "/settings/billing",
  "comp": "RequireAuth",
  "title": "Settings Billing"
 },
 {
  "path": "/settings/notifications",
  "comp": "RequireAuth",
  "title": "Settings Notifications"
 },
 {
  "path": "/signals",
  "comp": "Signals",
  "title": "Signals"
 },
 {
  "path": "/signup",
  "comp": "Signup",
  "title": "Signup"
 },
 {
  "path": "/simulate",
  "comp": "Redirect",
  "title": "Simulate"
 },
 {
  "path": "/singapore-ai-governance",
  "comp": "JurisdictionAct",
  "title": "Singapore Ai Governance"
 },
 {
  "path": "/sla",
  "comp": "ServiceLevelAgreement",
  "title": "Service Level Agreement"
 },
 {
  "path": "/soai-pdca",
  "comp": "SOAIPDCAFramework",
  "title": "SOAIPDCAFramework"
 },
 {
  "path": "/soai-pdca/government",
  "comp": "GovernmentPortal",
  "title": "Government Portal"
 },
 {
  "path": "/social",
  "comp": "SocialOS",
  "title": "Social OS"
 },
 {
  "path": "/south-korea-ai-act",
  "comp": "JurisdictionAct",
  "title": "South Korea Ai Act"
 },
 {
  "path": "/sov-space",
  "comp": "Redirect",
  "title": "Sov Space"
 },
 {
  "path": "/sov-town-lab",
  "comp": "Redirect",
  "title": "Sov Town Lab"
 },
 {
  "path": "/sov-towns",
  "comp": "Redirect",
  "title": "Sov Towns"
 },
 {
  "path": "/sov3",
  "comp": "Redirect",
  "title": "Sov3"
 },
 {
  "path": "/sov3-model-card",
  "comp": "Redirect",
  "title": "Sov3 Model Card"
 },
 {
  "path": "/sov3-system-card",
  "comp": "Redirect",
  "title": "Sov3 System Card"
 },
 {
  "path": "/sov3-whitepaper",
  "comp": "Redirect",
  "title": "Sov3 Whitepaper"
 },
 {
  "path": "/sovereign",
  "comp": "Redirect",
  "title": "Sovereign"
 },
 {
  "path": "/sovereign-network",
  "comp": "Redirect",
  "title": "Sovereign Network"
 },
 {
  "path": "/sovereign-pricing",
  "comp": "Redirect",
  "title": "Sovereign Pricing"
 },
 {
  "path": "/sovereign-space",
  "comp": "Redirect",
  "title": "Sovereign Space"
 },
 {
  "path": "/sovereign-town",
  "comp": "Redirect",
  "title": "Sovereign Town"
 },
 {
  "path": "/sovereign-twin",
  "comp": "Redirect",
  "title": "Sovereign Twin"
 },
 {
  "path": "/standards",
  "comp": "Standards",
  "title": "Standards"
 },
 {
  "path": "/start",
  "comp": "OnboardOS",
  "title": "Onboard OS"
 },
 {
  "path": "/status",
  "comp": "StatusPage",
  "title": "Status Page"
 },
 {
  "path": "/statute-to-predicate",
  "comp": "StatuteToPredicate",
  "title": "Statute To Predicate"
 },
 {
  "path": "/stripe-checkout.js",
  "comp": "Gone",
  "title": "Gone"
 },
 {
  "path": "/support",
  "comp": "Support",
  "title": "Support"
 },
 {
  "path": "/system",
  "comp": "StatusPage",
  "title": "Status Page"
 },
 {
  "path": "/system-card",
  "comp": "SystemCard",
  "title": "System Card"
 },
 {
  "path": "/system-status",
  "comp": "Status",
  "title": "Status"
 },
 {
  "path": "/systemcard",
  "comp": "SystemCard",
  "title": "System Card"
 },
 {
  "path": "/tc260",
  "comp": "TC260Guide",
  "title": "TC260 Guide"
 },
 {
  "path": "/technology",
  "comp": "Technology",
  "title": "Technology"
 },
 {
  "path": "/temples",
  "comp": "Temples",
  "title": "Temples"
 },
 {
  "path": "/terms",
  "comp": "TermsOfService",
  "title": "Terms Of Service"
 },
 {
  "path": "/terms-of-service",
  "comp": "TermsOfService",
  "title": "Terms Of Service"
 },
 {
  "path": "/texas-ai-act",
  "comp": "UsStateAct",
  "title": "Texas Ai Act"
 },
 {
  "path": "/tool-commons",
  "comp": "ToolCommons",
  "title": "Tool Commons"
 },
 {
  "path": "/tools",
  "comp": "ToolCommons",
  "title": "Tool Commons"
 },
 {
  "path": "/tour",
  "comp": "SovereignTour",
  "title": "Sovereign Tour"
 },
 {
  "path": "/towns",
  "comp": "Redirect",
  "title": "Towns"
 },
 {
  "path": "/tracks",
  "comp": "Academy",
  "title": "Academy"
 },
 {
  "path": "/traction",
  "comp": "Traction",
  "title": "Traction"
 },
 {
  "path": "/training",
  "comp": "TrainingV2",
  "title": "Training"
 },
 {
  "path": "/training-hub",
  "comp": "TrainingHub",
  "title": "Training Hub"
 },
 {
  "path": "/transparency",
  "comp": "PublicDashboard",
  "title": "Public Dashboard"
 },
 {
  "path": "/trust-center",
  "comp": "TrustCenter",
  "title": "Trust Center"
 },
 {
  "path": "/try",
  "comp": "TryCouncil",
  "title": "Try Council"
 },
 {
  "path": "/uk-ai-regulation",
  "comp": "JurisdictionAct",
  "title": "Uk Ai Regulation"
 },
 {
  "path": "/us-ai-regulation",
  "comp": "JurisdictionAct",
  "title": "Us Ai Regulation"
 },
 {
  "path": "/usp",
  "comp": "WhyCSOAI",
  "title": "Why CSOAI"
 },
 {
  "path": "/vanta-alternative",
  "comp": "AltPage",
  "title": "Vanta Alternative"
 },
 {
  "path": "/verifiable-trust",
  "comp": "VerifiableTrust",
  "title": "Verifiable Trust"
 },
 {
  "path": "/verify-certificate",
  "comp": "CertificateVerification",
  "title": "Certificate Verification"
 },
 {
  "path": "/verify-leaderboard",
  "comp": "VerifyLeaderboard",
  "title": "Verify Leaderboard"
 },
 {
  "path": "/voice",
  "comp": "SovereignMinds",
  "title": "Sovereign Minds"
 },
 {
  "path": "/vs",
  "comp": "Compare",
  "title": "Compare"
 },
 {
  "path": "/vs-competitors",
  "comp": "Compare",
  "title": "Compare"
 },
 {
  "path": "/vulnerability-disclosure",
  "comp": "VulnerabilityDisclosure",
  "title": "Vulnerability Disclosure"
 },
 {
  "path": "/watchdog",
  "comp": "Watchdog",
  "title": "Watchdog"
 },
 {
  "path": "/watchdog-heatmap",
  "comp": "WatchdogMap",
  "title": "Watchdog Map"
 },
 {
  "path": "/watchdog-hub",
  "comp": "PublicWatchdogHub",
  "title": "Public Watchdog Hub"
 },
 {
  "path": "/watchdog-leaderboard",
  "comp": "WatchdogLeaderboard",
  "title": "Watchdog Leaderboard"
 },
 {
  "path": "/watchdog-map",
  "comp": "WatchdogMap",
  "title": "Watchdog Map"
 },
 {
  "path": "/watchdog-signup",
  "comp": "WatchdogSignup",
  "title": "Watchdog Signup"
 },
 {
  "path": "/watchdog/help-protect-humanity",
  "comp": "WatchdogHelpProtectHumanity",
  "title": "Watchdog Help Protect Humanity"
 },
 {
  "path": "/watchdog/incident",
  "comp": "WatchdogIncidentReport",
  "title": "Watchdog Incident Report"
 },
 {
  "path": "/watchdog/report",
  "comp": "PublicWatchdogHub",
  "title": "Public Watchdog Hub"
 },
 {
  "path": "/webhooks",
  "comp": "Webhooks",
  "title": "Webhooks"
 },
 {
  "path": "/welcome",
  "comp": "Welcome",
  "title": "Welcome"
 },
 {
  "path": "/where-the-record-lives",
  "comp": "WhereTheRecordLives",
  "title": "Where The Record Lives"
 },
 {
  "path": "/white-label",
  "comp": "EmbedPage",
  "title": "Embed Page"
 },
 {
  "path": "/why",
  "comp": "WhyCSOAI",
  "title": "Why CSOAI"
 },
 {
  "path": "/why-csoai",
  "comp": "WhyCSOAI",
  "title": "Why CSOAI"
 },
 {
  "path": "/widget",
  "comp": "WidgetCourses",
  "title": "Widget Courses"
 },
 {
  "path": "/workbench",
  "comp": "RequireAuth",
  "title": "Workbench"
 },
 {
  "path": "/workbench-paper",
  "comp": "CouncilWhitepaper",
  "title": "Council Whitepaper"
 },
 {
  "path": "/world",
  "comp": "Redirect",
  "title": "World"
 },
 {
  "path": "/world-3d",
  "comp": "RealWorldMap",
  "title": "Real World Map"
 },
 {
  "path": "/world-data",
  "comp": "GovGraph",
  "title": "Gov Graph"
 },
 {
  "path": "/xrpl-attest",
  "comp": "XrplAttest",
  "title": "Xrpl Attest"
 }
];
