// GENERATED by extensions/chrome-gspc-verify/scripts/build.mjs from
// functions/_lib/cardVerify.ts — do not edit; edit the source and rebuild.


// functions/_lib/cardVerify.ts
var CARD_ATTESTATION_KID = "did:web:csoai.org#card-attestation-1";
var CARD_ATTESTATION_HEX = "d4cb0eaa16d5f50bf7633a36aa34fe09a55e124b9316ded2abdb122bb9c37e38";
var PINNED_ANCHORS = [
  { id: "did:web:csoai.org#site-release-1", hex: "d3783d97e75534654401555642b254f5a2ed9184cddee011779d8fec312afbc8" },
  { id: "did:web:csoai.org#estate-chain-1", hex: "33472e026871db20cdbd99e76c47532ebfcf84b37abed5b260dae3589df5696d" },
  { id: "did:web:csoai.org#board-attestation-1", hex: "9367cf59be9cb72bbc9796adf056201ec1c58adfeaa13f83b2c5b754d6c20170" },
  { id: CARD_ATTESTATION_KID, hex: CARD_ATTESTATION_HEX }
];
var GSPC_FLOAT_FIELDS = (k) => k === "accuracy" || k.endsWith("_ci_low") || k.endsWith("_ci_high");
var NO_FLOAT_FIELDS = () => false;
function pyString(s) {
  return JSON.stringify(s).replace(
    /[\u0080-\uffff]/g,
    (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0")
  );
}
function pyNumber(v, isFloat) {
  if (!Number.isFinite(v)) {
    throw new Error("non-finite number in preimage");
  }
  if (isFloat && Number.isInteger(v)) return v.toFixed(1);
  return JSON.stringify(v);
}
function byCodePoint(a, b) {
  const ca = [...a];
  const cb = [...b];
  for (let i = 0; i < Math.min(ca.length, cb.length); i++) {
    const d = ca[i].codePointAt(0) - cb[i].codePointAt(0);
    if (d !== 0) return d;
  }
  return ca.length - cb.length;
}
function pyCanonical(v, isFloatField = NO_FLOAT_FIELDS) {
  if (v === null) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return pyNumber(v, false);
  if (typeof v === "string") return pyString(v);
  if (Array.isArray(v)) return "[" + v.map((x) => pyCanonical(x, isFloatField)).join(",") + "]";
  if (typeof v === "object") {
    const o = v;
    return "{" + Object.keys(o).sort(byCodePoint).map((k) => {
      const val = o[k];
      const rendered = typeof val === "number" ? pyNumber(val, isFloatField(k)) : pyCanonical(val, isFloatField);
      return pyString(k) + ":" + rendered;
    }).join(",") + "}";
  }
  throw new Error("value is not JSON");
}
function hexToBytes(s) {
  return Uint8Array.from(s.match(/.{2}/g) ?? [], (h) => parseInt(h, 16));
}
function bytesToHex(b) {
  return [...b].map((x) => x.toString(16).padStart(2, "0")).join("");
}
function b64ToBytes(s) {
  const bin = atob(s.replace(/-/g, "+").replace(/_/g, "/"));
  return Uint8Array.from(bin, (c) => c.charCodeAt(0));
}
function bytesToB64(b) {
  return btoa(String.fromCharCode(...b));
}
async function sha256hex(bytes) {
  const d = await crypto.subtle.digest("SHA-256", bytes);
  return bytesToHex(new Uint8Array(d));
}
var utf8 = (s) => new TextEncoder().encode(s);
function decodeSig(sig) {
  try {
    if (/^[0-9a-fA-F]+$/.test(sig) && sig.length % 2 === 0) return hexToBytes(sig);
    return b64ToBytes(sig);
  } catch {
    return null;
  }
}
function decodeKey(k) {
  try {
    if (/^[0-9a-fA-F]{64}$/.test(k)) return hexToBytes(k);
    return b64ToBytes(k);
  } catch {
    return null;
  }
}
var Ed25519Unsupported = class extends Error {
};
async function ed25519Verify(pubkey, sig, msg) {
  let key;
  try {
    key = await crypto.subtle.importKey(
      "raw",
      pubkey,
      { name: "Ed25519" },
      false,
      ["verify"]
    );
  } catch (e) {
    if (e?.name === "NotSupportedError") {
      throw new Ed25519Unsupported("this runtime's WebCrypto lacks Ed25519");
    }
    return false;
  }
  try {
    return await crypto.subtle.verify(
      { name: "Ed25519" },
      key,
      sig,
      msg
    );
  } catch {
    return false;
  }
}
function anchorsFromDid(did) {
  const methods = did?.verificationMethod ?? [];
  const out = [];
  for (const m of methods) {
    try {
      if (m.publicKeyHex) out.push({ id: m.id, hex: m.publicKeyHex.toLowerCase() });
      else if (m.publicKeyJwk?.x) out.push({ id: m.id, hex: bytesToHex(b64ToBytes(m.publicKeyJwk.x)) });
    } catch {
    }
  }
  return out;
}
function isObj(v) {
  return !!v && typeof v === "object" && !Array.isArray(v);
}
function detectFamily(rec) {
  if (!isObj(rec)) return "unknown";
  if (isObj(rec.body) && typeof rec.id === "string" && typeof rec.signature === "string" && typeof rec.pubkey === "string") {
    return "gspc.measurement-card";
  }
  if (typeof rec.content_id === "string" && isObj(rec.signature)) return "csoai.content-id-card";
  if (typeof rec.content_id === "string") return "csoai.estate-envelope";
  return "unknown";
}
var FAMILY_LABEL = {
  // A family label names a SHAPE. It used to carry "(the 150 signed board cards)" — a typed
  // census inside a type name, shown on /gspc-verify and returned as `family_label` by the MCP
  // verify tool. public/signed/cards/ holds 313 card files and the packaged verifier reports
  // VALID 313 · INVALID 0 · UNCHECKABLE 0 over them, so the label contradicted the bytes it
  // was describing. Counts belong in /api/state (signed_cards.count), which derives them.
  "gspc.measurement-card": "Measurement card \u2014 a signed GSPC board card.",
  "csoai.content-id-card": "Content_id card (cross-border / axis-signal family).",
  "csoai.estate-envelope": "Estate envelope (content_id, unsigned or flat signature).",
  unknown: "unrecognised"
};
async function verifyCard(rec, anchors) {
  const family = detectFamily(rec);
  const checks = [];
  const reasons = [];
  const fail = (code) => {
    if (!reasons.includes(code)) reasons.push(code);
  };
  if (family === "unknown") {
    checks.push({
      label: "Family",
      ok: null,
      code: "unrecognised_family",
      detail: "UNRECOGNISED \u2014 not a shape CSOAI publishes, so nothing was checked. This is not a claim that the document is forged. Expected either a gspc.measurement-card (top-level id + body + pubkey + signature) or a content_id card (top-level content_id + signature)."
    });
    return { family, family_label: FAMILY_LABEL[family], valid: false, reasons: ["unrecognised_family"], checks, id: null };
  }
  const r = rec;
  checks.push({
    label: "Family",
    ok: true,
    code: "family",
    detail: `${family} \u2014 ${FAMILY_LABEL[family]}.`
  });
  let preimage;
  let declaredId;
  let sigOver;
  let sigRaw;
  let keyRaw;
  let idLabel;
  try {
    if (family === "gspc.measurement-card") {
      idLabel = "Card id";
      declaredId = r.id;
      preimage = utf8(pyCanonical(r.body, GSPC_FLOAT_FIELDS));
      sigOver = preimage;
      sigRaw = r.signature;
      keyRaw = r.pubkey;
    } else {
      idLabel = "content_id";
      declaredId = r.content_id;
      const body = {};
      for (const k of Object.keys(r)) if (k !== "content_id" && k !== "signature") body[k] = r[k];
      preimage = utf8(pyCanonical(body, NO_FLOAT_FIELDS));
      sigOver = utf8(declaredId);
      const s = r.signature;
      if (isObj(s)) {
        sigRaw = typeof s.sig === "string" ? s.sig : typeof s.signature === "string" ? s.signature : null;
        keyRaw = typeof s.pubkey === "string" ? s.pubkey : null;
      } else {
        sigRaw = typeof s === "string" ? s : null;
        keyRaw = typeof r.pubkey === "string" ? r.pubkey : null;
      }
    }
  } catch (e) {
    checks.push({
      label: "Preimage",
      ok: false,
      code: "preimage_uncomputable",
      detail: `The signed bytes could not be reconstructed: ${e.message}.`
    });
    return { family, family_label: FAMILY_LABEL[family], valid: false, reasons: ["preimage_uncomputable"], checks, id: null };
  }
  let computed = await sha256hex(preimage);
  let idOk = computed === declaredId;
  let integralAsInt = false;
  if (!idOk && family === "gspc.measurement-card") {
    const alt = utf8(pyCanonical(r.body, NO_FLOAT_FIELDS));
    const altHex = await sha256hex(alt);
    if (altHex === declaredId) {
      preimage = alt;
      sigOver = alt;
      computed = altHex;
      idOk = true;
      integralAsInt = true;
    }
  }
  if (!idOk) fail("preimage_mismatch");
  checks.push({
    label: idLabel,
    ok: idOk,
    code: idOk ? "id_match" : "preimage_mismatch",
    detail: idOk ? `sha256 of the canonical body reproduces ${declaredId.slice(0, 16)}\u2026` : `MISMATCH \u2014 the card declares ${declaredId.slice(0, 16)}\u2026 but its body hashes to ${computed.slice(0, 16)}\u2026. The body was altered, or it was serialised by a different rule. This says nothing about which key signed it.`
  });
  if (integralAsInt) {
    checks.push({
      label: "Preimage rendering",
      ok: null,
      code: "integral_numbers_as_int",
      detail: 'The declared-float fields hold integral values that the signer rendered as integers ("0", not "0.0"). That rendering reproduces the id, so it is the signed preimage; the signature is checked over exactly those bytes.'
    });
  }
  const keyBytes = keyRaw ? decodeKey(keyRaw) : null;
  const keyHex = keyBytes ? bytesToHex(keyBytes) : null;
  let anchorId = null;
  if (!keyHex) {
    checks.push({
      label: "Signing key",
      ok: false,
      code: "key_malformed",
      detail: "The card carries no readable public key."
    });
    fail("key_malformed");
  } else {
    const pinnedHit = PINNED_ANCHORS.find((a) => a.hex === keyHex);
    if (pinnedHit) {
      anchorId = pinnedHit.id;
      checks.push({
        label: "Trust anchor",
        ok: true,
        code: "anchor_match",
        detail: `${keyHex.slice(0, 8)}\u2026 is published as ${pinnedHit.id} \u2014 matched against the anchor set pinned in this verifier's source, so no key was looked up at check time.`
      });
      if (family === "gspc.measurement-card" && keyHex !== CARD_ATTESTATION_HEX) {
        fail("wrong_anchor_for_family");
        checks.push({
          label: "Expected anchor",
          ok: false,
          code: "wrong_anchor_for_family",
          detail: `A gspc.measurement-card must be signed by ${CARD_ATTESTATION_KID}; this one is not.`
        });
      }
    } else {
      fail("untrusted_signer");
      checks.push({
        label: "Trust anchor",
        ok: false,
        code: "untrusted_signer",
        detail: `${keyHex.slice(0, 8)}\u2026 is NOT among the keys published at did:web:csoai.org and pinned in this verifier. A card that carries its own key proves only self-consistency \u2014 anyone can mint one. The signature check below is reported separately.`
      });
    }
    if (anchors.length > 0) {
      const liveHit = anchors.find((a) => a.hex === keyHex);
      const agrees = !!liveHit === !!pinnedHit;
      checks.push({
        label: "Live anchor cross-check",
        ok: null,
        code: agrees ? "live_anchor_agrees" : "live_anchor_disagrees",
        detail: agrees ? "The live did.json agrees with the pinned anchor set for this key. Cross-check only \u2014 the pinned set decided." : `The live did.json ${liveHit ? "lists" : "does not list"} this key while the pinned set ${pinnedHit ? "also does" : "does not"} \u2014 the published document has drifted from this verifier's pin. The pinned set decided the verdict above; treat the drift as a reason to re-fetch this verifier, not to re-fetch the key.`
      });
    } else {
      checks.push({
        label: "Live anchor cross-check",
        ok: null,
        code: "live_anchor_unavailable",
        detail: "did.json was not consulted or could not be fetched. The verdict is unaffected: the trust anchor is pinned in this verifier's source, and the live document is only ever a cross-check."
      });
    }
  }
  if (!sigRaw) {
    checks.push({ label: "Signature", ok: null, code: "unsigned", detail: "UNSIGNED \u2014 hash only." });
  } else {
    const sigBytes = decodeSig(sigRaw);
    if (!sigBytes || !keyBytes) {
      fail("signature_malformed");
      checks.push({
        label: "Signature",
        ok: false,
        code: "signature_malformed",
        detail: "The signature or key could not be decoded as hex or base64."
      });
    } else {
      try {
        const sigOk = await ed25519Verify(keyBytes, sigBytes, sigOver);
        if (!sigOk) fail("signature_invalid");
        checks.push({
          label: "Signature",
          ok: sigOk,
          code: sigOk ? "signature_valid" : "signature_invalid",
          detail: sigOk ? `VALID against ${anchorId ?? `an unpublished key ${keyHex?.slice(0, 8)}\u2026`} \u2014 Ed25519 verifies over ${family === "gspc.measurement-card" ? "the canonical body bytes" : "the content_id"}.` : `INVALID \u2014 the signature does not verify over ${family === "gspc.measurement-card" ? "the canonical body bytes" : "the content_id"} under the key the card carries. The bytes and the signature disagree; this is not a statement about key publication.`
        });
      } catch (e) {
        if (e instanceof Ed25519Unsupported) {
          fail("ed25519_unsupported");
          checks.push({
            label: "Signature",
            ok: null,
            code: "ed25519_unsupported",
            detail: "This browser's WebCrypto has no Ed25519, so the signature could not be checked here. The hash above was still recomputed locally. Verify offline with the recipe at /signed/HOW-TO-VERIFY.md."
          });
        } else {
          throw e;
        }
      }
    }
  }
  const valid = reasons.length === 0 && checks.every((c) => c.ok !== false);
  const framing = rec?.body?.public_framing;
  if (typeof framing === "string") {
    checks.push({
      label: "Framing",
      ok: null,
      code: "framing_frozen",
      detail: `The card carries public_framing "${framing}". A card is signed over its own bytes and cannot be re-signed, so this string is frozen \u2014 read the live count from GET /api/gspc, never from inside a card.`
    });
  }
  return { family, family_label: FAMILY_LABEL[family], valid, reasons, checks, id: declaredId };
}
export {
  CARD_ATTESTATION_HEX,
  CARD_ATTESTATION_KID,
  Ed25519Unsupported,
  GSPC_FLOAT_FIELDS,
  NO_FLOAT_FIELDS,
  PINNED_ANCHORS,
  anchorsFromDid,
  b64ToBytes,
  bytesToB64,
  bytesToHex,
  detectFamily,
  hexToBytes,
  pyCanonical,
  sha256hex,
  verifyCard
};
