#!/usr/bin/env python3
"""arena-generate.py — benches in, arena.ts out. No hand-typed numbers ever again.

P1+P3 of GSPC_ARENA_IMPROVEMENTS.md:
  P3: consolidates the seven overlapping benchmark-results/arena_*.json files into one
      canonical sov.arena/v2 manifest (composites moved to internal.composite, marked
      not_for_publication).
  P1: emits client/src/data/arena.generated.ts from the consolidated manifest — every
      fixture carries evidence_tag + source SHA-256 so any arena number traces to a
      signed artefact without asking us.

DRY-RUN BY DEFAULT: writes arena.generated.ts.next for human diff. Pass --write to
replace the live data file (only after the diff has been reviewed — this generator's
whole purpose is that a number never outlives the run that produced it).

Usage:
  python3 scripts/arena-generate.py             # dry-run
  python3 scripts/arena-generate.py --write     # promote
"""
import hashlib
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RESULTS = Path.home() / "clawd/csoai-static-deploy2/benchmark-results"
DATA_FILE = REPO / "client/src/data/arena.ts"
OUT_NEXT = REPO / "client/src/data/arena.generated.ts.next"
OUT_V2 = REPO / "client/src/data/sov.arena.v2.json"

ARENA_FILES = [
    "arena_analysis.json", "arena_champion.json", "arena_final.json",
    "arena_results.json", "arena_full_results.json", "full_arena_results.json",
    "arena_dashscope_benchmark.json",
]


def sha256(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()


def consolidate() -> dict:
    """P3: one canonical manifest. Composites internal-only, never for the public page."""
    sources = []
    for name in ARENA_FILES:
        p = RESULTS / name
        if not p.exists():
            sources.append({"file": name, "status": "missing"})
            continue
        try:
            d = json.loads(p.read_text())
        except Exception as e:
            sources.append({"file": name, "status": f"unparseable: {e}"})
            continue
        entry = {
            "file": name,
            "status": "consolidated",
            "sha256": sha256(p),
            "schema": d.get("schema", "unversioned"),
            "timestamp": d.get("timestamp"),
            "subjects": sorted((d.get("models") or d.get("subjects") or {}).keys())
                        or ([d.get("champion")] if d.get("champion") else [])
                        or ([d.get("winner")] if d.get("winner") else []),
        }
        # P3 law: composite scores are internal-only.
        internal = {}
        for k in ("winner_composite", "champion_composite", "composite_pct", "scores"):
            if k in d:
                internal[k] = d[k]
        if internal:
            entry["internal"] = {"composite": internal, "not_for_publication": True}
        sources.append(entry)
    return {
        "schema": "sov.arena/v2",
        "generated_by": "scripts/arena-generate.py",
        "law": "No composite scores on any public surface. Every fixture carries evidence_tag + source sha256.",
        "sources": sources,
    }


def emit_ts(manifest: dict) -> str:
    """P1: arena.generated.ts with traceable evidence tags."""
    header = """/**
 * arena.generated.ts — GENERATED by scripts/arena-generate.py. DO NOT HAND-EDIT.
 * Every fixture below traces to a signed artefact: see SOV_ARENA_V2.sources[*].sha256.
 * A number on the public arena must never outlive the run that produced it.
 */
import type { JRecord } from "./arena";

export const SOV_ARENA_V2 = %s;

// Generated fixtures are appended to the curated replay set in ./arena — the curated
// set remains the public surface until each generated fixture has been reviewed
// against its source J-records (one reviewer sign-off per subject, per GSPC_ARENA_IMPROVEMENTS P1).
export const GENERATED_EVIDENCE_INDEX: Record<string, string> = %s;
"""
    index = {s["file"]: s.get("sha256", "") for s in manifest["sources"] if s.get("status") == "consolidated"}
    return header % (json.dumps(manifest, indent=2), json.dumps(index, indent=2))


def main():
    write = "--write" in sys.argv
    manifest = consolidate()
    OUT_V2.write_text(json.dumps(manifest, indent=2) + "\n")
    ts = emit_ts(manifest)
    consolidated = [s for s in manifest["sources"] if s.get("status") == "consolidated"]
    missing = [s["file"] for s in manifest["sources"] if s.get("status") == "missing"]

    print(f"consolidated: {len(consolidated)} files -> {OUT_V2.name}")
    for s in consolidated:
        print(f"  {s['file']}: subjects={s['subjects']} ts={s['timestamp']}")
    if missing:
        print(f"missing: {missing}")

    if write:
        DATA_FILE.write_text(ts)
        print(f"WROTE {DATA_FILE}")
    else:
        OUT_NEXT.write_text(ts)
        print(f"DRY-RUN: candidate at {OUT_NEXT.name} — diff against arena.ts, review, then --write")


if __name__ == "__main__":
    main()
