#!/usr/bin/env python3
"""art50_probe v0 — deterministic EU AI Act Article 50 transparency probe.

WHAT IT IS:  a heuristic, evidence-carrying scanner (50(1) disclosure, 50(2)
             machine-readable marking, 50(4) deepfake/AI-media labelling) over
             live sites. Every verdict carries its evidence snippet or the
             explicit note "checked, none found". JSON output.
WHAT IT IS NOT: certification, a credential, or signed. Output is UNSIGNED probe
             observations (measurement-class data; signed cards come from the
             CSOAI pipeline separately). Stdlib-only (curl fallback for the
             Mac cert quirk). No prices ever appear in output.
Usage:       python3 art50_probe.py https://example.com [--json out.json]
"""
import json
import re
import subprocess
import sys
import urllib.request
from datetime import datetime, timezone

UA = "CSOAI-Art50-Probe/0.1 (+councilof.ai; independent measurement, not certification)"

DISCLOSURE_PATTERNS = [
    r"\bAI assistant\b", r"\bAI[- ]powered assistant\b", r"\bI am an AI\b",
    r"\bAI chatbot\b", r"\bchatbot\b", r"\bvirtual assistant\b",
    r"\bAI[- ]generated\b", r"\bgenerated by (an? )?AI\b", r"\bartificial intelligence\b",
]
MARKING_PATTERNS = [
    (r'c2pa|jumb\s*manifest|contentcredentials', "C2PA/Content Credentials"),
    (r'trainedAlgorithmicMedia|digitalSourceType|IPTC.*[Aa]lgorithmic', "IPTC algorithmic-media metadata"),
    (r'name=["\']ai-generated["\']|property=["\']ai:generated|aiGenerated', "ai-generated meta tags"),
    (r'"@type"\s*:\s*"SoftwareApplication"|json-ld|application/ld\+json', "JSON-LD structured data"),
]
MEDIA_LABEL_PATTERNS = [
    r"AI[- ]generated (image|video|audio|media)", r"deepfake", r"synthetic (image|video|audio|media)",
    r"generated with AI", r"created using AI", r"machine[- ]generated",
]
CHAT_WIDGET_MARKERS = [
    "intercom", "drift", "crisp.chat", "zendesk", "hubspot.*chat", "chatwoot",
    "openai.*chat", "chatgpt", "dialogflow", "landbot", "typebot", "ada.cx",
    "kommunicate", "tidio", "livechat", "gorgias", "voiceflow", "botpress",
]


def fetch(url: str) -> str:
    """Fetch with urllib; fall back to curl -sk on the local cert quirk."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        with urllib.request.urlopen(req, timeout=20) as r:
            return r.read(500_000).decode("utf-8", "replace")
    except Exception:
        try:
            out = subprocess.run(["curl", "-skL", "--max-time", "20", "-A", UA, url],
                                 capture_output=True, text=True, timeout=30)
            return out.stdout[:500_000]
        except Exception:
            return ""


def probe(url: str) -> dict:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    if not url.startswith("http"):
        url = "https://" + url
    html = fetch(url)
    if not html:
        return {"url": url, "ts": ts, "error": "UNREACHABLE (fetch failed)", "verdicts": None}
    low = html.lower()

    # 50(1) — AI interaction disclosure
    chat = [m for m in CHAT_WIDGET_MARKERS if re.search(m, low)]
    disc = []
    for pat in DISCLOSURE_PATTERNS:
        m = re.search(pat, html, re.I)
        if m:
            disc.append(html[max(0, m.start() - 60):m.end() + 60].replace("\n", " ")[:140])
    v501 = ("PASS" if disc else ("ABSENT" if chat else "N/A-NO-AI-SURFACE-DETECTED"))

    # 50(2) — machine-readable marking of synthetic content
    marks = []
    for pat, label in MARKING_PATTERNS:
        if re.search(pat, html, re.I):
            marks.append(label)
    v502 = "PASS" if any(m for m in marks if m != "JSON-LD structured data") else ("PARTIAL" if marks else "ABSENT")

    # 50(4) — deepfake / AI-media labelling
    labels = []
    for pat in MEDIA_LABEL_PATTERNS:
        m = re.search(pat, html, re.I)
        if m:
            labels.append(html[max(0, m.start() - 50):m.end() + 50].replace("\n", " ")[:120])
    v504 = "PASS" if labels else "ABSENT-OR-N/A"

    return {
        "url": url, "ts": ts, "bytes_scanned": len(html),
        "chat_widgets": chat[:4] or "none-detected",
        "verdicts": {
            "art50_1_disclosure": {"verdict": v501, "evidence": disc[:2] or "checked, none found (may be JS-mounted)"},
            "art50_2_marking": {"verdict": v502, "evidence": marks or "checked, none found"},
            "art50_4_media_labels": {"verdict": v504, "evidence": labels[:2] or "checked, none found"},
        },
        "disclaimer": "UNSIGNED probe v0 heuristic observation — measurement data, NOT certification or a credential. JS-mounted widgets may evade static scan.",
    }


def main():
    urls = sys.argv[1:] or ["https://councilof.ai"]
    results = [probe(u) for u in urls if not u.startswith("--")]
    out = {"probe": "art50_probe v0", "class": "independent measurement (not certification)",
           "results": results}
    txt = json.dumps(out, indent=2)
    for a, b in zip(sys.argv, sys.argv[1:]):
        if a == "--json":
            open(b, "w").write(txt)
            print(f"written: {b}")
    print(txt[:2500])


if __name__ == "__main__":
    main()
