#!/usr/bin/env python3
"""Rebuild the OTS manifest from what the files actually are, and quarantine what they are not.

WHY. public/interop/ots/manifest.json claimed 566 proofs, each row asserting
state PENDING_BITCOIN_CONFIRMATION. Checked on 17 September 2026, ZERO of the 566 parsed as an
OpenTimestamps proof: every one was a calendar response fragment saved under the .ots name. A row
asserting a stamp is awaiting confirmation, for bytes that are not a stamp, is a false claim about
evidence, which is the most serious kind this estate can make.

The deploy gate held it, so it never reached the public. This makes the repository honest too.

RULE: a manifest is generated from the bytes, never from the intention. This script reads every
.ots under the directory, keeps only those that deserialize, and writes the count it measured.
"""
import argparse, hashlib, json, pathlib, sys, datetime

sys.path.insert(0, "scripts")
from opentimestamps.core.serialize import BytesDeserializationContext
from opentimestamps.core.timestamp import DetachedTimestampFile


def classify(p: pathlib.Path):
    try:
        dtf = DetachedTimestampFile.deserialize(BytesDeserializationContext(p.read_bytes()))
        kinds = {type(a).__name__ for _, a in dtf.timestamp.all_attestations()}
        return ("BITCOIN" if "BitcoinBlockHeaderAttestation" in kinds else "PENDING"), dtf
    except Exception:
        return "NOT_A_PROOF", None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", default="public/interop/ots")
    ap.add_argument("--apply", action="store_true", help="quarantine non-proofs and write the manifest")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()

    if a.selftest:
        import tempfile
        t = pathlib.Path(tempfile.mkdtemp())
        (t / "fake.ots").write_bytes(b"this is not a timestamp")
        assert classify(t / "fake.ots")[0] == "NOT_A_PROOF", "a non-proof was classified as a proof"
        real = next(pathlib.Path("public").rglob("*.ots"), None)
        if real:
            assert classify(real)[0] != "NOT_A_PROOF", "a real proof was classified as a non-proof"
            print("selftest OK: a non-proof is rejected and a real proof is accepted")
        else:
            print("selftest PARTIAL: no real proof on disk to use as the positive control")
        return 0

    d = pathlib.Path(a.dir)
    if not d.exists():
        print(f"{d} does not exist"); return 1
    keep, drop = [], []
    for p in sorted(d.glob("*.ots")):
        state, _ = classify(p)
        (drop if state == "NOT_A_PROOF" else keep).append((p, state))

    print(f"{d}: {len(keep) + len(drop)} file(s) carrying the .ots name")
    print(f"  real proofs   : {len(keep)}")
    print(f"  NOT proofs    : {len(drop)}")

    if not a.apply:
        print("\n(dry run — pass --apply to quarantine and rewrite the manifest)")
        return 0

    for p, _ in drop:
        p.rename(p.with_suffix(p.suffix + ".invalid"))

    manifest = {
        "schema": "csoai.ots-manifest/0.3",
        "as_of": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "how_this_was_built": ("Generated by reading every .ots file in this directory and keeping only "
                               "those that deserialize as an OpenTimestamps detached proof. Never from a "
                               "list of files we intended to stamp."),
        "counts": {
            "proofs": len(keep),
            "bitcoin_attested": sum(1 for _, s in keep if s == "BITCOIN"),
            "calendar_pending": sum(1 for _, s in keep if s == "PENDING"),
            "quarantined_not_proofs": len(drop),
        },
        "pending_is_not_anchored": ("A calendar-pending proof is a submitted request, not evidence of a "
                                    "time. Only a Bitcoin attestation is that."),
        "supersedes": ("csoai.ots-manifest/0.2, which claimed 566 proofs of which none parsed. See "
                       "the correction register."),
        "proofs": [{"file": p.name, "state": s,
                    "sha256_of_proof": hashlib.sha256(p.read_bytes()).hexdigest()} for p, s in keep],
    }
    (d / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\nquarantined {len(drop)} file(s) as .ots.invalid")
    print(f"manifest rewritten: {len(keep)} proof(s), {manifest['counts']['bitcoin_attested']} Bitcoin-attested")
    return 0


if __name__ == "__main__":
    sys.exit(main())
