#!/usr/bin/env python3
"""Rebuild the OTS manifest from what the files actually are, and quarantine what they are not.

WHY. public/interop/ots/manifest.json claimed 566 proofs, each row asserting
state PENDING_BITCOIN_CONFIRMATION. Checked on 17 September 2026, ZERO of the 566 parsed as an
OpenTimestamps proof: every one was a calendar response fragment saved under the .ots name. A row
asserting a stamp is awaiting confirmation, for bytes that are not a stamp, is a false claim about
evidence, which is the most serious kind this estate can make.

The deploy gate held it, so it never reached the public. This makes the repository honest too.

RULE: a manifest is generated from the bytes, never from the intention. This script reads every
.ots under the directories it is given, keeps only those that deserialize, and writes the count it
measured.

SCOPE (2026-09-22, row 5 of WORK-NOT-DONE). The 0.3 manifest scanned ONE directory,
public/interop/ots/ — 10 proofs, none Bitcoin-attested — while 590 real proofs, 56 of them
carrying a BitcoinBlockHeaderAttestation, sat one level up in public/interop/ and were served
without a manifest row. "Anchored to Bitcoin" was invisible on our own site not because it was
false but because the producer looked in the wrong place. The default scan is now both
directories, each row carries the URL path it is served at, and a "staged" manifest is never
copied in: the numbers come from running this over the tree.

    python3 scripts/ots_manifest_rebuild.py                       # dry run over the default dirs
    python3 scripts/ots_manifest_rebuild.py --apply               # quarantine non-proofs, write the manifest
    python3 scripts/ots_manifest_rebuild.py --dir X --dir Y --out Z --apply
"""
import argparse, hashlib, json, pathlib, sys, datetime

sys.path.insert(0, "scripts")
from opentimestamps.core.serialize import BytesDeserializationContext
from opentimestamps.core.timestamp import DetachedTimestampFile

SCHEMA = "csoai.ots-manifest/0.4"
DEFAULT_DIRS = ["public/interop", "public/interop/ots"]
DEFAULT_OUT = "public/interop/ots/manifest.json"
PUBLIC = pathlib.Path("public")


def classify(p: pathlib.Path):
    try:
        dtf = DetachedTimestampFile.deserialize(BytesDeserializationContext(p.read_bytes()))
        kinds = {type(a).__name__ for _, a in dtf.timestamp.all_attestations()}
        return ("BITCOIN" if "BitcoinBlockHeaderAttestation" in kinds else "PENDING"), dtf
    except Exception:
        return "NOT_A_PROOF", None


def url_path(p: pathlib.Path, public: pathlib.Path) -> str:
    """The path a reader fetches. Files outside public/ (tests) are named by their own path."""
    try:
        return "/" + p.resolve().relative_to(public.resolve()).as_posix()
    except ValueError:
        return "/" + p.as_posix()


def row(p: pathlib.Path, state: str, public: pathlib.Path) -> dict:
    # A file-named proof (x.json.ots) asserts it is a detached proof OF x.json beside it. Whether
    # that subject is on disk is recorded, never assumed: an anchor without its subject is a
    # digest with a date, not evidence about any bytes a reader can fetch.
    subject = p.with_suffix("") if p.suffix == ".ots" and p.with_suffix("").suffix else None
    return {
        "file": p.name,
        "path": url_path(p, public),
        "state": state,
        "sha256_of_proof": hashlib.sha256(p.read_bytes()).hexdigest(),
        "subject": url_path(subject, public) if subject is not None else None,
        "subject_present": bool(subject is not None and subject.exists()),
    }


def build(dirs: list[pathlib.Path], public: pathlib.Path):
    keep, drop = [], []
    for d in dirs:
        for p in sorted(d.glob("*.ots")):
            state, _ = classify(p)
            (drop if state == "NOT_A_PROOF" else keep).append((p, state))
    manifest = {
        "schema": SCHEMA,
        "as_of": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "how_this_was_built": ("Generated by reading every .ots file in dirs_scanned and keeping only those that "
                               "deserialize as an OpenTimestamps detached proof. Never from a list of files we "
                               "intended to stamp, and never copied from a staged manifest."),
        "dirs_scanned": [url_path(d, public) for d in dirs],
        "counts": {
            "proofs": len(keep),
            "bitcoin_attested": sum(1 for _, s in keep if s == "BITCOIN"),
            "calendar_pending": sum(1 for _, s in keep if s == "PENDING"),
            "quarantined_not_proofs": len(drop),
            "subject_absent": sum(1 for p, _ in keep if not row(p, "", public)["subject_present"]),
        },
        "bitcoin_attested_means": ("The proof bytes carry a BitcoinBlockHeaderAttestation, parsed by python-opentimestamps. "
                                   "This producer does not check the block header against a Bitcoin node; "
                                   "`ots verify` with a node does that."),
        "pending_is_not_anchored": ("A calendar-pending proof is a submitted request, not evidence of a "
                                    "time. Only a Bitcoin attestation is that."),
        "subject_absent_means": ("The proof commits to a digest, but the file it is named for is not served beside it. "
                                 "A reader cannot check what was stamped; it is an anchor without a subject."),
        "supersedes": ("csoai.ots-manifest/0.3 (2026-09-17), which was true of one directory, /interop/ots/, and so "
                       "reported 10 proofs and 0 Bitcoin-attested while the proofs served from /interop/ were not "
                       "counted; and 0.2, which claimed 566 proofs of which none parsed. See the correction register."),
        "proofs": [row(p, s, public) for p, s in keep],
    }
    return manifest, keep, drop


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--dir", action="append", help=f"repeatable; default {DEFAULT_DIRS}")
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--public", default=str(PUBLIC), help="root that URL paths are relative to")
    ap.add_argument("--apply", action="store_true", help="quarantine non-proofs and write the manifest")
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args(argv)

    if a.selftest:
        import tempfile
        t = pathlib.Path(tempfile.mkdtemp())
        (t / "fake.ots").write_bytes(b"this is not a timestamp")
        assert classify(t / "fake.ots")[0] == "NOT_A_PROOF", "a non-proof was classified as a proof"
        real = next(pathlib.Path("public").rglob("*.ots"), None)
        if real:
            assert classify(real)[0] != "NOT_A_PROOF", "a real proof was classified as a non-proof"
            print("selftest OK: a non-proof is rejected and a real proof is accepted")
        else:
            print("selftest PARTIAL: no real proof on disk to use as the positive control")
        return 0

    dirs = [pathlib.Path(d) for d in (a.dir or DEFAULT_DIRS)]
    missing = [d for d in dirs if not d.exists()]
    if missing:
        print(f"{missing[0]} does not exist"); return 1
    public = pathlib.Path(a.public)
    manifest, keep, drop = build(dirs, public)

    print(f"{', '.join(map(str, dirs))}: {len(keep) + len(drop)} file(s) carrying the .ots name")
    print(f"  real proofs   : {len(keep)}  (BITCOIN {manifest['counts']['bitcoin_attested']}, "
          f"PENDING {manifest['counts']['calendar_pending']}, subject absent {manifest['counts']['subject_absent']})")
    print(f"  NOT proofs    : {len(drop)}")

    if not a.apply:
        print("\n(dry run — pass --apply to quarantine and rewrite the manifest)")
        return 0

    for p, _ in drop:
        p.rename(p.with_suffix(p.suffix + ".invalid"))

    out = pathlib.Path(a.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"\nquarantined {len(drop)} file(s) as .ots.invalid")
    print(f"manifest written to {out}: {len(keep)} proof(s), {manifest['counts']['bitcoin_attested']} Bitcoin-attested")
    return 0


if __name__ == "__main__":
    sys.exit(main())
