#!/usr/bin/env python3
"""Generate and check scripts/pod-loops/INSTALLED.json against the pod's live install.

Reads the live listing ("<sha256>  <name>" per line) on stdin — pod-loops-drift-check.sh
produces it, either locally on the pod or over ssh. This file holds the comparison so the
shell wrapper stays readable; it is never the thing that decides whether the pod is reachable.

Every failure is printed as a named line. A check that passes prints one RESULT line too: a
guard that says nothing when it agrees is indistinguishable from a guard that never ran.
"""
import argparse, datetime, hashlib, json, pathlib, re, sys

REPO_ONLY_DEFAULT = {
    "chain_tools.py": (
        "library, not a loop: mill-hourly.sh runs it as "
        "$CLONE/scripts/pod-loops/chain_tools.py from the repo checkout and it is never "
        "installed at $LOOPS. tests/pod_chain/test_chain_determinism.py covers it."
    ),
    "INSTALLED.json": "this manifest",
    "superseded": "retired scripts, kept as a directory of record",
}


def live_from_stdin():
    live = {}
    for line in sys.stdin.read().splitlines():
        line = line.strip()
        if not line:
            continue
        sha, _, name = line.partition("  ")
        if name:
            live[name] = sha
    return live


def mirror_shas(mirror: pathlib.Path):
    out = {}
    for p in sorted(mirror.iterdir()):
        if p.is_dir() or p.name == "INSTALLED.json":
            continue
        out[p.name] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


def scheduled_scripts(scheduler: pathlib.Path):
    """Every script the scheduler actually dispatches, from its dispatch lines only."""
    names = set()
    for raw in scheduler.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0] if raw.lstrip().startswith("#") else raw
        if not line.strip():
            continue
        names.update(re.findall(r'\$LOOPS/([A-Za-z0-9_.\-]+)', line))
        # the heartbeat is the one job invoked by absolute path, from the intake checkout
        names.update(re.findall(r'/([A-Za-z0-9_\-]+\.py)\s*\\?\s*$', line)
                     if "council-of-ai/scripts" in line else [])
    return names


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write"); ap.add_argument("--check")
    ap.add_argument("--mirror"); ap.add_argument("--doc"); ap.add_argument("--via", default="?")
    a = ap.parse_args()
    live = live_from_stdin()
    if not live:
        print("UNCHECKABLE empty live listing; NOT reporting agreement")
        return 2

    if a.write:
        path = pathlib.Path(a.write)
        prev = {}
        if path.exists():
            prev = json.loads(path.read_text(encoding="utf-8")).get("repo_only") or {}
        path.write_text(json.dumps({
            "_comment": (
                "GENERATED by scripts/pod-loops-drift-check.sh --write from the pod's live "
                "/workspace/lanes/loops. Do not hand-edit the installed map: the pod is the "
                "running system and this file only records it. repo_only is hand-maintained "
                "and each entry states why that file is in the repo but not installed."
            ),
            "generated_at": datetime.datetime.now(datetime.timezone.utc)
                            .strftime("%Y-%m-%dT%H:%M:%SZ"),
            "generated_from": a.via,
            "loops_dir": "/workspace/lanes/loops",
            "installed_count": len(live),
            "installed": dict(sorted(live.items())),
            "repo_only": prev or REPO_ONLY_DEFAULT,
        }, indent=2, sort_keys=False) + "\n", encoding="utf-8")
        return 0

    man = json.loads(pathlib.Path(a.check).read_text(encoding="utf-8"))
    mirror = pathlib.Path(a.mirror)
    repo = mirror_shas(mirror)
    repo_only = man.get("repo_only") or {}
    fails = []

    # 4. the manifest must still describe the live pod
    recorded = man.get("installed") or {}
    for name, sha in sorted(live.items()):
        if recorded.get(name) != sha:
            fails.append(f"MANIFEST_STALE {name} pod={sha[:12]} manifest="
                         f"{(recorded.get(name) or 'ABSENT')[:12]}")
    for name in sorted(set(recorded) - set(live)):
        fails.append(f"MANIFEST_STALE {name} recorded but NOT installed on the pod now")

    # 1. every installed loop must be mirrored byte-for-byte
    for name, sha in sorted(live.items()):
        if name not in repo:
            fails.append(f"MISSING_FROM_REPO {name} installed on the pod, absent from "
                         f"scripts/pod-loops/ — a reinstall from the repo would switch it off")
        elif repo[name] != sha:
            fails.append(f"BYTES_DIFFER {name} pod={sha[:12]} repo={repo[name][:12]}")

    # 2. repo files that are not installed must say why
    for name in sorted(set(repo) - set(live)):
        if name not in repo_only:
            fails.append(f"UNDECLARED_REPO_ONLY {name} in scripts/pod-loops/ but not installed "
                         f"on the pod and not declared in INSTALLED.json repo_only")

    # 3. the doc is a producer of this claim; it must name every dispatched script
    sched = mirror / "scheduler.sh"
    if sched.exists() and a.doc and pathlib.Path(a.doc).exists():
        doc = pathlib.Path(a.doc).read_text(encoding="utf-8")
        for name in sorted(scheduled_scripts(sched)):
            if name not in doc:
                fails.append(f"DOC_MISSING_JOB {name} dispatched by scheduler.sh but absent "
                             f"from {a.doc}")

    if fails:
        for f in fails:
            print(f)
        print(f"DRIFT pod-loops via={a.via} installed={len(live)} mirrored={len(repo)} "
              f"failures={len(fails)}")
        return 1
    print(f"OK pod-loops via={a.via} installed={len(live)} mirrored={len(repo)} "
          f"repo_only={len(repo_only)} — repo bytes, manifest and doc all agree with the pod")
    return 0


if __name__ == "__main__":
    sys.exit(main())
