"""Shared reader: the live GSPC board and free card verification through csoai-gspc. Generated by scripts/harness-x/render.mjs."""
from __future__ import annotations

import json
from typing import Optional, Union

from csoai_gspc import BOARD_URL, fetch_board, fetch_card, get_axis, totals
from csoai_gspc import verify_card as _verify_card

DOCTRINE_SHA256 = "845fc1d200eb9e867fc8d682750409d6725084bac632726187759f8fefdfbe0a"
DOCTRINE_SOURCE = "docs/DOCTRINE.md"
TOOL_NAME = "gspc_board"
TOOL_DESCRIPTION = "Read the live Council of AI GSPC board (https://councilof.ai/api/gspc). With no axis, returns the board totals verbatim; with an axis name, returns that one axis row. Quote totals.public_count exactly as printed; never add or re-derive a count. If the board cannot be fetched the state is UNREACHABLE and no number is returned. Measurement only: a card is evidence, never a grade, mark or endorsement. Verification is free."
VERIFY_TOOL_NAME = "verify_card"
VERIFY_TOOL_DESCRIPTION = "Verify one Council of AI signed measurement card — free, always. Pass card_id (the card's full 64-hex id; it is fetched from https://councilof.ai/signed/cards/<id>.json) or card (the card JSON). Returns VALID (the body reproduces its id and the Ed25519 signature verifies under the pinned did:web:csoai.org#card-attestation-1 key), INVALID with the reason, or UNCHECKABLE (the check could not complete — never read that as forged). Measurement only: a card is evidence, never a grade, mark or endorsement. Verification is free."
RULE_URL = "https://councilof.ai/signed/HOW-TO-VERIFY.md"


def read_board(axis: Optional[str] = None) -> dict:
    """Return the live board totals, or one axis row. Three outcomes: LIVE, ABSENT, UNREACHABLE."""
    base = {"source": BOARD_URL, "doctrine_sha256": DOCTRINE_SHA256}
    try:
        board = fetch_board()
    except Exception as exc:  # network, HTTP or JSON failure: say so, never substitute a number
        return {**base, "state": "UNREACHABLE", "error": type(exc).__name__}
    if axis is None:
        return {**base, "state": "LIVE", "totals": totals(board)}
    row = get_axis(axis, board)
    if row is None:
        return {**base, "state": "ABSENT", "axis": axis}
    return {**base, "state": "LIVE", "axis_row": row}


def read_verify(card_id: Optional[str] = None, card: Optional[Union[dict, str]] = None) -> dict:
    """Verify one signed card. Three outcomes only: VALID, INVALID (with the reason), UNCHECKABLE."""
    base = {"rule": RULE_URL, "doctrine_sha256": DOCTRINE_SHA256}
    try:
        if card is not None:
            obj = json.loads(card) if isinstance(card, str) else card
        elif card_id:
            obj = fetch_card(card_id)  # ValueError for anything but a full 64-hex id, before any network
        else:
            return {**base, "state": "UNCHECKABLE", "reason": "pass card_id (64 hex) or card (the card JSON)"}
    except ValueError as exc:  # a malformed id or card JSON: could not check, did not fail
        return {**base, "state": "UNCHECKABLE", "reason": str(exc)}
    except Exception as exc:  # network, HTTP: could not check — never a verdict
        return {**base, "state": "UNCHECKABLE", "reason": f"could not fetch the card: {type(exc).__name__}"}
    if not isinstance(obj, dict):
        return {**base, "state": "UNCHECKABLE", "reason": "the card is not a JSON object"}
    v = _verify_card(obj)  # pins did:web:csoai.org#card-attestation-1 from the published DID document
    return {**base, "state": v.state, "reason": v.reason, "card_id": v.card_id}
