"""CrewAI BaseTool for the GSPC board. Generated by scripts/harness-x/render.mjs."""
from __future__ import annotations

from typing import Optional, Type

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

from ._board import TOOL_DESCRIPTION, TOOL_NAME, read_board


class GSPCBoardInput(BaseModel):
    axis: Optional[str] = Field(default=None, description="Axis name for one board row; omit for the board totals.")


class GSPCBoardTool(BaseTool):
    name: str = TOOL_NAME
    description: str = TOOL_DESCRIPTION
    args_schema: Type[BaseModel] = GSPCBoardInput

    def _run(self, axis: Optional[str] = None) -> dict:
        return read_board(axis)
