#!/usr/bin/env python3
"""Build the -01 xml2rfc skeleton from the posted -00 XML plus test-vectors/vectors.json.

    curl -sO https://www.ietf.org/archive/id/draft-templeman-scitt-measurement-capsule-00.xml
    # sha256 d0e09398de658ac626bc1229a927db93e139ed5c9de421486a2f5b9c3b2487ae (75,071 bytes, read 2026-09-28)
    python3 make_skeleton.py draft-templeman-scitt-measurement-capsule-00.xml test-vectors/vectors.json \
        > draft-templeman-scitt-measurement-capsule-01.xml
    xml2rfc --text --html draft-templeman-scitt-measurement-capsule-01.xml   # 3.34.1: 0 warnings

Sections whose -01 text is decided are written out. Everything that must be read live on the
day of posting is a bracketed placeholder; no number is carried over from -00.
"""
import json
import re
import sys
import textwrap


def wrap_hex(h, width=64, indent=""):
    return "\n".join(indent + h[i:i + width] for i in range(0, len(h), width))


def wrap_text(s, width=68):
    return "\n".join(textwrap.wrap(s, width, break_long_words=True, break_on_hyphens=False))


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def replace_between(s, start, end, new, keep_end=True):
    a = s.index(start)
    b = s.index(end, a + len(start))
    return s[:a] + new + (s[b:] if keep_end else s[b + len(end):])


def main(x00, vpath):
    s = open(x00, encoding="utf-8").read()
    v = json.load(open(vpath, encoding="utf-8"))

    # ---- front matter
    s = s.replace('docName="draft-templeman-scitt-measurement-capsule-00"',
                  'docName="draft-templeman-scitt-measurement-capsule-01"')
    s = s.replace('<rfc ipr=', '<rfc xmlns:xi="http://www.w3.org/2001/XInclude" ipr=', 1)
    s = s.replace('<date year="2026" month="September" day="27"/>', '<date year="2026"/>')
    s = s.replace("<!-- generated by https://github.com/cabo/kramdown-rfc version 1.7.43 (Ruby 2.7.0) -->",
                  "<!-- -01 SKELETON, work in progress; built by make_skeleton.py from the posted -00 XML. "
                  "Not for upload until every bracketed placeholder is filled from live artefacts. -->")
    s = s.replace("""issued under other profiles, and one implementation, including where it
does not yet match this profile.</t>""", """issued under other profiles, its encoding as a COSE_Sign1 Signed
Statement with test vectors, and one implementation, including where it
does not yet match this profile.</t>""")

    # ---- introduction: add the MCP access-decision receipt draft to the survey
    s = s.replace("""categorical screening outcomes in agentic-payment flows. These readings""",
                  """categorical screening outcomes in agentic-payment flows; and
<xref target="I-D.farley-acta-signed-receipts"/> defines signed decision receipts
for access control at the MCP transport layer. These readings""")

    # ---- conventions: wording
    s = s.replace("REJECTED (an identity check failed)", "REJECTED (an identity check did not pass)")

    # ---- registration: replaced
    reg = """<section anchor="registration"><name>Registration as a SCITT Signed Statement</name>

<t>A batch record or an index is registered as the payload of a
COSE_Sign1 message <xref target="RFC9052"/>, tagged 18. Capsules are not
registered one by one: a capsule reaches the log through the batch root
that commits to it (<xref target="merkle"/>).</t>

<section anchor="cose-headers"><name>Protected Header</name>

<t>The protected header is a map in the core deterministic encoding of
<xref target="RFC8949" section="4.2.1"/>. It carries:</t>

<ul>
  <li>alg (1): -19, Ed25519 <xref target="RFC9864"/>, with an Ed25519 key
  <xref target="RFC8032"/>. The polymorphic EdDSA identifier (-8), which
  <xref target="RFC9864"/> deprecates, <bcp14>MUST NOT</bcp14> be used.</li>
  <li>kid (4): the UTF-8 bytes of the signing key's verification method, a
  DID URL <xref target="DID-WEB"/>. <xref target="RFC9943"/> requires kid when
  neither x5t nor x5chain is present.</li>
  <li>CWT Claims (15) <xref target="RFC9597"/>: iss (1), the Issuer's DID;
  sub (2), the batch's <tt>kind</tt>, or the fixed string
  <tt>measurement-capsule-index</tt> for an index; iat (6), the signing
  time.</li>
  <li>With an attached payload: content type (3), one of the media types in
  <xref target="iana"/>. The payload is the JCS serialisation of the
  record.</li>
  <li>With a COSE Hash Envelope <xref target="RFC9995"/>: payload_hash_alg
  (258) set to -16 (SHA-256), payload_preimage_content_type (259) set to the
  media type, and optionally payload_location (260). The payload is the
  32-byte SHA-256 of the record's JCS serialisation. Content type (3)
  <bcp14>MUST NOT</bcp14> be present, as <xref target="RFC9995"/> requires;
  -00 of this document said otherwise.</li>
</ul>

<t>The unprotected header is empty when the statement is signed. Receipts
obtained later are carried under label 394, as in <xref target="RFC9943"/>.</t>

</section>
<section anchor="cose-verify"><name>Signing and Verification</name>

<t>The Issuer signs the Sig_structure <tt>["Signature1", protected, h'', payload]</tt>
of <xref target="RFC9052" section="4.4"/>. A verifier decodes the message,
rejects a protected header that is not deterministically encoded, rebuilds
the Sig_structure, and verifies the signature under the key that kid
resolves to. For an attached payload it then checks that the payload is
exactly the JCS serialisation of the record it parses to; for a hash
envelope, that the SHA-256 of the retrieved record equals the payload.</t>

<t>A COSE statement is a new artefact over unchanged content. The capsule
identifiers, batch roots and index roots it commits to do not change, and
the JSON signatures an implementation already published over the same
records stay verifiable; the two are published side by side.
<xref target="test-vectors"/> gives vectors for both encodings.</t>

<t>[STATUS AT POSTING, READ LIVE: which records carry a COSE_Sign1
statement and under which key; "none" if the Issuer's signing service
cannot yet sign a Sig_structure.]</t>

</section>
</section>
<section anchor="receipts"><name>Receipts</name>

<t>Registration follows <xref target="I-D.ietf-scitt-scrapi"/>. The Receipt is
a COSE Receipt <xref target="RFC9942"/> whose verifiable data structure is set
by the Transparency Service; for a service built on CCF it is the profile in
<xref target="I-D.ietf-scitt-receipts-ccf-profile"/>. Inclusion of one capsule
is shown in two steps: capsule to batch root by an RFC 9162 audit path under
the Issuer's tree, then batch record or index to the log by the Receipt.</t>

<t>A Receipt shows that the Transparency Service registered the statement
at a time. It does not show that any measurement in it is correct.</t>

<t>[STATUS AT POSTING, FILLED ONLY FROM A RECEIPT THAT EXISTS: the
Transparency Service and its operator; whether the operator is a party
other than the Issuer; the registered statement's SHA-256; the entry
identifier; the Receipt's SHA-256; and the verifiers that checked it. If no
Receipt has been obtained, this paragraph says so and nothing more.]</t>

</section>
"""
    s = replace_between(s, '<section anchor="registration">', '<section anchor="states">', reg)

    # ---- states: vocabulary moves to Appendix B
    s = replace_between(
        s, "<t><spanx style=\"verb\">measurement_state</spanx> is one string from a vocabulary defined per kind.",
        "<t><list style=\"symbols\">\n  <t>UNCHECKABLE and each absence-and-inability state",
        """<t><spanx style="verb">measurement_state</spanx> is one string from a vocabulary defined per kind.
The vocabularies in use, with the family each state belongs to (agreement,
verification, reproduction, reading, and absence and inability), are listed
in <xref target="vocabularies"/>. For every kind:</t>

""")

    # ---- security: wording
    s = s.replace("instrument is sound or that the subject endorses the measurement.",
                  "instrument is sound or that the subject agrees with the measurement.")

    # ---- IANA: media types list now includes the index and batch types explicitly
    s = replace_between(s, '<section anchor="iana">', '<section anchor="implementation">',
                        """<section anchor="iana"><name>IANA Considerations</name>

<t>This document has no IANA actions. It uses three media types in the
vendor tree, <tt>application/vnd.csoai.measurement-capsule+json</tt>,
<tt>application/vnd.csoai.measurement-capsule-batch+json</tt> and
<tt>application/vnd.csoai.measurement-capsule-index+json</tt>, which can be
registered without IETF action. [STATUS AT POSTING: whether they have been
registered.] Their names are open issue 4.</t>

</section>
""")

    # ---- implementation status: placeholders only
    s = replace_between(s, '<section anchor="implementation">', '<section anchor="experiment">',
                        """<section anchor="implementation"><name>Implementation Status</name>

<t>This section records the status of known implementations at the time
of posting, following <xref target="RFC7942"/>. RFC Editor: please remove
this section before publication.</t>

<t>CSOAI measurement capsule builder (Council of AI, contact
nicholas@csoai.org). Every count, root, commit and URL in this section is
read from the live artefacts on the day of posting and given with the
time of reading; none is carried over from -00.</t>

<ul>
  <li>Index: schema, number of capsules, batches and kinds, index root,
  and where the files are published. [READ LIVE]</li>
  <li>COSE: see <xref target="cose-verify"/>. [READ LIVE]</li>
  <li>Receipt: see <xref target="receipts"/>. [READ LIVE]</li>
  <li>Anchors: the OpenTimestamps <xref target="OTS"/> state of each
  record's proof (calendar commitment or Bitcoin attestation) and the Rekor
  <xref target="REKOR"/> log indexes. Neither is a SCITT Transparency
  Service or issues Receipts. [READ LIVE]</li>
  <li>Capsules by kind and state, the number of self-measurements, and
  the number carrying a correction pointer or an effect reference.
  [READ LIVE]</li>
  <li>Test vectors: <xref target="test-vectors"/>, with a generator and a
  checker on a second code path (cbor2, rfc8785 and the RFC 9162
  Section 2.1.3.2 inclusion check). The checker is written by the same
  organisation, so it is not the independent implementation the
  experiment asks for. [URL WHEN PUBLISHED]</li>
</ul>

</section>
""")

    # ---- open issues: -01 disposition
    s = replace_between(s, '<section anchor="open-issues">', '</middle>',
                        """<section anchor="open-issues"><name>Open Issues</name>

<t>(1) COSE_Sign1 encoding: specified in this revision
(<xref target="registration"/>). (2) The superseded <tt>capsule_id</tt> in
<tt>correction_pointer</tt>: open. (3) A per-kind allowlist of member names
in place of the denylist: open; <xref target="vocabularies"/> lists state
vocabularies only. (4) Neutral names for the <tt>csoai.</tt>-prefixed
identifiers and media types: open; a rename changes every identifier and
would be published as new batches. (5) Blinded digests for non-public
sources: open. (6) Whether observation-only kinds belong here: open.
(7) An explicit self-measurement member: open. (8) Transparency Services
differ in the Issuer identities their registration policies accept (for
example did:x509 rather than did:web); which forms a measurer needs is
open.</t>

</section>

""", keep_end=True)

    # ---- references
    s = s.replace("""<reference anchor="RFC9052">""",
                  """<xi:include href="https://bib.ietf.org/public/rfc/bibxml/reference.RFC.8949.xml"/>
<xi:include href="https://bib.ietf.org/public/rfc/bibxml/reference.RFC.9942.xml"/>
<reference anchor="RFC9052">""", 1)
    s = s.replace("""<reference anchor="RFC9995">""", """<xi:include href="https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.farley-acta-signed-receipts.xml"/>
<xi:include href="https://bib.ietf.org/public/rfc/bibxml3/reference.I-D.ietf-scitt-receipts-ccf-profile.xml"/>
<reference anchor="RFC9995">""", 1)
    # RFC 9995 is normative now (the hash envelope rules are MUSTs here): move it.
    m = re.search(r'<reference anchor="RFC9995">.*?</reference>\n', s, re.S)
    ref9995 = m.group(0)
    s = s.replace(ref9995, "", 1)
    s = s.replace("""<reference anchor="RFC9052">""", ref9995 + """<reference anchor="RFC9052">""", 1)

    # ---- reference entries: drop the <abstract> blocks kramdown copied in (xml2rfc does not render
    # them in references; they only carried third-party prose into the source)
    s = re.sub(r"(<reference\b[^>]*>.*?)<abstract>.*?</abstract>(.*?</reference>)",
               lambda m: m.group(1) + m.group(2), s, flags=re.S)

    # ---- back matter: appendices before acknowledgments
    b = v["V2_batch"]
    c0 = v["V1_capsules"][0]
    v3 = v["V3_cose_sign1_attached"]
    v4 = v["V4_cose_hash_envelope"]
    cap_disp = wrap_text(c0["jcs_utf8"], 68)
    rows = "\n".join(
        "<tr><td>%s</td><td>%s</td><td>%s</td></tr>" % (esc(n["id"]), esc(n["expected"]["rule"]), esc(n["why"]))
        for n in v["N_controls"])
    app = """<section anchor="test-vectors"><name>Test Vectors</name>

<t>These vectors are synthetic. The signing key is the TEST 1 key of
<xref target="RFC8032" section="7.1"/>, whose secret is published there, so
nothing it signs means anything. Subjects are under <tt>.example</tt>, and
source digests are SHA-256 values of labelled placeholder strings. The
full vectors, their generator and a checker that shares no code with the
generator are published at [URL WHEN PUBLISHED] (vectors.json, SHA-256
[VECTORS SHA-256 AT POSTING]).</t>

<t>Public key (hex): {pk}. kid: <tt>{kid}</tt>.</t>

<section anchor="tv-capsule"><name>One Capsule</name>

<t>The first of five capsules, as its JCS bytes. Line breaks are added for
display only; the bytes contain none.</t>

<artwork><![CDATA[
{cap}
]]></artwork>

<t>capsule_id (SHA-256 of the JCS bytes without <tt>capsule_id</tt>):</t>
<artwork><![CDATA[
{cid}
]]></artwork>

</section>
<section anchor="tv-batch"><name>Batch and Audit Path</name>

<t>Five capsule_id leaves, sorted ascending:</t>
<artwork><![CDATA[
{leaves}
]]></artwork>

<t>RFC 9162 Merkle Tree Hash (SHA-256):</t>
<artwork><![CDATA[
{root}
]]></artwork>

<t>Audit path for leaf index {m} of {n}, verifiable with
<xref target="RFC9162" section="2.1.3.2"/>:</t>
<artwork><![CDATA[
{path}
]]></artwork>

<t>SHA-256 of the batch record's JCS bytes:</t>
<artwork><![CDATA[
{rsha}
]]></artwork>

</section>
<section anchor="tv-cose"><name>COSE_Sign1 with an Attached Payload</name>

<t>Protected header (EDN, then the deterministic encoding in hex):</t>
<artwork><![CDATA[
{edn3}

{prot3}
]]></artwork>
<t>Signature over the Sig_structure:</t>
<artwork><![CDATA[
{sig3}
]]></artwork>

</section>
<section anchor="tv-hash-envelope"><name>COSE_Sign1 with a Hash Envelope</name>

<t>Protected header (EDN, then hex). Label 3 is absent.</t>
<artwork><![CDATA[
{edn4}

{prot4}
]]></artwork>
<t>Payload (SHA-256 of the batch record's JCS bytes) and signature:</t>
<artwork><![CDATA[
{pay4}

{sig4}
]]></artwork>

</section>
<section anchor="tv-controls"><name>Controls</name>

<t>Each control is built to be rejected and names the one rule it breaks.
A verifier counts a control only when it is rejected for that rule. For
each rule, relaxing that rule alone in the checker changes the result of
the control that names it and of no other vector.</t>

<table>
<thead><tr><th>Control</th><th>Rule</th><th>Why it is rejected</th></tr></thead>
<tbody>
{rows}
</tbody>
</table>

</section>
</section>
<section anchor="vocabularies"><name>State Vocabularies</name>

<t>[GENERATED AT BUILD from the implementation's vocabulary file: for each
kind, each state, its family and a one-line meaning. Not written by hand,
so that the text and the implementation cannot drift apart.]</t>

</section>
<section anchor="changes"><name>Changes from -00</name>

<ul>
  <li>Specified the COSE_Sign1 encoding: header parameters, deterministic
  encoding, what is signed and how it is verified.</li>
  <li>Corrected the hash envelope rule: content type (3) is absent and the
  media type goes in label 259, as RFC 9995 requires.</li>
  <li>Registration is per batch record and index, not per capsule.</li>
  <li>Added the Receipts section, and moved RFC 9995 to the normative
  references; added RFC 8949 and RFC 9942.</li>
  <li>Added test vectors and controls.</li>
  <li>Moved the state vocabularies to a generated appendix.</li>
  <li>Implementation Status is re-read from live artefacts; no figure is
  carried over.</li>
  <li>Added the MCP access-decision receipt draft to the survey in the
  introduction, and open issue 8.</li>
  <li>[REFERENCES: re-read each cited draft's current revision on the day
  of posting.]</li>
</ul>

</section>
""".format(pk=v["test_key"]["public_hex"], kid=esc(v["test_key"]["kid"]), cap=cap_disp,
           cid=c0["capsule_id"], leaves="\n".join(b["leaves_sorted"]), root=b["merkle_root"],
           m=b["audit_path"]["leaf_index"], n=b["audit_path"]["tree_size"],
           path="\n".join(b["audit_path"]["path"]), rsha=b["record_sha256"],
           edn3=wrap_text(v3["protected_edn"], 68), prot3=wrap_hex(v3["protected_hex"]),
           sig3=wrap_hex(v3["signature_hex"]), edn4=wrap_text(v4["protected_edn"], 68),
           prot4=wrap_hex(v4["protected_hex"]), pay4=v4["payload_hex"], sig4=wrap_hex(v4["signature_hex"]),
           rows=rows)
    s = s.replace('<section numbered="false" anchor="acknowledgments">', app + '<section numbered="false" anchor="acknowledgments">', 1)
    sys.stdout.write(s)


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
