export type Tier = "nano" | "lvp" | "mvp" | "hvp" | "elite";

export interface Server {
  name: string;
  tier: Tier;
  price: string;
  extraSectors: string[];
}

export interface SectorGroup {
  id: string;
  name: string;
  count: number;
  servers: Server[];
}

export interface Stat {
  value: string;
  label: string;
}

export interface TierInfo {
  id: Tier;
  name: string;
  price: string;
  count: number;
  description: string;
}

export const stats: Stat[] = [
  { value: "271", label: "Published Servers" },
  { value: "12", label: "Industry Sectors" },
  { value: "5", label: "Pricing Tiers" },
  { value: "8", label: "Stripe Price Points" },
  { value: "3", label: "Compliance Packs" },
];

export const tiers: TierInfo[] = [
  { id: "lvp", name: "LVP", price: "£9/mo", count: 279, description: "Standard AI tools" },
  { id: "mvp", name: "MVP", price: "£29/mo", count: 35, description: "Advanced AI" },
  { id: "hvp", name: "HVP", price: "£79/mo", count: 28, description: "Governance & Security" },
  { id: "elite", name: "ELITE", price: "£199/mo", count: 6, description: "Specialized" },
];

export const sectorGroups: SectorGroup[] = [
  {
    id: "general",
    name: "General",
    count: 276,
    servers: [
      { name: "a2a-governance-bridge-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "accessibility-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "accounting-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "ad-copy-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "agent-commerce-protocol-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-cost-allocator-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-data-residency-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-delegation-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-handoff-certified-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-identity-trust-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-incident-relay-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-incident-reporter-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-mcp-router-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-negotiation-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-orchestrator-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-prompt-injection-firewall-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-rate-limiter-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-replay-debugger-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-token-budget-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agriculture-robotics-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "ai-bom-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "ai-gateway-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "ai-incident-reporting-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "ai-ops-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "ai-reflection-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "airspace-monitor-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "api-docs-generator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "api-tester-ai-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "ascii-art-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "backup-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "basel-ai-overlay-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "bft-governance-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "bft-progress-council-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "bias-detection-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "blockchain-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "blockchain-verification-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "budget-planner-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "c2pa-watermark-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "calendar-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "canada-aida-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "changelog-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "chas-elite-prep-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "churn-predictor-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "ci-cd-generator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "cisa-kev-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "citation-finder-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "cli-builder-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "clipboard-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "cobol-bridge-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "code-executor-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "code-reviewer-ai-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "color-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "commit-message-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "competitor-monitor-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "compression-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "concrete-pump-cpa-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "config-validator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "consciousness-engine-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "construction-iso-19650-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "coppa-ferpa-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "crane-hire-cpcs-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "creativity-engine-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "crm-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "cron-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "crypto-tracker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "csoai-governance-crosswalk-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "csv-analytics-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "csv-tools-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "currency-converter-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "customer-support-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "cybersecurity-ai-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "data-science-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "database-universal-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "dataprivacy-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "date-calculator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "deepfake-detector-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "dependency-updater-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "devops-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "diff-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "dispense-record-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "docker-helper-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "dockerfile-generator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "document-comparison-ai-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "dora-nis2-crosswalk-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "drone-airspace-governance-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "email-automation-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "email-validator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "emoji-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "encoder-ai-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "env-manager-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "eudi-wallet-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "event-planning-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "expense-tracker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "explainability-report-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "faker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "feedback-analyzer-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "file-organizer-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "firmware-attestation-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "fishkeeper-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "fitness-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "flashcard-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "flight-logger-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "focus-timer-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "fsa-food-safety-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "gardening-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "geolocation-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "git-helper-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "gods-eye-geospatial-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "gos-claim-validator-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "grammar-fix-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "habit-tracker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "hash-utils-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "hr-management-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "html-parser-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "hydration-reminder-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "image-metadata-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "invoice-generator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "ip-network-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "iso-27001-ai-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "iso-42001-ai-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "iso-42005-impact-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "job-description-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "json-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "jwt-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "keystone-catalogue-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "keystone-verify-proxy-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "keyword-extractor-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "korea-ai-basic-act-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "lead-scoring-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "license-checker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "linkedin-outreach-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "lorem-ipsum-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "markdown-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "marketing-analytics-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "math-solver-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "mcp-scorecard-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meal-planner-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meditation-guide-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meeting-summarizer-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "memory-search-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-aaif-agent-card-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "meok-abci-bridge-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-agents-md-lint-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "meok-ai-treaty-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-allmi-hiab-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-aquaponics-monitor-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-article-50-kit-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-asc-rspca-crosswalk-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-bs7121-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-c2pa-durable-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-c2pa-watermark-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-cra-annex-iv-classifier-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-cra-art14-reporter-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-credential-manager-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-dpia-edpb-template-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-drcf-agent-crosswalk-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "meok-dvsa-olicence-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-eu-aia-art-9-rms-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-eu-platform-worker-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-ev-recall-transport-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-fmcsa-hours-of-service-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "meok-fors-clocs-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-gaming-eve-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-gaming-ffxiv-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-gaming-minecraft-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-gaming-osrs-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-gaming-wow-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-governance-engine-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-haulage-governance-bridge-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-iata-dgr-air-cargo-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-imo-marpol-marine-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-iru-tir-international-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-koikeeper-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-laia-aquatic-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-libp2p-agent-mesh-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "meok-livestock-welfare-transport-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-mcp-cardgen-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-mcp-hardening-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-mcp-injection-scan-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-mcp-test-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "meok-nhvr-australia-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-nis2-de-register-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "meok-omnibus-tracker-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-rspca-aquaculture-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-transport-canada-hos-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-uae-rta-transport-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-uas-commercial-drone-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-uk-adm-article22c-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-uk-fhi-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-uk-phv-tfl-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-vehicle-handover-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-w3c-tdm-rights-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-watermark-attest-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "mica-crypto-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "mifid-ii-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "mitre-atlas-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "mitre-attack-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "mock-server-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "mortgage-calculator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "muckaway-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "music-production-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "nist-rmf-ai-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "note-taking-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "notification-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "nrswa-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "nutrition-tracker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "oasf-agent-directory-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "optometry-ai-safety-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "otp-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "owasp-agentic-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "password-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "pci-dss-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "pdf-document-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "pdf-merge-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "pdf-tools-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "performance-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "photography-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "plagiarism-checker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "planthire-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "pomodoro-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "price-tracker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "project-management-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "proofof-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "qidi-printer-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "qr-code-ai-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "quantum-scoring-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "quiz-generator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "rag-knowledge-graph-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "rag-knowledge-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "readme-generator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "real-estate-listing-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "recipe-finder-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "recruitment-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "regex-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "restaurant-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "resume-parser-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "risk-assessment-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "robotics-control-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "sbom-cyclonedx-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "scam-detector-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "schema-validator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "security-scanner-ai-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "self-healing-infrastructure-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "sentiment-analysis-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "seo-checker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "sigstore-cosign-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "skip-hire-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "slack-enterprise-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "sleep-tracker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "slugify-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "sql-builder-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "stock-analyzer-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "string-utils-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "subscription-tracker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "summarizer-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "survey-builder-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "tax-calculator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "text-stats-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "time-tracker-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "tone-rewriter-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "translation-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "translator-pro-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "trust-chain-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "unit-converter-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "url-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "uuid-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "validator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "vector-knowledge-graph-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "video-editing-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "voice-audio-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "watermarking-authenticity-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "weather-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "web-research-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "webhook-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "workout-planner-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "writing-assistant-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "legal",
    name: "Legal",
    count: 22,
    servers: [
      { name: "agent-audit-logger-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "ai-self-audit-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "contract-review-ai-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "cqc-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "cra-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "csrd-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: ["government"] },
      { name: "dora-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "eu-ai-act-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: ["government"] },
      { name: "gdpr-compliance-ai-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "haulage-uk-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "hipaa-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: ["healthcare"] },
      { name: "landlaw-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "legal-document-ai-mcp", tier: "elite", price: "£199/mo", extraSectors: [] },
      { name: "llm-compliance-comparison-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "mcp-spec-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "meok-cpa-contract-lift-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-law-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-tacho-audit-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "nis2-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "soc2-compliance-ai-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
      { name: "test-case-generator-ai-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "uk-ai-bill-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: [] },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    count: 18,
    servers: [
      { name: "care-home-cqc-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "care-home-scheduling-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "care-membrane-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "clinical-trials-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "domiciliary-care-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "fda-samd-mcp", tier: "elite", price: "£199/mo", extraSectors: [] },
      { name: "health-check-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "healthcare-ai-governance-mcp", tier: "elite", price: "£199/mo", extraSectors: [] },
      { name: "healthcare-fhir-mcp", tier: "elite", price: "£199/mo", extraSectors: [] },
      { name: "hipaa-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: ["legal"] },
      { name: "mdr-medical-device-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-cold-chain-pharma-mcp", tier: "elite", price: "£199/mo", extraSectors: [] },
      { name: "mhra-samd-optometry-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "neural-health-monitor-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "optical-care-home-bridge-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "optometry-patient-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "patient-safety-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "pet-care-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "finance",
    name: "Finance",
    count: 10,
    servers: [
      { name: "agent-commerce-payments-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "agent-x402-paywall-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "aml-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-ap2-mandate-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-coinbase-x402-receipt-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-stripe-acp-checkout-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-x402-wrap-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "personal-finance-ai-mcp", tier: "elite", price: "£199/mo", extraSectors: [] },
      { name: "stripe-billing-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "yaml-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "government",
    name: "Government",
    count: 10,
    servers: [
      { name: "agent-policy-enforcement-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "csrd-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: ["legal"] },
      { name: "eu-ai-act-compliance-mcp", tier: "hvp", price: "£79/mo", extraSectors: ["legal"] },
      { name: "icon-generator-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-eu-ai-act-2-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-eu-ai-act-art-13-ifu-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-eu-ai-act-art-26-fria-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "meok-eu-aigc-icon-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "regulatory-webhook-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "uk-ai-act-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "media",
    name: "Media",
    count: 4,
    servers: [
      { name: "agent-content-watermark-mcp", tier: "mvp", price: "£29/mo", extraSectors: [] },
      { name: "content-calendar-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "content-registry-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "social-media-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing",
    count: 4,
    servers: [
      { name: "logistics-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: ["transportation"] },
      { name: "meok-rail-freight-uk-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "slsa-supply-chain-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "supply-chain-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "retail",
    name: "Retail",
    count: 2,
    servers: [
      { name: "ecommerce-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "inventory-management-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "insurance",
    name: "Insurance",
    count: 2,
    servers: [
      { name: "insurance-verification-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
      { name: "nhs-gos-claims-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "transportation",
    name: "Transportation",
    count: 2,
    servers: [
      { name: "logistics-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: ["manufacturing"] },
      { name: "meok-eu-mobility-package-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "education",
    name: "Education",
    count: 1,
    servers: [
      { name: "education-ai-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
  {
    id: "energy",
    name: "Energy",
    count: 1,
    servers: [
      { name: "meok-soil-assoc-organic-aqua-mcp", tier: "lvp", price: "£9/mo", extraSectors: [] },
    ],
  },
];
