import { BookMarked, ShieldCheck, BarChart2, Boxes, Landmark, LayoutGrid, Globe2 } from 'lucide-react';
import { HOME_NAV } from '@/components/homeNav';
import { XRPL_STATUS_LABEL } from '@/data/anchoringClaim';
export { HOME_NAV };

interface NavItem { name: string; href: string; description: string; external?: boolean; section?: string }
interface NavGroup { name: string; href: string; icon: typeof Globe2; description: string; submenu: NavItem[] }

export const PRIMARY_LINKS: { name: string; href: string }[] = [
  { name: "Verify", href: "/gspc-verify" },
  { name: "Get measured", href: "/assess" },
  { name: "Board", href: "/gspc-scoreboard" },
  { name: "Council OS", href: "/dashboard" },
  { name: "Tools", href: "/tools" },
];

export const navigation: NavGroup[] = [
  {
    name: 'Measure',
    href: '/gspc-scoreboard',
    icon: BarChart2,
    description: 'The instrument and its living board',
    submenu: [
      { section: 'The board', name: 'The GSPC board', href: '/gspc-scoreboard', description: 'Every published axis. Counts and the stamp date come from GET /api/gspc — never typed into a page' },
      { name: 'The arena', href: '/gspc-arena', description: 'Head-to-head on the same frozen items. Deterministic grading — no model judges another' },
      { name: 'Arena — benchmarks', href: '/gspc-arena?view=benchmarks', description: 'The per-bank view of the arena: which instrument, which rows, which result' },
      { name: 'Arena — live training', href: '/gspc-arena?view=training', description: 'Runs in progress. Practice stays practice and is never quoted' },
      { name: 'Measured models', href: '/models', description: 'Ranked by signed GSPC results, not by parameter count' },
      { name: 'Measured results', href: '/benchmarks', description: 'Every number traces to a published artefact — the losses included' },
      { section: 'Get a card', name: 'Get measured', href: '/assess', description: 'Coming — Paddle waitlist. Verify stays free. Booking is not live' },
      { name: 'Verify a signed card', href: '/gspc-verify', description: 'Check any Ed25519-signed record offline against the published key. Free forever' },
      { name: 'Report an AI incident', href: '/report', description: 'Anyone can flag AI behaviour that looks wrong — the intake is public, not a vendor inbox' },
      { section: 'How it works', name: 'Methodology', href: '/methodology', description: 'Gold labels, n≥30, McNemar separation — and how to recompute every number yourself' },
      { name: 'The GSPC instrument', href: '/instrument', description: 'Four deterministic lenses over frozen provisions. No model sits in the verdict path' },
      { name: 'Published tools', href: '/tools', description: 'MCP servers you can run yourself — not a marketplace' },
      { section: 'Specialist boards', name: 'Financial axis', href: '/financial-axes', description: 'The declared financial slots — measured where measured, UNMEASURED and honest where not' },
      { name: 'EUNOMIA board', href: '/eunomia', description: 'Financial-verification axis, signed, across a two-tier fleet' },
      { name: 'Signed registers', href: '/registers', description: 'The financial-axis register — a stranger can re-derive every row' },
      { name: 'First-Fine Watch', href: '/first-fine-watch', description: 'Signed enforcement record: EU AI Act fines and the deadlines behind them' },
      { name: 'EUNOMIA data (commercial)', href: '/eunomia-data', description: 'x402 data-only lane — enforcement record + deadline calendar, never scores' },
      { name: 'EUNOMIA catalog', href: '/eunomia-catalog', description: 'Every surface, API, HF mirror, A2A card and MCP tool — catalogued and linked' },
      { name: 'EU AI Act × CRA watch', href: '/eunomia-crosswalk', description: 'Statute → axis → requirement → exposure, with live source links' },
      { name: 'EUNOMIA indices', href: '/eunomia-indices', description: 'The aspirational index axes — UNMEASURED on GET /api/gspc. Do not restore MEASURED-INDEX-v0.1' },
    ],
  },
  {
    name: 'Products',
    href: '/products',
    icon: Boxes,
    description: 'Signed evidence — and who it is for',
    submenu: [
      { section: 'The four SKUs', name: 'All products', href: '/products', description: 'Council OS is the workspace. Verify free. Ledger and Data on enquiry. A grade is never sold' },
      { name: 'Council OS', href: '/os', description: 'The workspace a stranger opens — board, verifier, assess, evidence in one window' },
      { name: 'Council Verify', href: '/gspc-verify', description: 'Paste a card. Your browser recomputes the signature. Free forever' },
      { name: 'Council Ledger', href: '/council-licensing', description: 'Signed evidence feed for insurers, procurement and deployers — never a purchased rank' },
      { name: 'Council Data', href: '/licensing-agreement', description: 'Licensed signed corpus. Buy data, never a score' },
      { section: 'Modules', name: 'GPAI Evidence Pack', href: '/gpai-evidence', description: 'Independent third-party evidence a GPAI provider can hand the AI Office. Evidence, never a conformity mark' },
      { name: 'CRA Readiness Kit', href: '/cra-readiness', description: 'The 24h / 72h / 14-day ENISA runbook and signed SBOM workflow we run on ourselves' },
      { name: 'Financial axis', href: '/financial-axes', description: 'The declared financial slots, coverage stated first — never a credit rating' },
      { name: 'Distribution integrity', href: '/distribution-integrity', description: 'Represented is not distributed: the committed-versus-distributed spread, coverage-first and UNMEASURED' },
      { name: 'Verify embed / white-label', href: '/embed', description: 'A self-verifying badge for your own site — WebCrypto checks the signature in the reader’s browser' },
      { name: 'Legacy modernization on-ramp', href: '/cobolbridge', description: 'In build — COBOL lineage under DORA / Basel / SOX. Apex 522. SPEC only, not a live mill' },
      { section: 'Who it is for', name: 'Enterprise', href: '/for/enterprise', description: 'Measure a portfolio of systems against the duties that actually bind them' },
      { name: 'Insurers and underwriters', href: '/insurers', description: 'An observed behavioural sample with a stated n and interval — something a risk model can price' },
      { name: 'Government and regulators', href: '/government', description: 'Independent measurement with a published method. We issue no conformity mark' },
      { name: 'Industries', href: '/industries', description: 'Sector by sector: the provisions that apply, and when they bite' },
      { name: 'Sector tooling', href: '/sectors', description: 'White-label tooling per sector — regulator, insurer, bond, legacy, vendor' },
      { name: 'Integrations', href: '/integrations', description: 'Wire the measurement into the tools you already run' },
      { name: 'How the free rail works', href: '/os?lobby=assess&task=pricing-overview', description: 'Verify is free. A grade is never sold. There are no public prices' },
    ],
  },
  {
    name: 'Regulation',
    href: '/eu-ai-act',
    icon: Landmark,
    description: 'The statute we measure against',
    submenu: [
      { name: 'EU AI Act — the guide', href: '/eu-ai-act', description: 'The whole Act, phased, with the Digital Omnibus amendments' },
      { name: 'Article 50 — transparency', href: '/article-50', description: 'Live since 2 Aug 2026; the marking grace period ends 2 Dec 2026' },
      { name: 'Dates and deadlines', href: '/ai-act-timeline', description: 'What applies when — Annex III deferred to 2 Dec 2027' },
      { name: 'GPAI model duties', href: '/gpai', description: 'Documentation, training-data summary, copyright policy' },
      { name: 'Readiness checklist', href: '/checklist', description: 'Work through the duties that are actually in force today' },
      { name: 'Global regulation tracker', href: '/regulation-tracker', description: 'Every AI regime worldwide, with its current dates' },
      { name: 'Regulator atlas', href: '/regulators', description: 'Who supervises what, jurisdiction by jurisdiction' },
      { name: 'Framework crosswalk', href: '/crosswalk', description: 'Map existing ISO 42001 / NIST controls onto Act duties' },
      { name: 'Regulation feed — live JSON', href: '/api/regulation', description: 'The machine-readable corpus and deadline feed', external: true },
    ],
  },
  {
    name: 'Council OS',
    href: '/dashboard',
    icon: LayoutGrid,
    description: 'One workspace over the whole rail',
    submenu: [
      { section: 'The workspace', name: 'Open Council OS', href: '/dashboard', description: 'The desktop: every live surface in one place, with a concierge that answers from published measurement or refuses' },
      { name: 'Lobby home', href: '/dashboard?tab=home', description: 'Chat is the OS. The lobby frames the live page — a pane can never drift from the page it shows' },
      { section: 'Panes', name: 'Live board', href: '/dashboard?tab=board', description: 'The living GSPC board, with in-lane measurements beside it — never mixed into board totals' },
      { name: 'Verify a card', href: '/dashboard?tab=verify', description: 'The offline verifier, in the workspace' },
      { name: 'Get measured', href: '/dashboard?tab=measured', description: 'Coming — Paddle waitlist. Verify stays free' },
      { name: 'Council Space', href: '/dashboard?tab=space', description: 'The continuous contest — model against model on one instrument' },
      { name: 'Models', href: '/models', description: 'What we measured, and what it scored' },
      { name: 'Tools', href: '/tools', description: 'The published MCP surface, runnable' },
      { name: 'Report an incident', href: '/report', description: 'The public intake for AI behaviour that looks wrong' },
      { name: 'Honesty gate', href: '/honesty/', description: 'What we cannot yet measure — published rather than hidden' },
      { name: 'Readiness assessment', href: '/dashboard?tab=measured', description: 'Work out which duties bind you before you measure' },
      { name: 'Library', href: '/library', description: 'Everything we have published, in the workspace' },
      { name: 'Workbench', href: '/workbench', description: 'Signed-in working surface. Strangers use Verify, Assess, or the board — no login' },
    ],
  },
  {
    name: 'Evidence',
    href: '/honesty',
    icon: ShieldCheck,
    description: 'Our receipts, including the losses',
    submenu: [
      { section: 'What we got wrong', name: 'The honesty gate', href: '/honesty', description: 'What we cannot yet measure, published rather than quietly omitted' },
      { name: 'Refutation Ledger', href: '/refutation-ledger', description: 'Experiments that killed our own theses — with the artefacts attached' },
      { name: 'Firewall Charter', href: '/firewall-charter', description: 'We measure; we never fix what we measure' },
      { name: 'Corrections — live JSON', href: '/api/corrections', description: 'Append-only. Corrections are published, never silently edited', external: true },
      { section: 'Machine surfaces', name: 'GSPC board — live JSON', href: '/api/gspc', description: 'The board exactly as an agent reads it', external: true },
      { name: 'did:web trust root', href: '/.well-known/did.json', description: 'The published signer — verify a card without us', external: true },
      { name: 'API documentation', href: '/api-docs', description: 'Every endpoint above, documented for agents' },
      { name: 'System status', href: '/status', description: 'What is up, and what is degraded' },
      { section: 'Interop', name: 'Attestation on a public ledger', href: '/xrpl-attest', description: XRPL_STATUS_LABEL + '. Reader of GET /root.json; /api/xrpl reader (writes_board false). Never a rating' },
      { name: 'Report an AI incident', href: '/report', description: 'A public intake. What we act on is measured and signed like everything else' },
    ],
  },
  {
    name: 'Company',
    href: '/about',
    icon: BookMarked,
    description: 'Council of AI — CSOAI Ltd',
    submenu: [
      { section: 'Who we are', name: 'About', href: '/about', description: 'An independent measurement instrument — and what that deliberately excludes' },
      { name: 'Trust Center', href: '/trust-center', description: 'Security posture — and the certifications we have NOT been awarded' },
      { name: 'Contact', href: '/contact', description: 'CSOAI Ltd, UK company 16939677' },
      { name: 'Legal and disclaimers', href: '/disclaimers', description: 'What a measurement card is not' },
      { section: 'Read', name: 'The Library — full archive', href: '/library', description: 'Everything we have published, dated and organized by sector' },
      { name: 'Blog', href: '/blog', description: 'Findings, corrections and notes' },
      { name: 'Questions people ask', href: '/faq', description: 'The plain-English answers, including the refusals' },
      { section: 'Academy', name: 'Council Academy', href: '/academy', description: 'Learn the statute and the method. Completion attests training, never conformity' },
      { name: 'Verify a training record', href: '/verify-certificate', description: 'Check a signed completion record. Verification is free forever' },
      { name: 'Accreditation — what we are not', href: '/accreditation', description: 'There is no accreditation chain behind us, and we say so' },
    ],
  },
];

/** Six-group master mega-menu — rendered on marketing chrome. HOME_NAV stays the short rail. */
export const ARCHIVE_NAV = navigation;
