[[TOKENS]]
issuer = "rHuiXXjHLpMP8ZE9sSQU5aADQVWDwv6h5p"
currency = "OUSG"
name = "Ondo Short-Term US Govt Fund"
desc = "Ondo Short-Term US Govt Fund"
icon = "https://ondo.finance/images/tokens/ousg.png"

[[ISSUERS]]
address = "rHuiXXjHLpMP8ZE9sSQU5aADQVWDwv6h5p"
name = "Ondo Short-Term US Govt Fund"