[[ACCOUNTS]]
address = "rH5CJsqvNqZGxrMyGaqLEoMWRYcVTAPZMt"
desc = "BBRL Issuer Account"

[[ACCOUNTS]]
address = "rB3y9EPnq1ZrZP3aXgfyfdXQThzdXMrLMc"
desc = "USDB Issuer Account"


[[ISSUERS]]
address = "rH5CJsqvNqZGxrMyGaqLEoMWRYcVTAPZMt"
name = "BBRL - Braza BRL"

[[ISSUERS]]
address = "rB3y9EPnq1ZrZP3aXgfyfdXQThzdXMrLMc"
name = "USDB - Braza USD"


[[TOKENS]]
issuer = "rH5CJsqvNqZGxrMyGaqLEoMWRYcVTAPZMt"
currency = "BBRL"
name = "BBRL - Braza BRL"
desc = "BBRL is a stablecoin pegged to the Brazilian real, issued by Braza. Its use complements BRL-denominated payments both within and outside the crypto ecosystem, offering instant liquidity and regulatory compliance."
icon = "https://brz-crypto-dev-public.s3.us-east-2.amazonaws.com/BBRL_Icone+1.svg"
asset_class = "rwa"
asset_subclass = "stablecoin"

[[TOKENS.URLS]]
url = "https://brazabank.com.br/bbrl"
type = "website"


[[TOKENS]]
issuer = "rB3y9EPnq1ZrZP3aXgfyfdXQThzdXMrLMc"
currency = "USDB"
name = "USDB - Braza USD"
desc = "USDB is a stablecoin pegged to the US dollar, issued by Braza. Its use complements USD-denominated payments both within and outside the crypto ecosystem, offering instant liquidity and regulatory compliance."
icon = "https://brz-crypto-dev-public.s3.us-east-2.amazonaws.com/USDB_Icone-positivo.svg"
asset_class = "rwa"
asset_subclass = "stablecoin"

[[TOKENS.URLS]]
url = "https://www.brazabank.com.br/usdb/"
type = "website"