"""GSPC Dify plugin entrypoint. Generated by scripts/harness-x/render.mjs — do not hand-edit."""
from dify_plugin import DifyPluginEnv, Plugin

plugin = Plugin(DifyPluginEnv(MAX_REQUEST_TIMEOUT=120))

if __name__ == "__main__":
    plugin.run()
