"""GSPC tool provider for Dify. No credentials: the free door needs none. Generated by scripts/harness-x/render.mjs."""
from typing import Any

from dify_plugin import ToolProvider


class GspcProvider(ToolProvider):
    def _validate_credentials(self, credentials: dict[str, Any]) -> None:
        return None
