apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "csoai.fullname" . }}
  labels: {{- include "csoai.labels" . | nindent 4 }}
data:
  did.json: |
{{ default (.Files.Get "files/did.json") .Values.didJson | indent 4 }}
  run.yaml: |
{{ .Files.Get "files/run.yaml" | indent 4 }}
