apiVersion: v1
kind: Service
metadata:
  name: {{ include "csoai.fullname" . }}
  labels: {{- include "csoai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "csoai.selector" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
