"""CSOAI GSPC — Gradio MCP server. Generated by scripts/harness-x/render.mjs — do not hand-edit."""
from __future__ import annotations

import json

import gradio as gr
from csoai_gspc import BOARD_URL, fetch_board, get_axis, totals, verify_card

DOCTRINE_SHA256 = "845fc1d200eb9e867fc8d682750409d6725084bac632726187759f8fefdfbe0a"


def gspc_board_totals() -> dict:
    """Live GSPC board totals, verbatim from https://councilof.ai/api/gspc. Quote public_count exactly; never re-derive a count.

    Returns state UNREACHABLE (and no number) if the board cannot be fetched.
    """
    try:
        return {"state": "LIVE", "source": BOARD_URL, "totals": totals(fetch_board())}
    except Exception as exc:
        return {"state": "UNREACHABLE", "source": BOARD_URL, "error": type(exc).__name__}


def gspc_axis(axis: str) -> dict:
    """One GSPC axis row by name, verbatim from the live board.

    Args:
        axis: the axis name as printed on the board.
    """
    try:
        row = get_axis(axis, fetch_board())
    except Exception as exc:
        return {"state": "UNREACHABLE", "source": BOARD_URL, "error": type(exc).__name__}
    return {"state": "ABSENT", "axis": axis} if row is None else {"state": "LIVE", "axis_row": row}


def gspc_verify_card(card_json: str) -> dict:
    """Verify a Council of AI signed measurement card. Three states: VALID, INVALID, UNCHECKABLE.

    Args:
        card_json: the card as a JSON string.
    """
    try:
        card = json.loads(card_json)
    except ValueError:
        return {"state": "UNCHECKABLE", "reason": "not JSON"}
    v = verify_card(card)
    return {"state": v.state, "reason": v.reason, "card_id": v.card_id}


demo = gr.TabbedInterface(
    [
        gr.Interface(gspc_board_totals, inputs=[], outputs=gr.JSON(), title="Board totals"),
        gr.Interface(gspc_axis, inputs=gr.Textbox(label="axis"), outputs=gr.JSON(), title="Axis"),
        gr.Interface(gspc_verify_card, inputs=gr.Textbox(label="card JSON", lines=12), outputs=gr.JSON(), title="Verify card"),
    ],
    ["Board", "Axis", "Verify"],
    title="CSOAI GSPC — measurement only",
)

if __name__ == "__main__":
    demo.launch(mcp_server=True)
